#pragma once

#include "spark_k3_model.h"

#define SPARK_LLM_FAMILY_TAG                    k3
#define SPARK_LLM_HIDDEN_DIMENSION              SPARK_K3_MODEL_HIDDEN_DIMENSION
#define SPARK_LLM_LAYER_COUNT                   SPARK_K3_MODEL_LAYER_COUNT
#define SPARK_LLM_OUTPUT_VOCAB_COUNT            SPARK_K3_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS        SPARK_K3_MODEL_MAXIMUM_CONTEXT_TOKENS
#define SPARK_LLM_RMS_NORM_EPSILON              SPARK_K3_MODEL_RMS_NORM_EPSILON
#define SPARK_LLM_END_OF_TEXT_TOKEN_ID          SPARK_K3_MODEL_END_OF_TEXT_TOKEN_ID
#define SPARK_LLM_KV_POOL_TOKENS                SPARK_K3_MODEL_KV_POOL_TOKENS
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH SPARK_K3_MODEL_MAX_PREFILL_TOKENS_PER_DISPATCH

#define SPARK_LLM_MLA_HEAD_COUNT                SPARK_K3_MODEL_MLA_HEAD_COUNT
#define SPARK_LLM_MLA_QUERY_A_DIMENSION         SPARK_K3_MODEL_MLA_QUERY_A_DIMENSION
#define SPARK_LLM_MLA_LATENT_DIMENSION          SPARK_K3_MODEL_MLA_LATENT_DIMENSION
#define SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION    SPARK_K3_MODEL_MLA_QK_NOPE_HEAD_DIMENSION
#define SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION    64u
#define SPARK_LLM_MLA_V_HEAD_DIMENSION          128u

#define SPARK_LLM_ATTENTION_PERIOD              SPARK_K3_MODEL_ATTENTION_PERIOD
#define SPARK_LLM_GLOBAL_ATTENTION_PHASE        SPARK_K3_MODEL_GLOBAL_ATTENTION_PHASE

#define SPARK_LLM_MOE_EXPERT_COUNT              SPARK_K3_MODEL_MOE_EXPERT_COUNT
#define SPARK_LLM_MOE_TOP_K                     SPARK_K3_MODEL_MOE_TOP_K
#define SPARK_LLM_MOE_SHARED_EXPERT_COUNT       SPARK_K3_MODEL_MOE_SHARED_EXPERT_COUNT
#define SPARK_LLM_MOE_INTERMEDIATE_DIMENSION    SPARK_K3_MODEL_MOE_INTERMEDIATE_DIMENSION
#define SPARK_LLM_MOE_ROUTED_SCALING_FACTOR     SPARK_K3_MODEL_MOE_ROUTED_SCALING_FACTOR
#define SPARK_LLM_MOE_NORM_TOPK_PROB            SPARK_K3_MODEL_MOE_NORM_TOPK_PROB
#define SPARK_LLM_FIRST_ROUTED_LAYER            SPARK_K3_MODEL_FIRST_ROUTED_LAYER
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION  SPARK_K3_MODEL_DENSE_INTERMEDIATE_DIMENSION

#define SPARK_LLM_KDA_LAYER_COUNT               69u
#define SPARK_LLM_KDA_HEAD_COUNT                SPARK_K3_MODEL_KDA_HEAD_COUNT
#define SPARK_LLM_KDA_HEAD_KEY_DIMENSION        SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION
#define SPARK_LLM_KDA_HEAD_VALUE_DIMENSION      SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION
#define SPARK_LLM_KDA_CONV_KERNEL               SPARK_K3_MODEL_KDA_CONV_KERNEL
#define SPARK_LLM_KDA_STATE_ELEMENT_BYTES       SPARK_K3_MODEL_KDA_STATE_ELEMENT_BYTES
#define SPARK_LLM_KDA_GATE_LOWER_BOUND          SPARK_K3_MODEL_KDA_GATE_LOWER_BOUND

#define SPARK_LLM_TILE_N                        128u
#define SPARK_LLM_TILE_STAGES                   2u
#define SPARK_LLM_LAYER_THREADS                 256u

#define SPARK_LLM_MTP_ENABLED                   0u
#define SPARK_LLM_MTP_DRAFT_DEPTH               1u

#define SPARK_LLM_TP_COLLECTIVE_BACKEND         0u
#define SPARK_LLM_TP_DEGREE                     16u
#define SPARK_LLM_STAGE_INDEX                   0u

#define SPARK_LLM_MISS_PACK_STRIDE              512u
#define SPARK_LLM_MISS_RING_CAPACITY            64u
#define SPARK_LLM_ROUTE_UNION_MAX               2400u
#define SPARK_LLM_ROUTE_UNION_TRIM              1888u

#define SPARK_LLM_ADAPTER_DESCRIPTOR            "spark.k3.serving-adapter.tp16.mxfp4.v1"
#define SPARK_LLM_MODEL_SOURCE_URI              "moonshotai/Kimi-K3"
#define SPARK_LLM_MODEL_REVISION                "f831ab66814297da540d832a5235f8e904f29d06"
