#pragma once

#include <stdint.h>

#if defined(__cplusplus)
#define SPARK_K3_ASSERT_STATIC(condition, message) \
	static_assert(condition, message)
#else
#define SPARK_K3_ASSERT_STATIC(condition, message) \
	_Static_assert(condition, message)
#endif

#define SPARK_K3_MODEL_HIDDEN_DIMENSION 7168u
#define SPARK_K3_MODEL_LAYER_COUNT 93u
#define SPARK_K3_MODEL_FIRST_ROUTED_LAYER 1u
#define SPARK_K3_MODEL_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_K3_MODEL_OUTPUT_VOCAB_COUNT 163840u
#define SPARK_K3_MODEL_RMS_NORM_EPSILON 1e-05f

#define SPARK_K3_MODEL_ATTENTION_PERIOD 4u
#define SPARK_K3_MODEL_GLOBAL_ATTENTION_PHASE 3u
#define SPARK_K3_MODEL_MLA_LAYER_COUNT \
	((SPARK_K3_MODEL_LAYER_COUNT / SPARK_K3_MODEL_ATTENTION_PERIOD) + 1u)
#define SPARK_K3_MODEL_KDA_LAYER_COUNT \
	(SPARK_K3_MODEL_LAYER_COUNT - SPARK_K3_MODEL_MLA_LAYER_COUNT)
#define SPARK_K3_MODEL_LAYER_IS_MLA(layer_index) \
	((((layer_index) % SPARK_K3_MODEL_ATTENTION_PERIOD) == \
	  SPARK_K3_MODEL_GLOBAL_ATTENTION_PHASE) || \
	 ((layer_index) == (SPARK_K3_MODEL_LAYER_COUNT - 1u)))
#define SPARK_K3_MODEL_LAYER_IS_KDA(layer_index) \
	(SPARK_K3_MODEL_LAYER_IS_MLA(layer_index) == 0u)

#define SPARK_K3_MODEL_MLA_HEAD_COUNT 96u
#define SPARK_K3_MODEL_MLA_QUERY_A_DIMENSION 1536u
#define SPARK_K3_MODEL_MLA_LATENT_DIMENSION 512u
#define SPARK_K3_MODEL_MLA_QK_NOPE_HEAD_DIMENSION 128u
#define SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION 64u
#define SPARK_K3_MODEL_MLA_ROPE_DIMENSION SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION
#define SPARK_K3_MODEL_MLA_VALUE_HEAD_DIMENSION 128u
#define SPARK_K3_MODEL_MLA_USE_NOPE 1u
#define SPARK_K3_MODEL_MLA_OUTPUT_GATE 1u
#define SPARK_K3_MODEL_MLA_QK_SCALE 0.07216878365f
#define SPARK_K3_MODEL_MLA_QK_HEAD_DIMENSION \
	(SPARK_K3_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + \
	 SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION)
#define SPARK_K3_MODEL_MLA_QUERY_B_DIMENSION \
	(SPARK_K3_MODEL_MLA_HEAD_COUNT * SPARK_K3_MODEL_MLA_QK_HEAD_DIMENSION)
#define SPARK_K3_MODEL_MLA_KV_A_DIMENSION \
	(SPARK_K3_MODEL_MLA_LATENT_DIMENSION + \
	 SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION)
#define SPARK_K3_MODEL_MLA_KV_B_DIMENSION \
	(SPARK_K3_MODEL_MLA_HEAD_COUNT * \
	 (SPARK_K3_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + \
	  SPARK_K3_MODEL_MLA_VALUE_HEAD_DIMENSION))
#define SPARK_K3_MODEL_MLA_CACHE_TOKEN_ELEMENTS \
	SPARK_K3_MODEL_MLA_KV_A_DIMENSION
#define SPARK_K3_MODEL_MLA_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_K3_MODEL_MLA_HEAD_COUNT * SPARK_K3_MODEL_MLA_VALUE_HEAD_DIMENSION)

#define SPARK_K3_MODEL_KDA_HEAD_COUNT 96u
#define SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION 128u
#define SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION 128u
#define SPARK_K3_MODEL_KDA_LOW_RANK_DIMENSION 128u
#define SPARK_K3_MODEL_KDA_CHUNK_TOKENS 64u
#define SPARK_K3_MODEL_KDA_QK_L2NORM 1u
#define SPARK_K3_MODEL_KDA_FULL_RANK_GATE 1u
#define SPARK_K3_MODEL_KDA_GATE_LOWER_BOUND -5.0f
#define SPARK_K3_MODEL_KDA_A_LOG_SOURCE_HEAD_COUNT 128u
#define SPARK_K3_MODEL_KDA_CONV_KERNEL 4u
#define SPARK_K3_MODEL_KDA_MIN_LOG_DECAY -16.0f
#define SPARK_K3_MODEL_KDA_QK_DIMENSION \
	(SPARK_K3_MODEL_KDA_HEAD_COUNT * SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION)
#define SPARK_K3_MODEL_KDA_VALUE_DIMENSION \
	(SPARK_K3_MODEL_KDA_HEAD_COUNT * SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_K3_KV_BITS 16u
#define SPARK_K3_KV_BYTES_PER_SCALAR (SPARK_K3_KV_BITS / 8u)
#define SPARK_K3_MODEL_KDA_STATE_ELEMENT_BYTES 4u
#define SPARK_K3_MODEL_KDA_STATE_ELEMENTS_PER_HEAD \
	(SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION * \
	 SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_K3_MODEL_KDA_STATE_ELEMENTS_PER_LAYER \
	(SPARK_K3_MODEL_KDA_HEAD_COUNT * \
	 SPARK_K3_MODEL_KDA_STATE_ELEMENTS_PER_HEAD)
#define SPARK_K3_MODEL_KDA_STATE_BYTES_PER_LAYER \
	((uint64_t)SPARK_K3_MODEL_KDA_HEAD_COUNT * \
	 SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION * \
	 SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION * \
	 SPARK_K3_MODEL_KDA_STATE_ELEMENT_BYTES)
#define SPARK_K3_MODEL_KDA_CONV_WINDOW_BYTES_PER_LAYER \
	(((2ull * SPARK_K3_MODEL_KDA_HEAD_COUNT * \
	   SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION) + \
	  ((uint64_t)SPARK_K3_MODEL_KDA_HEAD_COUNT * \
	   SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION)) * \
	 SPARK_K3_MODEL_KDA_CONV_KERNEL * SPARK_K3_KV_BYTES_PER_SCALAR)
#define SPARK_K3_MODEL_KDA_SLOT_BYTES \
	(SPARK_K3_MODEL_KDA_LAYER_COUNT * \
	 (SPARK_K3_MODEL_KDA_STATE_BYTES_PER_LAYER + \
	  SPARK_K3_MODEL_KDA_CONV_WINDOW_BYTES_PER_LAYER))

#define SPARK_K3_MODEL_MOE_EXPERT_COUNT 896u
#define SPARK_K3_MODEL_MOE_TOP_K 16u
#define SPARK_K3_MODEL_MOE_SHARED_EXPERT_COUNT 2u
#define SPARK_K3_MODEL_MOE_INTERMEDIATE_DIMENSION 3072u
#define SPARK_K3_MODEL_DENSE_INTERMEDIATE_DIMENSION 33792u
#define SPARK_K3_MODEL_MOE_ROUTED_SCALING_FACTOR 1.0f
#define SPARK_K3_MODEL_MOE_ROUTED_EXPERT_HIDDEN_DIMENSION 3584u
#define SPARK_K3_MODEL_MOE_NORM_TOPK_PROB 1u
#define SPARK_K3_MODEL_MOE_W1_COMPONENT_COUNT 2u

#define SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS 12u
#define SPARK_K3_MODEL_ATTNRES_BLOCK_COUNT \
	((SPARK_K3_MODEL_LAYER_COUNT + SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS - 1u) / \
	 SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS)
#define SPARK_K3_MODEL_ATTNRES_MAX_REPRESENTATIONS 9u

#define SPARK_K3_MODEL_MXFP4_GROUP_SIZE 32u
#define SPARK_K3_KV_PAGE_SLOTS 64u

#define SPARK_K3_PP_STAGE_COUNT 4u
#define SPARK_K3_PP_STAGE_BASE_LAYERS \
	(SPARK_K3_MODEL_LAYER_COUNT / SPARK_K3_PP_STAGE_COUNT)
#define SPARK_K3_PP_STAGE_REMAINDER \
	(SPARK_K3_MODEL_LAYER_COUNT % SPARK_K3_PP_STAGE_COUNT)
#define SPARK_K3_PP_STAGE_LAYERS(stage_index) \
	(SPARK_K3_PP_STAGE_BASE_LAYERS + \
	 ((stage_index) < SPARK_K3_PP_STAGE_REMAINDER ? 1u : 0u))
#define SPARK_K3_PP_STAGE_FIRST(stage_index) \
	(((stage_index) * SPARK_K3_PP_STAGE_BASE_LAYERS) + \
	 ((stage_index) < SPARK_K3_PP_STAGE_REMAINDER ? \
	  (stage_index) : SPARK_K3_PP_STAGE_REMAINDER))

SPARK_K3_ASSERT_STATIC(SPARK_K3_MODEL_MLA_LAYER_COUNT == 24u &&
	SPARK_K3_MODEL_KDA_LAYER_COUNT == 69u,
	"k3 hybrid layer split must be 24 mla plus 69 kda");
SPARK_K3_ASSERT_STATIC(SPARK_K3_MODEL_KDA_STATE_BYTES_PER_LAYER == 6291456ull &&
	SPARK_K3_MODEL_KDA_CONV_WINDOW_BYTES_PER_LAYER == 294912ull &&
	SPARK_K3_MODEL_KDA_SLOT_BYTES == 69ull * 6586368ull,
	"k3 kda state algebra must match the fleet receipt");
SPARK_K3_ASSERT_STATIC(SPARK_K3_MODEL_MLA_CACHE_TOKEN_ELEMENTS * \
	SPARK_K3_KV_BYTES_PER_SCALAR == 1152u,
	"k3 mla cache entry must be 1152 bytes per token per layer");
SPARK_K3_ASSERT_STATIC(SPARK_K3_PP_STAGE_FIRST(SPARK_K3_PP_STAGE_COUNT - 1u) +
	SPARK_K3_PP_STAGE_LAYERS(SPARK_K3_PP_STAGE_COUNT - 1u) ==
	SPARK_K3_MODEL_LAYER_COUNT,
	"k3 pp stage bounds must tile the layer stack");
SPARK_K3_ASSERT_STATIC(SPARK_K3_PP_STAGE_LAYERS(0u) == 24u &&
	SPARK_K3_PP_STAGE_LAYERS(1u) == 23u &&
	SPARK_K3_PP_STAGE_LAYERS(2u) == 23u &&
	SPARK_K3_PP_STAGE_LAYERS(3u) == 23u &&
	SPARK_K3_PP_STAGE_FIRST(1u) == 24u &&
	SPARK_K3_PP_STAGE_FIRST(2u) == 47u &&
	SPARK_K3_PP_STAGE_FIRST(3u) == 70u,
	"k3 pp stage receipt must be 0/24 24/23 47/23 70/23");
SPARK_K3_ASSERT_STATIC(SPARK_K3_MODEL_ATTNRES_MAX_REPRESENTATIONS ==
	(SPARK_K3_MODEL_ATTNRES_BLOCK_COUNT + 1u),
	"k3 attnres bank candidates must be the block count plus the embedding");
SPARK_K3_ASSERT_STATIC((SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION % 16u) == 0u &&
	(SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION % 64u) == 0u,
	"k3 kda head geometry must satisfy the chunk kernel tiling");
SPARK_K3_ASSERT_STATIC((SPARK_K3_MODEL_HIDDEN_DIMENSION %
	SPARK_K3_MODEL_MXFP4_GROUP_SIZE) == 0u &&
	(SPARK_K3_MODEL_MOE_INTERMEDIATE_DIMENSION %
	 SPARK_K3_MODEL_MXFP4_GROUP_SIZE) == 0u,
	"k3 quantized dimensions must be whole mxfp4 groups");
