#ifndef SPARKPIPE_SPARK_K3_MODEL_H
#define SPARKPIPE_SPARK_K3_MODEL_H

#include <stdint.h>

#include "sparkpipe/spark_k3_kv_geometry.h"

#define SPARK_K3_MODEL_HIDDEN_DIMENSION 7168u
#define SPARK_K3_MODEL_LAYER_COUNT 93u
#define SPARK_K3_MODEL_FIRST_ROUTED_LAYER 1u
#define SPARK_K3_MODEL_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_K3_MODEL_OUTPUT_VOCAB_COUNT 163840u
#define SPARK_K3_MODEL_RMS_NORM_EPSILON 1e-05f

#define SPARK_K3_MODEL_KV_POOL_TOKENS 4194304u
#define SPARK_K3_MODEL_RESTRICTED_VOCAB_COUNT 256u
#define SPARK_K3_MODEL_MAX_PREFILL_TOKENS_PER_DISPATCH 256u
#define SPARK_K3_MODEL_END_OF_TEXT_TOKEN_ID 163585u

#define SPARK_K3_MODEL_MOE_EXPERT_COUNT 896u
#define SPARK_K3_MODEL_MOE_TOP_K 16u
#define SPARK_K3_MODEL_MOE_SHARED_EXPERT_COUNT 2u
#define SPARK_K3_MODEL_MOE_INTERMEDIATE_DIMENSION 3072u
#define SPARK_K3_MODEL_DENSE_INTERMEDIATE_DIMENSION 33792u
#define SPARK_K3_MODEL_MOE_ROUTED_SCALING_FACTOR 1.0f
#define SPARK_K3_MODEL_MOE_ROUTED_EXPERT_HIDDEN_DIMENSION 3584u
#define SPARK_K3_MODEL_MOE_NORM_TOPK_PROB 1u
#define SPARK_K3_MODEL_MOE_W1_COMPONENT_COUNT 2u

#define SPARK_K3_MODEL_ATTENTION_PERIOD 4u
#define SPARK_K3_MODEL_GLOBAL_ATTENTION_PHASE 3u
#define SPARK_K3_MODEL_LAYER_IS_KDA(layer_index) \
	((((layer_index) % SPARK_K3_MODEL_ATTENTION_PERIOD) != SPARK_K3_MODEL_GLOBAL_ATTENTION_PHASE) && \
	 ((layer_index) != (SPARK_K3_MODEL_LAYER_COUNT - 1u)))

#define SPARK_K3_MODEL_KDA_HEAD_COUNT 96u
#define SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION 128u
#define SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION 128u
#define SPARK_K3_MODEL_KDA_LOW_RANK_DIMENSION 128u
#define SPARK_K3_MODEL_KDA_CHUNK_TOKENS 64u
#define SPARK_K3_MODEL_KDA_QK_L2NORM 1u
#define SPARK_K3_MODEL_KDA_FULL_RANK_GATE 1u
#define SPARK_K3_MODEL_KDA_GATE_LOWER_BOUND -5.0f
#define SPARK_K3_MODEL_KDA_A_LOG_SOURCE_HEAD_COUNT 128u
#define SPARK_K3_MODEL_KDA_CONV_KERNEL 4u
#define SPARK_K3_MODEL_KDA_MIN_LOG_DECAY -16.0f
#define SPARK_K3_MODEL_KDA_QK_DIMENSION \
	(SPARK_K3_MODEL_KDA_HEAD_COUNT * SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION)
#define SPARK_K3_MODEL_KDA_VALUE_DIMENSION \
	(SPARK_K3_MODEL_KDA_HEAD_COUNT * SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_K3_MODEL_KDA_STATE_ELEMENT_BYTES 4u
#define SPARK_K3_MODEL_KDA_STATE_ELEMENTS_PER_HEAD \
	(SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION * SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_K3_MODEL_KDA_STATE_ELEMENTS_PER_LAYER \
	(SPARK_K3_MODEL_KDA_HEAD_COUNT * SPARK_K3_MODEL_KDA_STATE_ELEMENTS_PER_HEAD)
#define SPARK_K3_MODEL_KDA_STATE_BYTES_PER_LAYER SPARK_K3_KV_KDA_STATE_BYTES_PER_LAYER
#define SPARK_K3_MODEL_KDA_CONV_WINDOW_BYTES_PER_LAYER SPARK_K3_KV_KDA_CONV_BYTES_PER_LAYER

#define SPARK_K3_MODEL_MLA_HEAD_COUNT 96u
#define SPARK_K3_MODEL_MLA_QUERY_A_DIMENSION 1536u
#define SPARK_K3_MODEL_MLA_LATENT_DIMENSION 512u
#define SPARK_K3_MODEL_MLA_QK_NOPE_HEAD_DIMENSION 128u
#define SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION 64u
#define SPARK_K3_MODEL_MLA_ROPE_DIMENSION SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION
#define SPARK_K3_MODEL_MLA_VALUE_HEAD_DIMENSION 128u
#define SPARK_K3_MODEL_MLA_USE_NOPE 1u
#define SPARK_K3_MODEL_MLA_OUTPUT_GATE 1u
#define SPARK_K3_MODEL_MLA_QK_SCALE 0.07216878365f
#define SPARK_K3_MODEL_MLA_QK_HEAD_DIMENSION \
	(SPARK_K3_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION)
#define SPARK_K3_MODEL_MLA_QUERY_B_DIMENSION \
	(SPARK_K3_MODEL_MLA_HEAD_COUNT * SPARK_K3_MODEL_MLA_QK_HEAD_DIMENSION)
#define SPARK_K3_MODEL_MLA_KV_A_DIMENSION \
	(SPARK_K3_MODEL_MLA_LATENT_DIMENSION + SPARK_K3_MODEL_MLA_UNROTATED_DIMENSION)
#define SPARK_K3_MODEL_MLA_KV_B_DIMENSION \
	(SPARK_K3_MODEL_MLA_HEAD_COUNT * \
	 (SPARK_K3_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + SPARK_K3_MODEL_MLA_VALUE_HEAD_DIMENSION))
#define SPARK_K3_MODEL_MLA_CACHE_TOKEN_ELEMENTS SPARK_K3_MODEL_MLA_KV_A_DIMENSION
#define SPARK_K3_MODEL_MLA_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_K3_MODEL_MLA_HEAD_COUNT * SPARK_K3_MODEL_MLA_VALUE_HEAD_DIMENSION)

#define SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS 12u
#define SPARK_K3_MODEL_ATTNRES_BLOCK_COUNT \
	((SPARK_K3_MODEL_LAYER_COUNT + SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS - 1u) / \
	 SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS)
#define SPARK_K3_MODEL_ATTNRES_MAX_REPRESENTATIONS 9u
#define SPARK_K3_MODEL_ATTNRES_COMPLETED_BLOCKS_BEFORE_LAYER(layer_index) \
	(1u + ((layer_index) / SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS))
#define SPARK_K3_MODEL_ATTNRES_LAYER_OPENS_BLOCK(layer_index) \
	(((((layer_index) + 1u) % SPARK_K3_MODEL_ATTNRES_BLOCK_LAYERS) == 0u) ? 1u : 0u)

#define SPARK_K3_MODEL_MXFP4_GROUP_SIZE 32u
#define SPARK_K3_MODEL_MXFP8_GROUP_SIZE 32u
#define SPARK_K3_MODEL_MXFP4_PAYLOAD_BYTES(rows, columns) \
	(((uint64_t)(rows) * (uint64_t)(columns)) / 2u)
#define SPARK_K3_MODEL_MXFP4_SCALE_BYTES(rows, columns) \
	(((uint64_t)(rows) * (uint64_t)(columns)) / (uint64_t)SPARK_K3_MODEL_MXFP4_GROUP_SIZE)

#define SPARK_K3_MODEL_BF16_ELEMENT_BYTES ((uint32_t)sizeof(uint16_t))
#define SPARK_K3_MODEL_HIDDEN_BF16_BYTES \
	(SPARK_K3_MODEL_HIDDEN_DIMENSION * SPARK_K3_MODEL_BF16_ELEMENT_BYTES)

#if SPARK_K3_MODEL_KDA_HEAD_COUNT != SPARK_K3_KV_KDA_HEADS
#error k3 model shim and kv geometry disagree on the kda head count
#endif
#if SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION != SPARK_K3_KV_KDA_KEY_DIM
#error k3 model shim and kv geometry disagree on the kda key dimension
#endif
#if SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION != SPARK_K3_KV_KDA_VALUE_DIM
#error k3 model shim and kv geometry disagree on the kda value dimension
#endif
#if SPARK_K3_MODEL_KDA_CONV_KERNEL != SPARK_K3_KV_KDA_CONV_KERNEL
#error k3 model shim and kv geometry disagree on the kda convolution kernel
#endif

#if SPARK_K3_MODEL_ATTNRES_MAX_REPRESENTATIONS != (SPARK_K3_MODEL_ATTNRES_BLOCK_COUNT + 1u)
#error k3 attnres bank candidates must be the block count plus the embedding
#endif
#if (SPARK_K3_MODEL_KDA_HEAD_KEY_DIMENSION % 16u) != 0u || \
    (SPARK_K3_MODEL_KDA_HEAD_VALUE_DIMENSION % 64u) != 0u
#error k3 kda head geometry must satisfy the chunk kernel tiling
#endif
#if (SPARK_K3_MODEL_HIDDEN_DIMENSION % SPARK_K3_MODEL_MXFP4_GROUP_SIZE) != 0u || \
    (SPARK_K3_MODEL_MOE_INTERMEDIATE_DIMENSION % SPARK_K3_MODEL_MXFP4_GROUP_SIZE) != 0u
#error k3 quantized dimensions must be whole mxfp4 groups
#endif

#endif
