#pragma once


#include <stdint.h>
#include "inference/kernels/layer_kind.cuh"
#include "sparkpipe/spark_glm52_model.h"

#define GLM52_HIDDEN SPARK_GLM52_MODEL_HIDDEN_DIMENSION
#define GLM52_LAYERS SPARK_GLM52_MODEL_LAYER_COUNT
#define GLM52_FIRST_ROUTED_LAYER SPARK_GLM52_MODEL_FIRST_ROUTED_LAYER
#define GLM52_VOCAB SPARK_GLM52_MODEL_OUTPUT_VOCAB_COUNT
#define GLM52_RESTRICTED_VOCAB SPARK_GLM52_MODEL_RESTRICTED_VOCAB_COUNT
#define GLM52_RMS_EPSILON SPARK_GLM52_MODEL_RMS_NORM_EPSILON
#define GLM52_ROPE_THETA SPARK_GLM52_MODEL_ROPE_THETA


#define GLM52_ATTN_HEADS SPARK_GLM52_MODEL_HEAD_COUNT
#define GLM52_LATENT SPARK_GLM52_MODEL_LATENT_DIMENSION
#define GLM52_ROPE_DIM SPARK_GLM52_MODEL_ROPE_DIMENSION
#define GLM52_QK_NOPE_DIM SPARK_GLM52_MODEL_QK_NOPE_HEAD_DIMENSION
#define GLM52_VALUE_DIM SPARK_GLM52_MODEL_VALUE_HEAD_DIMENSION
#define GLM52_QUERY_A_DIM SPARK_GLM52_MODEL_QUERY_A_DIMENSION

#define GLM52_DSA_SELECTED SPARK_GLM52_MODEL_DSA_SELECTED_TOKEN_COUNT
#define GLM52_DSA_INDEX_HEADS SPARK_GLM52_MODEL_DSA_INDEX_HEAD_COUNT
#define GLM52_DSA_INDEX_DIM SPARK_GLM52_MODEL_DSA_INDEX_HEAD_DIMENSION
#define GLM52_DSA_QUERY_DIM (GLM52_DSA_INDEX_HEADS * GLM52_DSA_INDEX_DIM)
#define GLM52_DSA_INDEX_EPSILON SPARK_GLM52_MODEL_DSA_INDEX_NORM_EPSILON
#define GLM52_DSA_INDEX_SCALE SPARK_GLM52_MODEL_DSA_INDEX_SOFTMAX_SCALE


#define GLM52_EXPERTS SPARK_GLM52_MODEL_MOE_EXPERT_COUNT
#define GLM52_TOP_K SPARK_GLM52_MODEL_MOE_TOP_K
#define GLM52_EXPERT_INTERMEDIATE SPARK_GLM52_MODEL_MOE_INTERMEDIATE_DIMENSION
#define GLM52_DENSE_INTERMEDIATE SPARK_GLM52_MODEL_DENSE_INTERMEDIATE_DIMENSION
#define GLM52_ROUTED_SCALE SPARK_GLM52_MODEL_MOE_ROUTED_SCALING_FACTOR
#define GLM52_W1_COMPONENTS SPARK_GLM52_MODEL_MOE_W1_COMPONENT_COUNT


#define GLM52_FP8_SCALE_BLOCK SPARK_GLM52_MODEL_FP8_SCALE_BLOCK
#define GLM52_NVFP4_GROUP SPARK_GLM52_MODEL_NVFP4_GROUP_SIZE
#define GLM52_MXFP4_GROUP SPARK_GLM52_MODEL_MXFP4_GROUP_SIZE


#define GLM52_MTP_DRAFT_TOKENS SPARK_GLM52_MODEL_MTP_DRAFT_TOKEN_COUNT
#define GLM52_MTP_LAYER_INDEX SPARK_GLM52_MODEL_MTP_LAYER_INDEX


#define GLM52_KV_BITS 16u
#define GLM52_KV_PAGE_SLOTS 64u
#define GLM52_KV_SLOT_BYTES ((GLM52_LATENT_ROW * GLM52_KV_BITS) / 8u)


#define GLM52_ROUTED_LAYERS (GLM52_LAYERS - GLM52_FIRST_ROUTED_LAYER)
#define GLM52_GATE_UP_DIM (GLM52_EXPERT_INTERMEDIATE * GLM52_W1_COMPONENTS)
#define GLM52_LATENT_ROW (GLM52_LATENT + GLM52_ROPE_DIM)
#define GLM52_WEIGHT_LAYERS SPARK_GLM52_MODEL_WEIGHT_LAYER_COUNT

static inline uint32_t Glm52RowsPerExpert(uint32_t tokens)
{
	return(((tokens * GLM52_TOP_K) + GLM52_EXPERTS - 1u) / GLM52_EXPERTS);
}

static inline uint32_t Glm52LayerHasFullIndexer(uint32_t layer)
{
	return(layer < 3u || (layer >= 6u && ((layer - 6u) % SPARK_GLM52_MODEL_DSA_INDEX_SHARE_GROUP_LAYER_COUNT) == 0u) ? 1u : 0u);
}

#define GLM52_LAYER_KIND(layer) ((void)(layer), LM_LAYER_LATENT)
