// Qwen 3.6's model geometry for the host tiers, mirroring the values in
// inference/llms/qwen_3_6/config.h. The firmware config is the source
// of truth; a conformance check holds the two in lockstep.
#ifndef SPARKPIPE_SPARK_QWEN36_MODEL_H
#define SPARKPIPE_SPARK_QWEN36_MODEL_H

#define SPARK_QWEN36_MODEL_HIDDEN_DIMENSION 5120u
#define SPARK_QWEN36_MODEL_LAYER_COUNT 64u
#define SPARK_QWEN36_MODEL_VOCAB_COUNT 248320u
#define SPARK_QWEN36_MODEL_ATTENTION_HEAD_COUNT 24u
#define SPARK_QWEN36_MODEL_KV_HEAD_COUNT 4u
#define SPARK_QWEN36_MODEL_HEAD_DIMENSION 256u
#define SPARK_QWEN36_MODEL_GDN_KEY_HEAD_COUNT 16u
#define SPARK_QWEN36_MODEL_GDN_VALUE_HEAD_COUNT 48u

// The resident decode stage module predates the shim above and speaks the
// wider geometry vocabulary below. Every value is either a config.h constant
// under its second name or derived from them; the two additions with no
// config.h counterpart are MAXIMUM_CONTEXT_TOKENS (checkpoint config
// max_position_embeddings) and GDN_CHUNK_TOKENS (the module's chunk width).
#define SPARK_QWEN36_MODEL_OUTPUT_VOCAB_COUNT SPARK_QWEN36_MODEL_VOCAB_COUNT
#define SPARK_QWEN36_MODEL_MAXIMUM_CONTEXT_TOKENS 262144u
#define SPARK_QWEN36_MODEL_RMS_NORM_EPSILON 1e-06f
#define SPARK_QWEN36_MODEL_FFN_INTERMEDIATE_DIMENSION 17408u
#define SPARK_QWEN36_MODEL_MTP_LAYER_COUNT 1u

#define SPARK_QWEN36_MODEL_ATTENTION_PERIOD 4u
#define SPARK_QWEN36_MODEL_FULL_ATTENTION_PHASE 3u
#define SPARK_QWEN36_MODEL_LAYER_IS_GDN(layer_index) \
	(((layer_index) % SPARK_QWEN36_MODEL_ATTENTION_PERIOD) != SPARK_QWEN36_MODEL_FULL_ATTENTION_PHASE)
#define SPARK_QWEN36_MODEL_GDN_LAYER_COUNT 48u
#define SPARK_QWEN36_MODEL_FULL_ATTENTION_LAYER_COUNT 16u

#define SPARK_QWEN36_MODEL_GDN_HEAD_KEY_DIMENSION 128u
#define SPARK_QWEN36_MODEL_GDN_HEAD_VALUE_DIMENSION 128u
#define SPARK_QWEN36_MODEL_GDN_VALUE_HEADS_PER_KEY_HEAD \
	(SPARK_QWEN36_MODEL_GDN_VALUE_HEAD_COUNT / SPARK_QWEN36_MODEL_GDN_KEY_HEAD_COUNT)
#define SPARK_QWEN36_MODEL_GDN_CONV_KERNEL 4u
#define SPARK_QWEN36_MODEL_GDN_QK_DIMENSION \
	(SPARK_QWEN36_MODEL_GDN_KEY_HEAD_COUNT * SPARK_QWEN36_MODEL_GDN_HEAD_KEY_DIMENSION)
#define SPARK_QWEN36_MODEL_GDN_VALUE_DIMENSION \
	(SPARK_QWEN36_MODEL_GDN_VALUE_HEAD_COUNT * SPARK_QWEN36_MODEL_GDN_HEAD_VALUE_DIMENSION)
#define SPARK_QWEN36_MODEL_GDN_CONV_CHANNELS \
	((2u * SPARK_QWEN36_MODEL_GDN_QK_DIMENSION) + SPARK_QWEN36_MODEL_GDN_VALUE_DIMENSION)
#define SPARK_QWEN36_MODEL_GDN_CONV_TAIL_COLUMNS (SPARK_QWEN36_MODEL_GDN_CONV_KERNEL - 1u)
#define SPARK_QWEN36_MODEL_GDN_CHUNK_TOKENS 64u

#define SPARK_QWEN36_MODEL_ATTN_QUERY_HEAD_COUNT SPARK_QWEN36_MODEL_ATTENTION_HEAD_COUNT
#define SPARK_QWEN36_MODEL_ATTN_KV_HEAD_COUNT SPARK_QWEN36_MODEL_KV_HEAD_COUNT
#define SPARK_QWEN36_MODEL_ATTN_HEAD_DIMENSION SPARK_QWEN36_MODEL_HEAD_DIMENSION
#define SPARK_QWEN36_MODEL_ATTN_ROPE_DIMENSION 64u
#define SPARK_QWEN36_MODEL_ATTN_ROPE_THETA 10000000.0f
#define SPARK_QWEN36_MODEL_ATTN_QUERY_DIMENSION \
	(SPARK_QWEN36_MODEL_ATTN_QUERY_HEAD_COUNT * SPARK_QWEN36_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_QWEN36_MODEL_ATTN_KV_DIMENSION \
	(SPARK_QWEN36_MODEL_ATTN_KV_HEAD_COUNT * SPARK_QWEN36_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_QWEN36_MODEL_ATTN_CACHE_TOKEN_ELEMENTS \
	(2u * SPARK_QWEN36_MODEL_ATTN_KV_DIMENSION)

#define SPARK_QWEN36_MODEL_BF16_ELEMENT_BYTES 2u
#define SPARK_QWEN36_MODEL_HIDDEN_BF16_BYTES \
	(SPARK_QWEN36_MODEL_HIDDEN_DIMENSION * SPARK_QWEN36_MODEL_BF16_ELEMENT_BYTES)

#endif
