#ifndef SPARKPIPE_SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FIRMWARE_H
#define SPARKPIPE_SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FIRMWARE_H

#include <stdint.h>

#include "sparkpipe/spark_qwen4_flash_model.h"
#include "sparkpipe/spark_module_abi.h"
#include "sparkpipe/spark_hidden_transport.h"

#ifdef __cplusplus
extern "C" {
#endif


#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_NODE_CONTEXT_ABI_VERSION SPARK_LLM_NODE_CONTEXT_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_ABI_VERSION SPARK_LLM_FRAME_CONTEXT_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_PREFILL_FRAME_VIEW_ABI_VERSION SPARK_LLM_PREFILL_FRAME_VIEW_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_MTP_DRAFT_VIEW_ABI_VERSION SPARK_LLM_MTP_DRAFT_VIEW_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_GDN_SNAPSHOT_VIEW_ABI_VERSION SPARK_LLM_GDN_SNAPSHOT_VIEW_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_MAX_MTP_DRAFT_TOKENS SPARK_LLM_MAX_MTP_DRAFT_TOKENS
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_MAX_GDN_SNAPSHOT_SLOTS SPARK_LLM_MAX_GDN_SNAPSHOT_SLOTS
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_GDN_STATE_POOL_ABI_VERSION SPARK_LLM_GDN_STATE_POOL_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_KV_BLOCK_TABLE_ABI_VERSION SPARK_LLM_KV_BLOCK_TABLE_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_LINEAR_VIEW_ABI_VERSION SPARK_LLM_LINEAR_VIEW_ABI_VERSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_DECODE_BATCH_VIEW_ABI_VERSION SPARK_LLM_DECODE_BATCH_VIEW_ABI_VERSION

#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_HIDDEN_DIMENSION SPARK_LLM_HIDDEN_DIMENSION
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_LAYER_COUNT SPARK_LLM_LAYER_COUNT
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_MAX_STAGE_COUNT SPARK_LLM_MAX_STAGE_COUNT
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_HEAD_SCREEN_CAP SPARK_LLM_HEAD_SCREEN_CAP
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_MAX_PIPELINE_SLOT_COUNT SPARK_LLM_MAX_PIPELINE_SLOT_COUNT
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_MAX_ACTIVE_SEQUENCE_COUNT SPARK_LLM_MAX_ACTIVE_SEQUENCE_COUNT
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_KV_BLOCK_TOKENS SPARK_LLM_KV_BLOCK_TOKENS
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_INVALID_TOKEN_ID SPARK_LLM_INVALID_TOKEN_ID
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_NO_BLOCK SPARK_LLM_NO_BLOCK

#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_BF16 SPARK_STAGEPACK_FORMAT_WEIGHT_BF16
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_F32 SPARK_STAGEPACK_FORMAT_WEIGHT_F32
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_U32 SPARK_STAGEPACK_FORMAT_WEIGHT_U32
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_MXFP4_E2M1 SPARK_STAGEPACK_FORMAT_WEIGHT_MXFP4_E2M1
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_F32B128 SPARK_STAGEPACK_FORMAT_WEIGHT_FP8_E4M3_F32B128
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_E8M0B128 SPARK_STAGEPACK_FORMAT_WEIGHT_FP8_E4M3_E8M0B128
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_I64 SPARK_STAGEPACK_FORMAT_WEIGHT_I64
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_NVFP4_PACKED SPARK_STAGEPACK_FORMAT_WEIGHT_NVFP4_PACKED

_Static_assert(SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_BF16 == 0u,"bf16 weight code must match the shared format");
_Static_assert(SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_MXFP4_E2M1 == 3u,"mxfp4 weight code must match the shared format");
_Static_assert(SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_E8M0B128 == 6u,"e8m0 weight code must match the shared format");

#define SPARK_ABI_TYPE(name) SparkQwen4Flash##name
#include "sparkpipe/family/abi/spark_abi_linear_view.h"

#include "sparkpipe/family/abi/spark_abi_gdn_attn_layer_weights.h"

#include "sparkpipe/family/abi/spark_abi_moe_weights.h"

typedef struct SparkQwen4FlashHcWeights
{
	const void *hc_norm_weight_bf16;
	SparkQwen4FlashLinearView mix_down;
	SparkQwen4FlashLinearView mix_up;
	SparkQwen4FlashLinearView block_inject;
} SparkQwen4FlashHcWeights;

typedef struct SparkQwen4FlashHcMixer
{
	const void *hc_norm_weight_bf16;
	SparkQwen4FlashLinearView mix_down;
	SparkQwen4FlashLinearView mix_up;
} SparkQwen4FlashHcMixer;

typedef struct SparkQwen4FlashIndexerWeights
{
	SparkQwen4FlashLinearView index_qk;
	const void *q_norm_weight_bf16;
	const void *k_norm_weight_bf16;
} SparkQwen4FlashIndexerWeights;

typedef struct SparkQwen4FlashPleWeights
{
	SparkQwen4FlashLinearView key_proj;
	SparkQwen4FlashLinearView value_proj;
	const void *norm_key_weight_bf16;
	const void *norm_query_weight_bf16;
	const void *norm_conv_weight_bf16;
	const void *conv_weight_bf16;
	const int64_t *layer_multipliers;
	const int64_t *head_vocab_sizes;
	const int64_t *head_offsets;
	const void *ngram_embedding_bf16;
} SparkQwen4FlashPleWeights;

typedef struct SparkQwen4FlashMtpWeights
{
	SparkQwen4FlashLinearView fc;
	const void *embed_norm_weight_bf16;
	const void *hidden_norm_weight_bf16;
	SparkQwen4FlashHcMixer readout_mixer;
	SparkQwen4FlashHcWeights attention_hc;
	SparkQwen4FlashHcWeights mlp_hc;
	SparkQwen4FlashIndexerWeights indexer;
	SparkQwen4FlashAttnLayerWeights attention;
	SparkQwen4FlashMoeWeights moe;
} SparkQwen4FlashMtpWeights;

#include "sparkpipe/family/abi/spark_abi_gdn_state_pool.h"

#include "sparkpipe/family/abi/spark_abi_kv_block_table_view.h"

#include "sparkpipe/family/abi/spark_abi_pipeline_node_context.h"

#include "sparkpipe/family/abi/spark_abi_decode_batch_view.h"

#include "sparkpipe/family/abi/spark_abi_prefill_frame_view.h"

#include "sparkpipe/family/abi/spark_abi_speculative_views.h"

#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_KV_BLOCK_TABLE 0x00000001u
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_DECODE_BATCH_VIEW 0x00000002u
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_INPUT_TRANSPORT 0x00000004u
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_OUTPUT_TRANSPORT 0x00000008u
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_PREFILL_FRAME_VIEW 0x00000010u
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_MTP_DRAFT_AFTER 0x00000020u
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_SPECULATIVE_VERIFY 0x00000040u
#define SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_GDN_RESTORE_FIRST 0x00000080u

#include "sparkpipe/family/abi/spark_abi_frame_context_speculative.h"
#undef SPARK_ABI_TYPE

SparkStatus SparkQwen4FlashResidentDecodeStageInitialize(const SparkFirmwareModuleConfiguration *configuration, const SparkFirmwareModuleHostServices *host_services, void **module_state);
SparkStatus SparkQwen4FlashResidentDecodeStageExecute(void *module_state, SparkModelDriverFrame *frame);
SparkStatus SparkQwen4FlashResidentDecodeStageAdmit(void *module_state, const SparkModelDriverAdmissionRequest *request, SparkModelDriverAdmissionDecision *decision);
SparkStatus SparkQwen4FlashResidentDecodeStageSnapshot(void *module_state, uint32_t program_id, SparkModelDriverRuntimeSnapshot *snapshot);
void SparkQwen4FlashResidentDecodeStageDestroy(void *module_state);

#ifdef __cplusplus
}
#endif

#endif
