#ifndef SPARKPIPE_SPARK_QWEN38_FLASH_STAGE_MODEL_H
#define SPARKPIPE_SPARK_QWEN38_FLASH_STAGE_MODEL_H

#include "sparkpipe/spark_stage_runner_model.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SPARK_QWEN38_FLASH_STAGE_TP_DEGREE 16u
#define SPARK_QWEN38_FLASH_STAGE_PAGE_SLOTS 64u
#define SPARK_QWEN38_FLASH_STAGE_KV_HEADS 2u
#define SPARK_QWEN38_FLASH_STAGE_HEAD_DIM 256u
#define SPARK_QWEN38_FLASH_STAGE_KV_SLOT_BYTES (SPARK_QWEN38_FLASH_STAGE_KV_HEADS * SPARK_QWEN38_FLASH_STAGE_HEAD_DIM * 2u * 2u)
#define SPARK_QWEN38_FLASH_STAGE_QKV_WIDTH 13312u
#define SPARK_QWEN38_FLASH_STAGE_HIDDEN 2560u
#define SPARK_QWEN38_FLASH_STAGE_LAYERS 48u
#define SPARK_QWEN38_FLASH_STAGE_KV_LAYERS 12u
#define SPARK_QWEN38_FLASH_STAGE_INDEX_DIM 128u
#define SPARK_QWEN38_FLASH_STAGE_INDEX_RATIO 4u
#define SPARK_QWEN38_FLASH_STAGE_INDEX_BLOCKS 512u

const SparkStageRunnerModelInterface *SparkQwen38FlashStageModel(void);

#ifdef __cplusplus
}
#endif

#endif
