#pragma once

#include "sparkpipe/spark_dsv4_model.h"

#define SPARK_DSV4_HC_SPLIT_K_ELEMENTS 256u
#define SPARK_DSV4_HC_SPLIT_K_COUNT \
	(SPARK_DSV4_MODEL_BOUNDARY_STREAM_ELEMENTS / SPARK_DSV4_HC_SPLIT_K_ELEMENTS)
#define SPARK_DSV4_HC_SPLIT_K_PARTIALS (1u + SPARK_DSV4_MODEL_HC_MIX_ROWS)
