#pragma once

/*
 * DSV4 Pro in the model-generic SPARK_DSV4_MODEL_* namespace.
 *
 * The generic DSV4 resident-decode module and serving adapter are written
 * against the Flash header's full derived surface. This header provides the
 * identical name space backed by the Pro geometry, so a Pro build is a
 * compile-time header swap (module Makefile MODEL_HEADER override, adapter
 * -include) rather than a source fork.
 *
 * Force-include this INSTEAD of spark_dsv4_model.h for Pro builds; never
 * include both in one translation unit.
 */

#include <stdint.h>

#include "sparkpipe/spark_weight_codec.h"
#include "sparkpipe/spark_dsv4_pro_model.h"

#define SPARK_DSV4_MODEL_ID SPARK_DSV4_PRO_ID
#define SPARK_DSV4_MODEL_SOURCE_REVISION SPARK_DSV4_PRO_SOURCE_REVISION

#define SPARK_DSV4_MODEL_HIDDEN_DIMENSION SPARK_DSV4_PRO_HIDDEN_DIMENSION
#define SPARK_DSV4_MODEL_LAYER_COUNT SPARK_DSV4_PRO_LAYER_COUNT
#define SPARK_DSV4_MODEL_MTP_LAYER_COUNT SPARK_DSV4_PRO_MTP_LAYER_COUNT
#define SPARK_DSV4_MODEL_VOCAB_COUNT SPARK_DSV4_PRO_VOCAB_COUNT
#define SPARK_DSV4_MODEL_QUERY_LORA_RANK SPARK_DSV4_PRO_QUERY_LORA_RANK
#define SPARK_DSV4_MODEL_OUTPUT_LORA_RANK SPARK_DSV4_PRO_OUTPUT_LORA_RANK
#define SPARK_DSV4_MODEL_OUTPUT_GROUP_COUNT SPARK_DSV4_PRO_OUTPUT_GROUP_COUNT
#define SPARK_DSV4_MODEL_INDEX_HEAD_COUNT SPARK_DSV4_PRO_INDEX_HEAD_COUNT
#define SPARK_DSV4_MODEL_INDEX_HEAD_DIMENSION SPARK_DSV4_PRO_INDEX_HEAD_DIMENSION
#define SPARK_DSV4_MODEL_INDEX_TOP_K SPARK_DSV4_PRO_INDEX_TOP_K
#define SPARK_DSV4_MODEL_SLIDING_WINDOW_TOKENS SPARK_DSV4_PRO_SLIDING_WINDOW_TOKENS
#define SPARK_DSV4_MODEL_YARN_FACTOR SPARK_DSV4_PRO_YARN_FACTOR
#define SPARK_DSV4_MODEL_ROUTED_EXPERT_COUNT SPARK_DSV4_PRO_ROUTED_EXPERT_COUNT
#define SPARK_DSV4_MODEL_SHARED_EXPERT_COUNT SPARK_DSV4_PRO_SHARED_EXPERT_COUNT
#define SPARK_DSV4_MODEL_EXPERTS_PER_TOKEN SPARK_DSV4_PRO_EXPERTS_PER_TOKEN
#define SPARK_DSV4_MODEL_EXPERT_INTERMEDIATE_DIMENSION SPARK_DSV4_PRO_EXPERT_INTERMEDIATE_DIMENSION
#define SPARK_DSV4_MODEL_HASH_ROUTED_LAYER_COUNT SPARK_DSV4_PRO_HASH_ROUTED_LAYER_COUNT
#define SPARK_DSV4_MODEL_CHECKPOINT_DSPARK_LAYER_COUNT SPARK_DSV4_PRO_MTP_LAYER_COUNT
#define SPARK_DSV4_MODEL_MAX_POSITIONS SPARK_DSV4_PRO_MAXIMUM_CONTEXT_TOKENS
#define SPARK_DSV4_MODEL_ATTN_QUERY_HEAD_COUNT SPARK_DSV4_PRO_ATTENTION_HEAD_COUNT
#define SPARK_DSV4_MODEL_ATTN_KV_HEAD_COUNT SPARK_DSV4_PRO_KV_HEAD_COUNT
#define SPARK_DSV4_MODEL_HEAD_DIMENSION SPARK_DSV4_PRO_HEAD_DIMENSION
#define SPARK_DSV4_MODEL_ATTN_ROPE_DIMENSION SPARK_DSV4_PRO_QK_ROPE_HEAD_DIMENSION
#define SPARK_DSV4_MODEL_ATTN_YARN_ORIGINAL_POSITIONS SPARK_DSV4_PRO_YARN_ORIGINAL_CONTEXT_TOKENS
#define SPARK_DSV4_MODEL_HC_STREAM_COUNT SPARK_DSV4_PRO_HYPER_CONNECTION_STREAM_COUNT
#define SPARK_DSV4_MODEL_HC_SINKHORN_ITERATIONS SPARK_DSV4_PRO_HYPER_CONNECTION_SINKHORN_ITERATIONS

#define SPARK_DSV4_MODEL_DRIVER_MODEL_ID "deepseek.v4.pro.resident-decode-stage-firmware"
#define SPARK_DSV4_MODEL_DRIVER_REVISION "h7168-l61-dsa-e384k6-hash3-v129280-ga0731-v1"
/* sha256 of examples/model_descriptions/dsv4_pro_resident_decode_stage_firmware*.json */
#define SPARK_DSV4_MODEL_DESCRIPTION_SHA256 "7715ba4b01c533fc203d906cb44a9e645b8a1a164f682c165e06fb1ae394b9d7"
#define SPARK_DSV4_MODEL_DESCRIPTION_SHA256_B1 "d0481e4d22740abe5313132e0269bd8e3d8ddd51f5ba08d16c1591470f709858"
#define SPARK_DSV4_MODEL_MODULE_ID "spark.dsv4.pro.resident_decode_stage.linear_fp8.expert_mxfp4.kv_bf16.h7168.l61.e384.k6.ga0731.v1"
#define SPARK_DSV4_MODEL_MODULE_TARGET "cuda.sm121.dsv4.pro.resident_decode_stage.linear_fp8.expert_mxfp4.kv_bf16"

#define SPARK_DSV4_MODEL_ATTN_HEAD_DIMENSION SPARK_DSV4_MODEL_HEAD_DIMENSION
#define SPARK_DSV4_MODEL_ATTN_ROPE_THETA SPARK_DSV4_PRO_ROPE_THETA
#define SPARK_DSV4_MODEL_COMPRESS_ROPE_THETA SPARK_DSV4_PRO_COMPRESSED_ROPE_THETA
#define SPARK_DSV4_MODEL_ATTN_YARN_FACTOR SPARK_DSV4_PRO_YARN_FACTOR
#define SPARK_DSV4_MODEL_RMS_NORM_EPSILON SPARK_DSV4_PRO_RMS_NORM_EPSILON
#define SPARK_DSV4_MODEL_HC_EPSILON SPARK_DSV4_PRO_HYPER_CONNECTION_EPSILON
#define SPARK_DSV4_MODEL_ROUTED_SCALING_FACTOR SPARK_DSV4_PRO_ROUTED_SCALING_FACTOR
#define SPARK_DSV4_MODEL_SWIGLU_LIMIT SPARK_DSV4_PRO_SWIGLU_LIMIT

#define SPARK_DSV4_MODEL_EXPERT_WEIGHT_CODEC SPARK_DSV4_PRO_EXPERT_WEIGHT_CODEC
#define SPARK_DSV4_MODEL_NON_EXPERT_WEIGHT_CODEC SPARK_DSV4_PRO_NON_EXPERT_WEIGHT_CODEC
#define SPARK_DSV4_MODEL_KV_CACHE_CODEC SPARK_DSV4_PRO_KV_CACHE_CODEC
#define SPARK_DSV4_MODEL_NON_EXPERT_ACTIVATION_CODEC SPARK_DSV4_PRO_NON_EXPERT_ACTIVATION_CODEC
#define SPARK_DSV4_MODEL_EXPERT_ACTIVATION_CODEC SPARK_DSV4_PRO_EXPERT_ACTIVATION_CODEC
#define SPARK_DSV4_MODEL_OUTPUT_COMPOSITION_ACTIVATION_CODEC SPARK_DSV4_PRO_OUTPUT_COMPOSITION_ACTIVATION_CODEC

#define SPARK_DSV4_MODEL_CSA_COMPRESS_RATIO 4u
#define SPARK_DSV4_MODEL_HCA_COMPRESS_RATIO 128u
#define SPARK_DSV4_MODEL_ROPE_BETA_FAST 32u
#define SPARK_DSV4_MODEL_ROPE_BETA_SLOW 1u
#define SPARK_DSV4_MODEL_KV_QUANT_BLOCK 64u
#define SPARK_DSV4_MODEL_FP4_QUANT_BLOCK 32u
#define SPARK_DSV4_MODEL_FP8_MAX 448.0f
#define SPARK_DSV4_MODEL_FP4_MAX 6.0f
#define SPARK_DSV4_MODEL_CSA_OVERLAP_FACTOR 2u
#define SPARK_DSV4_MODEL_BF16_ELEMENT_BYTES 2u

#define SPARK_DSV4_MODEL_HC_MIX_ROWS \
	((2u + SPARK_DSV4_MODEL_HC_STREAM_COUNT) * SPARK_DSV4_MODEL_HC_STREAM_COUNT)
#define SPARK_DSV4_MODEL_ATTN_QUERY_DIMENSION \
	(SPARK_DSV4_MODEL_ATTN_QUERY_HEAD_COUNT * SPARK_DSV4_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_DSV4_MODEL_OUTPUT_GROUP_DIMENSION \
	(SPARK_DSV4_MODEL_ATTN_QUERY_DIMENSION / SPARK_DSV4_MODEL_OUTPUT_GROUP_COUNT)
#define SPARK_DSV4_MODEL_INDEX_DIMENSION \
	(SPARK_DSV4_MODEL_INDEX_HEAD_COUNT * SPARK_DSV4_MODEL_INDEX_HEAD_DIMENSION)
#define SPARK_DSV4_MODEL_BOUNDARY_STREAM_ELEMENTS \
	(SPARK_DSV4_MODEL_HC_STREAM_COUNT * SPARK_DSV4_MODEL_HIDDEN_DIMENSION)

#define SPARK_DSV4_MODEL_LAYER_KIND_SWA 0u
#define SPARK_DSV4_MODEL_LAYER_KIND_CSA 1u
#define SPARK_DSV4_MODEL_LAYER_KIND_HCA 2u
#define SPARK_DSV4_MODEL_LAYER_KIND_INVALID UINT32_MAX

/* Pro backbone ratios: layers 0-1 HCA (128), then alternating CSA (4) and
 * HCA (128); the MTP layer is SWA (0). Mirrors SparkDsv4ProCompressionRatios. */
static const uint16_t SparkDsv4ModelCompressionRatios[SPARK_DSV4_MODEL_LAYER_COUNT] =
{
    128u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u
};

static inline uint16_t SparkDsv4ModelBackboneCompressionRatio(uint32_t layer_index)
{
	if ( layer_index >= SPARK_DSV4_MODEL_LAYER_COUNT )
		return(UINT16_MAX);
	return(SparkDsv4ModelCompressionRatios[layer_index]);
}

static inline uint16_t SparkDsv4ModelMtpCompressionRatio(void)
{
	return(0u);
}

#define SPARK_DSV4_MODEL_MTP_LAYER_KIND SPARK_DSV4_MODEL_LAYER_KIND_SWA

static inline uint32_t SparkDsv4ModelLayerKind(uint32_t layer_index)
{
	uint16_t ratio;
	ratio = SparkDsv4ModelBackboneCompressionRatio(layer_index);
	if ( ratio == 0u )
		return(SPARK_DSV4_MODEL_LAYER_KIND_SWA);
	if ( ratio == SPARK_DSV4_MODEL_CSA_COMPRESS_RATIO )
		return(SPARK_DSV4_MODEL_LAYER_KIND_CSA);
	if ( ratio == SPARK_DSV4_MODEL_HCA_COMPRESS_RATIO )
		return(SPARK_DSV4_MODEL_LAYER_KIND_HCA);
	return(SPARK_DSV4_MODEL_LAYER_KIND_INVALID);
}
