#pragma once

#include <stdint.h>

#include "sparkpipe/spark_weight_codec.h"

/* Generated from the exact source revision by tools/generate_dsv4_contracts.py. */
#define SPARK_DSV4_MODEL_ID "deepseek-ai/DeepSeek-V4-Flash-0731"
#define SPARK_DSV4_MODEL_SOURCE_REVISION "7872f01b1d1fe23eabc4c98b48bffcef5a386062"

#define SPARK_DSV4_MODEL_HIDDEN_DIMENSION 4096u
#define SPARK_DSV4_MODEL_LAYER_COUNT 43u
#define SPARK_DSV4_MODEL_MTP_LAYER_COUNT 0u
#define SPARK_DSV4_MODEL_VOCAB_COUNT 129280u
#define SPARK_DSV4_MODEL_QUERY_LORA_RANK 1024u
#define SPARK_DSV4_MODEL_OUTPUT_LORA_RANK 1024u
#define SPARK_DSV4_MODEL_OUTPUT_GROUP_COUNT 8u
#define SPARK_DSV4_MODEL_INDEX_HEAD_COUNT 64u
#define SPARK_DSV4_MODEL_INDEX_HEAD_DIMENSION 128u
#define SPARK_DSV4_MODEL_INDEX_TOP_K 512u
#define SPARK_DSV4_MODEL_SLIDING_WINDOW_TOKENS 128u
#define SPARK_DSV4_MODEL_YARN_FACTOR 16u
#define SPARK_DSV4_MODEL_ROUTED_EXPERT_COUNT 256u
#define SPARK_DSV4_MODEL_SHARED_EXPERT_COUNT 1u
#define SPARK_DSV4_MODEL_EXPERTS_PER_TOKEN 6u
#define SPARK_DSV4_MODEL_EXPERT_INTERMEDIATE_DIMENSION 2048u
#define SPARK_DSV4_MODEL_HASH_ROUTED_LAYER_COUNT 3u
#define SPARK_DSV4_MODEL_CHECKPOINT_DSPARK_LAYER_COUNT 3u
#define SPARK_DSV4_MODEL_MAX_POSITIONS 1048576u
#define SPARK_DSV4_MODEL_ATTN_QUERY_HEAD_COUNT 64u
#define SPARK_DSV4_MODEL_ATTN_KV_HEAD_COUNT 1u
#define SPARK_DSV4_MODEL_HEAD_DIMENSION 512u
#define SPARK_DSV4_MODEL_ATTN_ROPE_DIMENSION 64u
#define SPARK_DSV4_MODEL_ATTN_YARN_ORIGINAL_POSITIONS 65536u
#define SPARK_DSV4_MODEL_HC_STREAM_COUNT 4u
#define SPARK_DSV4_MODEL_HC_SINKHORN_ITERATIONS 20u
#define SPARK_DSV4_MODEL_DRIVER_MODEL_ID "deepseek.v4.flash.resident-decode-stage-firmware"
#define SPARK_DSV4_MODEL_DRIVER_REVISION "h4096-l43-dsa-e256k6-hash3-v129280-ga0731-v3"
#define SPARK_DSV4_MODEL_DESCRIPTION_SHA256 "cb5c21055aa2184711e4c77f75f279a7039cf3ff2ad515eb5e99f2513c982938"
#define SPARK_DSV4_MODEL_MODULE_ID "spark.dsv4.flash.resident_decode_stage.linear_fp8.expert_mxfp4.kv_bf16.h4096.l43.e256.k6.ga0731.v3"
#define SPARK_DSV4_MODEL_MODULE_TARGET "cuda.sm121.dsv4.flash.resident_decode_stage.linear_fp8.expert_mxfp4.kv_bf16"
#define SPARK_DSV4_MODEL_ATTN_HEAD_DIMENSION SPARK_DSV4_MODEL_HEAD_DIMENSION
#define SPARK_DSV4_MODEL_ATTN_ROPE_THETA 10000.0f
#define SPARK_DSV4_MODEL_COMPRESS_ROPE_THETA 160000.0f
#define SPARK_DSV4_MODEL_ATTN_YARN_FACTOR 16u
#define SPARK_DSV4_MODEL_RMS_NORM_EPSILON 1e-06f
#define SPARK_DSV4_MODEL_HC_EPSILON 1e-06f
#define SPARK_DSV4_MODEL_ROUTED_SCALING_FACTOR 1.5f
#define SPARK_DSV4_MODEL_SWIGLU_LIMIT 10.0f
#define SPARK_DSV4_MODEL_EXPERT_WEIGHT_CODEC SPARK_WEIGHT_CODEC_MXFP4_E2M1
#define SPARK_DSV4_MODEL_NON_EXPERT_WEIGHT_CODEC SPARK_WEIGHT_CODEC_FP8_E4M3
#define SPARK_DSV4_MODEL_KV_CACHE_CODEC SPARK_WEIGHT_CODEC_BF16
#define SPARK_DSV4_MODEL_ACTIVATION_CODEC SPARK_ACTIVATION_CODEC_FP8_E4M3_UE8M0
#define SPARK_DSV4_MODEL_OUTPUT_COMPOSITION_ACTIVATION_CODEC SPARK_ACTIVATION_CODEC_NONE
#define SPARK_DSV4_MODEL_CSA_COMPRESS_RATIO 4u
#define SPARK_DSV4_MODEL_HCA_COMPRESS_RATIO 128u
#define SPARK_DSV4_MODEL_ROPE_BETA_FAST 32u
#define SPARK_DSV4_MODEL_ROPE_BETA_SLOW 1u
#define SPARK_DSV4_MODEL_KV_QUANT_BLOCK 64u
#define SPARK_DSV4_MODEL_FP4_QUANT_BLOCK 32u
#define SPARK_DSV4_MODEL_FP8_MAX 448.0f
#define SPARK_DSV4_MODEL_FP4_MAX 6.0f
#define SPARK_DSV4_MODEL_CSA_OVERLAP_FACTOR 2u
#define SPARK_DSV4_MODEL_BF16_ELEMENT_BYTES 2u
#define SPARK_DSV4_MODEL_HC_MIX_ROWS ((2u + SPARK_DSV4_MODEL_HC_STREAM_COUNT) * SPARK_DSV4_MODEL_HC_STREAM_COUNT)
#define SPARK_DSV4_MODEL_ATTN_QUERY_DIMENSION (SPARK_DSV4_MODEL_ATTN_QUERY_HEAD_COUNT * SPARK_DSV4_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_DSV4_MODEL_OUTPUT_GROUP_DIMENSION (SPARK_DSV4_MODEL_ATTN_QUERY_DIMENSION / SPARK_DSV4_MODEL_OUTPUT_GROUP_COUNT)
#define SPARK_DSV4_MODEL_INDEX_DIMENSION (SPARK_DSV4_MODEL_INDEX_HEAD_COUNT * SPARK_DSV4_MODEL_INDEX_HEAD_DIMENSION)
#define SPARK_DSV4_MODEL_BOUNDARY_STREAM_ELEMENTS (SPARK_DSV4_MODEL_HC_STREAM_COUNT * SPARK_DSV4_MODEL_HIDDEN_DIMENSION)
#define SPARK_DSV4_MODEL_LAYER_KIND_SWA 0u
#define SPARK_DSV4_MODEL_LAYER_KIND_CSA 1u
#define SPARK_DSV4_MODEL_LAYER_KIND_HCA 2u
#define SPARK_DSV4_MODEL_LAYER_KIND_INVALID UINT32_MAX

static const uint16_t SparkDsv4ModelCompressionRatios[43u] =
{
    0u, 0u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u, 4u, 128u,
    4u, 128u, 4u, 128u, 4u, 128u, 4u
};

static inline uint16_t SparkDsv4ModelBackboneCompressionRatio(uint32_t layer_index)
{
	if ( layer_index >= SPARK_DSV4_MODEL_LAYER_COUNT )
		return(UINT16_MAX);
	return(SparkDsv4ModelCompressionRatios[layer_index]);
}

static inline uint16_t SparkDsv4ModelMtpCompressionRatio(void)
{
	return(UINT16_MAX);
}

#define SPARK_DSV4_MODEL_MTP_LAYER_KIND SPARK_DSV4_MODEL_LAYER_KIND_SWA

static inline uint32_t SparkDsv4ModelLayerKind(uint32_t layer_index)
{
	uint16_t ratio;
	ratio = SparkDsv4ModelBackboneCompressionRatio(layer_index);
	if ( ratio == 0u )
		return(SPARK_DSV4_MODEL_LAYER_KIND_SWA);
	if ( ratio == SPARK_DSV4_MODEL_CSA_COMPRESS_RATIO )
		return(SPARK_DSV4_MODEL_LAYER_KIND_CSA);
	if ( ratio == SPARK_DSV4_MODEL_HCA_COMPRESS_RATIO )
		return(SPARK_DSV4_MODEL_LAYER_KIND_HCA);
	return(SPARK_DSV4_MODEL_LAYER_KIND_INVALID);
}
