#pragma once


#include <stdint.h>
#include "inference/kernels/layer_kind.cuh"
#include "sparkpipe/spark_laguna_model.h"

#define LAGUNA_HIDDEN SPARK_LAGUNA_MODEL_HIDDEN_DIMENSION
#define LAGUNA_LAYERS SPARK_LAGUNA_MODEL_LAYER_COUNT
#define LAGUNA_FIRST_ROUTED_LAYER SPARK_LAGUNA_MODEL_FIRST_ROUTED_LAYER
#define LAGUNA_VOCAB SPARK_LAGUNA_MODEL_OUTPUT_VOCAB_COUNT
#define LAGUNA_RESTRICTED_VOCAB SPARK_LAGUNA_MODEL_RESTRICTED_VOCAB_COUNT
#define LAGUNA_RMS_EPSILON SPARK_LAGUNA_MODEL_RMS_NORM_EPSILON

#define LAGUNA_LAYER_IS_SLIDING(layer_index) \
	SPARK_LAGUNA_MODEL_LAYER_IS_SLIDING(layer_index)
#define LAGUNA_LAYER_HEADS(layer_index) \
	SPARK_LAGUNA_MODEL_LAYER_HEAD_COUNT(layer_index)
#define LAGUNA_LAYER_KIND(layer_index) \
	(LAGUNA_LAYER_IS_SLIDING(layer_index) ? LM_LAYER_WINDOW : LM_LAYER_FULL)

#define LAGUNA_HEAD_DIM SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION
#define LAGUNA_KV_HEADS SPARK_LAGUNA_MODEL_TP8_KV_HEAD_COUNT
#define LAGUNA_WINDOW SPARK_LAGUNA_MODEL_SLIDING_WINDOW
#define LAGUNA_ATTN_SCALE SPARK_LAGUNA_MODEL_ATTENTION_SCALE
#define LAGUNA_ROPE_FULL_ROT SPARK_LAGUNA_MODEL_ROPE_FULL_ROTARY_DIMENSION
#define LAGUNA_ROPE_SLIDING_ROT SPARK_LAGUNA_MODEL_ROPE_SLIDING_ROTARY_DIMENSION
#define LAGUNA_ROPE_FULL_THETA SPARK_LAGUNA_MODEL_ROPE_FULL_THETA
#define LAGUNA_ROPE_SLIDING_THETA SPARK_LAGUNA_MODEL_ROPE_SLIDING_THETA
#define LAGUNA_ROPE_FULL_ATTENTION_FACTOR \
	SPARK_LAGUNA_MODEL_ROPE_FULL_ATTENTION_FACTOR
#define LAGUNA_Q_HEADS_FULL SPARK_LAGUNA_MODEL_TP8_Q_HEAD_COUNT_FULL
#define LAGUNA_Q_HEADS_SLIDING SPARK_LAGUNA_MODEL_TP8_Q_HEAD_COUNT_SLIDING
#define LAGUNA_Q_HEADS(layer_index) \
	(LAGUNA_LAYER_IS_SLIDING(layer_index) ? LAGUNA_Q_HEADS_SLIDING : LAGUNA_Q_HEADS_FULL)
#define LAGUNA_ATTN_HEADS LAGUNA_Q_HEADS_SLIDING

#define LAGUNA_EXPERTS SPARK_LAGUNA_MODEL_MOE_EXPERT_COUNT
#define LAGUNA_TOP_K SPARK_LAGUNA_MODEL_MOE_TOP_K
#define LAGUNA_EXPERT_INTERMEDIATE SPARK_LAGUNA_MODEL_MOE_INTERMEDIATE_DIMENSION
#define LAGUNA_DENSE_INTERMEDIATE SPARK_LAGUNA_MODEL_DENSE_INTERMEDIATE_DIMENSION
#define LAGUNA_ROUTED_SCALE SPARK_LAGUNA_MODEL_MOE_ROUTED_SCALING_FACTOR
#define LAGUNA_W1_COMPONENTS SPARK_LAGUNA_MODEL_MOE_W1_COMPONENT_COUNT

#define LAGUNA_FP8_SCALE_BLOCK SPARK_LAGUNA_MODEL_FP8_SCALE_BLOCK

#define LAGUNA_KV_BITS SPARK_LAGUNA_MODEL_KV_BITS
#define LAGUNA_KV_PAGE_SLOTS SPARK_LAGUNA_MODEL_KV_PAGE_SLOTS
#define LAGUNA_KV_SLOT_BYTES SPARK_LAGUNA_MODEL_KV_SLOT_BYTES_TP8

#define LAGUNA_ROUTED_LAYERS (LAGUNA_LAYERS - LAGUNA_FIRST_ROUTED_LAYER)
#define LAGUNA_GATE_UP_DIM (LAGUNA_EXPERT_INTERMEDIATE * LAGUNA_W1_COMPONENTS)
#define LAGUNA_WEIGHT_LAYERS SPARK_LAGUNA_MODEL_WEIGHT_LAYER_COUNT

#define LAGUNA_STAGE_LAYER_COUNT(stage_count,stage_index) \
	SPARK_LAGUNA_MODEL_STAGE_LAYER_COUNT(stage_count,stage_index)

static_assert(LAGUNA_ATTN_HEADS * LAGUNA_HEAD_DIM == 9u * 128u,
	"the sliding rank slice is 9 whole heads at TP8");
static_assert(LAGUNA_Q_HEADS_FULL * LAGUNA_HEAD_DIM == 6u * 128u,
	"the full-attention rank slice is 6 whole heads at TP8");
static_assert(LAGUNA_KV_HEADS == 1u,
	"one kv head per rank at TP8");
static_assert(LAGUNA_Q_HEADS_SLIDING % LAGUNA_KV_HEADS == 0u,
	"the GQA decode groups query heads onto kv heads");

static inline uint32_t LagunaRowsPerExpert(uint32_t tokens)
{
	return(((tokens * LAGUNA_TOP_K) + LAGUNA_EXPERTS - 1u) / LAGUNA_EXPERTS);
}
