#include <stdint.h>

#define SPARK_DSPARK_TARGET_DSV4_PRO_0813
#include "sparkpipe/spark_dspark_drafter.h"

#define PIN(expr) _Static_assert((expr), #expr)

PIN(SPARK_DSPARK_ABI_VERSION == 3u);
PIN(SPARK_DSPARK_BLOCK_SIZE == 5u);
PIN(SPARK_DSPARK_DRAFT_LAYER_COUNT == 3u);
PIN(SPARK_DSPARK_MARKOV_RANK == 512u);
PIN(SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION == 3072u);
PIN(SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT == 128u);
PIN(SPARK_DSPARK_DRAFT_KV_HEAD_COUNT == 1u);
PIN(SPARK_DSPARK_DRAFT_HEAD_DIMENSION == 512u);
PIN(SPARK_DSPARK_HIDDEN_DIMENSION == 7168u);
PIN(SPARK_DSPARK_FULL_VOCAB_SIZE == 129280u);
PIN(SPARK_DSPARK_MASK_TOKEN_ID == 128799u);
PIN(SPARK_DSPARK_MAX_ANCHORS == 1024u);
PIN(SPARK_DSPARK_MAXIMUM_CONTEXT_TOKENS == 1048576u);
PIN(SPARK_DSPARK_AUX_LAYER_COUNT == 3u);
PIN(SPARK_DSV4_PRO_DSPARK_ATTENTION_HEAD_COUNT == 128u);
PIN(SPARK_DSV4_PRO_DSPARK_KV_HEAD_COUNT == 1u);
PIN(SPARK_DSV4_PRO_DSPARK_HEAD_DIMENSION == 512u);
PIN(SPARK_DSV4_PRO_DSPARK_INTERMEDIATE_DIMENSION == 3072u);

int main(void)
{
	static const uint32_t aux_ids[] = SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER;
	const uint32_t expected_aux[] = { 58u, 59u, 60u };
	uint32_t index;
	for (index = 0u; index < SPARK_DSPARK_AUX_LAYER_COUNT; ++index)
	{
		if ( aux_ids[index] != expected_aux[index] )
			return(1);
	}
	return(0);
}
