#!/usr/bin/env python3
"""Differential mutation gate for the stage-pack collapse.

Every family's stage-pack format header is built TWICE from one shared
harness driver: once against the frozen reference revision under
tests/fixtures/stagepack_parity/<family>/ (the last blessed revision, with
the frozen reader mechanics it shipped against) and once against the live
tree. The harness sweeps every field class a pack carries - header fields,
directory entries (kind/layer/format/rows/columns/byte counts/offsets/group
sizes), truncation boundaries, misversions and hostile values - through the
loader's exact decision order and prints one verdict line per case. The two
outputs must be BYTE-IDENTICAL: any drift in what a driver accepts, receives
or rejects - including error codes - fails this gate.

The frozen references are the point: a future edit to a family header or to
runtime/spark_stagepack_reader.h that changes parse behavior trips this gate
instead of silently changing accepted byte streams.

BOTH format generations are pinned:

- generation 3 by the five per-family legs above (frozen reference versus
  live tree) - the historical dialect set is frozen contract;
- generation 4 by the mechanics leg below: tests/test_stagepack_parity_v4.c
  drives the shared reader's versioned dispatch surface (generation gate,
  the ONE accounting table, the normalized entry chain, inventory equality,
  and the per-generation divergence proof) and its verdict stream is
  compared BYTE-IDENTICAL against the frozen golden under
  tests/fixtures/stagepack_parity/_v4/. The golden is minted once with the
  spike and never regenerated by this gate; changing generation-4 behavior
  requires re-minting it deliberately, alongside the change.
"""
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests/fixtures/stagepack_parity"
MECHANICS = FIXTURES / "_mechanics"
V4_DRIVER = ROOT / "tests/test_stagepack_parity_v4.c"
V4_GOLDEN = FIXTURES / "_v4" / "v4_mechanics.golden.txt"

FAMILIES = (
    {
        "name": "dsv4",
        "variants": (
            ("flash", ()),
            ("pro", ('-DSPARK_PARITY_DSV4_MODEL="sparkpipe/spark_dsv4_pro_model.h"', "-DSPARK_PARITY_DSV4_PRO")),
        ),
        "includes": ("model-families/dsv4/include",
                     "modules/dsv4_resident_decode_stage/include",
                     "modules/dsv4_resident_decode_stage/source"),
    },
    {
        "name": "qwen38_27b",
        "variants": (("default", ()),),
        "includes": ("model-families/qwen38_27b/include",
                     "modules/qwen38_27b_resident_decode_stage/include",
                     "modules/qwen38_27b_resident_decode_stage/source"),
    },
    {
        "name": "qwen38_max",
        "variants": (("default", ()),),
        "includes": ("model-families/qwen38_max/include",
                     "modules/qwen38_max_resident_decode_stage/include",
                     "modules/qwen38_max_resident_decode_stage/source"),
    },
    {
        "name": "glm52",
        "variants": (("default", ()),),
        "includes": ("model-families/glm52/include",
                     "modules/glm52_resident_decode_stage/include",
                     "modules/glm52_resident_decode_stage/source"),
    },
)


def compile_driver(driver: Path, out: Path, frozen: bool, extra_flags) -> subprocess.CompletedProcess:
    family = driver_family(driver)
    # Frozen builds put the frozen family header and the frozen mechanics
    # FIRST so "runtime/..." resolves to the revision each frozen header
    # shipped against; firmware/model headers fall through to the live tree.
    command = ["cc", "-std=c11", "-O2", "-I" + str(ROOT / "tests/cuda_stub")]
    if frozen:
        command += ["-I" + str(FIXTURES / family), "-I" + str(MECHANICS)]
    command += ["-I" + str(ROOT), "-I" + str(ROOT / "include")]
    for relative in FAMILY_INCLUDES[family]:
        command += ["-I" + str(ROOT / relative)]
    command += [str(driver), "-o", str(out)] + list(extra_flags)
    return subprocess.run(command, capture_output=True, text=True)


FAMILY_INCLUDES = {family["name"]: family["includes"] for family in FAMILIES}


def driver_family(driver: Path) -> str:
    return driver.stem.replace("test_stagepack_parity_", "")


def run_v4_leg(work: Path) -> str:
    """Build the generation-4 mechanics driver against the live tree and
    return its verdict stream, or raise RuntimeError on any failure."""
    binary = work / "v4_mechanics_live"
    command = ["cc", "-std=c11", "-O2", "-Wall", "-Wextra", "-Werror",
               "-I" + str(ROOT), "-I" + str(ROOT / "include"),
               str(V4_DRIVER), "-o", str(binary)]
    build = subprocess.run(command, capture_output=True, text=True)
    if build.returncode != 0:
        raise RuntimeError(f"v4 leg build failed: {build.stderr[-400:]}")
    run = subprocess.run([str(binary)], capture_output=True)
    if run.returncode != 0:
        raise RuntimeError(f"v4 leg run failed rc={run.returncode}: {run.stderr[-200:]!r}")
    return run.stdout.decode()


def compare_v4_leg(work: Path) -> tuple[bool, str]:
    try:
        live = run_v4_leg(work)
    except RuntimeError as error:
        return False, f"FAIL v4/mechanics: {error}"
    if not V4_GOLDEN.is_file():
        return False, (f"FAIL v4/mechanics: frozen golden missing at {V4_GOLDEN}; "
                       "mint it deliberately from a reviewed verdict stream")
    golden = V4_GOLDEN.read_bytes()
    if golden != live.encode():
        old_lines = golden.decode(errors="replace").splitlines()
        new_lines = live.splitlines()
        divergences = [(a, b) for a, b in zip(old_lines, new_lines) if a != b]
        hint = "" if len(old_lines) == len(new_lines) else \
            f" (line count {len(old_lines)} -> {len(new_lines)}; re-mint deliberately if intended)"
        return False, f"FAIL v4/mechanics: verdict stream diverges from frozen golden{hint} (first: {divergences[:2]})"
    return True, f"PASS v4/mechanics: {len(live.splitlines())} verdicts match frozen golden"


def main() -> int:
    failures = 0
    with tempfile.TemporaryDirectory(prefix="stagepack_parity_") as temporary:
        work = Path(temporary)
        for family in FAMILIES:
            name = family["name"]
            driver = ROOT / "tests" / f"test_stagepack_parity_{name}.c"
            for variant, flags in family["variants"]:
                old_binary = work / f"{name}_{variant}_old"
                new_binary = work / f"{name}_{variant}_new"
                label = f"{name}/{variant}"
                build_old = compile_driver(driver, old_binary, True, flags)
                if build_old.returncode != 0:
                    print(f"FAIL {label}: reference build: {build_old.stderr[-400:]}")
                    failures += 1
                    continue
                build_new = compile_driver(driver, new_binary, False, flags)
                if build_new.returncode != 0:
                    print(f"FAIL {label}: live build: {build_new.stderr[-400:]}")
                    failures += 1
                    continue
                run_old = subprocess.run([str(old_binary)], capture_output=True)
                run_new = subprocess.run([str(new_binary)], capture_output=True)
                if run_old.returncode != 0 or run_new.returncode != 0:
                    print(f"FAIL {label}: harness run rc old={run_old.returncode} new={run_new.returncode}")
                    failures += 1
                    continue
                if run_old.stdout != run_new.stdout:
                    old_lines = run_old.stdout.decode(errors="replace").splitlines()
                    new_lines = run_new.stdout.decode(errors="replace").splitlines()
                    divergences = [(a, b) for a, b in zip(old_lines, new_lines) if a != b]
                    print(f"FAIL {label}: {len(old_lines)} verdicts diverge "
                          f"(first: {divergences[:2]})")
                    failures += 1
                    continue
                print(f"PASS {label}: {len(run_old.stdout.splitlines())} verdicts byte-identical")
        ok, message = compare_v4_leg(work)
        print(message)
        if not ok:
            failures += 1
    if failures:
        print(f"\n{failures} leg(s) diverged from their frozen reference")
        return 1
    print("\nall stage-pack dialects accept/reject identical byte streams as their frozen references; generation 4 matches its frozen golden")
    return 0


if __name__ == "__main__":
    env_tmpdir = ROOT / "build" / "tmp"
    if env_tmpdir.is_dir():
        # Some sandboxes deny cc its default TMPDIR; keep builds in-tree.
        os.environ.setdefault("TMPDIR", str(env_tmpdir))
    sys.exit(main())
