#!/usr/bin/env python3
"""Committed-manifest gates for model-families/k3/smoke_experts.json.

The manifest is machine-generated by tools/k3_smoke_experts.py from two
byte bases (the deployed per-rank pack summaries and the committed T1R
fixtures) and is the M3 batch-preload list under the manager ruling of
2026-09-23: experts[] is the repetition head of the touched census and
the lazy attach covers the strays. This gate holds that contract with
STDLIB ONLY and NO fleet access:

  1. schema: every lane_budget_calc field present with the right type
     and family constants (k3, TP4xPP4, 16 nodes, tp shard, mxfp4);
  2. preload list integrity: deduplicated, in-range (layer, expert)
     pairs, uniform full-model expert bytes derived from k3's own
     chunk-union factor;
  3. provenance: the recorded fixture/prompts/defines identities match
     the committed files byte for byte, the census arithmetic closes,
     and spine/byte bases are positive and consistent with the rank
     records;
  4. the <= 2 GiB/node preload target of the fleet smoke convention
     holds for the committed head (drift fails loud);
  5. the producer module parses the committed defines, recomputes the
     B1 kv floor identically, and enforces the chunk-union law on
     synthetic rank inputs (16 records pass, 15 fail).
"""
import hashlib
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import k3_smoke_experts as producer  # noqa: E402

MANIFEST = ROOT / "model-families/k3/smoke_experts.json"
WSET = ROOT / "model-families/k3/smoke-k3-v1.wset"
FIXTURE_DIR = ROOT / "qualification/t1_reference/k3"
DEFINES = ROOT / "model-families/k3/include/sparkpipe/spark_k3_llm_defines.h"
GIB = 2 ** 30


def check(condition, failures, message):
    if not condition:
        failures.append(message)


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def manifest_gates(document, failures):
    check(document["schema_version"] == 1, failures, "schema_version")
    check(document["family"] == "k3", failures, "family must be k3")
    check(document["topology"] == "TP4xPP4", failures, "topology")
    check(document["nodes"] == 16, failures, "nodes must be 16")
    check(document["expert_shard"] == "tp", failures, "expert_shard")
    check(document["codec"] == "mxfp4", failures, "codec must be mxfp4")
    check(document["prompt_set"] == "k3-t1-prompts-v1", failures,
          "prompt_set id")
    for field in ("spine_bytes", "kv_floor_bytes", "workspace_bytes"):
        value = document[field]
        check(isinstance(value, int) and value > 0, failures,
              f"{field} must be a positive integer")

    defines = producer.parse_defines(str(DEFINES))
    check(defines["layer_count"] == 93, failures, "layer_count defines")
    check(defines["expert_count"] == 896, failures, "expert_count defines")
    check(defines["moe_top_k"] == 16, failures, "moe_top_k defines")

    experts = document["experts"]
    seen = set()
    sizes = set()
    for entry in experts:
        pair = (entry["layer"], entry["expert"])
        check(pair not in seen, failures, f"duplicate expert entry {pair}")
        seen.add(pair)
        check(entry["codec"] == "mxfp4", failures, f"{pair}: codec")
        check(isinstance(entry["bytes"], int) and entry["bytes"] > 0,
              failures, f"{pair}: bytes")
        sizes.add(entry["bytes"])
        check(defines["first_routed_layer"] <= entry["layer"]
              < defines["layer_count"], failures, f"{pair}: layer range")
        check(0 <= entry["expert"] < defines["expert_count"], failures,
              f"{pair}: expert range")
    check(len(sizes) == 1, failures,
          f"expert bytes not uniform: {sorted(sizes)}")

    provenance = document["provenance"]
    bases = provenance["byte_bases"]
    spans = bases["per_rank_expert_span_bytes"]
    check(bases["chunk_union_factor"] == producer.TP, failures,
          "chunk-union factor must be computed as the TP shard count")
    expected = (spans["w1"] + spans["w2"]) * producer.TP
    check(sizes and sizes.pop() == expected, failures,
          "full-model expert bytes != per-rank spans x chunk-union")
    check(bases["full_model_expert_bytes"] == expected, failures,
          "provenance full-model expert bytes disagree")

    check(provenance["llm_defines_sha256"] == sha256_file(DEFINES),
          failures, "llm_defines sha drift")
    fixture_manifest = json.loads(
        (FIXTURE_DIR / "MANIFEST.json").read_text())
    check(provenance["prompts_sha256"] == fixture_manifest["prompts_sha256"],
          failures, "prompts sha drift vs fixture MANIFEST")
    check(provenance["prompts_sha256"]
          == sha256_file(FIXTURE_DIR / "prompts.json"), failures,
          "prompts sha drift vs prompts.json")
    for record in provenance["fixtures"]:
        name = record["fixture"]
        check(name in fixture_manifest["fixtures"], failures,
              f"provenance fixture {name} not in MANIFEST")
        check(sha256_file(FIXTURE_DIR / name)
              == fixture_manifest["fixtures"][name]["sha256"], failures,
              f"fixture {name} bytes drift")

    census = provenance["census"]
    check(census["head_pairs"] == len(experts), failures,
          "head_pairs must equal len(experts)")
    check(0 < census["head_pairs"] < census["touched_pairs"], failures,
          "head must be a strict non-empty subset of the census")
    check(census["route_arrays"] > 0, failures, "route_arrays positivity")
    check(0 < census["head_selection_coverage"] < 1, failures,
          "coverage must be a fraction")
    maximum = census["route_arrays"] * defines["moe_top_k"]
    check(census["selections"] <= maximum, failures,
          "selections exceed positions x top_k")
    check(">= 5" in provenance["cut_rule"], failures,
          "cut rule must state the repetition threshold")
    curve = census.get("coverage_curve", [])
    check(len(curve) >= 2, failures, "coverage curve must be recorded")
    for earlier, later in zip(curve, curve[1:]):
        check(later["pairs"] < earlier["pairs"]
              and later["selection_coverage"]
              < earlier["selection_coverage"], failures,
              "coverage curve must be monotone in the cut")
    ruled = [entry for entry in curve
             if entry["min_positions"] == producer.CUT_RULE]
    check(len(ruled) == 1 and ruled[0]["pairs"] == census["head_pairs"]
          and abs(ruled[0]["selection_coverage"]
                  - census["head_selection_coverage"]) < 1e-3, failures,
          "the ruled cut's curve entry must match the frozen head")
    check(provenance["kv_floor"]["sequences"] == 1, failures,
          "shared-lane smoke keeps B1 (one active sequence)")

    spine = sum(rank["spine_bytes"] for rank in provenance["ranks"])
    check(len(provenance["ranks"]) == 16, failures, "16 rank records")
    check(spine == document["spine_bytes"], failures,
          "spine bytes != sum of rank spine bytes")
    check(all(rank["pack_sha256"] and len(rank["pack_sha256"]) == 64
              for rank in provenance["ranks"]), failures,
          "every rank record needs its pack digest")

    check(document["kv_floor_bytes"]
          == producer.kv_floor_bytes(producer.parse_defines(str(DEFINES))),
          failures, "kv floor must recompute from the defines")

    per_node = len(experts) * expected / document["nodes"]
    check(per_node <= 2 * GIB, failures,
          f"preload working set {per_node / GIB:.2f} GiB/node exceeds "
          "the 2 GiB fleet smoke target")


def synthetic_gates(failures):
    defines = producer.parse_defines(str(DEFINES))
    stage_layers = [[1, 23], [24, 46], [47, 69], [70, 92]]

    def record(stage):
        first, last = stage_layers[stage]
        layers = list(range(first, last + 1))
        return {"pack": f"synthetic.stage{stage}.pack", "pack_bytes": 1,
                "pack_sha256": "0" * 64, "spine_bytes": 1000,
                "expert_layers": len(layers),
                "expert_records": len(layers) * defines["expert_count"] * 2,
                "expert_span_bytes": {
                    str(layer): {"w1": 2924544, "w2": 1462272}
                    for layer in layers}}
    sixteen = [record(stage) for stage in range(4) for _ in range(4)]
    bases = producer.byte_bases(sixteen, defines)
    check(bases["chunk_union_factor"] == 4, failures,
          "16 synthetic ranks must yield chunk-union 4")
    check(bases["spine_bytes"] == 16000, failures,
          "synthetic spine sum")
    check(bases["full_model_expert_bytes"]
          == (2924544 + 1462272) * 4, failures,
          "synthetic full-model expert bytes")
    try:
        producer.byte_bases(sixteen[:15], defines)
        failures.append("15 rank records must fail the chunk-union law")
    except SystemExit:
        pass


def wset_gates(document, failures):
    """The binary working set IS the manifest preload list; the rank-local
    subsets stay inside each PP stage's layers so weightd_warm's manifest
    validation cannot fail closed on a foreign-layer key."""
    if not WSET.is_file():
        failures.append("committed wset missing (run --emit-wset)")
        return
    data = WSET.read_bytes()
    check(len(data) > 0 and len(data) % 8 == 0, failures,
          "wset must be complete key pairs")
    pairs = [struct.unpack_from("<II", data, index)
             for index in range(0, len(data), 8)]
    expected = [(entry["layer"], entry["expert"])
                for entry in document["experts"]]
    check(sorted(pairs) == sorted(expected), failures,
          "wset pairs must equal the manifest experts exactly")
    check(len(set(pairs)) == len(pairs), failures, "wset must be deduplicated")
    check(producer.wset_bytes(pairs) == data, failures,
          "wset bytes must be the producer's canonical encoding")
    check(producer.WSET_NAME == "smoke-k3-v1.wset", failures,
          "wset artifact name drifted")
    stage_table = {0: (0, 23), 1: (24, 46), 2: (47, 69), 3: (70, 92)}
    check(producer.STAGE_LAYERS == tuple(stage_table.values()), failures,
          "stage layer table must match the PP4 runner table "
          "{0,24,47,70} x {24,23,23,23}")
    subsets = [producer.stage_pairs(pairs, stage) for stage in range(4)]
    check(sum(len(subset) for subset in subsets) == len(pairs), failures,
          "per-stage subsets must partition the working set")
    for stage, subset in enumerate(subsets):
        first, last = stage_table[stage]
        check(all(first <= layer <= last for layer, _ in subset), failures,
              f"stage {stage} subset leaks a foreign layer")
        check(len(subset) > 0, failures, f"stage {stage} subset is empty")


def main():
    failures = []
    document = json.loads(MANIFEST.read_text())
    manifest_gates(document, failures)
    synthetic_gates(failures)
    wset_gates(document, failures)
    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        return 1
    census = document["provenance"]["census"]
    print(f"k3 smoke experts gates PASS "
          f"({census['head_pairs']} preload experts of "
          f"{census['touched_pairs']} touched, coverage "
          f"{census['head_selection_coverage']:.3f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
