#!/usr/bin/env python3
"""Committed-manifest gates for model-families/laguna/smoke_experts.json.

The manifest is machine-generated by tools/laguna_smoke_experts.py from
two byte bases (the deployed per-rank .lgsp pack summaries and the
committed T1R fixtures) and is the M3 batch-preload list under the k3
M2 manager ruling of 2026-09-23 applied to laguna: experts[] is the
repetition head of the touched census and the lazy attach covers the
strays. This gate holds that contract with STDLIB ONLY and NO fleet
access:

  1. schema: every lane_budget_calc field present with the right type
     and family constants (laguna, TP8xPP2, 16 nodes, tp shard, bf16);
  2. preload list integrity: deduplicated, in-range (layer, expert)
     pairs, uniform full-model expert bytes derived from laguna's own
     chunk-union factor 8 (every expert lives in all 8 packs of its
     stage's TP group - the intermediate dimension is sharded, not the
     expert identity);
  3. provenance: the recorded fixture/prompts/defines identities match
     the committed files byte for byte, the census arithmetic closes,
     and spine/byte bases are positive and consistent with the rank
     records;
  4. the <= 2 GiB/node preload target of the fleet smoke convention
     holds for the committed head measured the laguna way: the WORST
     STAGE's pairs at the per-rank span (a node preloads only its own
     stage's layers; the full/16 fleet metric undercounts laguna 8x and
     is not the gate);
  5. the producer module parses the committed defines, recomputes the
     B1 kv floor identically, and enforces the chunk-union law on
     synthetic rank inputs (16 records pass, 15 fail).
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import laguna_smoke_experts as producer  # noqa: E402

MANIFEST = ROOT / "model-families/laguna/smoke_experts.json"
FIXTURE_DIR = ROOT / "qualification/t1_reference/laguna"
DEFINES = ROOT / "model-families/laguna/include/sparkpipe/llm_defines.h"
GIB = 2 ** 30
MIB = 2 ** 20


def check(condition, failures, message):
    if not condition:
        failures.append(message)


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def manifest_gates(document, failures):
    check(document["schema_version"] == 1, failures, "schema_version")
    check(document["family"] == "laguna", failures, "family must be laguna")
    check(document["topology"] == "TP8xPP2", failures, "topology")
    check(document["nodes"] == 16, failures, "nodes must be 16")
    check(document["expert_shard"] == "tp", failures, "expert_shard")
    check(document["codec"] == "bf16", failures, "codec must be bf16")
    check(document["prompt_set"] == "laguna-t1-prompts-v1", failures,
          "prompt_set id")
    for field in ("spine_bytes", "kv_floor_bytes", "workspace_bytes"):
        value = document[field]
        check(isinstance(value, int) and value > 0, failures,
              f"{field} must be a positive integer")

    defines = producer.parse_defines(str(DEFINES))
    check(defines["layer_count"] == 48, failures, "layer_count defines")
    check(defines["expert_count"] == 256, failures, "expert_count defines")
    check(defines["moe_top_k"] == 10, failures, "moe_top_k defines")
    check(defines["tp_degree"] == 8, failures, "tp_degree defines")

    experts = document["experts"]
    seen = set()
    sizes = set()
    for entry in experts:
        pair = (entry["layer"], entry["expert"])
        check(pair not in seen, failures, f"duplicate expert entry {pair}")
        seen.add(pair)
        check(entry["codec"] == "bf16", failures, f"{pair}: codec")
        check(isinstance(entry["bytes"], int) and entry["bytes"] > 0,
              failures, f"{pair}: bytes")
        sizes.add(entry["bytes"])
        check(defines["first_routed_layer"] <= entry["layer"]
              < defines["layer_count"], failures, f"{pair}: layer range")
        check(0 <= entry["expert"] < defines["expert_count"], failures,
              f"{pair}: expert range")
    check(len(sizes) == 1, failures,
          f"expert bytes not uniform: {sorted(sizes)}")

    provenance = document["provenance"]
    bases = provenance["byte_bases"]
    spans = bases["per_rank_expert_span_bytes"]
    check(spans["w1"] == 1572864 and spans["w2"] == 786432, failures,
          "per-rank spans must match the placed bf16 pack geometry "
          "(w1 2*128*3072*2, w2 3072*128*2)")
    check(bases["chunk_union_factor"] == producer.TP, failures,
          "chunk-union factor must be computed as the TP group size")
    expected = (spans["w1"] + spans["w2"]) * producer.TP
    check(sizes and sizes.pop() == expected, failures,
          "full-model expert bytes != per-rank spans x chunk-union")
    check(bases["full_model_expert_bytes"] == expected, failures,
          "provenance full-model expert bytes disagree")

    check(provenance["llm_defines_sha256"] == sha256_file(DEFINES),
          failures, "llm_defines sha drift")
    fixture_manifest = json.loads(
        (FIXTURE_DIR / "MANIFEST.json").read_text())
    check(provenance["census"]["prompt_set_sha256"]
          == fixture_manifest["prompts_sha256"], failures,
          "prompts sha drift vs fixture MANIFEST")
    check(provenance["census"]["prompt_set_sha256"]
          == sha256_file(FIXTURE_DIR / "prompts.json"), failures,
          "prompts sha drift vs prompts.json")
    for record in provenance["fixtures"]:
        name = record["fixture"]
        check(name in fixture_manifest["fixtures"], failures,
              f"provenance fixture {name} not in MANIFEST")
        check(sha256_file(FIXTURE_DIR / name)
              == fixture_manifest["fixtures"][name]["sha256"], failures,
              f"fixture {name} bytes drift")

    census = provenance["census"]
    check(census["head_pairs"] == len(experts), failures,
          "head_pairs must equal len(experts)")
    check(0 < census["head_pairs"] < census["touched_pairs"], failures,
          "head must be a strict non-empty subset of the census")
    check(census["route_arrays"] > 0, failures, "route_arrays positivity")
    check(0 < census["head_selection_coverage"] < 1, failures,
          "coverage must be a fraction")
    maximum = census["route_arrays"] * defines["moe_top_k"]
    check(census["selections"] <= maximum, failures,
          "selections exceed positions x top_k")
    check(f">= {producer.CUT_RULE}" in provenance["census"]["cut_rule"],
          failures, "cut rule must state the repetition threshold")
    curve = census.get("coverage_curve", [])
    check(len(curve) >= 2, failures, "coverage curve must be recorded")
    for earlier, later in zip(curve, curve[1:]):
        check(later["pairs"] < earlier["pairs"]
              and later["selection_coverage"]
              < earlier["selection_coverage"], failures,
              "coverage curve must be monotone in the cut")
    ruled = [entry for entry in curve
             if entry["min_positions"] == producer.CUT_RULE]
    check(len(ruled) == 1 and ruled[0]["pairs"] == census["head_pairs"]
          and abs(ruled[0]["selection_coverage"]
                  - census["head_selection_coverage"]) < 1e-3, failures,
          "the ruled cut's curve entry must match the frozen head")
    check(provenance["kv_floor"]["sequences"] == 1, failures,
          "shared-lane smoke keeps B1 (one active sequence)")

    spine = sum(rank["spine_bytes"] for rank in provenance["ranks"])
    check(len(provenance["ranks"]) == 16, failures, "16 rank records")
    check(spine == document["spine_bytes"], failures,
          "spine bytes != sum of rank spine bytes")
    check(all(rank["pack_sha256"] and len(rank["pack_sha256"]) == 64
              for rank in provenance["ranks"]), failures,
          "every rank record needs its pack digest")
    stage0 = [rank for rank in provenance["ranks"]
              if ".stage0." in rank["pack"]]
    stage1 = [rank for rank in provenance["ranks"]
              if ".stage1." in rank["pack"]]
    check(len(stage0) == 8 and len(stage1) == 8, failures,
          "rank records must split 8/8 over the two PP stages")
    check(all(rank["expert_layers"] == 23 for rank in stage0)
          and all(rank["expert_layers"] == 24 for rank in stage1),
          failures, "stage packs own 23/24 routed layers (layer 0 dense)")
    check(sum(rank["expert_bytes"] for rank in stage0)
          == 23 * 256 * expected // producer.TP * 8, failures,
          "stage0 expert bytes must close over the geometry")

    check(document["kv_floor_bytes"]
          == producer.kv_floor_bytes(producer.parse_defines(str(DEFINES))),
          failures, "kv floor must recompute from the defines")

    # the laguna preload gate: the WORST STAGE's head pairs at the
    # per-rank span (a node preloads only its stage's layers)
    per_rank = spans["w1"] + spans["w2"]
    stage_layers = defines["layer_count"] // 2
    per_stage = {0: 0, 1: 0}
    for entry in experts:
        per_stage[entry["layer"] // stage_layers] += 1
    worst = max(per_stage.values()) * per_rank
    check(worst <= 2 * GIB, failures,
          f"worst-stage preload {worst / MIB:.1f} MiB/node exceeds the "
          "2 GiB fleet smoke target")


def synthetic_gates(failures):
    defines = producer.parse_defines(str(DEFINES))
    stage_layers = [[1, 23], [24, 47]]

    def record(stage):
        first, last = stage_layers[stage]
        layers = list(range(first, last + 1))
        return {"pack": f"laguna_stage.tp8.pp2.stage{stage}.rank{stage * 8}.lgsp",
                "pack_bytes": 1,
                "pack_sha256": "0" * 64, "spine_bytes": 1000,
                "expert_bytes": len(layers) * 256 * (1572864 + 786432),
                "expert_layers": len(layers),
                "expert_records": len(layers) * defines["expert_count"] * 2,
                "expert_span_bytes": {
                    str(layer): {"w1": 1572864, "w2": 786432}
                    for layer in layers}}
    sixteen = [record(stage) for stage in (0, 1) for _ in range(8)]
    bases = producer.byte_bases(sixteen, defines)
    check(bases["chunk_union_factor"] == 8, failures,
          "16 synthetic ranks must yield chunk-union 8")
    check(bases["spine_bytes"] == 16000, failures,
          "synthetic spine sum")
    check(bases["full_model_expert_bytes"]
          == (1572864 + 786432) * 8, failures,
          "synthetic full-model expert bytes")
    try:
        producer.byte_bases(sixteen[:15], defines)
        failures.append("15 rank records must fail the summary-count law")
    except SystemExit:
        pass


def main() -> int:
    failures = []
    document = json.loads(MANIFEST.read_text())
    manifest_gates(document, failures)
    synthetic_gates(failures)
    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        return 1
    census = document["provenance"]["census"]
    print(f"laguna smoke experts gates PASS "
          f"({census['head_pairs']} preload experts of "
          f"{census['touched_pairs']} touched, coverage "
          f"{census['head_selection_coverage']:.3f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
