#!/usr/bin/env python3
"""Committed-manifest gates for model-families/ling/smoke_experts.json.

The manifest is machine-generated by tools/ling_smoke_experts.py from two
byte bases (the deployed per-rank pack summaries walked through the
ling .lspk directory contract, and the committed T1R fixtures) and is
the M3 batch-preload list under the manager ruling of 2026-09-23:
experts[] is the repetition head of the touched census and the lazy
attach covers the strays. This gate holds that contract with STDLIB
ONLY and NO fleet access:

  1. schema: every lane_budget_calc field present with the right type
     and family constants (ling, TP16, 16 nodes, tp shard, bf16);
  2. preload list integrity: deduplicated, in-range (layer, expert)
     pairs inside the routed span (2..41 - the packs omit the MTP
     layer), uniform full-model expert bytes derived from ling's own
     chunk-union factor;
  3. provenance: the recorded fixture/prompts/defines identities match
     the committed files byte for byte, the census arithmetic closes,
     the repetition curve is monotone with the ruled cut consistent,
     and the byte bases agree with the placement receipt (spine
     625,519,384 B and expert payload 15,099,494,400 B per rank);
  4. the <= 2 GiB/node preload target of the fleet smoke convention
     holds for the committed head (drift fails loud);
  5. the committed .wset equals the manifest preload list exactly
     (deduplicated sorted u32 pairs - the weightd_warm --wset format);
  6. the producer module parses the committed defines, recomputes the
     B1 kv floor identically (KDA state dominates), and enforces the
     chunk-union law on synthetic rank inputs (16 records pass, 15
     fail);
  7. the pack-format constants stay in lockstep with the packer
     (tools/ling_stagepack.py) - drift fails here, not on the fleet.
"""
import hashlib
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import ling_smoke_experts as producer  # noqa: E402

MANIFEST = ROOT / "model-families/ling/smoke_experts.json"
WSET = ROOT / "model-families/ling/smoke-ling-v1.wset"
FIXTURE_DIR = ROOT / "qualification/t1_reference/ling"
DEFINES = [
    ROOT / "model-families/ling/include/sparkpipe/spark_ling_model.h",
    ROOT / "model-families/ling/include/sparkpipe/llm_defines.h",
    ROOT / "model-families/ling/include/sparkpipe/spark_ling_kv_geometry.h",
]
GIB = 2 ** 30


def check(condition, failures, message):
    if not condition:
        failures.append(message)


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def manifest_gates(document, failures):
    check(document["schema_version"] == 1, failures, "schema_version")
    check(document["family"] == "ling", failures, "family must be ling")
    check(document["topology"] == "TP16", failures, "topology")
    check(document["nodes"] == 16, failures, "nodes must be 16")
    check(document["expert_shard"] == "tp", failures, "expert_shard")
    check(document["codec"] == "bf16", failures, "codec must be bf16")
    check(document["prompt_set"] == "ling-t1-prompts-v1", failures,
          "prompt_set id")
    for field in ("spine_bytes", "kv_floor_bytes", "workspace_bytes"):
        value = document[field]
        check(isinstance(value, int) and value > 0, failures,
              f"{field} must be a positive integer")

    defines = producer.parse_defines(str(ROOT))
    check(defines["layer_count"] == 42, failures, "layer_count defines")
    check(defines["expert_count"] == 512, failures, "expert_count defines")
    check(defines["moe_top_k"] == 8, failures, "moe_top_k defines")
    check(defines["first_routed_layer"] == 2, failures, "first routed layer")
    check(defines["mtp_layer"] == 42, failures,
          "mtp layer aliases the layer count (packs omit it)")

    experts = document["experts"]
    seen = set()
    sizes = set()
    for entry in experts:
        pair = (entry["layer"], entry["expert"])
        check(pair not in seen, failures, f"duplicate expert entry {pair}")
        seen.add(pair)
        check(entry["codec"] == "bf16", failures, f"{pair}: codec")
        check(isinstance(entry["bytes"], int) and entry["bytes"] > 0,
              failures, f"{pair}: bytes")
        sizes.add(entry["bytes"])
        check(defines["first_routed_layer"] <= entry["layer"]
              < defines["mtp_layer"], failures, f"{pair}: layer range")
        check(0 <= entry["expert"] < defines["expert_count"], failures,
              f"{pair}: expert range")
    check(len(sizes) == 1, failures,
          f"expert bytes not uniform: {sorted(sizes)}")

    provenance = document["provenance"]
    spans = provenance["span_bytes"]["per_pair_per_rank"]
    check(provenance["chunk_union_factor"] == producer.TP, failures,
          "chunk-union factor must be computed as the TP shard count")
    expected = (spans["up_gate"] + spans["down"]) * producer.TP
    check(sizes and sizes.pop() == expected, failures,
          "full-model expert bytes != per-rank spans x chunk-union")
    check(provenance["chunk_union_factor"] == 16, failures,
          "ling col-shards the expert inter dimension: every rank pack "
          "holds every pair's shard (computed chunk-union must be 16)")

    check(provenance["defines_sha256"] == hashlib.sha256(
        "".join(path.read_text() for path in DEFINES)
        .encode("utf-8")).hexdigest(), failures, "defines sha drift")
    fixture_manifest = json.loads(
        (FIXTURE_DIR / "MANIFEST.json").read_text())
    check(provenance["prompts_sha256"] == fixture_manifest["prompts_sha256"],
          failures, "prompts sha drift vs fixture MANIFEST")
    check(provenance["prompts_sha256"]
          == sha256_file(FIXTURE_DIR / "prompts.json"), failures,
          "prompts sha drift vs prompts.json")
    for record in provenance["fixtures"]:
        name = record["fixture"]
        check(name in fixture_manifest["fixtures"], failures,
              f"provenance fixture {name} not in MANIFEST")
        check(sha256_file(FIXTURE_DIR / name)
              == fixture_manifest["fixtures"][name]["sha256"], failures,
              f"fixture {name} bytes drift")

    census = provenance["census"]
    check(provenance["expert_pair_count"] == len(experts), failures,
          "expert_pair_count must equal len(experts)")
    check(0 < census["distinct_pairs"], failures, "census positivity")
    check(len(experts) <= census["distinct_pairs"], failures,
          "head must be a subset of the census")
    check(census["positions"] == provenance["cut_rule"]["positions"],
          failures, "position count agreement")
    maximum = census["positions"] * defines["moe_top_k"]
    check(census["selections"] <= maximum, failures,
          "selections exceed positions x top_k")
    check(provenance["cut_rule"]["min_positions"] == producer.CUT_RULE,
          failures, "cut rule must state the repetition threshold")
    curve = census.get("repetition_curve", [])
    check(len(curve) >= 2, failures, "coverage curve must be recorded")
    for earlier, later in zip(curve, curve[1:]):
        check(later["pairs"] < earlier["pairs"]
              and later["selection_coverage"]
              < earlier["selection_coverage"], failures,
              "coverage curve must be monotone in the cut")
    ruled = [entry for entry in curve
             if entry["min_positions"] == producer.CUT_RULE]
    check(len(ruled) == 1 and ruled[0]["pairs"] == len(experts)
          and abs(ruled[0]["selection_coverage"]
                  - census["kept_selection_coverage"]) < 1e-3, failures,
          "the ruled cut's curve entry must match the frozen head")

    check(document["kv_floor_bytes"]
          == producer.kv_floor_bytes(defines), failures,
          "kv floor must recompute from the defines")

    identity = provenance["pack_identity"]
    check(len(identity["packs"]) == 16, failures, "16 pack records")
    check(identity["emission_receipt_spine_bytes"]
          == producer.RECEIPT_SPINE_BYTES, failures, "receipt spine pin")
    check(identity["emission_receipt_expert_payload_bytes"]
          == producer.RECEIPT_EXPERT_BYTES, failures, "receipt payload pin")
    check(document["spine_bytes"]
          == producer.RECEIPT_SPINE_BYTES * 16, failures,
          "full-model spine == per-rank receipt spine x 16 ranks")
    per_node = len(experts) * expected / document["nodes"]
    check(per_node <= 2 * GIB, failures,
          f"preload working set {per_node / GIB:.2f} GiB/node exceeds "
          "the 2 GiB fleet smoke target")
    check(provenance["span_bytes"]["per_node_experts"]
          == len(experts) * (spans["up_gate"] + spans["down"]), failures,
          "per-node expert bytes must equal pairs x per-rank span")


def wset_gates(document, failures):
    """The binary working set IS the manifest preload list."""
    if not WSET.is_file():
        failures.append("committed wset missing (run --emit-wset)")
        return
    data = WSET.read_bytes()
    check(len(data) > 0 and len(data) % 8 == 0, failures,
          "wset must be complete key pairs")
    pairs = [struct.unpack_from("<II", data, index)
             for index in range(0, len(data), 8)]
    expected = [(entry["layer"], entry["expert"])
                for entry in document["experts"]]
    check(pairs == sorted(set(pairs)), failures,
          "wset pairs must be deduplicated and sorted")
    check(pairs == sorted(expected), failures,
          "wset pairs must equal the manifest experts exactly")


def synthetic_gates(failures):
    defines = producer.parse_defines(str(ROOT))
    routed = list(range(defines["first_routed_layer"],
                        defines["mtp_layer"]))

    def record(rank):
        return {"pack": f"ling.bf16.tp16.rank{rank:x}.sp", "pack_bytes": 1,
                "pack_sha256": "0" * 64, "spine_bytes":
                    producer.RECEIPT_SPINE_BYTES,
                "expert_codec": "bf16",
                "expert_layers": len(routed),
                "expert_groups_per_layer": [1024],
                "expert_records": len(routed) * defines["expert_count"] * 2,
                "expert_scale_bytes": 0,
                "expert_span_bytes": {
                    str(layer): {"up_gate": 251658240,
                                 "down": 125829120}
                    for layer in routed}}
    sixteen = [record(rank) for rank in range(16)]
    bases = producer.byte_bases(sixteen, defines)
    check(bases["chunk_union_factor"] == 16, failures,
          "16 synthetic ranks must yield chunk-union 16")
    check(bases["spine_bytes"] == producer.RECEIPT_SPINE_BYTES * 16,
          failures, "synthetic spine sum")
    check(bases["full_model_pair_expert_bytes"]
          == (251658240 + 125829120) // 512 * 16, failures,
          "synthetic full-model per-pair expert bytes")
    try:
        producer.byte_bases(sixteen[:15], defines)
        failures.append("15 rank records must fail the summary count law")
    except SystemExit:
        pass
    mutated = json.loads(json.dumps(sixteen))
    mutated[0]["expert_span_bytes"][str(routed[0])]["up_gate"] += 512
    try:
        producer.byte_bases(mutated, defines)
        failures.append("non-uniform expert spans must fail closed")
    except SystemExit:
        pass


def lockstep_gates(failures):
    """The producer inlines the packer constants so --dump-rank runs on
    bare fleet pythons; parse the packer's own literals (stdlib only -
    importing it would pull numpy) and pin the two files together."""
    import re
    packer = (ROOT / "tools/ling_stagepack.py").read_text()

    def packer_int(name):
        match = re.search(rf"^{name}\b[^=\n]*=\s*(0x[0-9A-Fa-f]+|\d+)\s*"
                          rf"(,|$)", packer, re.M)
        if not match:
            failures.append(f"packer constant {name} not found")
            return None
        return int(match.group(1), 0)

    pairs = (
        ("PACK_MAGIC", "MAGIC"),
        ("PACK_ENTRY_BYTES", "ENTRY_BYTES"),
        ("PACK_HIDDEN", "HIDDEN"),
        ("PACK_VOCAB", "VOCAB"),
        ("PACK_EXPERTS", "EXPERTS"),
        ("PACK_LAYERS", "LAYERS"),
        ("PACK_CODEC_BF16", "CODEC_BF16"),
        ("PACK_CODEC_FP8", "CODEC_FP8"),
    )
    for mine, theirs in pairs:
        expected = packer_int(theirs)
        if expected is not None:
            check(getattr(producer, mine) == expected, failures,
                  f"{mine} drifted from tools/ling_stagepack.py {theirs}")


def main() -> int:
    document = json.loads(MANIFEST.read_text())
    failures = []
    manifest_gates(document, failures)
    wset_gates(document, failures)
    synthetic_gates(failures)
    lockstep_gates(failures)
    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        print(f"\nFAIL ({len(failures)})")
        return 1
    print("PASS ling smoke-expert manifest")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
