#ifndef SPARKPIPE_SPARK_STATUS_H
#define SPARKPIPE_SPARK_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum SparkStatus
{
    SPARK_STATUS_OK = 0,
    SPARK_STATUS_INVALID_ARGUMENT,
    SPARK_STATUS_CAPACITY_EXCEEDED,
    SPARK_STATUS_NOT_FOUND,
    SPARK_STATUS_KV_LEASE_NOT_READY,
    SPARK_STATUS_GRAPH_NOT_AVAILABLE,
    SPARK_STATUS_IO_ERROR,
    SPARK_STATUS_CORRUPT_STAGE_PACK,
    SPARK_STATUS_INTERNAL_ERROR,
    SPARK_STATUS_EVENT_NOT_READY,
    SPARK_STATUS_WIRE_PROTOCOL_ERROR,
    SPARK_STATUS_FAST_RING_NOT_READY,
    SPARK_STATUS_STAGE_PACK_MISMATCH,
    SPARK_STATUS_CANCELLED,
    SPARK_STATUS_DRAINING,
    SPARK_STATUS_SERVICE_REJECTED,
    SPARK_STATUS_REQUEST_CANCELLED,
    SPARK_STATUS_TENSOR_MANIFEST_ERROR
} SparkStatus;

const char *SparkStatusToString(SparkStatus status);

#ifdef __cplusplus
}
#endif

#endif
