#pragma once


#include <stdint.h>


#if SPARK_BATCH_BUCKET != 1u && SPARK_BATCH_BUCKET != 2u && \
	SPARK_BATCH_BUCKET != 4u && SPARK_BATCH_BUCKET != 8u && \
	SPARK_BATCH_BUCKET != 16u && SPARK_BATCH_BUCKET != 32u && \
	SPARK_BATCH_BUCKET != 64u && SPARK_BATCH_BUCKET != 128u && \
	SPARK_BATCH_BUCKET != 256u && SPARK_BATCH_BUCKET != 512u && \
	SPARK_BATCH_BUCKET != 1024u && \
	   \
	SPARK_BATCH_BUCKET != 6u && SPARK_BATCH_BUCKET != 9u && \
	SPARK_BATCH_BUCKET != 11u
#error SPARK_BATCH_BUCKET must name a built variant bucket: 1, 2, 4, 6, 8, 9, 11, 16, 32, 64, 128, 256, 512, 1024
#endif

#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX \
	"spark.dsv4.flash.resident_decode_stage.linear_fp8.expert_mxfp4.kv_bf16.h4096.l43.e256.k6.ga0731"
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX \
	"v4"
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B1 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b1." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B2 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b2." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B4 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b4." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B6 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b6." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B8 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b8." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B9 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b9." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B16 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b16." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B11 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b11." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B32 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b32." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B64 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b64." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B128 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b128." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B256 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b256." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B512 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b512." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B1024 \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_PREFIX ".b1024." \
	SPARK_DSV4_BATCH_VARIANT_MODULE_ID_SUFFIX

#if SPARK_BATCH_BUCKET == 1u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B1
#elif SPARK_BATCH_BUCKET == 2u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B2
#elif SPARK_BATCH_BUCKET == 4u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B4
#elif SPARK_BATCH_BUCKET == 6u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B6
#elif SPARK_BATCH_BUCKET == 8u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B8
#elif SPARK_BATCH_BUCKET == 9u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B9
#elif SPARK_BATCH_BUCKET == 16u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B16
#elif SPARK_BATCH_BUCKET == 11u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B11
#elif SPARK_BATCH_BUCKET == 32u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B32
#elif SPARK_BATCH_BUCKET == 64u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B64
#elif SPARK_BATCH_BUCKET == 128u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B128
#elif SPARK_BATCH_BUCKET == 256u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B256
#elif SPARK_BATCH_BUCKET == 512u
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B512
#else
#define SPARK_DSV4_BATCH_TUNING_MODULE_ID SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B1024
#endif

#define SPARK_DSV4_BATCH_TUNING_SEQUENCE_CEILING \
	SPARK_BATCH_BUCKET

#define SPARK_DSV4_BATCH_TUNING_GROUPED_PEAK_ROWS \
	((((SPARK_BATCH_BUCKET) * SPARK_DSV4_MODEL_EXPERTS_PER_TOKEN + \
	SPARK_DSV4_MODEL_ROUTED_EXPERT_COUNT - 1u) / \
	SPARK_DSV4_MODEL_ROUTED_EXPERT_COUNT) * 2u)
#define SPARK_DSV4_BATCH_TUNING_GROUPED_TILE_M \
	(SPARK_DSV4_BATCH_TUNING_GROUPED_PEAK_ROWS <= 16u ? 16u : \
	SPARK_DSV4_BATCH_TUNING_GROUPED_PEAK_ROWS <= 32u ? 32u : 64u)

static inline uint32_t SparkDsv4BatchVariantBucketCeiling(
	uint32_t max_active_sequence_count)
{
	if (max_active_sequence_count == 0u ||
		max_active_sequence_count > 1024u)
		return(0u);
	if (max_active_sequence_count <= 1u)
		return(1u);
	if (max_active_sequence_count <= 2u)
		return(2u);
	if (max_active_sequence_count <= 4u)
		return(4u);
	if (max_active_sequence_count <= 8u)
		return(8u);
	if (max_active_sequence_count <= 16u)
		return(16u);
	if (max_active_sequence_count <= 32u)
		return(32u);
	if (max_active_sequence_count <= 64u)
		return(64u);
	if (max_active_sequence_count <= 128u)
		return(128u);
	if (max_active_sequence_count <= 256u)
		return(256u);
	if (max_active_sequence_count <= 512u)
		return(512u);
	return(1024u);
}

static inline const char *SparkDsv4BatchVariantModuleId(
	uint32_t batch_bucket)
{
	switch (batch_bucket)
	{
	case 1u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B1);
	case 2u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B2);
	case 4u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B4);
	case 6u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B6);
	case 8u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B8);
	case 9u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B9);
	case 16u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B16);
	case 11u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B11);
	case 32u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B32);
	case 64u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B64);
	case 128u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B128);
	case 256u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B256);
	case 512u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B512);
	case 1024u:
		return(SPARK_DSV4_BATCH_VARIANT_MODULE_ID_B1024);
	default:
		return(0);
	}
}
