#pragma once

#include <stdint.h>

#include "sparkpipe/spark_qwen38_27b_resident_decode_stage_firmware.h"


#define SPARK_QWEN38_27B_DFLASH2_FRAME_KV_ROWS 2056u

#define SPARK_QWEN38_27B_DSPARK_LAYER_COUNT 5u
#define SPARK_QWEN38_27B_DSPARK_ATTN_QUERY_HEADS 32u
#define SPARK_QWEN38_27B_DSPARK_ATTN_KV_HEADS 8u
#define SPARK_QWEN38_27B_DSPARK_ATTN_HEAD_DIMENSION 128u
#define SPARK_QWEN38_27B_DSPARK_ATTN_ROPE_DIMENSION 64u
#define SPARK_QWEN38_27B_DSPARK_FFN_INTERMEDIATE 17408u
#define SPARK_QWEN38_27B_DSPARK_BLOCK_SIZE 8u
#define SPARK_QWEN38_27B_DSPARK_TARGET_TAP_COUNT 5u
#define SPARK_QWEN38_27B_DSPARK_SELECTOR_RANK 256u
#define SPARK_QWEN38_27B_DSPARK_SELECTOR_TOP_K 16u
#define SPARK_QWEN38_27B_DSPARK_CONV_KERNEL_SIZE 2u
#define SPARK_QWEN38_27B_DSPARK_CONV_GROUP_SIZE 16u
#define SPARK_QWEN38_27B_DSPARK_SLIDING_WINDOW 2048u
#define SPARK_QWEN38_27B_DSPARK_MASK_TOKEN_ID 248070u

typedef enum SparkQwen38_27bDsparkTensorKind
{
	SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_QUERY = 0,
	SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_KEY = 1,
	SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_VALUE = 2,
	SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_OUTPUT = 3,
	SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_QUERY_NORM = 4,
	SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_KEY_NORM = 5,
	SPARK_QWEN38_27B_DSPARK_TENSOR_ATTENTION_NORM = 6,
	SPARK_QWEN38_27B_DSPARK_TENSOR_MLP_NORM = 7,
	SPARK_QWEN38_27B_DSPARK_TENSOR_FFN_GATE = 8,
	SPARK_QWEN38_27B_DSPARK_TENSOR_FFN_UP = 9,
	SPARK_QWEN38_27B_DSPARK_TENSOR_FFN_DOWN = 10,
	SPARK_QWEN38_27B_DSPARK_TENSOR_PROJECTOR = 11,
	SPARK_QWEN38_27B_DSPARK_TENSOR_SELECTOR_PRED = 12,
	SPARK_QWEN38_27B_DSPARK_TENSOR_SELECTOR_SUCC = 13,
	SPARK_QWEN38_27B_DSPARK_TENSOR_SELECTOR_HIDDEN_PROJ = 14,
	SPARK_QWEN38_27B_DSPARK_TENSOR_FINAL_NORM = 15,
	SPARK_QWEN38_27B_DSPARK_TENSOR_HIDDEN_NORM = 16,
	SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_ATTN_BASE = 17,
	SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_ATTN_PROJ = 18,
	SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_MLP_BASE = 19,
	SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_MLP_PROJ = 20,
	SPARK_QWEN38_27B_DSPARK_TENSOR_KIND_COUNT = 21
} SparkQwen38_27bDsparkTensorKind;

#define SPARK_QWEN38_27B_DSPARK_CONV_BASE_ROWS 2u
#define SPARK_QWEN38_27B_DSPARK_CONV_BASE_COLUMNS (SPARK_QWEN38_27B_DSPARK_CONV_KERNEL_SIZE * SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION)
#define SPARK_QWEN38_27B_DSPARK_CONV_PROJ_ROWS (2u * SPARK_QWEN38_27B_DSPARK_CONV_KERNEL_SIZE * (SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION / SPARK_QWEN38_27B_DSPARK_CONV_GROUP_SIZE))

static inline void SparkQwen38_27bDsparkKindShape(
	uint32_t kind,
	uint32_t *rows,
	uint32_t *columns)
{
	switch (kind)
	{
	case SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_QUERY:
		*rows = SPARK_QWEN38_27B_DSPARK_ATTN_QUERY_HEADS * SPARK_QWEN38_27B_DSPARK_ATTN_HEAD_DIMENSION;
		*columns = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_KEY:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_VALUE:
		*rows = SPARK_QWEN38_27B_DSPARK_ATTN_KV_HEADS * SPARK_QWEN38_27B_DSPARK_ATTN_HEAD_DIMENSION;
		*columns = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_OUTPUT:
		*rows = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		*columns = SPARK_QWEN38_27B_DSPARK_ATTN_QUERY_HEADS * SPARK_QWEN38_27B_DSPARK_ATTN_HEAD_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_QUERY_NORM:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_ATTN_KEY_NORM:
		*rows = 1u;
		*columns = SPARK_QWEN38_27B_DSPARK_ATTN_HEAD_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_ATTENTION_NORM:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_MLP_NORM:
		*rows = 1u;
		*columns = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_FFN_GATE:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_FFN_UP:
		*rows = SPARK_QWEN38_27B_DSPARK_FFN_INTERMEDIATE;
		*columns = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_FFN_DOWN:
		*rows = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		*columns = SPARK_QWEN38_27B_DSPARK_FFN_INTERMEDIATE;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_PROJECTOR:
		*rows = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		*columns = SPARK_QWEN38_27B_DSPARK_TARGET_TAP_COUNT * SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_SELECTOR_PRED:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_SELECTOR_SUCC:
		*rows = SPARK_QWEN38_27B_MODEL_OUTPUT_VOCAB_COUNT;
		*columns = SPARK_QWEN38_27B_DSPARK_SELECTOR_RANK;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_SELECTOR_HIDDEN_PROJ:
		*rows = SPARK_QWEN38_27B_DSPARK_SELECTOR_RANK;
		*columns = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_FINAL_NORM:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_HIDDEN_NORM:
		*rows = 1u;
		*columns = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_ATTN_BASE:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_MLP_BASE:
		*rows = SPARK_QWEN38_27B_DSPARK_CONV_BASE_ROWS;
		*columns = SPARK_QWEN38_27B_DSPARK_CONV_BASE_COLUMNS;
		return;
	case SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_ATTN_PROJ:
	case SPARK_QWEN38_27B_DSPARK_TENSOR_CONV_MLP_PROJ:
		*rows = SPARK_QWEN38_27B_DSPARK_CONV_PROJ_ROWS;
		*columns = SPARK_QWEN38_27B_MODEL_HIDDEN_DIMENSION;
		return;
	default:
		*rows = 0u;
		*columns = 0u;
		return;
	}
}
