#ifndef SPARKPIPE_SPARK_MUSE_GLIMMER_MODEL_H
#define SPARKPIPE_SPARK_MUSE_GLIMMER_MODEL_H

#include "llm_defines.h"

#define SPARK_MUSE_GLIMMER_MODEL_MTP_LAYER_COUNT 0u

#define SPARK_MUSE_GLIMMER_MODEL_LAYER_IS_FULL_ATTENTION(layer_index) \
	(((layer_index) % SPARK_MUSE_GLIMMER_MODEL_ATTENTION_PERIOD) == SPARK_MUSE_GLIMMER_MODEL_FULL_ATTENTION_PHASE)

#define SPARK_MUSE_GLIMMER_MODEL_ATTN_QUERY_HEAD_COUNT SPARK_MUSE_GLIMMER_MODEL_ATTENTION_HEAD_COUNT
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_HEAD_COUNT SPARK_MUSE_GLIMMER_MODEL_KV_HEAD_COUNT
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION SPARK_MUSE_GLIMMER_MODEL_HEAD_DIMENSION
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_ROPE_DIMENSION SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_QK_NORM_EPSILON SPARK_MUSE_GLIMMER_MODEL_RMS_NORM_EPSILON
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_SCALE (1.0f / sqrtf((float)SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION))
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_QUERY_DIMENSION \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_QUERY_HEAD_COUNT * SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_DIMENSION \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_HEAD_COUNT * SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_QUERY_GROUP \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_QUERY_HEAD_COUNT / SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_HEAD_COUNT)
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_CACHE_TOKEN_ELEMENTS \
	(2u * SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_DIMENSION)

#define SPARK_MUSE_GLIMMER_MODEL_KV_SHARD_COUNT(tp_degree) \
	(((uint32_t)(tp_degree) < SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_HEAD_COUNT) \
		? (uint32_t)(tp_degree) \
		: SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_HEAD_COUNT)
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_HEAD_COUNT \
		/ SPARK_MUSE_GLIMMER_MODEL_KV_SHARD_COUNT(tp_degree))
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_RANK_KV_HEAD_BASE(tp_degree, tp_rank) \
	((((uint32_t)(tp_rank)) * SPARK_MUSE_GLIMMER_MODEL_ATTN_KV_HEAD_COUNT) \
		/ (uint32_t)(tp_degree))
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_QUERY_HEAD_COUNT(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_QUERY_HEAD_COUNT / (uint32_t)(tp_degree))
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_QUERY_DIMENSION(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_QUERY_HEAD_COUNT(tp_degree) \
		* SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_KV_DIMENSION(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
		* SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_QUERY_GATE_DIMENSION(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_QUERY_HEAD_COUNT(tp_degree) \
		* 2u * SPARK_MUSE_GLIMMER_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_MUSE_GLIMMER_MODEL_QGKV_LOCAL_ROWS(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_QUERY_GATE_DIMENSION(tp_degree) \
		+ (2u * SPARK_MUSE_GLIMMER_MODEL_ATTN_LOCAL_KV_DIMENSION(tp_degree)))
#define SPARK_MUSE_GLIMMER_MODEL_MLP_LOCAL_INTERMEDIATE(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_INTERMEDIATE_DIMENSION / (uint32_t)(tp_degree))
#define SPARK_MUSE_GLIMMER_MODEL_VOCAB_LOCAL_ROWS(tp_degree) \
	(SPARK_MUSE_GLIMMER_MODEL_OUTPUT_VOCAB_COUNT / (uint32_t)(tp_degree))

#define SPARK_MUSE_GLIMMER_MODEL_BF16_ELEMENT_BYTES 2u
#define SPARK_MUSE_GLIMMER_MODEL_HIDDEN_BF16_BYTES \
	(SPARK_MUSE_GLIMMER_MODEL_HIDDEN_DIMENSION * SPARK_MUSE_GLIMMER_MODEL_BF16_ELEMENT_BYTES)

#endif
