#pragma once
#include <stdint.h>
#include "inference/kernels/layer_kind.cuh"


#define K3_HIDDEN 7168u
#define K3_LAYERS 93u
#define K3_VOCAB 163840u
#define K3_RMS_EPSILON 1e-05f
#define K3_LORA_RMS_EPSILON 1e-06f
#define K3_MAX_CONTEXT 1048576u

#define K3_FIRST_ROUTED_LAYER 1u
#define K3_EXPERTS 896u
#define K3_TOP_K 16u
#define K3_SHARED_EXPERTS 2u
#define K3_EXPERT_INTERMEDIATE 3072u
#define K3_ROUTED_EXPERT_HIDDEN 3584u
#define K3_DENSE_INTERMEDIATE 33792u
#define K3_ROUTED_SCALE 1.0f

#define K3_MLA_HEADS 96u
#define K3_KV_LORA_RANK 512u
#define K3_Q_LORA_RANK 1536u
#define K3_QK_NOPE_DIM 128u
#define K3_QK_UNROTATED_DIM 64u
#define K3_V_HEAD_DIM 128u
#define K3_MLA_QK_SCALE 0.07216878365f
#define K3_MLA_USE_NOPE 1u
#define K3_MLA_OUTPUT_GATE 1u


#define K3_KDA_HEADS 96u
#define K3_KDA_KEY_DIM 128u
#define K3_KDA_VALUE_DIM 128u
#define K3_KDA_CONV_KERNEL 4u
#define K3_KDA_GATE_LOWER_BOUND -5.0f
#define K3_KDA_FULL_RANK_GATE 1u

#define K3_ATTNRES_MAX_SOURCES 9u

#define K3_ATTNRES_BANK_BYTES \
	(K3_ATTNRES_MAX_SOURCES * K3_HIDDEN * (K3_KV_BITS / 8u))

#define K3_ATTNRES_BANK_SLOTS K3_ATTNRES_MAX_SOURCES
#define K3_ATTNRES_PARTIAL_BYTES (K3_HIDDEN * (K3_KV_BITS / 8u))

#define K3_ATTNRES_BLOCK_SIZE 12u

#define K3_SITU_BETA 4.0f
#define K3_SITU_LINEAR_BETA 25.0f

#define K3_MXFP4_GROUP 32u

#define K3_MTP_LAYERS 0u

#define K3_KV_BITS 16u
#define K3_KV_PAGE_SLOTS 64u

#define K3_KDA_A_LOG_SOURCE_HEADS 128u
#define K3_KDA_QK_L2NORM 1u
#define K3_KDA_STATE_ELEMENT_BYTES 4u
#define K3_KDA_CONV_WINDOW_BYTES \
	(((2u * K3_KDA_HEADS * K3_KDA_KEY_DIM) + (K3_KDA_HEADS * K3_KDA_VALUE_DIM)) \
		* K3_KDA_CONV_KERNEL * (K3_KV_BITS / 8u))
#define K3_KDA_STATE_SLOT_BYTES \
	(K3_KDA_HEADS * K3_KDA_KEY_DIM * K3_KDA_VALUE_DIM * K3_KDA_STATE_ELEMENT_BYTES)
#define K3_KDA_STATE_BYTES (K3_KDA_STATE_SLOT_BYTES + K3_KDA_CONV_WINDOW_BYTES)

#define K3_KDA_STATE_ELEMENT_BYTES_BF16 2u
#define K3_KDA_STATE_SLOT_BYTES_BF16 \
	(K3_KDA_HEADS * K3_KDA_KEY_DIM * K3_KDA_VALUE_DIM \
		* K3_KDA_STATE_ELEMENT_BYTES_BF16)
#define K3_KDA_LAYER_COUNT 69u
#define K3_MLA_LAYER_COUNT 24u

#define K3_LAYER_IS_LINEAR(layer) \
	((((layer) % 4u) != 3u) && ((layer) != (K3_LAYERS - 1u)))

#define K3_LAYER_KIND(layer) \
	(K3_LAYER_IS_LINEAR(layer) ? LM_LAYER_RECURRENT : LM_LAYER_LATENT)
