#pragma once


#include <assert.h>
#include <stdint.h>

#include "inference/llms/kimi_k3/config.h"

#define K3_DSPARK_BLOCK_SIZE 7u
#define K3_DSPARK_DRAFT_LAYER_COUNT 5u
#define K3_DSPARK_AUX_LAYER_COUNT 5u
#define K3_DSPARK_AUX_LAYER_IDS_INITIALIZER { 7u, 23u, 51u, 67u, 83u }

#define K3_DSPARK_DRAFT_ATTENTION_HEAD_COUNT 64u
#define K3_DSPARK_DRAFT_KV_HEAD_COUNT 16u
#define K3_DSPARK_DRAFT_HEAD_DIMENSION 64u
#define K3_DSPARK_DRAFT_INTERMEDIATE_DIMENSION 14336u
#define K3_DSPARK_HIDDEN_DIMENSION K3_HIDDEN
#define K3_DSPARK_FULL_VOCAB_SIZE K3_VOCAB
#define K3_DSPARK_RMS_EPSILON 1e-05f

#define K3_DSPARK_DRAFT_ROPE_THETA 10000.0f
#define K3_DSPARK_DRAFT_HEAD_ROPE_DIM K3_DSPARK_DRAFT_HEAD_DIMENSION

#define K3_DSPARK_MASK_TOKEN_ID 163824u

#define K3_DSPARK_MARKOV_RANK 256u

#define K3_DSPARK_CONFIDENCE_WITH_MARKOV 1u
#define K3_DSPARK_CONFIDENCE_INPUT_DIMENSION \
	(K3_DSPARK_HIDDEN_DIMENSION + K3_DSPARK_MARKOV_RANK)

#define K3_DSPARK_CONFIDENCE_MILLI_ONE 1000u

static_assert(K3_DSPARK_AUX_LAYER_COUNT <= K3_LAYERS,
	"a tap cannot name a layer the target does not have");
static_assert(K3_DSPARK_MASK_TOKEN_ID < K3_VOCAB,
	"the mask token is a real vocabulary id");

#define K3_DSPARK_TRIM_MIN_BATCH 8u

#define K3_DSPARK_VERIFY_POSITIONS (K3_DSPARK_BLOCK_SIZE + 1u)

