#ifndef SPARKPIPE_SPARK_GLM5_NEXT_KV_GEOMETRY_H
#define SPARKPIPE_SPARK_GLM5_NEXT_KV_GEOMETRY_H

#include "sparkpipe/spark_kv_cache.h"
#include "sparkpipe/spark_glm5_next_model.h"


#define SPARK_GLM5_NEXT_KV_LAYOUT SPARK_KV_CACHE_LAYOUT_COMPRESSED_KEY_VALUE
#define SPARK_GLM5_NEXT_KV_LAYER_COUNT SPARK_GLM5_NEXT_MODEL_DSA_LAYER_COUNT
#define SPARK_GLM5_NEXT_KV_COMPRESSED_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_MLA_LATENT_DIMENSION
#define SPARK_GLM5_NEXT_KV_POSITION_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_MLA_QK_ROPE_HEAD_DIMENSION
#define SPARK_GLM5_NEXT_KV_BYTES_PER_SCALAR 2u
#define SPARK_GLM5_NEXT_KV_FP8_SCALE_BLOCK_SIZE \
	SPARK_GLM5_NEXT_MODEL_FP8_SCALE_BLOCK
#define SPARK_GLM5_NEXT_KV_BLOCK_TOKEN_COUNT 64u
#define SPARK_GLM5_NEXT_KV_ARENA_KV_HEAD_COUNT 1u
#define SPARK_GLM5_NEXT_KV_ARENA_HEAD_DIM \
	SPARK_GLM5_NEXT_MODEL_MLA_KV_A_DIMENSION
#define SPARK_GLM5_NEXT_KV_INDEX_KEY_LAYER_COUNT 0u
#define SPARK_GLM5_NEXT_KV_INDEX_KEY_DIMENSION 0u
#define SPARK_GLM5_NEXT_KV_INDEX_KEY_BYTES_PER_SCALAR 0u

static inline void SparkGlm5NextKvFillCapacityRequest(
	SparkKvCacheCapacityRequest *request)
{
	request->abi_version = SPARK_KV_CACHE_ABI_VERSION;
	request->descriptor_bytes =
		SPARK_KV_CACHE_CAPACITY_REQUEST_DESCRIPTOR_BYTES;
	request->layout = SPARK_GLM5_NEXT_KV_LAYOUT;
	request->layer_count = SPARK_GLM5_NEXT_KV_LAYER_COUNT;
	request->head_count = 0u;
	request->query_key_head_dimension = 0u;
	request->value_head_dimension = 0u;
	request->compressed_dimension = SPARK_GLM5_NEXT_KV_COMPRESSED_DIMENSION;
	request->position_dimension = SPARK_GLM5_NEXT_KV_POSITION_DIMENSION;
	request->bytes_per_scalar = SPARK_GLM5_NEXT_KV_BYTES_PER_SCALAR;
	request->fp8_scale_block_size = SPARK_GLM5_NEXT_KV_FP8_SCALE_BLOCK_SIZE;
	request->index_key_layer_count = SPARK_GLM5_NEXT_KV_INDEX_KEY_LAYER_COUNT;
	request->index_key_dimension = SPARK_GLM5_NEXT_KV_INDEX_KEY_DIMENSION;
	request->index_key_bytes_per_scalar =
		SPARK_GLM5_NEXT_KV_INDEX_KEY_BYTES_PER_SCALAR;
}

#endif
