#include <stdio.h>
#include "spark_minimax_h3_stagepack_format.h"

static const uint32_t kinds[] = {
	SPARK_MINIMAX_H3_ENCODER_EMBEDDING,
	SPARK_MINIMAX_H3_ENCODER_ATTENTION_QUERY,
	SPARK_MINIMAX_H3_ENCODER_ATTENTION_KEY,
	SPARK_MINIMAX_H3_ENCODER_ATTENTION_VALUE,
	SPARK_MINIMAX_H3_ENCODER_ATTENTION_OUTPUT,
	SPARK_MINIMAX_H3_ENCODER_ATTENTION_QUERY_NORM,
	SPARK_MINIMAX_H3_ENCODER_ATTENTION_KEY_NORM,
	SPARK_MINIMAX_H3_ENCODER_MLP_GATE,
	SPARK_MINIMAX_H3_ENCODER_MLP_UP,
	SPARK_MINIMAX_H3_ENCODER_MLP_DOWN,
	SPARK_MINIMAX_H3_ENCODER_INPUT_NORM,
	SPARK_MINIMAX_H3_ENCODER_POST_NORM,
	SPARK_MINIMAX_H3_DIT_CONTEXT_EMBEDDER,
	SPARK_MINIMAX_H3_DIT_TIME_EMBED_LINEAR_1,
	SPARK_MINIMAX_H3_DIT_TIME_EMBED_LINEAR_2,
	SPARK_MINIMAX_H3_DIT_PROJ_IN,
	SPARK_MINIMAX_H3_DIT_PROJ_OUT,
	SPARK_MINIMAX_H3_DIT_AUDIO_PROJ_IN,
	SPARK_MINIMAX_H3_DIT_AUDIO_PROJ_OUT,
	SPARK_MINIMAX_H3_DIT_FINAL_NORM,
	SPARK_MINIMAX_H3_DIT_NORM_OUT_LINEAR,
	SPARK_MINIMAX_H3_DIT_ATTENTION_QUERY,
	SPARK_MINIMAX_H3_DIT_ATTENTION_KEY,
	SPARK_MINIMAX_H3_DIT_ATTENTION_VALUE,
	SPARK_MINIMAX_H3_DIT_ATTENTION_OUTPUT,
	SPARK_MINIMAX_H3_DIT_ATTENTION_QUERY_NORM,
	SPARK_MINIMAX_H3_DIT_ATTENTION_KEY_NORM,
	SPARK_MINIMAX_H3_DIT_FFN_GATE_UP,
	SPARK_MINIMAX_H3_DIT_FFN_DOWN,
	SPARK_MINIMAX_H3_DIT_ADALN,
	SPARK_MINIMAX_H3_DIT_NORM1,
	SPARK_MINIMAX_H3_DIT_NORM2,
	SPARK_MINIMAX_H3_VIDEO_PROJ_IN,
	SPARK_MINIMAX_H3_VIDEO_REGISTER_TOKENS,
	SPARK_MINIMAX_H3_VIDEO_FINAL_NORM,
	SPARK_MINIMAX_H3_VIDEO_PROJ_OUT,
	SPARK_MINIMAX_H3_VIDEO_POST_QUANT_CONV,
	SPARK_MINIMAX_H3_VIDEO_ATTENTION_QUERY,
	SPARK_MINIMAX_H3_VIDEO_ATTENTION_KEY,
	SPARK_MINIMAX_H3_VIDEO_ATTENTION_VALUE,
	SPARK_MINIMAX_H3_VIDEO_ATTENTION_OUTPUT,
	SPARK_MINIMAX_H3_VIDEO_FFN_GATE_UP,
	SPARK_MINIMAX_H3_VIDEO_FFN_DOWN,
	SPARK_MINIMAX_H3_VIDEO_NORM1,
	SPARK_MINIMAX_H3_VIDEO_NORM2,
	SPARK_MINIMAX_H3_VIDEO_SCALE1,
	SPARK_MINIMAX_H3_VIDEO_SCALE2,
	SPARK_MINIMAX_H3_AUDIO_IN_PROJ,
	SPARK_MINIMAX_H3_AUDIO_PRE_ATTN_QKV,
	SPARK_MINIMAX_H3_AUDIO_PRE_ATTN_PROJ,
	SPARK_MINIMAX_H3_AUDIO_PRE_MLP,
	SPARK_MINIMAX_H3_AUDIO_PRE_NORM,
	SPARK_MINIMAX_H3_AUDIO_CONV_PRE,
	SPARK_MINIMAX_H3_AUDIO_RESBLOCK_CONV1,
	SPARK_MINIMAX_H3_AUDIO_RESBLOCK_CONV2,
	SPARK_MINIMAX_H3_AUDIO_RESBLOCK_SNAKE,
	SPARK_MINIMAX_H3_AUDIO_RESBLOCK_FILTER,
	SPARK_MINIMAX_H3_AUDIO_UPS,
	SPARK_MINIMAX_H3_AUDIO_CONV_POST,
	SPARK_MINIMAX_H3_AUDIO_POST_SNAKE,
	SPARK_MINIMAX_H3_AUDIO_POST_FILTER
};

int main(void)
{
	SparkStagePackTensorShape shape;
	uint32_t index;
	int32_t failures;
	failures = 0;
	for (index=0u; index<sizeof(kinds)/sizeof(kinds[0]); index++)
	{
		if ( SparkMinimaxH3StagePackTensorShapeOf(kinds[index],&shape) < 0 )
		{
			failures++;
			printf("FAIL unresolved kind=0x%04x\n",kinds[index]);
		}
	}
	if ( SparkMinimaxH3StagePackResolvedShape(
		SPARK_MINIMAX_H3_DIT_ATTENTION_QUERY,
		SPARK_MINIMAX_H3_DIT_TOTAL_BLOCK_COUNT,0u,&shape) == 0 )
	{
		failures++;
		printf("FAIL dit block out of range accepted\n");
	}
	if ( SparkMinimaxH3StagePackResolvedShape(
		SPARK_MINIMAX_H3_ENCODER_ATTENTION_QUERY,
		SPARK_MINIMAX_H3_ENCODER_LAYER_COUNT,0u,&shape) == 0 )
	{
		failures++;
		printf("FAIL encoder layer out of range accepted\n");
	}
	if ( SparkMinimaxH3StagePackResolvedShape(
		SPARK_MINIMAX_H3_VIDEO_ATTENTION_QUERY,
		SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_LAYER_COUNT,0u,&shape) == 0 )
	{
		failures++;
		printf("FAIL video block out of range accepted\n");
	}
	if ( SparkMinimaxH3StagePackResolvedShape(
		SPARK_MINIMAX_H3_DIT_ATTENTION_QUERY,
		(7u << SPARK_MINIMAX_H3_STAGEPACK_SUB_SHIFT),0u,&shape) != 0 )
	{
		failures++;
		printf("FAIL sub-entry rejected\n");
	}
	if ( SparkMinimaxH3StagePackPayloadBytes(
		SPARK_STAGEPACK_FORMAT_WEIGHT_BF16,
		SPARK_MINIMAX_H3_DIT_QKV_DIMENSION,
		SPARK_MINIMAX_H3_DIT_HIDDEN_DIMENSION) !=
		(uint64_t)SPARK_MINIMAX_H3_DIT_QKV_DIMENSION *
		SPARK_MINIMAX_H3_DIT_HIDDEN_DIMENSION * 2u )
	{
		failures++;
		printf("FAIL bf16 payload bytes\n");
	}
	if ( failures != 0 )
		return(1);
	printf("OK %zu declared kinds resolve, range + sub + payload checks pass\n",
		sizeof(kinds)/sizeof(kinds[0]));
	return(0);
}
