#pragma once

#include <stdint.h>

#define SPARK_LLM_HIDDEN_DIMENSION 8192u
#define SPARK_LLM_LAYER_COUNT 92u
#define SPARK_LLM_VOCAB_COUNT 248320u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT SPARK_LLM_VOCAB_COUNT
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS 262144u
#define SPARK_LLM_RMS_NORM_EPSILON 1e-06f
#ifndef SPARK_LLM_MTP_LAYER_COUNT
#define SPARK_LLM_MTP_LAYER_COUNT 1u
#endif

#define SPARK_LLM_ATTN_HEAD_COUNT 64u
#define SPARK_LLM_KV_HEAD_COUNT 4u
#define SPARK_LLM_HEAD_DIMENSION 256u
#define SPARK_LLM_ATTN_QUERY_HEAD_COUNT SPARK_LLM_ATTN_HEAD_COUNT
#define SPARK_LLM_ATTN_KV_HEAD_COUNT SPARK_LLM_KV_HEAD_COUNT
#define SPARK_LLM_ATTN_HEAD_DIMENSION SPARK_LLM_HEAD_DIMENSION
#define SPARK_LLM_ROPE_DIMENSION 64u
#define SPARK_LLM_ROPE_THETA 10000000.0f
#define SPARK_LLM_ATTN_QUERY_DIMENSION \
	(SPARK_LLM_ATTN_QUERY_HEAD_COUNT * SPARK_LLM_ATTN_HEAD_DIMENSION)
#define SPARK_LLM_ATTN_KV_DIMENSION \
	(SPARK_LLM_ATTN_KV_HEAD_COUNT * SPARK_LLM_ATTN_HEAD_DIMENSION)
#define SPARK_LLM_ATTN_CACHE_TOKEN_ELEMENTS \
	(2u * SPARK_LLM_ATTN_KV_DIMENSION)
#define SPARK_LLM_ATTN_KV_SHARD_COUNT(tp_degree) \
	(((tp_degree) < SPARK_LLM_ATTN_KV_HEAD_COUNT) \
		? (uint32_t)(tp_degree) \
		: SPARK_LLM_ATTN_KV_HEAD_COUNT)
#define SPARK_LLM_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_ATTN_KV_HEAD_COUNT \
		/ SPARK_LLM_ATTN_KV_SHARD_COUNT(tp_degree))
#define SPARK_LLM_ATTN_RANK_KV_HEAD_BASE(tp_degree, tp_rank) \
	((((uint32_t)(tp_rank)) * SPARK_LLM_ATTN_KV_HEAD_COUNT) \
		/ (uint32_t)(tp_degree))
#define SPARK_LLM_ATTN_LOCAL_KV_DIMENSION(tp_degree) \
	(SPARK_LLM_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
		* SPARK_LLM_ATTN_HEAD_DIMENSION)
#define SPARK_LLM_ATTN_HEADS_PER_CTA 2u

#define SPARK_LLM_ATTN_PERIOD 4u
#define SPARK_LLM_FULL_ATTENTION_PHASE 3u
#define SPARK_LLM_LAYER_IS_GDN(layer_index) \
	(((layer_index) % SPARK_LLM_ATTN_PERIOD) != SPARK_LLM_FULL_ATTENTION_PHASE)
#define SPARK_LLM_GDN_LAYER_COUNT 69u
#define SPARK_LLM_FULL_ATTENTION_LAYER_COUNT 23u

#define SPARK_LLM_GDN_KEY_HEAD_COUNT 16u
#define SPARK_LLM_GDN_VALUE_HEAD_COUNT 128u
#define SPARK_LLM_GDN_HEAD_KEY_DIMENSION 128u
#define SPARK_LLM_GDN_HEAD_VALUE_DIMENSION 128u
#define SPARK_LLM_GDN_VALUE_HEADS_PER_KEY_HEAD \
	(SPARK_LLM_GDN_VALUE_HEAD_COUNT / SPARK_LLM_GDN_KEY_HEAD_COUNT)
#define SPARK_LLM_GDN_LOCAL_KEY_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_GDN_KEY_HEAD_COUNT / (tp_degree))
#define SPARK_LLM_GDN_LOCAL_VALUE_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_GDN_VALUE_HEAD_COUNT / (tp_degree))
#define SPARK_LLM_GDN_LOCAL_QK_DIMENSION(tp_degree) \
	(SPARK_LLM_GDN_LOCAL_KEY_HEAD_COUNT(tp_degree) \
		* SPARK_LLM_GDN_HEAD_KEY_DIMENSION)
#define SPARK_LLM_GDN_LOCAL_VALUE_DIMENSION(tp_degree) \
	(SPARK_LLM_GDN_LOCAL_VALUE_HEAD_COUNT(tp_degree) \
		* SPARK_LLM_GDN_HEAD_VALUE_DIMENSION)
#define SPARK_LLM_GDN_LOCAL_CONV_CHANNELS(tp_degree) \
	((2u * SPARK_LLM_GDN_LOCAL_QK_DIMENSION(tp_degree)) \
		+ SPARK_LLM_GDN_LOCAL_VALUE_DIMENSION(tp_degree))
#define SPARK_LLM_GDN_CONV_KERNEL 4u
#define SPARK_LLM_GDN_QK_DIMENSION \
	(SPARK_LLM_GDN_KEY_HEAD_COUNT * SPARK_LLM_GDN_HEAD_KEY_DIMENSION)
#define SPARK_LLM_GDN_VALUE_DIMENSION \
	(SPARK_LLM_GDN_VALUE_HEAD_COUNT * SPARK_LLM_GDN_HEAD_VALUE_DIMENSION)
#define SPARK_LLM_GDN_CONV_CHANNELS \
	((2u * SPARK_LLM_GDN_QK_DIMENSION) + SPARK_LLM_GDN_VALUE_DIMENSION)
#define SPARK_LLM_GDN_CONV_TAIL_COLUMNS (SPARK_LLM_GDN_CONV_KERNEL - 1u)
#define SPARK_LLM_GDN_CHUNK_TOKENS 64u

#define SPARK_LLM_ROUTED_EXPERT_COUNT 512u
#define SPARK_LLM_EXPERTS_PER_TOKEN 10u
#define SPARK_LLM_SHARED_EXPERT_COUNT 1u
#define SPARK_LLM_EXPERT_INTERMEDIATE_DIMENSION 2048u
#define SPARK_LLM_MXFP4_GROUP_SIZE 32u
#define SPARK_LLM_SWIGLU_LIMIT 10.0f
#define SPARK_LLM_ROUTER_SORT_CAPACITY 512u

#define SPARK_LLM_BF16_ELEMENT_BYTES 2u
#define SPARK_LLM_HIDDEN_BF16_BYTES \
	(SPARK_LLM_HIDDEN_DIMENSION * SPARK_LLM_BF16_ELEMENT_BYTES)

#define SPARK_LLM_NODE_CONTEXT_ABI_VERSION 1u
#define SPARK_LLM_FRAME_CONTEXT_ABI_VERSION 3u
#define SPARK_LLM_PREFILL_FRAME_VIEW_ABI_VERSION 1u
#define SPARK_LLM_MTP_DRAFT_VIEW_ABI_VERSION 1u
#define SPARK_LLM_GDN_SNAPSHOT_VIEW_ABI_VERSION 1u
#define SPARK_LLM_MAX_MTP_DRAFT_TOKENS 8u
#define SPARK_LLM_MAX_GDN_SNAPSHOT_SLOTS 8u
#define SPARK_LLM_GDN_STATE_POOL_ABI_VERSION 1u
#define SPARK_LLM_KV_BLOCK_TABLE_ABI_VERSION 1u
#define SPARK_LLM_LINEAR_VIEW_ABI_VERSION 1u
#define SPARK_LLM_DECODE_BATCH_VIEW_ABI_VERSION 1u
#define SPARK_LLM_MAX_STAGE_COUNT 32u
#define SPARK_LLM_HEAD_SCREEN_CAP 4096u
#define SPARK_LLM_HEAD_SHADOW_GROUP 32u
#define SPARK_LLM_MAX_PIPELINE_SLOT_COUNT 4u
#define SPARK_LLM_MAX_ACTIVE_SEQUENCE_COUNT 512u
#ifndef SPARK_LLM_KV_BLOCK_TOKENS
#define SPARK_LLM_KV_BLOCK_TOKENS 64u
#endif
#define SPARK_LLM_KV_STAGING_RECORDS 16u
#define SPARK_LLM_KV_POLL_BOUND 10000u
#define SPARK_LLM_KV_MAX_BLOCKS_PER_LANE 4096u
#define SPARK_LLM_KV_RESTORE_PRIORITY_IMMEDIATE 0u
#define SPARK_LLM_KV_RESTORE_PRIORITY_SPECULATIVE 1u
#define SPARK_LLM_KV_BATCH_IDLE 0u
#define SPARK_LLM_KV_BATCH_SUBMITTED 1u
#define SPARK_LLM_KV_BATCH_READY 2u
#define SPARK_LLM_INVALID_TOKEN_ID UINT32_MAX
#define SPARK_LLM_NO_BLOCK 0xffffffffu

#define SPARK_LLM_WEIGHT_FORMAT_BF16 0u
#define SPARK_LLM_WEIGHT_FORMAT_F32 1u
#define SPARK_LLM_WEIGHT_FORMAT_U32 2u
#define SPARK_LLM_WEIGHT_FORMAT_MXFP4_E2M1 3u
#define SPARK_LLM_WEIGHT_FORMAT_FP8_E4M3_F32B128 4u
#define SPARK_LLM_WEIGHT_FORMAT_NVFP4_PACKED 8u

#define SPARK_LLM_FRAME_CONTEXT_FLAG_KV_BLOCK_TABLE 0x00000001u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_DECODE_BATCH_VIEW 0x00000002u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_HIDDEN_INPUT_TRANSPORT 0x00000004u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_HIDDEN_OUTPUT_TRANSPORT 0x00000008u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_PREFILL_FRAME_VIEW 0x00000010u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_MTP_DRAFT_AFTER 0x00000020u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_SPECULATIVE_VERIFY 0x00000040u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_GDN_RESTORE_FIRST 0x00000080u

#define SPARK_LLM_FAMILY_TAG                    qwen38_max
#define SPARK_LLM_KV_POOL_TOKENS                4194304u
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH 256u
#define SPARK_LLM_GLOBAL_ATTENTION_PHASE        3u
#define SPARK_LLM_ROPE_YARN_FACTOR              1.0f
#define SPARK_LLM_END_OF_TEXT_TOKEN_ID          248044u
#define SPARK_LLM_MLA_HEAD_COUNT                64u
#define SPARK_LLM_MLA_QUERY_A_DIMENSION         0u
#define SPARK_LLM_MLA_LATENT_DIMENSION          0u
#define SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION    256u
#define SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION    0u
#define SPARK_LLM_MLA_V_HEAD_DIMENSION          256u
#define SPARK_LLM_FIRST_ROUTED_LAYER            0u
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION  0u
#define SPARK_LLM_KDA_LAYER_COUNT               69u
#define SPARK_LLM_KDA_HEAD_COUNT                128u
#define SPARK_LLM_KDA_HEAD_KEY_DIMENSION        128u
#define SPARK_LLM_KDA_HEAD_VALUE_DIMENSION      128u
#define SPARK_LLM_KDA_CONV_KERNEL               4u
#define SPARK_LLM_KDA_CHUNK_TOKENS              64u
#define SPARK_LLM_KDA_STATE_ELEMENT_BYTES       4u
#define SPARK_LLM_KDA_GATE_LOWER_BOUND          0.0f
#define SPARK_LLM_KDA_LOW_RANK_GATE_BOTTLENECK  0u
#define SPARK_LLM_TILE_N                        128u
#define SPARK_LLM_TILE_STAGES                   2u
#define SPARK_LLM_LAYER_THREADS                 256u
#define SPARK_LLM_MTP_ENABLED                   1u
#define SPARK_LLM_MTP_DRAFT_DEPTH               1u
#define SPARK_LLM_TP_COLLECTIVE_BACKEND         0u
#define SPARK_LLM_TP_DEGREE                     16u
#define SPARK_LLM_STAGE_INDEX                   0u
#define SPARK_LLM_MISS_PACK_STRIDE              512u
#define SPARK_LLM_MISS_RING_CAPACITY            64u
#define SPARK_LLM_ROUTE_UNION_MAX               2400u
#define SPARK_LLM_ROUTE_UNION_TRIM              1888u
#define SPARK_LLM_ADAPTER_DESCRIPTOR            "spark.qwen38_max.serving-adapter.tp16.nvfp4.v1"
#define SPARK_LLM_MODEL_SOURCE_URI              "Qwen/Qwen3.8-2.4T-A95B"
#define SPARK_LLM_MODEL_REVISION                "nvfp4-radixark-bf16-spine"
