// Qwen 3.8's model geometry for the host tiers, mirroring the values the
// qwen38 driver family will pin in inference/llms/qwen_3_8/config.h. The
// firmware config is the source of truth; a conformance check holds the two
// in lockstep, same as the qwen38_27b family.
#ifndef SPARKPIPE_SPARK_QWEN38_MAX_MODEL_H
#define SPARKPIPE_SPARK_QWEN38_MAX_MODEL_H

#define SPARK_QWEN38_MAX_MODEL_HIDDEN_DIMENSION 8192u
#define SPARK_QWEN38_MAX_MODEL_LAYER_COUNT 92u
#define SPARK_QWEN38_MAX_MODEL_VOCAB_COUNT 248320u
#define SPARK_QWEN38_MAX_MODEL_ATTENTION_HEAD_COUNT 64u
#define SPARK_QWEN38_MAX_MODEL_KV_HEAD_COUNT 4u
#define SPARK_QWEN38_MAX_MODEL_HEAD_DIMENSION 256u
#define SPARK_QWEN38_MAX_MODEL_GDN_KEY_HEAD_COUNT 16u
#define SPARK_QWEN38_MAX_MODEL_GDN_VALUE_HEAD_COUNT 128u

// Wider geometry vocabulary for the resident decode stage module.
#define SPARK_QWEN38_MAX_MODEL_OUTPUT_VOCAB_COUNT SPARK_QWEN38_MAX_MODEL_VOCAB_COUNT
#define SPARK_QWEN38_MAX_MODEL_MAXIMUM_CONTEXT_TOKENS 262144u
#define SPARK_QWEN38_MAX_MODEL_RMS_NORM_EPSILON 1e-06f
#define SPARK_QWEN38_MAX_MODEL_MTP_LAYER_COUNT 1u

#define SPARK_QWEN38_MAX_MODEL_ATTENTION_PERIOD 4u
#define SPARK_QWEN38_MAX_MODEL_FULL_ATTENTION_PHASE 3u
#define SPARK_QWEN38_MAX_MODEL_LAYER_IS_GDN(layer_index) \
	(((layer_index) % SPARK_QWEN38_MAX_MODEL_ATTENTION_PERIOD) != SPARK_QWEN38_MAX_MODEL_FULL_ATTENTION_PHASE)
#define SPARK_QWEN38_MAX_MODEL_GDN_LAYER_COUNT 69u
#define SPARK_QWEN38_MAX_MODEL_FULL_ATTENTION_LAYER_COUNT 23u

#define SPARK_QWEN38_MAX_MODEL_GDN_HEAD_KEY_DIMENSION 128u
#define SPARK_QWEN38_MAX_MODEL_GDN_HEAD_VALUE_DIMENSION 128u
#define SPARK_QWEN38_MAX_MODEL_GDN_VALUE_HEADS_PER_KEY_HEAD \
	(SPARK_QWEN38_MAX_MODEL_GDN_VALUE_HEAD_COUNT / SPARK_QWEN38_MAX_MODEL_GDN_KEY_HEAD_COUNT)
#define SPARK_QWEN38_MAX_MODEL_GDN_CONV_KERNEL 4u
#define SPARK_QWEN38_MAX_MODEL_GDN_QK_DIMENSION \
	(SPARK_QWEN38_MAX_MODEL_GDN_KEY_HEAD_COUNT * SPARK_QWEN38_MAX_MODEL_GDN_HEAD_KEY_DIMENSION)
#define SPARK_QWEN38_MAX_MODEL_GDN_VALUE_DIMENSION \
	(SPARK_QWEN38_MAX_MODEL_GDN_VALUE_HEAD_COUNT * SPARK_QWEN38_MAX_MODEL_GDN_HEAD_VALUE_DIMENSION)
#define SPARK_QWEN38_MAX_MODEL_GDN_CONV_CHANNELS \
	((2u * SPARK_QWEN38_MAX_MODEL_GDN_QK_DIMENSION) + SPARK_QWEN38_MAX_MODEL_GDN_VALUE_DIMENSION)
#define SPARK_QWEN38_MAX_MODEL_GDN_CONV_TAIL_COLUMNS (SPARK_QWEN38_MAX_MODEL_GDN_CONV_KERNEL - 1u)
#define SPARK_QWEN38_MAX_MODEL_GDN_CHUNK_TOKENS 64u

#define SPARK_QWEN38_MAX_MODEL_ATTN_QUERY_HEAD_COUNT SPARK_QWEN38_MAX_MODEL_ATTENTION_HEAD_COUNT
#define SPARK_QWEN38_MAX_MODEL_ATTN_KV_HEAD_COUNT SPARK_QWEN38_MAX_MODEL_KV_HEAD_COUNT
#define SPARK_QWEN38_MAX_MODEL_ATTN_HEAD_DIMENSION SPARK_QWEN38_MAX_MODEL_HEAD_DIMENSION
#define SPARK_QWEN38_MAX_MODEL_ATTN_ROPE_DIMENSION 64u
#define SPARK_QWEN38_MAX_MODEL_ATTN_ROPE_THETA 10000000.0f
#define SPARK_QWEN38_MAX_MODEL_ATTN_QUERY_DIMENSION \
	(SPARK_QWEN38_MAX_MODEL_ATTN_QUERY_HEAD_COUNT * SPARK_QWEN38_MAX_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_QWEN38_MAX_MODEL_ATTN_KV_DIMENSION \
	(SPARK_QWEN38_MAX_MODEL_ATTN_KV_HEAD_COUNT * SPARK_QWEN38_MAX_MODEL_ATTN_HEAD_DIMENSION)
#define SPARK_QWEN38_MAX_MODEL_ATTN_CACHE_TOKEN_ELEMENTS \
	(2u * SPARK_QWEN38_MAX_MODEL_ATTN_KV_DIMENSION)

// Attention KV sharding at a TP degree: whole-kv-head cuts only. When the
// degree exceeds the kv head count (TP16 with 4 kv heads) the kv heads
// replicate across consecutive rank groups - each rank's query heads sit
// inside one GQA group either way, so ranks sharing a head also share a
// cache shard and the output all-reduce still sums exactly once per head.
#define SPARK_QWEN38_MAX_MODEL_ATTN_KV_SHARD_COUNT(tp_degree) \
	(((tp_degree) < SPARK_QWEN38_MAX_MODEL_ATTN_KV_HEAD_COUNT) \
		? (uint32_t)(tp_degree) \
		: SPARK_QWEN38_MAX_MODEL_ATTN_KV_HEAD_COUNT)
#define SPARK_QWEN38_MAX_MODEL_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
	(SPARK_QWEN38_MAX_MODEL_ATTN_KV_HEAD_COUNT \
		/ SPARK_QWEN38_MAX_MODEL_ATTN_KV_SHARD_COUNT(tp_degree))
/* The rank's first kv head, in whole-head units. For degrees dividing the
 * kv head count this is the plain rank*local block; for replicating
 * degrees it is the shared group's head (ranks 0..3 -> head 0 at TP16). */
#define SPARK_QWEN38_MAX_MODEL_ATTN_RANK_KV_HEAD_BASE(tp_degree, tp_rank) \
	((((uint32_t)(tp_rank)) * SPARK_QWEN38_MAX_MODEL_ATTN_KV_HEAD_COUNT) \
		/ (uint32_t)(tp_degree))
#define SPARK_QWEN38_MAX_MODEL_ATTN_LOCAL_KV_DIMENSION(tp_degree) \
	(SPARK_QWEN38_MAX_MODEL_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
		* SPARK_QWEN38_MAX_MODEL_ATTN_HEAD_DIMENSION)

// Routed MoE, pinned against config.json at the contract revision.
#define SPARK_QWEN38_MAX_MODEL_ROUTED_EXPERT_COUNT 512u
#define SPARK_QWEN38_MAX_MODEL_EXPERTS_PER_TOKEN 10u
#define SPARK_QWEN38_MAX_MODEL_SHARED_EXPERT_COUNT 1u
#define SPARK_QWEN38_MAX_MODEL_EXPERT_INTERMEDIATE_DIMENSION 2048u
#define SPARK_QWEN38_MAX_MODEL_MXFP4_GROUP_SIZE 32u
#define SPARK_QWEN38_MAX_MODEL_SWIGLU_LIMIT 10.0f

#define SPARK_QWEN38_MAX_MODEL_BF16_ELEMENT_BYTES 2u
#define SPARK_QWEN38_MAX_MODEL_HIDDEN_BF16_BYTES \
	(SPARK_QWEN38_MAX_MODEL_HIDDEN_DIMENSION * SPARK_QWEN38_MAX_MODEL_BF16_ELEMENT_BYTES)

#endif
