#pragma once

#include <stdint.h>

#include "sparkpipe/spark_qwen36_resident_decode_stage_firmware.h"

/*
 * DSpark drafter pack: the 5-layer full-attention DSpark drafter
 * (Doopeworld/Qwen3.8-27B-DSpark-vLLM), packed by
 * tools/qwen36_dspark_stagepack.py into the SAME wire layout as the qwen36
 * target pack (spark_qwen36_stagepack_format.h): magic Q6SP, header 26I2Q,
 * entry 6I4Q. The drafter shares the target's token embedding and lm_head, so
 * this pack carries only the 5-layer backbone + projector + Markov/confidence
 * heads (62 tensors, all BF16).
 *
 * Header field repurposing (mirror the packer): mxfp4_group_size -> block_size
 * (7), mtp_layer_count -> target_tap_count (5). Everything else (hidden 5120,
 * attn 40 Q / 8 KV x 128, ffn 10240, vocab 248320) is literal.
 */

#define SPARK_QWEN36_DSPARK_LAYER_COUNT 5u
#define SPARK_QWEN36_DSPARK_ATTN_QUERY_HEADS 40u
#define SPARK_QWEN36_DSPARK_ATTN_KV_HEADS 8u
#define SPARK_QWEN36_DSPARK_ATTN_HEAD_DIMENSION 128u
#define SPARK_QWEN36_DSPARK_ATTN_ROPE_DIMENSION 64u
#define SPARK_QWEN36_DSPARK_FFN_INTERMEDIATE 10240u
#define SPARK_QWEN36_DSPARK_BLOCK_SIZE 7u
#define SPARK_QWEN36_DSPARK_TARGET_TAP_COUNT 5u
#define SPARK_QWEN36_DSPARK_MARKOV_RANK 256u
#define SPARK_QWEN36_DSPARK_CONFIDENCE_INPUT 	(SPARK_QWEN36_MODEL_HIDDEN_DIMENSION + SPARK_QWEN36_DSPARK_MARKOV_RANK)

typedef enum SparkQwen36DsparkTensorKind
{
	SPARK_QWEN36_DSPARK_TENSOR_ATTN_QUERY = 0,
	SPARK_QWEN36_DSPARK_TENSOR_ATTN_KEY = 1,
	SPARK_QWEN36_DSPARK_TENSOR_ATTN_VALUE = 2,
	SPARK_QWEN36_DSPARK_TENSOR_ATTN_OUTPUT = 3,
	SPARK_QWEN36_DSPARK_TENSOR_ATTN_QUERY_NORM = 4,
	SPARK_QWEN36_DSPARK_TENSOR_ATTN_KEY_NORM = 5,
	SPARK_QWEN36_DSPARK_TENSOR_ATTENTION_NORM = 6,
	SPARK_QWEN36_DSPARK_TENSOR_MLP_NORM = 7,
	SPARK_QWEN36_DSPARK_TENSOR_FFN_GATE = 8,
	SPARK_QWEN36_DSPARK_TENSOR_FFN_UP = 9,
	SPARK_QWEN36_DSPARK_TENSOR_FFN_DOWN = 10,
	SPARK_QWEN36_DSPARK_TENSOR_PROJECTOR = 11,
	SPARK_QWEN36_DSPARK_TENSOR_MARKOV_W1 = 12,
	SPARK_QWEN36_DSPARK_TENSOR_MARKOV_W2 = 13,
	SPARK_QWEN36_DSPARK_TENSOR_CONFIDENCE = 14,
	SPARK_QWEN36_DSPARK_TENSOR_FINAL_NORM = 15,
	SPARK_QWEN36_DSPARK_TENSOR_HIDDEN_NORM = 16,
	SPARK_QWEN36_DSPARK_TENSOR_KIND_COUNT = 17
} SparkQwen36DsparkTensorKind;

static inline void SparkQwen36DsparkKindShape(
	uint32_t kind,
	uint32_t *rows,
	uint32_t *columns)
{
	switch (kind)
	{
	case SPARK_QWEN36_DSPARK_TENSOR_ATTN_QUERY:
		*rows = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		*columns = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_ATTN_KEY:
	case SPARK_QWEN36_DSPARK_TENSOR_ATTN_VALUE:
		*rows = SPARK_QWEN36_DSPARK_ATTN_KV_HEADS * SPARK_QWEN36_DSPARK_ATTN_HEAD_DIMENSION;
		*columns = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_ATTN_OUTPUT:
		*rows = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		*columns = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_ATTN_QUERY_NORM:
	case SPARK_QWEN36_DSPARK_TENSOR_ATTN_KEY_NORM:
		*rows = 1u;
		*columns = SPARK_QWEN36_DSPARK_ATTN_HEAD_DIMENSION;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_ATTENTION_NORM:
	case SPARK_QWEN36_DSPARK_TENSOR_MLP_NORM:
		*rows = 1u;
		*columns = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_FFN_GATE:
	case SPARK_QWEN36_DSPARK_TENSOR_FFN_UP:
		*rows = SPARK_QWEN36_DSPARK_FFN_INTERMEDIATE;
		*columns = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_FFN_DOWN:
		*rows = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		*columns = SPARK_QWEN36_DSPARK_FFN_INTERMEDIATE;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_PROJECTOR:
		*rows = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		*columns = SPARK_QWEN36_DSPARK_TARGET_TAP_COUNT * SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_MARKOV_W1:
	case SPARK_QWEN36_DSPARK_TENSOR_MARKOV_W2:
		*rows = SPARK_QWEN36_MODEL_OUTPUT_VOCAB_COUNT;
		*columns = SPARK_QWEN36_DSPARK_MARKOV_RANK;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_CONFIDENCE:
		*rows = 1u;
		*columns = SPARK_QWEN36_DSPARK_CONFIDENCE_INPUT;
		return;
	case SPARK_QWEN36_DSPARK_TENSOR_FINAL_NORM:
	case SPARK_QWEN36_DSPARK_TENSOR_HIDDEN_NORM:
		*rows = 1u;
		*columns = SPARK_QWEN36_MODEL_HIDDEN_DIMENSION;
		return;
	default:
		*rows = 0u;
		*columns = 0u;
		return;
	}
}
