#pragma once

#include <stdint.h>
#include "inference/kernels/layer_kind.cuh"
#include "sparkpipe/llm_defines.h"

#define GLM_HIDDEN SPARK_LLM_HIDDEN_DIMENSION
#define GLM_LAYERS SPARK_LLM_LAYER_COUNT
#define GLM_FIRST_ROUTED_LAYER SPARK_LLM_FIRST_ROUTED_LAYER
#define GLM_VOCAB SPARK_LLM_OUTPUT_VOCAB_COUNT
#define GLM_RESTRICTED_VOCAB SPARK_LLM_RESTRICTED_VOCAB_COUNT
#define GLM_RMS_EPSILON SPARK_LLM_RMS_NORM_EPSILON
#define GLM_ROPE_THETA SPARK_LLM_ROPE_THETA

#define GLM_ATTN_HEADS SPARK_LLM_MLA_HEAD_COUNT
#define GLM_LATENT SPARK_LLM_MLA_LATENT_DIMENSION
#define GLM_ROPE_DIM SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION
#define GLM_QK_NOPE_DIM SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION
#define GLM_VALUE_DIM SPARK_LLM_MLA_V_HEAD_DIMENSION
#define GLM_QUERY_A_DIM SPARK_LLM_MLA_QUERY_A_DIMENSION

#define GLM_DSA_SELECTED SPARK_LLM_DSA_SELECTED_TOKEN_COUNT
#define GLM_DSA_INDEX_HEADS SPARK_LLM_DSA_INDEX_HEAD_COUNT
#define GLM_DSA_INDEX_DIM SPARK_LLM_DSA_INDEX_HEAD_DIMENSION
#define GLM_DSA_QUERY_DIM (GLM_DSA_INDEX_HEADS * GLM_DSA_INDEX_DIM)
#define GLM_DSA_INDEX_EPSILON SPARK_LLM_DSA_INDEX_NORM_EPSILON
#define GLM_DSA_INDEX_SCALE SPARK_LLM_DSA_INDEX_SOFTMAX_SCALE

#define GLM_EXPERTS SPARK_LLM_MOE_EXPERT_COUNT
#define GLM_TOP_K SPARK_LLM_MOE_TOP_K
#define GLM_EXPERT_INTERMEDIATE SPARK_LLM_MOE_INTERMEDIATE_DIMENSION
#define GLM_DENSE_INTERMEDIATE SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION
#define GLM_ROUTED_SCALE SPARK_LLM_MOE_ROUTED_SCALING_FACTOR
#define GLM_W1_COMPONENTS SPARK_LLM_MOE_W1_COMPONENT_COUNT

#define GLM_FP8_SCALE_BLOCK SPARK_LLM_FP8_SCALE_BLOCK
#define GLM_NVFP4_GROUP SPARK_LLM_NVFP4_GROUP_SIZE
#define GLM_MXFP4_GROUP SPARK_LLM_MXFP4_GROUP_SIZE

#define GLM_MTP_DRAFT_TOKENS SPARK_LLM_MTP_DRAFT_TOKEN_COUNT
#define GLM_MTP_LAYER_INDEX SPARK_LLM_MTP_LAYER_INDEX

#define GLM_KV_BITS SPARK_LLM_KV_BITS
#define GLM_KV_PAGE_SLOTS SPARK_LLM_KV_PAGE_SLOTS
#define GLM_KV_SLOT_BYTES ((GLM_LATENT_ROW * GLM_KV_BITS) / 8u)

#define GLM_ROUTED_LAYERS (GLM_LAYERS - GLM_FIRST_ROUTED_LAYER)
#define GLM_GATE_UP_DIM (GLM_EXPERT_INTERMEDIATE * GLM_W1_COMPONENTS)
#define GLM_LATENT_ROW (GLM_LATENT + GLM_ROPE_DIM)
#define GLM_WEIGHT_LAYERS SPARK_LLM_WEIGHT_LAYER_COUNT

static inline uint32_t GlmRowsPerExpert(uint32_t tokens)
{
	return(((tokens * GLM_TOP_K) + GLM_EXPERTS - 1u) / GLM_EXPERTS);
}

static inline uint32_t GlmLayerHasFullIndexer(uint32_t layer)
{
	return(layer < SPARK_LLM_DSA_INDEX_FULL_FIRST_LAYER ||
		(layer >= SPARK_LLM_DSA_INDEX_FULL_GROUP_LAYER &&
		((layer - SPARK_LLM_DSA_INDEX_FULL_GROUP_LAYER) %
		SPARK_LLM_DSA_INDEX_SHARE_GROUP_LAYER_COUNT) == 0u) ? 1u : 0u);
}

#define GLM_LAYER_KIND(layer) ((void)(layer), LM_LAYER_LATENT)
