#pragma once

#define SPARK_LLM_FAMILY_TAG                    SET_ME_FAMILY_TAG
#define SPARK_LLM_HIDDEN_DIMENSION              SET_ME_HIDDEN_DIMENSION
#define SPARK_LLM_LAYER_COUNT                   SET_ME_LAYER_COUNT
#define SPARK_LLM_OUTPUT_VOCAB_COUNT            SET_ME_OUTPUT_VOCAB_COUNT
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS        SET_ME_MAXIMUM_CONTEXT_TOKENS
#define SPARK_LLM_RMS_NORM_EPSILON              SET_ME_RMS_NORM_EPSILON
#define SPARK_LLM_SWIGLU_LIMIT                  SET_ME_SWIGLU_LIMIT
#define SPARK_LLM_END_OF_TEXT_TOKEN_ID          SET_ME_END_OF_TEXT_TOKEN_ID
#define SPARK_LLM_KV_POOL_TOKENS                SET_ME_KV_POOL_TOKENS
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH SET_ME_MAX_PREFILL_TOKENS_PER_DISPATCH

#define SPARK_LLM_MLA_HEAD_COUNT                SET_ME_MLA_HEAD_COUNT
#define SPARK_LLM_MLA_QUERY_A_DIMENSION         SET_ME_MLA_QUERY_A_DIMENSION
#define SPARK_LLM_MLA_LATENT_DIMENSION          SET_ME_MLA_LATENT_DIMENSION
#define SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION    SET_ME_MLA_QK_NOPE_HEAD_DIMENSION
#define SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION    SET_ME_MLA_QK_ROPE_HEAD_DIMENSION
#define SPARK_LLM_MLA_V_HEAD_DIMENSION          SET_ME_MLA_V_HEAD_DIMENSION

#define SPARK_LLM_ATTENTION_PERIOD              SET_ME_ATTENTION_PERIOD
#define SPARK_LLM_GLOBAL_ATTENTION_PHASE        SET_ME_GLOBAL_ATTENTION_PHASE
#define SPARK_LLM_ROPE_THETA                    SET_ME_ROPE_THETA
#define SPARK_LLM_ROPE_YARN_FACTOR              SET_ME_ROPE_YARN_FACTOR

#define SPARK_LLM_MOE_EXPERT_COUNT              SET_ME_MOE_EXPERT_COUNT
#define SPARK_LLM_MOE_TOP_K                     SET_ME_MOE_TOP_K
#define SPARK_LLM_MOE_SHARED_EXPERT_COUNT       SET_ME_MOE_SHARED_EXPERT_COUNT
#define SPARK_LLM_MOE_INTERMEDIATE_DIMENSION    SET_ME_MOE_INTERMEDIATE_DIMENSION
#define SPARK_LLM_MOE_ROUTED_SCALING_FACTOR     SET_ME_MOE_ROUTED_SCALING_FACTOR
#define SPARK_LLM_MOE_NORM_TOPK_PROB            SET_ME_MOE_NORM_TOPK_PROB
#define SPARK_LLM_FIRST_ROUTED_LAYER            SET_ME_FIRST_ROUTED_LAYER
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION  SET_ME_DENSE_INTERMEDIATE_DIMENSION

#define SPARK_LLM_KDA_LAYER_COUNT               SET_ME_KDA_LAYER_COUNT
#define SPARK_LLM_KDA_HEAD_COUNT                SET_ME_KDA_HEAD_COUNT
#define SPARK_LLM_KDA_HEAD_KEY_DIMENSION        SET_ME_KDA_HEAD_KEY_DIMENSION
#define SPARK_LLM_KDA_HEAD_VALUE_DIMENSION      SET_ME_KDA_HEAD_VALUE_DIMENSION
#define SPARK_LLM_KDA_CONV_KERNEL               SET_ME_KDA_CONV_KERNEL
#define SPARK_LLM_KDA_CHUNK_TOKENS              SET_ME_KDA_CHUNK_TOKENS
#define SPARK_LLM_KDA_STATE_ELEMENT_BYTES       SET_ME_KDA_STATE_ELEMENT_BYTES
#define SPARK_LLM_KDA_GATE_LOWER_BOUND          SET_ME_KDA_GATE_LOWER_BOUND
#define SPARK_LLM_KDA_LOW_RANK_GATE_BOTTLENECK  SET_ME_KDA_LOW_RANK_GATE_BOTTLENECK

#define SPARK_LLM_TILE_N                        SET_ME_TILE_N
#define SPARK_LLM_TILE_STAGES                   SET_ME_TILE_STAGES
#define SPARK_LLM_LAYER_THREADS                 SET_ME_LAYER_THREADS

#define SPARK_LLM_MTP_ENABLED                   SET_ME_MTP_ENABLED
#define SPARK_LLM_MTP_DRAFT_DEPTH               SET_ME_MTP_DRAFT_DEPTH

#define SPARK_LLM_TP_COLLECTIVE_BACKEND         SET_ME_TP_COLLECTIVE_BACKEND
#define SPARK_LLM_TP_DEGREE                     SET_ME_TP_DEGREE
#define SPARK_LLM_STAGE_INDEX                   SET_ME_STAGE_INDEX

#define SPARK_LLM_MISS_PACK_STRIDE              SET_ME_MISS_PACK_STRIDE
#define SPARK_LLM_MISS_RING_CAPACITY            SET_ME_MISS_RING_CAPACITY
#define SPARK_LLM_ROUTE_UNION_MAX               SET_ME_ROUTE_UNION_MAX
#define SPARK_LLM_ROUTE_UNION_TRIM              SET_ME_ROUTE_UNION_TRIM

#define SPARK_LLM_ADAPTER_DESCRIPTOR            SET_ME_ADAPTER_DESCRIPTOR
#define SPARK_LLM_MODEL_SOURCE_URI              SET_ME_MODEL_SOURCE_URI
#define SPARK_LLM_MODEL_REVISION                SET_ME_MODEL_REVISION
