#pragma once

/* Neutral DSpark drafter constants.
 *
 * One draft backend, many drafter shapes. The target is selected at package
 * compile time with exactly one of SPARK_DSPARK_TARGET_GLM52 /
 * SPARK_DSPARK_TARGET_K3 / SPARK_DSPARK_TARGET_DSV4_PRO_0813; every
 * shape-dependent value resolves through this header. The GLM52 table aliases
 * the measured model constants, so the existing GLM52 path is byte-identical;
 * tests/test_dspark_drafter_pin.c pins that case against the measured
 * literals. K3's table comes from inference/llms/kimi_k3/dspark.h (the
 * drafter config read from the released DSparkDraftModel checkpoint);
 * DSV4 Pro 0813's table comes from the GA contract (3 packed draft layers,
 * markov 512, noise token 128799) - fields its drafter does not declare yet
 * are zero with a comment.
 *
 * Descriptor-byte macros stay with the per-model ABI header for now
 * (spark_glm52_dspark.h owns the struct layouts); they move here when the
 * structs are neutralized. */
#include <stdint.h>

#if defined(SPARK_DSPARK_TARGET_GLM52)
#include "sparkpipe/spark_glm52_model.h"
#define SPARK_DSPARK_HIDDEN_DIMENSION SPARK_GLM52_MODEL_HIDDEN_DIMENSION
#define SPARK_DSPARK_MAXIMUM_CONTEXT_TOKENS SPARK_GLM52_MODEL_MAXIMUM_CONTEXT_TOKENS
#define SPARK_DSPARK_FULL_VOCAB_SIZE SPARK_GLM52_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_DSPARK_RMS_NORM_EPSILON SPARK_GLM52_MODEL_RMS_NORM_EPSILON
#define SPARK_DSPARK_ROPE_THETA SPARK_GLM52_MODEL_ROPE_THETA
#define SPARK_DSPARK_MASK_TOKEN_ID SPARK_GLM52_MODEL_DSPARK_MASK_TOKEN_ID
#define SPARK_DSPARK_AUX_LAYER_COUNT SPARK_GLM52_MODEL_DSPARK_AUX_LAYER_COUNT
#define SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER SPARK_GLM52_MODEL_DSPARK_AUX_LAYER_IDS_INITIALIZER
#define SPARK_DSPARK_DRAFT_LAYER_COUNT SPARK_GLM52_MODEL_DSPARK_DRAFT_LAYER_COUNT
#define SPARK_DSPARK_BLOCK_SIZE SPARK_GLM52_MODEL_DSPARK_BLOCK_SIZE
#define SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT SPARK_GLM52_MODEL_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT
#define SPARK_DSPARK_MARKOV_RANK SPARK_GLM52_MODEL_DSPARK_MARKOV_RANK
#define SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION SPARK_GLM52_MODEL_DSPARK_DRAFT_INTERMEDIATE_DIMENSION
#define SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT SPARK_GLM52_MODEL_DSPARK_DRAFT_ATTENTION_HEAD_COUNT
#define SPARK_DSPARK_DRAFT_KV_HEAD_COUNT SPARK_GLM52_MODEL_DSPARK_DRAFT_KV_HEAD_COUNT
#define SPARK_DSPARK_DRAFT_HEAD_DIMENSION SPARK_GLM52_MODEL_DSPARK_DRAFT_HEAD_DIMENSION
#define SPARK_DSPARK_MAX_ANCHORS SPARK_GLM52_MODEL_DSPARK_MAX_ANCHORS
#elif defined(SPARK_DSPARK_TARGET_K3)
#include "sparkpipe/spark_k3_model.h"
/* Kimi K3 drafter, read from the released DSparkDraftModel config.json
 * (inference/llms/kimi_k3/dspark.h): block 7, 8 verify positions, aux
 * {7,23,51,67,83}, 5 draft layers, 64 query heads over 16 KV heads, head
 * dim 64, intermediate 14336, markov 256, mask token 163824, rope 10000. */
#define SPARK_DSPARK_HIDDEN_DIMENSION SPARK_K3_MODEL_HIDDEN_DIMENSION
#define SPARK_DSPARK_MAXIMUM_CONTEXT_TOKENS SPARK_K3_MODEL_MAXIMUM_CONTEXT_TOKENS
#define SPARK_DSPARK_FULL_VOCAB_SIZE SPARK_K3_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_DSPARK_RMS_NORM_EPSILON SPARK_K3_MODEL_RMS_NORM_EPSILON
#define SPARK_DSPARK_ROPE_THETA 10000.0f
#define SPARK_DSPARK_MASK_TOKEN_ID 163824u
#define SPARK_DSPARK_AUX_LAYER_COUNT 5u
#define SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER { 7u, 23u, 51u, 67u, 83u }
#define SPARK_DSPARK_DRAFT_LAYER_COUNT 5u
#define SPARK_DSPARK_BLOCK_SIZE 7u
#define SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT 8u
#define SPARK_DSPARK_MARKOV_RANK 256u
#define SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION 14336u
#define SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT 64u
#define SPARK_DSPARK_DRAFT_KV_HEAD_COUNT 16u
#define SPARK_DSPARK_DRAFT_HEAD_DIMENSION 64u
#define SPARK_DSPARK_MAX_ANCHORS 1024u
#elif defined(SPARK_DSPARK_TARGET_DSV4_PRO_0813)
#include "sparkpipe/spark_dsv4_pro_model.h"
/* DSV4 Pro GA 0813 drafter (model_contracts/dsv4_pro_authoritative.json
 * dspark block): 3 draft layers at taps {58,59,60}, block 5, markov 512,
 * noise token 128799. Draft attention heads/intermediate are not declared
 * by the contract yet - zero until the Pro session pins them. */
#define SPARK_DSPARK_HIDDEN_DIMENSION SPARK_DSV4_PRO_HIDDEN_DIMENSION
#define SPARK_DSPARK_MAXIMUM_CONTEXT_TOKENS SPARK_DSV4_PRO_MAXIMUM_CONTEXT_TOKENS
#define SPARK_DSPARK_FULL_VOCAB_SIZE SPARK_DSV4_PRO_VOCAB_COUNT
#define SPARK_DSPARK_RMS_NORM_EPSILON SPARK_DSV4_PRO_RMS_NORM_EPSILON
#define SPARK_DSPARK_ROPE_THETA SPARK_DSV4_PRO_COMPRESSED_ROPE_THETA
#define SPARK_DSPARK_MASK_TOKEN_ID 128799u
#define SPARK_DSPARK_AUX_LAYER_COUNT 3u
#define SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER { 58u, 59u, 60u }
#define SPARK_DSPARK_DRAFT_LAYER_COUNT 3u
#define SPARK_DSPARK_BLOCK_SIZE 5u
#define SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT 8u
#define SPARK_DSPARK_MARKOV_RANK 512u
#define SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION 0u /* not declared yet */
#define SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT 0u /* not declared yet */
#define SPARK_DSPARK_DRAFT_KV_HEAD_COUNT 0u /* not declared yet */
#define SPARK_DSPARK_DRAFT_HEAD_DIMENSION 0u /* not declared yet */
#define SPARK_DSPARK_MAX_ANCHORS 1024u
#else
#error "select a DSpark drafter target: define SPARK_DSPARK_TARGET_GLM52, SPARK_DSPARK_TARGET_K3, or SPARK_DSPARK_TARGET_DSV4_PRO_0813"
#endif

/* Shape-independent constants (one drafter ABI). */
#define SPARK_DSPARK_ABI_VERSION 3u
/* Request priority at or above this value selects the realtime confidence
 * floor. */
#define SPARK_DSPARK_POLICY_REALTIME_PRIORITY_THRESHOLD 4000000000u
#define SPARK_DSPARK_CONFIDENCE_MILLI_ONE 1000u
#define SPARK_DSPARK_DEFAULT_MIN_CONFIDENCE_MILLI 350u
#define SPARK_DSPARK_DEFAULT_REALTIME_MIN_CONFIDENCE_MILLI 250u
#define SPARK_DSPARK_DEFAULT_MAX_VERIFY_TOKENS SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT
#define SPARK_DSPARK_INVALID_LAYER_INDEX 0xffffffffu
#define SPARK_DSPARK_VERIFIER_HIDDEN_DTYPE_BF16 1u
#define SPARK_DSPARK_DRAFT_DTYPE_BF16 1u

#define SPARK_DSPARK_POLICY_FLAG_ENABLE_REALTIME 0x00000001u
#define SPARK_DSPARK_POLICY_FLAG_ENABLE_UNDERFILLED_DECODE 0x00000002u
#define SPARK_DSPARK_POLICY_FLAG_REQUIRE_CONFIDENCE_HEAD 0x00000004u
#define SPARK_DSPARK_POLICY_FLAG_REQUIRE_MARKOV_HEAD 0x00000008u
#define SPARK_DSPARK_POLICY_DEFAULT_FLAGS \
    (SPARK_DSPARK_POLICY_FLAG_ENABLE_REALTIME | \
     SPARK_DSPARK_POLICY_FLAG_ENABLE_UNDERFILLED_DECODE | \
     SPARK_DSPARK_POLICY_FLAG_REQUIRE_CONFIDENCE_HEAD | \
     SPARK_DSPARK_POLICY_FLAG_REQUIRE_MARKOV_HEAD)
#define SPARK_DSPARK_POLICY_KNOWN_FLAGS \
    SPARK_DSPARK_POLICY_DEFAULT_FLAGS

#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_VALID 0x00000001u
#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_TAPS_READY 0x00000002u
#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_DRAFT_READY 0x00000004u
#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_VERIFY_INFLIGHT 0x00000008u

#define SPARK_DSPARK_DRAFT_RESULT_FLAG_CONFIDENCE_TRUNCATED 0x00000001u
#define SPARK_DSPARK_DRAFT_RESULT_KNOWN_FLAGS \
    SPARK_DSPARK_DRAFT_RESULT_FLAG_CONFIDENCE_TRUNCATED

#define SPARK_DSPARK_VERIFY_RESULT_FLAG_ACCEPTED_ALL UINT32_C(0x00000001)
#define SPARK_DSPARK_VERIFY_RESULT_FLAG_REJECTED UINT32_C(0x00000002)
#define SPARK_DSPARK_VERIFY_RESULT_KNOWN_FLAGS \
    (SPARK_DSPARK_VERIFY_RESULT_FLAG_ACCEPTED_ALL | \
     SPARK_DSPARK_VERIFY_RESULT_FLAG_REJECTED)
