#pragma once

#include <stdint.h>

#if defined(__cplusplus)
#define SPARK_LLM_STATIC_ASSERT(condition,message) static_assert(condition,message)
#else
#define SPARK_LLM_STATIC_ASSERT(condition,message) _Static_assert(condition,message)
#endif

#define SPARK_LLM_ATTENTION_KIND_MLA 1
#define SPARK_LLM_ATTENTION_KIND_GQA 2
#define SPARK_LLM_ATTENTION_KIND_LATENT_LINEAR 3

#define SPARK_LLM_ROPE_MODE_THETA 1
#define SPARK_LLM_ROPE_MODE_YARN 2
#define SPARK_LLM_ROPE_MODE_TABLE 3

#ifndef SPARK_LLM_HIDDEN_DIMENSION
#error "llm_defines: set SPARK_LLM_HIDDEN_DIMENSION (SET_ME_HIDDEN_DIMENSION)"
#endif
#ifndef SPARK_LLM_LAYER_COUNT
#error "llm_defines: set SPARK_LLM_LAYER_COUNT (SET_ME_LAYER_COUNT)"
#endif
#ifndef SPARK_LLM_OUTPUT_VOCAB_COUNT
#error "llm_defines: set SPARK_LLM_OUTPUT_VOCAB_COUNT (SET_ME_OUTPUT_VOCAB_COUNT)"
#endif
#ifndef SPARK_LLM_MAXIMUM_CONTEXT_TOKENS
#error "llm_defines: set SPARK_LLM_MAXIMUM_CONTEXT_TOKENS (SET_ME_MAXIMUM_CONTEXT_TOKENS)"
#endif
#ifndef SPARK_LLM_RMS_NORM_EPSILON
#error "llm_defines: set SPARK_LLM_RMS_NORM_EPSILON (SET_ME_RMS_NORM_EPSILON)"
#endif
#ifndef SPARK_LLM_FP8_SCALE_BLOCK
#error "llm_defines: set SPARK_LLM_FP8_SCALE_BLOCK (SET_ME_FP8_SCALE_BLOCK)"
#endif
#ifndef SPARK_LLM_KV_BITS
#error "llm_defines: set SPARK_LLM_KV_BITS (SET_ME_KV_BITS)"
#endif
#ifndef SPARK_LLM_BF16_ELEMENT_BYTES
#error "llm_defines: set SPARK_LLM_BF16_ELEMENT_BYTES (SET_ME_BF16_ELEMENT_BYTES)"
#endif
#ifndef SPARK_LLM_KV_PAGE_SLOTS
#error "llm_defines: set SPARK_LLM_KV_PAGE_SLOTS (SET_ME_KV_PAGE_SLOTS)"
#endif
#ifndef SPARK_LLM_ATTENTION_PERIOD
#error "llm_defines: set SPARK_LLM_ATTENTION_PERIOD (SET_ME_FULL_LAYER_PERIOD)"
#endif
#ifndef SPARK_LLM_GLOBAL_ATTENTION_PHASE
#error "llm_defines: set SPARK_LLM_GLOBAL_ATTENTION_PHASE (SET_ME_FULL_LAYER_PHASE)"
#endif

#ifndef SPARK_LLM_ATTENTION_KIND
#error "llm_defines: set SPARK_LLM_ATTENTION_KIND to SPARK_LLM_ATTENTION_KIND_MLA, _GQA or _LATENT_LINEAR (SET_ME_ATTENTION_KIND)"
#endif

#if SPARK_LLM_ATTENTION_KIND == SPARK_LLM_ATTENTION_KIND_MLA || \
	SPARK_LLM_ATTENTION_KIND == SPARK_LLM_ATTENTION_KIND_LATENT_LINEAR

#ifndef SPARK_LLM_MLA_LATENT_DIMENSION
#error "llm_defines: set SPARK_LLM_MLA_LATENT_DIMENSION (SET_ME_LATENT_DIMENSION)"
#endif
#ifndef SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION
#error "llm_defines: set SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION (SET_ME_QK_NOPE_HEAD_DIMENSION)"
#endif
#ifndef SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION
#error "llm_defines: set SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION (SET_ME_QK_ROPE_HEAD_DIMENSION)"
#endif
#ifndef SPARK_LLM_MLA_V_HEAD_DIMENSION
#error "llm_defines: set SPARK_LLM_MLA_V_HEAD_DIMENSION (SET_ME_MLA_VALUE_HEAD_DIMENSION)"
#endif
#ifndef SPARK_LLM_MLA_HEAD_COUNT
#error "llm_defines: set SPARK_LLM_MLA_HEAD_COUNT (SET_ME_MLA_HEAD_COUNT)"
#endif
#ifndef SPARK_LLM_ROPE_THETA
#error "llm_defines: set SPARK_LLM_ROPE_THETA (SET_ME_ROPE_THETA)"
#endif

#define SPARK_LLM_MLA_QK_HEAD_DIMENSION \
	(SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION + SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_LLM_MLA_QUERY_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * SPARK_LLM_MLA_QK_HEAD_DIMENSION)
#define SPARK_LLM_MLA_KV_A_DIMENSION \
	(SPARK_LLM_MLA_LATENT_DIMENSION + SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_LLM_MLA_KV_B_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * \
	 (SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION + \
	  SPARK_LLM_MLA_V_HEAD_DIMENSION))
#define SPARK_LLM_MLA_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * SPARK_LLM_MLA_V_HEAD_DIMENSION)
#define SPARK_LLM_MLA_ROPE_HEAD_DIMENSION SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION

SPARK_LLM_STATIC_ASSERT(SPARK_LLM_MLA_QK_HEAD_DIMENSION ==
	(SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION + SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION),
	"latent attention heads carry nope then rope sections");

#endif

#if SPARK_LLM_ATTENTION_KIND == SPARK_LLM_ATTENTION_KIND_LATENT_LINEAR

#ifndef SPARK_LLM_KDA_HEAD_COUNT
#error "llm_defines: set SPARK_LLM_KDA_HEAD_COUNT (SET_ME_KDA_HEAD_COUNT)"
#endif
#ifndef SPARK_LLM_KDA_HEAD_KEY_DIMENSION
#error "llm_defines: set SPARK_LLM_KDA_HEAD_KEY_DIMENSION (SET_ME_KDA_HEAD_KEY_DIMENSION)"
#endif
#ifndef SPARK_LLM_KDA_HEAD_VALUE_DIMENSION
#error "llm_defines: set SPARK_LLM_KDA_HEAD_VALUE_DIMENSION (SET_ME_KDA_HEAD_VALUE_DIMENSION)"
#endif
#ifndef SPARK_LLM_KDA_CONV_KERNEL
#error "llm_defines: set SPARK_LLM_KDA_CONV_KERNEL (SET_ME_KDA_CONV_KERNEL)"
#endif
#ifndef SPARK_LLM_KDA_SHORT_CONV_KERNEL
#error "llm_defines: set SPARK_LLM_KDA_SHORT_CONV_KERNEL (SET_ME_KDA_SHORT_CONV_KERNEL)"
#endif
#ifndef SPARK_LLM_KDA_STATE_ELEMENT_BYTES
#error "llm_defines: set SPARK_LLM_KDA_STATE_ELEMENT_BYTES (SET_ME_KDA_STATE_ELEMENT_BYTES)"
#endif
#ifndef SPARK_LLM_KDA_GATE_LOWER_BOUND
#error "llm_defines: set SPARK_LLM_KDA_GATE_LOWER_BOUND (SET_ME_KDA_GATE_LOWER_BOUND)"
#endif

#define SPARK_LLM_KDA_QK_DIM \
	(SPARK_LLM_KDA_HEAD_COUNT * SPARK_LLM_KDA_HEAD_KEY_DIMENSION)
#define SPARK_LLM_KDA_VALUE_DIM \
	(SPARK_LLM_KDA_HEAD_COUNT * SPARK_LLM_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_LLM_KDA_STATE_ELEMENTS_PER_HEAD \
	(SPARK_LLM_KDA_HEAD_KEY_DIMENSION * SPARK_LLM_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_LLM_KDA_STATE_BYTES_PER_LAYER \
	(SPARK_LLM_KDA_HEAD_COUNT * \
	 SPARK_LLM_KDA_STATE_ELEMENTS_PER_HEAD * \
	 SPARK_LLM_KDA_STATE_ELEMENT_BYTES)
#define SPARK_LLM_KDA_CONV_WINDOW_BYTES_PER_LAYER \
	(3u * SPARK_LLM_KDA_QK_DIM * \
	 SPARK_LLM_KDA_SHORT_CONV_KERNEL * SPARK_LLM_BF16_ELEMENT_BYTES)
#define SPARK_LLM_KDA_A_LOG_HEAD_COUNT SPARK_LLM_KDA_HEAD_COUNT

SPARK_LLM_STATIC_ASSERT(SPARK_LLM_KDA_STATE_BYTES_PER_LAYER ==
	SPARK_LLM_KDA_HEAD_COUNT * SPARK_LLM_KDA_HEAD_KEY_DIMENSION *
		SPARK_LLM_KDA_HEAD_VALUE_DIMENSION *
		SPARK_LLM_KDA_STATE_ELEMENT_BYTES,
	"the kda state slot holds one full-width recurrent state");

SPARK_LLM_STATIC_ASSERT(SPARK_LLM_KDA_CONV_WINDOW_BYTES_PER_LAYER ==
	SPARK_LLM_KDA_QK_DIM * 3u * SPARK_LLM_KDA_SHORT_CONV_KERNEL *
		SPARK_LLM_BF16_ELEMENT_BYTES,
	"the kda conv window derives from the qk row count and the short conv kernel");

#endif

#if SPARK_LLM_ATTENTION_KIND == SPARK_LLM_ATTENTION_KIND_GQA

#ifndef SPARK_LLM_FULL_QUERY_HEAD_COUNT
#error "llm_defines: set SPARK_LLM_FULL_QUERY_HEAD_COUNT (SET_ME_Q_HEAD_COUNT)"
#endif
#ifndef SPARK_LLM_FULL_KV_HEAD_COUNT
#error "llm_defines: set SPARK_LLM_FULL_KV_HEAD_COUNT (SET_ME_KV_HEAD_COUNT)"
#endif
#ifndef SPARK_LLM_HEAD_DIMENSION
#error "llm_defines: set SPARK_LLM_HEAD_DIMENSION (SET_ME_GQA_HEAD_DIMENSION)"
#endif
#ifndef SPARK_LLM_ATTENTION_SCALE
#error "llm_defines: set SPARK_LLM_ATTENTION_SCALE (SET_ME_ATTENTION_SCALE)"
#endif
#ifndef SPARK_LLM_SLIDING_WINDOW_TOKENS
#error "llm_defines: set SPARK_LLM_SLIDING_WINDOW_TOKENS (SET_ME_WINDOW_TOKENS)"
#endif
#ifndef SPARK_LLM_ROPE_MODE
#error "llm_defines: set SPARK_LLM_ROPE_MODE to SPARK_LLM_ROPE_MODE_THETA, _YARN or _TABLE (SET_ME_ROPE_MODE)"
#endif
#if SPARK_LLM_ROPE_MODE == SPARK_LLM_ROPE_MODE_YARN || \
	SPARK_LLM_ROPE_MODE == SPARK_LLM_ROPE_MODE_THETA
#ifndef SPARK_LLM_ROPE_FULL_THETA
#error "llm_defines: set SPARK_LLM_ROPE_FULL_THETA (SET_ME_ROPE_FULL_THETA)"
#endif
#endif
#if SPARK_LLM_ROPE_MODE == SPARK_LLM_ROPE_MODE_YARN
#ifndef SPARK_LLM_ROPE_YARN_FACTOR
#error "llm_defines: set SPARK_LLM_ROPE_YARN_FACTOR (SET_ME_ROPE_ATTENTION_FACTOR)"
#endif
#endif
#if SPARK_LLM_ROPE_MODE == SPARK_LLM_ROPE_MODE_TABLE
#ifndef SPARK_LLM_ROPE_TABLE_ELEMENTS
#error "llm_defines: set SPARK_LLM_ROPE_TABLE_ELEMENTS (SET_ME_ROPE_TABLE_ELEMENTS)"
#endif
#endif

#define SPARK_LLM_MLA_HEAD_COUNT SPARK_LLM_FULL_QUERY_HEAD_COUNT

#endif

#ifndef SPARK_LLM_FIRST_ROUTED_LAYER
#define SPARK_LLM_FIRST_ROUTED_LAYER SPARK_LLM_LAYER_COUNT
#endif

#if SPARK_LLM_FIRST_ROUTED_LAYER != SPARK_LLM_LAYER_COUNT

#ifndef SPARK_LLM_MOE_EXPERT_COUNT
#error "llm_defines: set SPARK_LLM_MOE_EXPERT_COUNT (SET_ME_ROUTED_EXPERT_COUNT)"
#endif
#ifndef SPARK_LLM_MOE_TOP_K
#error "llm_defines: set SPARK_LLM_MOE_TOP_K (SET_ME_EXPERTS_PER_TOKEN)"
#endif
#ifndef SPARK_LLM_MOE_INTERMEDIATE_DIMENSION
#error "llm_defines: set SPARK_LLM_MOE_INTERMEDIATE_DIMENSION (SET_ME_EXPERT_INTERMEDIATE_DIMENSION)"
#endif
#ifndef SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION
#error "llm_defines: set SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION (SET_ME_DENSE_INTERMEDIATE_DIMENSION)"
#endif
#ifndef SPARK_LLM_MOE_ROUTED_SCALING_FACTOR
#error "llm_defines: set SPARK_LLM_MOE_ROUTED_SCALING_FACTOR (SET_ME_ROUTED_SCALE)"
#endif
#ifndef SPARK_LLM_MOE_W1_COMPONENT_COUNT
#error "llm_defines: set SPARK_LLM_MOE_W1_COMPONENT_COUNT (SET_ME_W1_COMPONENT_COUNT)"
#endif
#ifndef SPARK_LLM_MOE_ROUTER_GROUP_COUNT
#error "llm_defines: set SPARK_LLM_MOE_ROUTER_GROUP_COUNT (SET_ME_ROUTER_GROUP_COUNT)"
#endif
#ifndef SPARK_LLM_MOE_ROUTER_TOP_GROUPS
#error "llm_defines: set SPARK_LLM_MOE_ROUTER_TOP_GROUPS (SET_ME_ROUTER_TOP_GROUPS)"
#endif

#define SPARK_LLM_ROUTED_LAYERS \
	(SPARK_LLM_LAYER_COUNT - SPARK_LLM_FIRST_ROUTED_LAYER)
#define SPARK_LLM_MOE_ROUTED_GATE_UP_DIMENSION \
	(SPARK_LLM_MOE_INTERMEDIATE_DIMENSION * \
	 SPARK_LLM_MOE_W1_COMPONENT_COUNT)

SPARK_LLM_STATIC_ASSERT(SPARK_LLM_MOE_ROUTER_TOP_GROUPS <
	SPARK_LLM_MOE_ROUTER_GROUP_COUNT,
	"router top groups must be a strict subset of the score groups");

#endif

#define SPARK_LLM_VOCAB_COUNT SPARK_LLM_OUTPUT_VOCAB_COUNT
#define SPARK_LLM_WEIGHT_LAYER_COUNT (SPARK_LLM_LAYER_COUNT + 1u)
#define SPARK_LLM_LAYER_IS_FULL(layer_index) \
	(((layer_index) % SPARK_LLM_ATTENTION_PERIOD) == \
	 SPARK_LLM_GLOBAL_ATTENTION_PHASE)
#define SPARK_LLM_LAYER_IS_LINEAR(layer_index) \
	(((layer_index) % SPARK_LLM_ATTENTION_PERIOD) != \
	 SPARK_LLM_GLOBAL_ATTENTION_PHASE)

SPARK_LLM_STATIC_ASSERT((SPARK_LLM_LAYER_COUNT %
	SPARK_LLM_ATTENTION_PERIOD) == 0u,
	"layer groups must tile the stack exactly");
