#pragma once

/* Neutral DSpark drafter constants.
 *
 * One draft backend, many drafter shapes. The target is selected at package
 * compile time with exactly one of SPARK_DSPARK_TARGET_GLM52 /
 * SPARK_DSPARK_TARGET_K3 / SPARK_DSPARK_TARGET_DSV4_PRO_0813; every
 * shape-dependent value resolves through this header. The GLM52 table aliases
 * the measured model constants, so the existing GLM52 path is byte-identical;
 * tests/test_dspark_drafter_pin.c pins that case against the measured
 * literals. K3's table comes from inference/llms/kimi_k3/dspark.h (the
 * drafter config read from the released DSparkDraftModel checkpoint);
 * DSV4 Pro 0813's table comes from the GA contract (3 packed draft layers,
 * markov 512, noise token 128799) - fields its drafter does not declare yet
 * are zero with a comment.
 *
 * The dispatch-policy structs and the shape-independent policy constants are
 * neutral (spark_speculation_policy.h); the SPARK_DSPARK_* names below alias
 * them so the adopting models compile unchanged. */
#include <stdint.h>

#include "sparkpipe/spark_speculation_policy.h"

#if defined(SPARK_DSPARK_TARGET_GLM52)
#include "sparkpipe/spark_glm52_model.h"
#define SPARK_DSPARK_HIDDEN_DIMENSION SPARK_GLM52_MODEL_HIDDEN_DIMENSION
#define SPARK_DSPARK_MAXIMUM_CONTEXT_TOKENS SPARK_GLM52_MODEL_MAXIMUM_CONTEXT_TOKENS
#define SPARK_DSPARK_FULL_VOCAB_SIZE SPARK_GLM52_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_DSPARK_RMS_NORM_EPSILON SPARK_GLM52_MODEL_RMS_NORM_EPSILON
#define SPARK_DSPARK_ROPE_THETA SPARK_GLM52_MODEL_ROPE_THETA
#define SPARK_DSPARK_MASK_TOKEN_ID SPARK_GLM52_MODEL_DSPARK_MASK_TOKEN_ID
#define SPARK_DSPARK_AUX_LAYER_COUNT SPARK_GLM52_MODEL_DSPARK_AUX_LAYER_COUNT
#define SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER SPARK_GLM52_MODEL_DSPARK_AUX_LAYER_IDS_INITIALIZER
#define SPARK_DSPARK_DRAFT_LAYER_COUNT SPARK_GLM52_MODEL_DSPARK_DRAFT_LAYER_COUNT
#define SPARK_DSPARK_BLOCK_SIZE SPARK_GLM52_MODEL_DSPARK_BLOCK_SIZE
#define SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT SPARK_GLM52_MODEL_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT
#define SPARK_DSPARK_MARKOV_RANK SPARK_GLM52_MODEL_DSPARK_MARKOV_RANK
#define SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION SPARK_GLM52_MODEL_DSPARK_DRAFT_INTERMEDIATE_DIMENSION
#define SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT SPARK_GLM52_MODEL_DSPARK_DRAFT_ATTENTION_HEAD_COUNT
#define SPARK_DSPARK_DRAFT_KV_HEAD_COUNT SPARK_GLM52_MODEL_DSPARK_DRAFT_KV_HEAD_COUNT
#define SPARK_DSPARK_DRAFT_HEAD_DIMENSION SPARK_GLM52_MODEL_DSPARK_DRAFT_HEAD_DIMENSION
#define SPARK_DSPARK_MAX_ANCHORS SPARK_GLM52_MODEL_DSPARK_MAX_ANCHORS
#elif defined(SPARK_DSPARK_TARGET_K3)
#include "sparkpipe/spark_k3_model.h"
/* Kimi K3 drafter, read from the released DSparkDraftModel config.json
 * (inference/llms/kimi_k3/dspark.h): block 7, 8 verify positions, aux
 * {7,23,51,67,83}, 5 draft layers, 64 query heads over 16 KV heads, head
 * dim 64, intermediate 14336, markov 256, mask token 163824, rope 10000. */
#define SPARK_DSPARK_HIDDEN_DIMENSION SPARK_K3_MODEL_HIDDEN_DIMENSION
#define SPARK_DSPARK_MAXIMUM_CONTEXT_TOKENS SPARK_K3_MODEL_MAXIMUM_CONTEXT_TOKENS
#define SPARK_DSPARK_FULL_VOCAB_SIZE SPARK_K3_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_DSPARK_RMS_NORM_EPSILON SPARK_K3_MODEL_RMS_NORM_EPSILON
#define SPARK_DSPARK_ROPE_THETA 10000.0f
#define SPARK_DSPARK_MASK_TOKEN_ID 163824u
#define SPARK_DSPARK_AUX_LAYER_COUNT 5u
#define SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER { 7u, 23u, 51u, 67u, 83u }
#define SPARK_DSPARK_DRAFT_LAYER_COUNT 5u
#define SPARK_DSPARK_BLOCK_SIZE 7u
#define SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT 8u
#define SPARK_DSPARK_MARKOV_RANK 256u
#define SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION 14336u
#define SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT 64u
#define SPARK_DSPARK_DRAFT_KV_HEAD_COUNT 16u
#define SPARK_DSPARK_DRAFT_HEAD_DIMENSION 64u
#define SPARK_DSPARK_MAX_ANCHORS 1024u
#elif defined(SPARK_DSPARK_TARGET_DSV4_PRO_0813)
#include "sparkpipe/spark_dsv4_pro_model.h"
/* DSV4 Pro GA 0813 drafter (model_contracts/dsv4_pro_authoritative.json
 * dspark block): 3 draft layers at taps {58,59,60}, block 5, markov 512,
 * noise token 128799. Draft shapes pinned from the GA 0813 rank pack
 * (spark0 dsv4_pro_tp4_pp4_stage.spstage): the mtp.0/1/2 draft layers are
 * full-width mHC blocks - 128 attn heads x 512 head-dim, 1 KV head (MLA),
 * 3072 expert intermediate, 384 experts (identical to the main layer). */
#define SPARK_DSPARK_HIDDEN_DIMENSION SPARK_DSV4_PRO_HIDDEN_DIMENSION
#define SPARK_DSPARK_MAXIMUM_CONTEXT_TOKENS SPARK_DSV4_PRO_MAXIMUM_CONTEXT_TOKENS
#define SPARK_DSPARK_FULL_VOCAB_SIZE SPARK_DSV4_PRO_VOCAB_COUNT
#define SPARK_DSPARK_RMS_NORM_EPSILON SPARK_DSV4_PRO_RMS_NORM_EPSILON
#define SPARK_DSPARK_ROPE_THETA SPARK_DSV4_PRO_COMPRESSED_ROPE_THETA
#define SPARK_DSPARK_MASK_TOKEN_ID 128799u
#define SPARK_DSPARK_AUX_LAYER_COUNT 3u
#define SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER { 58u, 59u, 60u }
#define SPARK_DSPARK_DRAFT_LAYER_COUNT 3u
#define SPARK_DSPARK_BLOCK_SIZE 5u
#define SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT 8u
#define SPARK_DSPARK_MARKOV_RANK 512u
#define SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION SPARK_DSV4_PRO_DSPARK_INTERMEDIATE_DIMENSION
#define SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT SPARK_DSV4_PRO_DSPARK_ATTENTION_HEAD_COUNT
#define SPARK_DSPARK_DRAFT_KV_HEAD_COUNT SPARK_DSV4_PRO_DSPARK_KV_HEAD_COUNT
#define SPARK_DSPARK_DRAFT_HEAD_DIMENSION SPARK_DSV4_PRO_DSPARK_HEAD_DIMENSION
#define SPARK_DSPARK_MAX_ANCHORS 1024u
#else
#error "select a DSpark drafter target: define SPARK_DSPARK_TARGET_GLM52, SPARK_DSPARK_TARGET_K3, or SPARK_DSPARK_TARGET_DSV4_PRO_0813"
#endif

/* Shape-independent constants (one drafter ABI), aliased to the neutral
 * dispatch-policy core; only DEFAULT_MAX_VERIFY_TOKENS stays target-shaped. */
#define SPARK_DSPARK_ABI_VERSION SPARK_SPECULATION_ABI_VERSION
/* Request priority at or above this value selects the realtime confidence
 * floor. */
#define SPARK_DSPARK_POLICY_REALTIME_PRIORITY_THRESHOLD \
    SPARK_SPECULATION_POLICY_REALTIME_PRIORITY_THRESHOLD
#define SPARK_DSPARK_CONFIDENCE_MILLI_ONE SPARK_SPECULATION_CONFIDENCE_MILLI_ONE
#define SPARK_DSPARK_DEFAULT_MIN_CONFIDENCE_MILLI \
    SPARK_SPECULATION_DEFAULT_MIN_CONFIDENCE_MILLI
#define SPARK_DSPARK_DEFAULT_REALTIME_MIN_CONFIDENCE_MILLI \
    SPARK_SPECULATION_DEFAULT_REALTIME_MIN_CONFIDENCE_MILLI
#define SPARK_DSPARK_DEFAULT_MAX_VERIFY_TOKENS SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT
#define SPARK_DSPARK_INVALID_LAYER_INDEX SPARK_SPECULATION_INVALID_LAYER_INDEX
#define SPARK_DSPARK_VERIFIER_HIDDEN_DTYPE_BF16 \
    SPARK_SPECULATION_VERIFIER_HIDDEN_DTYPE_BF16
#define SPARK_DSPARK_DRAFT_DTYPE_BF16 SPARK_SPECULATION_DRAFT_DTYPE_BF16

#define SPARK_DSPARK_POLICY_FLAG_ENABLE_REALTIME \
    SPARK_SPECULATION_POLICY_FLAG_ENABLE_REALTIME
#define SPARK_DSPARK_POLICY_FLAG_ENABLE_UNDERFILLED_DECODE \
    SPARK_SPECULATION_POLICY_FLAG_ENABLE_UNDERFILLED_DECODE
#define SPARK_DSPARK_POLICY_FLAG_REQUIRE_CONFIDENCE_HEAD \
    SPARK_SPECULATION_POLICY_FLAG_REQUIRE_CONFIDENCE_HEAD
#define SPARK_DSPARK_POLICY_FLAG_REQUIRE_MARKOV_HEAD \
    SPARK_SPECULATION_POLICY_FLAG_REQUIRE_MARKOV_HEAD
#define SPARK_DSPARK_POLICY_DEFAULT_FLAGS SPARK_SPECULATION_POLICY_DEFAULT_FLAGS
#define SPARK_DSPARK_POLICY_KNOWN_FLAGS SPARK_SPECULATION_POLICY_KNOWN_FLAGS

#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_VALID \
    SPARK_SPECULATION_SEQUENCE_STATE_FLAG_VALID
#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_TAPS_READY \
    SPARK_SPECULATION_SEQUENCE_STATE_FLAG_TAPS_READY
#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_DRAFT_READY \
    SPARK_SPECULATION_SEQUENCE_STATE_FLAG_DRAFT_READY
#define SPARK_DSPARK_SEQUENCE_STATE_FLAG_VERIFY_INFLIGHT \
    SPARK_SPECULATION_SEQUENCE_STATE_FLAG_VERIFY_INFLIGHT

#define SPARK_DSPARK_DRAFT_RESULT_FLAG_CONFIDENCE_TRUNCATED \
    SPARK_SPECULATION_DRAFT_RESULT_FLAG_CONFIDENCE_TRUNCATED
#define SPARK_DSPARK_DRAFT_RESULT_KNOWN_FLAGS \
    SPARK_SPECULATION_DRAFT_RESULT_KNOWN_FLAGS

#define SPARK_DSPARK_VERIFY_RESULT_FLAG_ACCEPTED_ALL \
    SPARK_SPECULATION_VERIFY_RESULT_FLAG_ACCEPTED_ALL
#define SPARK_DSPARK_VERIFY_RESULT_FLAG_REJECTED \
    SPARK_SPECULATION_VERIFY_RESULT_FLAG_REJECTED
#define SPARK_DSPARK_VERIFY_RESULT_KNOWN_FLAGS \
    SPARK_SPECULATION_VERIFY_RESULT_KNOWN_FLAGS

#define SPARK_DSPARK_CONFIGURATION_DESCRIPTOR_BYTES \
    SPARK_SPECULATION_CONFIGURATION_DESCRIPTOR_BYTES
#define SPARK_DSPARK_DESCRIPTOR_BYTES SPARK_SPECULATION_DESCRIPTOR_BYTES
#define SPARK_DSPARK_SEQUENCE_STATE_DESCRIPTOR_BYTES \
    SPARK_SPECULATION_SEQUENCE_STATE_DESCRIPTOR_BYTES
#define SPARK_DSPARK_MODEL_CONTRACT_DESCRIPTOR_BYTES \
    SPARK_SPECULATION_MODEL_CONTRACT_DESCRIPTOR_BYTES
#define SPARK_DSPARK_DRAFT_REQUEST_DESCRIPTOR_BYTES \
    SPARK_SPECULATION_DRAFT_REQUEST_DESCRIPTOR_BYTES
#define SPARK_DSPARK_DRAFT_RESULT_DESCRIPTOR_BYTES \
    SPARK_SPECULATION_DRAFT_RESULT_DESCRIPTOR_BYTES
#define SPARK_DSPARK_VERIFY_RESULT_DESCRIPTOR_BYTES \
    SPARK_SPECULATION_VERIFY_RESULT_DESCRIPTOR_BYTES
