#define _POSIX_C_SOURCE 200809L
#define _FILE_OFFSET_BITS 64

#include "spark_gemma4_stagepack_format.h"


#define SPARK_SYNTH_QWEN_TEMPLATE 1
#define SPARK_SYNTH_TOOL_NAME "gemma4_pack_synthesize"
#define SPARK_SYNTH_MAX_TENSORS 2048u
#define SPARK_SYNTH_CHUNK_BYTES (8u * 1024u * 1024u)
#define SPARK_SYNTH_ALIGN_UNIT SPARK_GEMMA4_STAGEPACK_PAYLOAD_ALIGNMENT
#define SPARK_SYNTH_ENTRY_T SparkGemma4StagePackEntry
#define SPARK_SYNTH_HEADER_T SparkGemma4StagePackHeader
#define SPARK_SYNTH_SHAPE_T SparkGemma4StagePackTensorShape
#define SPARK_SYNTH_HEADER_BYTES SPARK_GEMMA4_STAGEPACK_HEADER_BYTES
#define SPARK_SYNTH_ENTRY_BYTES SPARK_GEMMA4_STAGEPACK_ENTRY_BYTES
#define SPARK_SYNTH_RESOLVE_SHAPE(kind, layer, is_global, shape) \
	(SparkGemma4StagePackResolvedShape((kind),(layer),(is_global),(shape)) < 0)
#define SPARK_SYNTH_SELECT_FORMAT(quantize, shape) \
	((quantize) != 0u ? (shape).natural_format : \
		((shape).natural_format == SPARK_GEMMA4_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_F32B128 ? \
		 SPARK_GEMMA4_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_BF16 : (shape).natural_format))
#define SPARK_SYNTH_SCALE_GROUP_SIZE(format) \
	((format) == SPARK_GEMMA4_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_MXFP4_E2M1 ? 32u : \
		((format) == SPARK_GEMMA4_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_F32B128 ? 128u : 0u))
#define SPARK_SYNTH_PAYLOAD_KIND(entry) ((entry)->weight_format)
#define SPARK_SYNTH_PACKED_FORMAT SPARK_GEMMA4_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_MXFP4_E2M1
#define SPARK_SYNTH_PACKED_NAN_MASK 0u
#define SPARK_SYNTH_F32_FORMAT SPARK_GEMMA4_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_F32
#define SPARK_SYNTH_PAYLOAD_BYTES(format, rows, columns) \
	SparkGemma4StagePackPayloadBytes((format),(rows),(columns))
#define SPARK_SYNTH_SCALE_BYTES(format, rows, columns) \
	SparkGemma4StagePackScaleBytes((format),(rows),(columns))
#define SPARK_SYNTH_FILL_SCALE(entry, buffer, bytes, state) \
	((entry)->weight_format == SPARK_GEMMA4_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_F32B128 ? \
		SparkSynthFillScaleF32Blocks((buffer),(bytes),(state)) : \
		SparkSynthFillScaleBytes((buffer),(bytes),(state)))
#define SPARK_SYNTH_MTP_LAYER SPARK_GEMMA4_STAGEPACK_MTP_LAYER
#define SPARK_SYNTH_GLOBAL_LAYER SPARK_GEMMA4_STAGEPACK_GLOBAL_LAYER
#define SPARK_SYNTH_TENSOR_EMBEDDING SPARK_GEMMA4_STAGEPACK_TENSOR_EMBEDDING
#define SPARK_SYNTH_TENSOR_FINAL_NORM SPARK_GEMMA4_STAGEPACK_TENSOR_FINAL_NORM
#define SPARK_SYNTH_TENSOR_LM_HEAD SPARK_GEMMA4_STAGEPACK_TENSOR_LM_HEAD
#define SPARK_SYNTH_MODEL_LAYER_COUNT SPARK_GEMMA4_MODEL_LAYER_COUNT
#define SPARK_SYNTH_MODEL_IS_GDN(layer) (SPARK_GEMMA4_MODEL_LAYER_IS_GDN(layer) != 0u)
#define SPARK_SYNTH_EXPECTED_TENSOR_COUNT(first, count) \
	SparkGemma4StagePackExpectedTensorCount((first),(count))
#define SPARK_SYNTH_EXPECTED_GEOMETRY(header, first, count) \
	SparkGemma4StagePackExpectedGeometry((header),(first),(count),0u)
#define SPARK_SYNTH_EVERY_LAYER_KINDS \
	SPARK_GEMMA4_STAGEPACK_TENSOR_ATTENTION_NORM,SPARK_GEMMA4_STAGEPACK_TENSOR_MLP_NORM, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_HC_DOWN,SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_HC_UP, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_HC_INJECT,SPARK_GEMMA4_STAGEPACK_TENSOR_MLP_HC_DOWN, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MLP_HC_UP,SPARK_GEMMA4_STAGEPACK_TENSOR_MLP_HC_INJECT, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_GATE,SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_W1, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_W3,SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_DOWN, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_SHARED_GATE,SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_SHARED_UP, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_SHARED_DOWN,SPARK_GEMMA4_STAGEPACK_TENSOR_MOE_SHARED_GATE_WEIGHT
#define SPARK_SYNTH_GDN_LAYER_KINDS \
	SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_QKV,SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_GATE, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_BETA,SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_DECAY, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_OUTPUT,SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_CONV_WEIGHT, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_A_LOG,SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_DT_BIAS, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_GDN_NORM
#define SPARK_SYNTH_ATTN_LAYER_KINDS \
	SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_QUERY,SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_KEY, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_VALUE,SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_OUTPUT, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_QUERY_NORM,SPARK_GEMMA4_STAGEPACK_TENSOR_ATTN_KEY_NORM, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_INDEXER_QK,SPARK_GEMMA4_STAGEPACK_TENSOR_INDEXER_Q_NORM, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_INDEXER_K_NORM
#define SPARK_SYNTH_MTP_GLOBAL_KINDS \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MTP_FC,SPARK_GEMMA4_STAGEPACK_TENSOR_MTP_EMBED_NORM, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MTP_HIDDEN_NORM,SPARK_GEMMA4_STAGEPACK_TENSOR_MTP_FINAL_NORM, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MIXER_DOWN,SPARK_GEMMA4_STAGEPACK_TENSOR_MIXER_UP, \
	SPARK_GEMMA4_STAGEPACK_TENSOR_MTP_MIXER_DOWN,SPARK_GEMMA4_STAGEPACK_TENSOR_MTP_MIXER_UP

#include "sparkpipe/spark_pack_synthesize_common.h"
