#pragma once


#include <stdint.h>
#include "inference/kernels/layer_kind.cuh"
#include "sparkpipe/spark_ling_model.h"

#define LING_HIDDEN SPARK_LING_MODEL_HIDDEN_DIMENSION
#define LING_LAYERS SPARK_LING_MODEL_LAYER_COUNT
#define LING_FIRST_ROUTED_LAYER SPARK_LING_MODEL_FIRST_ROUTED_LAYER
#define LING_VOCAB SPARK_LING_MODEL_OUTPUT_VOCAB_COUNT
#define LING_RMS_EPSILON SPARK_LING_MODEL_RMS_NORM_EPSILON
#define LING_SWIGLU_LIMIT(layer_index) \
	SPARK_LING_MODEL_EXPERT_SWIGLU_LIMIT(layer_index)
#define LING_SHARED_SWIGLU_LIMIT(layer_index) \
	SPARK_LING_MODEL_SHARED_SWIGLU_LIMIT(layer_index)

#define LING_LAYER_IS_KDA(layer_index) \
	SPARK_LING_MODEL_LAYER_IS_KDA(layer_index)
#define LING_LAYER_KIND(layer_index) \
	(LING_LAYER_IS_KDA(layer_index) ? LM_LAYER_LINEAR : LM_LAYER_LATENT)

#define LING_ATTN_HEADS SPARK_LING_MODEL_MLA_HEAD_COUNT
#define LING_LATENT SPARK_LING_MODEL_MLA_LATENT_DIMENSION
#define LING_ROPE_DIM SPARK_LING_MODEL_MLA_QK_ROPE_HEAD_DIMENSION
#define LING_QK_NOPE_DIM SPARK_LING_MODEL_MLA_QK_NOPE_HEAD_DIMENSION
#define LING_VALUE_DIM SPARK_LING_MODEL_MLA_VALUE_HEAD_DIMENSION
#define LING_QUERY_DIM SPARK_LING_MODEL_MLA_QUERY_DIMENSION
#define LING_QK_HEAD_DIM SPARK_LING_MODEL_MLA_QK_HEAD_DIMENSION
#define LING_ROPE_THETA SPARK_LING_MODEL_MLA_ROPE_THETA
#define LING_LATENT_ROW (LING_LATENT + LING_ROPE_DIM)
static_assert(LING_ROPE_DIM == 64u,
	"ling rotates the 64 rope dims of every latent attention head");
static_assert(LING_QK_HEAD_DIM == (LING_QK_NOPE_DIM + LING_ROPE_DIM),
	"ling attention heads carry nope then rope sections");

#define LING_KDA_HEADS SPARK_LING_MODEL_KDA_HEAD_COUNT
#define LING_KDA_KEY_DIM SPARK_LING_MODEL_KDA_HEAD_KEY_DIMENSION
#define LING_KDA_VALUE_DIM SPARK_LING_MODEL_KDA_HEAD_VALUE_DIMENSION
#define LING_KDA_QK_DIM SPARK_LING_MODEL_KDA_QKV_DIMENSION
#define LING_KDA_CONV_KERNEL SPARK_LING_MODEL_KDA_CONV_KERNEL
#define LING_KDA_GATE_LOWER_BOUND SPARK_LING_MODEL_KDA_GATE_LOWER_BOUND
#define LING_KDA_STATE_ELEMENT_BYTES SPARK_LING_MODEL_KDA_STATE_ELEMENT_BYTES
#define LING_KDA_STATE_BYTES_PER_LAYER SPARK_LING_MODEL_KDA_STATE_BYTES_PER_LAYER

#define LING_EXPERTS SPARK_LING_MODEL_MOE_EXPERT_COUNT
#define LING_TOP_K SPARK_LING_MODEL_MOE_TOP_K
#define LING_EXPERT_INTERMEDIATE SPARK_LING_MODEL_MOE_INTERMEDIATE_DIMENSION
#define LING_DENSE_INTERMEDIATE SPARK_LING_MODEL_DENSE_INTERMEDIATE_DIMENSION
#define LING_ROUTED_SCALE SPARK_LING_MODEL_MOE_ROUTED_SCALING_FACTOR
#define LING_W1_COMPONENTS SPARK_LING_MODEL_MOE_W1_COMPONENT_COUNT
#define LING_ROUTER_GROUPS SPARK_LING_MODEL_MOE_ROUTER_GROUP_COUNT
#define LING_ROUTER_TOP_GROUPS SPARK_LING_MODEL_MOE_ROUTER_TOP_GROUPS

#define LING_FP8_SCALE_BLOCK SPARK_LING_MODEL_FP8_SCALE_BLOCK

#define LING_MTP_LAYER_INDEX SPARK_LING_MODEL_MTP_LAYER_INDEX

#define LING_KV_BITS 16u
#define LING_KV_PAGE_SLOTS 64u
#define LING_KV_SLOT_BYTES SPARK_LING_MODEL_KV_SLOT_BYTES
#define LING_KDA_CONV_WINDOW_BYTES_PER_LAYER \
	(LING_KDA_QK_DIM * 3u * LING_KDA_CONV_KERNEL * 2u)

#define LING_ROUTED_LAYERS (LING_LAYERS - LING_FIRST_ROUTED_LAYER)
#define LING_GATE_UP_DIM (LING_EXPERT_INTERMEDIATE * LING_W1_COMPONENTS)
#define LING_WEIGHT_LAYERS SPARK_LING_MODEL_WEIGHT_LAYER_COUNT

static inline uint32_t LingRowsPerExpert(uint32_t tokens)
{
	return(((tokens * LING_TOP_K) + LING_EXPERTS - 1u) / LING_EXPERTS);
}
