#ifndef SPARKPIPE_SPARK_GLM52_BATCH_TUNING_H
#define SPARKPIPE_SPARK_GLM52_BATCH_TUNING_H


#include <stdint.h>

#include "sparkpipe/spark_glm52_model.h"

#ifndef SPARK_BATCH_BUCKET
#define SPARK_BATCH_BUCKET 1024u
#endif

#if SPARK_BATCH_BUCKET != 1u && SPARK_BATCH_BUCKET != 2u && \
	SPARK_BATCH_BUCKET != 4u && SPARK_BATCH_BUCKET != 8u && \
	SPARK_BATCH_BUCKET != 16u && SPARK_BATCH_BUCKET != 32u && \
	SPARK_BATCH_BUCKET != 64u && SPARK_BATCH_BUCKET != 128u && \
	SPARK_BATCH_BUCKET != 256u && SPARK_BATCH_BUCKET != 512u && \
	SPARK_BATCH_BUCKET != 1024u
#error SPARK_BATCH_BUCKET must name a built variant bucket: 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
#endif

#ifndef GLM52_EXPERT_CODEC_NAME
#error GLM52_EXPERT_CODEC_NAME is required: the variant module identifier names the expert codec
#endif

#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_PREFIX \
	"spark.glm52.resident_decode_stage.bf16.expert_" GLM52_EXPERT_CODEC_NAME \
	".h6144.l78.e256.k8"
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_SUFFIX \
	"v2"

#define SPARK_BATCH_VARIANT_MODULE_ID_PREFIX \
	SPARK_GLM52_BATCH_VARIANT_MODULE_ID_PREFIX
#define SPARK_BATCH_VARIANT_MODULE_ID_SUFFIX \
	SPARK_GLM52_BATCH_VARIANT_MODULE_ID_SUFFIX
#define SPARK_BATCH_VARIANT_TOP_K SPARK_GLM52_MODEL_MOE_TOP_K
#define SPARK_BATCH_VARIANT_EXPERT_COUNT SPARK_GLM52_MODEL_MOE_EXPERT_COUNT
#define SPARK_BATCH_VARIANT_FN(name) SparkGlm52BatchVariant##name

#include "sparkpipe/spark_batch_variant_tuning_common.h"

#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B1 SPARK_BATCH_VARIANT_MODULE_ID_B1
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B2 SPARK_BATCH_VARIANT_MODULE_ID_B2
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B4 SPARK_BATCH_VARIANT_MODULE_ID_B4
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B8 SPARK_BATCH_VARIANT_MODULE_ID_B8
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B16 SPARK_BATCH_VARIANT_MODULE_ID_B16
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B32 SPARK_BATCH_VARIANT_MODULE_ID_B32
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B64 SPARK_BATCH_VARIANT_MODULE_ID_B64
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B128 SPARK_BATCH_VARIANT_MODULE_ID_B128
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B256 SPARK_BATCH_VARIANT_MODULE_ID_B256
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B512 SPARK_BATCH_VARIANT_MODULE_ID_B512
#define SPARK_GLM52_BATCH_VARIANT_MODULE_ID_B1024 SPARK_BATCH_VARIANT_MODULE_ID_B1024
#define SPARK_GLM52_BATCH_TUNING_MODULE_ID SPARK_BATCH_VARIANT_MODULE_ID
#define SPARK_GLM52_BATCH_TUNING_GROUPED_PEAK_ROWS SPARK_BATCH_VARIANT_GROUPED_PEAK_ROWS
#define SPARK_GLM52_BATCH_TUNING_GROUPED_TILE_M SPARK_BATCH_VARIANT_GROUPED_TILE_M

#endif
