#pragma once

#include <stdint.h>

#include "sparkpipe/spark_glm52_model.h"
#include "sparkpipe/spark_status.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SPARK_DSPARK_TARGET_GLM52 1
#include "sparkpipe/spark_dspark_drafter.h"
#include "sparkpipe/spark_speculation_policy.h"

#define SPARK_GLM52_DSPARK_ABI_VERSION SPARK_DSPARK_ABI_VERSION
#define SPARK_GLM52_DSPARK_AUX_LAYER_COUNT SPARK_DSPARK_AUX_LAYER_COUNT
#define SPARK_GLM52_DSPARK_AUX_LAYER_IDS_INITIALIZER SPARK_DSPARK_AUX_LAYER_IDS_INITIALIZER
#define SPARK_GLM52_DSPARK_DRAFT_LAYER_COUNT SPARK_DSPARK_DRAFT_LAYER_COUNT
#define SPARK_GLM52_DSPARK_BLOCK_SIZE SPARK_DSPARK_BLOCK_SIZE
#define SPARK_GLM52_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT SPARK_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT
#define SPARK_GLM52_DSPARK_FULL_VOCAB_SIZE SPARK_DSPARK_FULL_VOCAB_SIZE
#define SPARK_GLM52_DSPARK_HIDDEN_DIMENSION SPARK_DSPARK_HIDDEN_DIMENSION
#define SPARK_GLM52_DSPARK_MARKOV_RANK SPARK_DSPARK_MARKOV_RANK
#define SPARK_GLM52_DSPARK_DRAFT_INTERMEDIATE_DIMENSION SPARK_DSPARK_DRAFT_INTERMEDIATE_DIMENSION
#define SPARK_GLM52_DSPARK_DRAFT_ATTENTION_HEAD_COUNT SPARK_DSPARK_DRAFT_ATTENTION_HEAD_COUNT
#define SPARK_GLM52_DSPARK_DRAFT_KV_HEAD_COUNT SPARK_DSPARK_DRAFT_KV_HEAD_COUNT
#define SPARK_GLM52_DSPARK_DRAFT_HEAD_DIMENSION SPARK_DSPARK_DRAFT_HEAD_DIMENSION
#define SPARK_GLM52_DSPARK_MAX_ANCHORS SPARK_DSPARK_MAX_ANCHORS
#define SPARK_GLM52_DSPARK_CONFIDENCE_MILLI_ONE SPARK_DSPARK_CONFIDENCE_MILLI_ONE
#define SPARK_GLM52_DSPARK_DEFAULT_MIN_CONFIDENCE_MILLI SPARK_DSPARK_DEFAULT_MIN_CONFIDENCE_MILLI
#define SPARK_GLM52_DSPARK_DEFAULT_REALTIME_MIN_CONFIDENCE_MILLI SPARK_DSPARK_DEFAULT_REALTIME_MIN_CONFIDENCE_MILLI
#define SPARK_GLM52_DSPARK_DEFAULT_MAX_VERIFY_TOKENS SPARK_DSPARK_DEFAULT_MAX_VERIFY_TOKENS
#define SPARK_GLM52_DSPARK_INVALID_LAYER_INDEX SPARK_DSPARK_INVALID_LAYER_INDEX
#define SPARK_GLM52_DSPARK_VERIFIER_HIDDEN_DTYPE_BF16 SPARK_DSPARK_VERIFIER_HIDDEN_DTYPE_BF16
#define SPARK_GLM52_DSPARK_DRAFT_DTYPE_BF16 SPARK_DSPARK_DRAFT_DTYPE_BF16
#define SPARK_GLM52_DSPARK_POLICY_FLAG_ENABLE_REALTIME SPARK_DSPARK_POLICY_FLAG_ENABLE_REALTIME
#define SPARK_GLM52_DSPARK_POLICY_FLAG_ENABLE_UNDERFILLED_DECODE SPARK_DSPARK_POLICY_FLAG_ENABLE_UNDERFILLED_DECODE
#define SPARK_GLM52_DSPARK_POLICY_FLAG_REQUIRE_CONFIDENCE_HEAD SPARK_DSPARK_POLICY_FLAG_REQUIRE_CONFIDENCE_HEAD
#define SPARK_GLM52_DSPARK_POLICY_FLAG_REQUIRE_MARKOV_HEAD SPARK_DSPARK_POLICY_FLAG_REQUIRE_MARKOV_HEAD
#define SPARK_GLM52_DSPARK_POLICY_DEFAULT_FLAGS SPARK_DSPARK_POLICY_DEFAULT_FLAGS
#define SPARK_GLM52_DSPARK_POLICY_KNOWN_FLAGS SPARK_DSPARK_POLICY_KNOWN_FLAGS
#define SPARK_GLM52_DSPARK_SEQUENCE_STATE_FLAG_VALID SPARK_DSPARK_SEQUENCE_STATE_FLAG_VALID
#define SPARK_GLM52_DSPARK_SEQUENCE_STATE_FLAG_TAPS_READY SPARK_DSPARK_SEQUENCE_STATE_FLAG_TAPS_READY
#define SPARK_GLM52_DSPARK_SEQUENCE_STATE_FLAG_DRAFT_READY SPARK_DSPARK_SEQUENCE_STATE_FLAG_DRAFT_READY
#define SPARK_GLM52_DSPARK_SEQUENCE_STATE_FLAG_VERIFY_INFLIGHT SPARK_DSPARK_SEQUENCE_STATE_FLAG_VERIFY_INFLIGHT
#define SPARK_GLM52_DSPARK_DRAFT_RESULT_FLAG_CONFIDENCE_TRUNCATED SPARK_DSPARK_DRAFT_RESULT_FLAG_CONFIDENCE_TRUNCATED
#define SPARK_GLM52_DSPARK_DRAFT_RESULT_KNOWN_FLAGS SPARK_DSPARK_DRAFT_RESULT_KNOWN_FLAGS
#define SPARK_GLM52_DSPARK_VERIFY_RESULT_FLAG_ACCEPTED_ALL SPARK_DSPARK_VERIFY_RESULT_FLAG_ACCEPTED_ALL
#define SPARK_GLM52_DSPARK_VERIFY_RESULT_FLAG_REJECTED SPARK_DSPARK_VERIFY_RESULT_FLAG_REJECTED
#define SPARK_GLM52_DSPARK_VERIFY_RESULT_KNOWN_FLAGS SPARK_DSPARK_VERIFY_RESULT_KNOWN_FLAGS

#define SPARK_GLM52_DSPARK_CONFIGURATION_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkSpeculatorConfiguration))
#define SPARK_GLM52_DSPARK_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkSpeculator))
#define SPARK_GLM52_DSPARK_SEQUENCE_STATE_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkSequenceState))
#define SPARK_GLM52_DSPARK_MODEL_CONTRACT_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkModelContract))
#define SPARK_GLM52_DSPARK_DRAFT_REQUEST_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkDraftRequest))
#define SPARK_GLM52_DSPARK_DRAFT_RESULT_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkDraftResult))
#define SPARK_GLM52_DSPARK_VERIFY_RESULT_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkVerifyResult))
#define SPARK_GLM52_DSPARK_HIDDEN_TAP_PLAN_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkGlm52DsparkHiddenTapPlan))


typedef SparkSpeculationModelContract SparkGlm52DsparkModelContract;
typedef SparkSpeculationPolicyDraftRequest SparkGlm52DsparkDraftRequest;
typedef SparkSpeculationPolicyDraftResult SparkGlm52DsparkDraftResult;
typedef SparkSpeculationPolicyVerifyResult SparkGlm52DsparkVerifyResult;
typedef SparkSpeculationSequenceState SparkGlm52DsparkSequenceState;
typedef SparkSpeculationConfiguration SparkGlm52DsparkSpeculatorConfiguration;
typedef SparkSpeculationSpeculator SparkGlm52DsparkSpeculator;
typedef SparkSpeculationDraftFunction SparkGlm52DsparkDraftFunction;

SparkStatus SparkGlm52DsparkBuildDefaultModelContract(
    SparkGlm52DsparkModelContract *model_contract);

#define SparkGlm52DsparkValidateModelContract SparkSpeculationPolicyValidateModelContract
#define SparkGlm52DsparkInitialize SparkSpeculationPolicyInitialize
#define SparkGlm52DsparkValidate SparkSpeculationPolicyValidate
#define SparkGlm52DsparkMarkVerifierTapsReady SparkSpeculationPolicyMarkVerifierTapsReady
#define SparkGlm52DsparkEnsureDraft SparkSpeculationPolicyEnsureDraft
#define SparkGlm52DsparkGetDraft SparkSpeculationPolicyGetDraft
#define SparkGlm52DsparkCompleteVerify SparkSpeculationPolicyCompleteVerify
#define SparkGlm52DsparkResolveVerifierTokens SparkSpeculationPolicyResolveVerifierTokens
#define SparkGlm52DsparkCancelSequence SparkSpeculationPolicyCancelSequence

typedef struct SparkGlm52DsparkTapStage
{
    uint32_t target_layer_index;
    uint32_t stage_index;
    uint32_t stage_first_layer_index;
    uint32_t stage_layer_count;
    uint32_t layer_offset_in_stage;
    uint32_t reserved;
} SparkGlm52DsparkTapStage;

typedef struct SparkGlm52DsparkHiddenTapPlan
{
    uint32_t abi_version;
    uint32_t descriptor_bytes;
    uint32_t aux_layer_count;
    uint32_t hidden_dimension;
    uint32_t pp_stage_count;
    uint32_t pp_stage_layer_count;
    uint32_t reserved0;
    uint32_t reserved1;
    SparkGlm52DsparkTapStage tap_stages[SPARK_GLM52_DSPARK_AUX_LAYER_COUNT];
} SparkGlm52DsparkHiddenTapPlan;
SparkStatus SparkGlm52DsparkBuildDefaultHiddenTapPlan(
    SparkGlm52DsparkHiddenTapPlan *tap_plan);
SparkStatus SparkGlm52DsparkValidateHiddenTapPlan(
    const SparkGlm52DsparkHiddenTapPlan *tap_plan);


#ifdef __cplusplus
}
#endif
