#pragma once

#define SPARK_LLM_HIDDEN_DIMENSION 2560u
#define SPARK_LLM_LAYER_COUNT 42u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT 157184u
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS 262144u
#define SPARK_LLM_RMS_NORM_EPSILON 1e-06f
#define SPARK_LLM_FP8_SCALE_BLOCK 128u
#define SPARK_LLM_KV_BITS 16u
#define SPARK_LLM_BF16_ELEMENT_BYTES 2u
#define SPARK_LLM_KV_PAGE_SLOTS 64u

#define SPARK_LLM_ATTENTION_KIND SPARK_LLM_ATTENTION_KIND_LATENT_LINEAR
#define SPARK_LLM_ATTENTION_PERIOD 6u
#define SPARK_LLM_GLOBAL_ATTENTION_PHASE 5u

#define SPARK_LLM_MLA_HEAD_COUNT 32u
#define SPARK_LLM_MLA_LATENT_DIMENSION 512u
#define SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION 128u
#define SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION 64u
#define SPARK_LLM_MLA_V_HEAD_DIMENSION 128u
#define SPARK_LLM_ROPE_THETA 6000000.0f
#define SPARK_LLM_MLA_Q_LORA_RANK 0u
#define SPARK_LLM_MLA_USE_NOPE 1u
#define SPARK_LLM_MLA_ROPE_INTERLEAVE 1u
#define SPARK_LLM_MLA_ROPE_PARTIAL_FACTOR 1.0f
#define SPARK_LLM_MLA_QK_SCALE 0.07216878364870323f
#define SPARK_LLM_MLA_OUTPUT_GATE 1u

#define SPARK_LLM_KDA_HEAD_COUNT 32u
#define SPARK_LLM_KDA_HEAD_KEY_DIMENSION 128u
#define SPARK_LLM_KDA_HEAD_VALUE_DIMENSION 128u
#define SPARK_LLM_KDA_CONV_KERNEL 4u
#define SPARK_LLM_KDA_SHORT_CONV_KERNEL 4u
#define SPARK_LLM_KDA_STATE_ELEMENT_BYTES 4u
#define SPARK_LLM_KDA_GATE_LOWER_BOUND -5.0f
#define SPARK_LLM_KDA_CHUNK_TOKENS 64u
#define SPARK_LLM_KDA_QK_L2NORM 1u
#define SPARK_LLM_KDA_FULL_RANK_GATE 1u
#define SPARK_LLM_KDA_SAFE_GATE 1u

#define SPARK_LLM_FIRST_ROUTED_LAYER 2u
#define SPARK_LLM_MOE_EXPERT_COUNT 512u
#define SPARK_LLM_MOE_TOP_K 8u
#define SPARK_LLM_MOE_INTERMEDIATE_DIMENSION 768u
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION 6144u
#define SPARK_LLM_MOE_ROUTED_SCALING_FACTOR 2.5f
#define SPARK_LLM_MOE_W1_COMPONENT_COUNT 2u
#define SPARK_LLM_MOE_ROUTER_GROUP_COUNT 8u
#define SPARK_LLM_MOE_ROUTER_TOP_GROUPS 4u
#define SPARK_LLM_MOE_ROUTER_CORRECTION_BIAS 1u
#define SPARK_LLM_MOE_NORM_TOPK_PROB 1u
#define SPARK_LLM_MOE_SHARED_EXPERT_COUNT 1u

#define SPARK_LLM_END_OF_TEXT_TOKEN_ID 156895u
#define SPARK_LLM_PAD_TOKEN_ID 156892u

#define SPARK_LLM_MTP_LAYER_INDEX SPARK_LLM_LAYER_COUNT
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH 256u

#include "sparkpipe/spark_driver_defines.h"

#if SPARK_LLM_MLA_Q_LORA_RANK != 0u
#error ling applies the query projection directly; a lora rank belongs to another family
#endif
#if SPARK_LLM_MLA_OUTPUT_GATE != 1u
#error ling gates the attention output head-wise; disable the gate only with a contract change
#endif
#if SPARK_LLM_MLA_LATENT_DIMENSION != 512u || \
	SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION != 64u
#error ling inherits the k3 latent cache slot layout (512 latent + 64 rope)
#endif
#if (SPARK_LLM_MLA_HEAD_COUNT % 16u) != 0u || \
	(SPARK_LLM_KDA_HEAD_COUNT % 16u) != 0u
#error ling assumes TP16: every head count must divide by 16
#endif
#if (SPARK_LLM_MOE_EXPERT_COUNT % 16u) != 0u
#error ling assumes TP16: the expert count must divide into 16 ranks
#endif

#define SPARK_LLM_KV_SLOT_BYTES \
	((SPARK_LLM_MLA_KV_A_DIMENSION * SPARK_LLM_KV_BITS) / 8u)

SPARK_LLM_STATIC_ASSERT(SPARK_LLM_KV_SLOT_BYTES ==
	SPARK_LLM_MLA_KV_A_DIMENSION * SPARK_LLM_KV_BITS / 8u,
	"the ling kv slot carries the latent-plus-rope row in the stated kv format");
