#ifndef SPARKPIPE_SPARK_LING_MODEL_H
#define SPARKPIPE_SPARK_LING_MODEL_H

#include <stdint.h>

#define SPARK_LING_MODEL_HIDDEN_DIMENSION 2560u
#define SPARK_LING_MODEL_LAYER_COUNT 42u
#define SPARK_LING_MODEL_MTP_LAYER_INDEX 42u
#define SPARK_LING_MODEL_OUTPUT_VOCAB_COUNT 157184u
#define SPARK_LING_MODEL_VOCAB_COUNT SPARK_LING_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_LING_MODEL_MAXIMUM_CONTEXT_TOKENS 262144u
#define SPARK_LING_MODEL_RMS_NORM_EPSILON 1e-06f
#define SPARK_LING_MODEL_END_OF_TEXT_TOKEN_ID 156895u
#define SPARK_LING_MODEL_PAD_TOKEN_ID 156892u

#define SPARK_LING_MODEL_MAX_PREFILL_TOKENS_PER_DISPATCH 256u

#define SPARK_LING_MODEL_ATTENTION_PERIOD 6u
#define SPARK_LING_MODEL_GLOBAL_ATTENTION_PHASE 5u
#define SPARK_LING_MODEL_MLA_LAYER_COUNT 7u
#define SPARK_LING_MODEL_KDA_LAYER_COUNT 35u
#define SPARK_LING_MODEL_LAYER_IS_MLA(layer_index) \
	(((layer_index) % SPARK_LING_MODEL_ATTENTION_PERIOD) == \
	 SPARK_LING_MODEL_GLOBAL_ATTENTION_PHASE)
#define SPARK_LING_MODEL_LAYER_IS_KDA(layer_index) \
	(((layer_index) % SPARK_LING_MODEL_ATTENTION_PERIOD) != \
	 SPARK_LING_MODEL_GLOBAL_ATTENTION_PHASE)

#define SPARK_LING_MODEL_KDA_HEAD_COUNT 32u
#define SPARK_LING_MODEL_KDA_HEAD_KEY_DIMENSION 128u
#define SPARK_LING_MODEL_KDA_HEAD_VALUE_DIMENSION 128u
#define SPARK_LING_MODEL_KDA_QKV_DIMENSION \
	(SPARK_LING_MODEL_KDA_HEAD_COUNT * SPARK_LING_MODEL_KDA_HEAD_KEY_DIMENSION)
#define SPARK_LING_MODEL_KDA_VALUE_DIMENSION \
	(SPARK_LING_MODEL_KDA_HEAD_COUNT * SPARK_LING_MODEL_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_LING_MODEL_KDA_CONV_KERNEL 4u
#define SPARK_LING_MODEL_KDA_CHUNK_TOKENS 64u
#define SPARK_LING_MODEL_KDA_QK_L2NORM 1u
#define SPARK_LING_MODEL_KDA_FULL_RANK_GATE 1u
#define SPARK_LING_MODEL_KDA_SAFE_GATE 1u
#define SPARK_LING_MODEL_KDA_GATE_LOWER_BOUND -5.0f
#define SPARK_LING_MODEL_KDA_SHORT_CONV_KERNEL 4u
#define SPARK_LING_MODEL_KDA_STATE_ELEMENT_BYTES 4u
#define SPARK_LING_MODEL_KDA_STATE_ELEMENTS_PER_HEAD \
	(SPARK_LING_MODEL_KDA_HEAD_KEY_DIMENSION * SPARK_LING_MODEL_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_LING_MODEL_KDA_STATE_BYTES_PER_LAYER \
	(SPARK_LING_MODEL_KDA_HEAD_COUNT * \
	 SPARK_LING_MODEL_KDA_STATE_ELEMENTS_PER_HEAD * \
	 SPARK_LING_MODEL_KDA_STATE_ELEMENT_BYTES)
#define SPARK_LING_MODEL_KDA_CONV_WINDOW_BYTES_PER_LAYER \
	(3u * SPARK_LING_MODEL_KDA_QKV_DIMENSION * \
	 SPARK_LING_MODEL_KDA_SHORT_CONV_KERNEL * 2u)
#define SPARK_LING_MODEL_KDA_A_LOG_HEAD_COUNT SPARK_LING_MODEL_KDA_HEAD_COUNT

#define SPARK_LING_MODEL_MLA_HEAD_COUNT 32u
#define SPARK_LING_MODEL_MLA_Q_LORA_RANK 0u
#define SPARK_LING_MODEL_MLA_LATENT_DIMENSION 512u
#define SPARK_LING_MODEL_MLA_QK_NOPE_HEAD_DIMENSION 128u
#define SPARK_LING_MODEL_MLA_QK_ROPE_HEAD_DIMENSION 64u
#define SPARK_LING_MODEL_MLA_VALUE_HEAD_DIMENSION 128u
#define SPARK_LING_MODEL_MLA_USE_NOPE 1u
#define SPARK_LING_MODEL_MLA_ROPE_THETA 6000000.0f
#define SPARK_LING_MODEL_MLA_ROPE_INTERLEAVE 1u
#define SPARK_LING_MODEL_MLA_ROPE_PARTIAL_FACTOR 1.0f
#define SPARK_LING_MODEL_MLA_QK_SCALE 0.07216878364870323f
#define SPARK_LING_MODEL_MLA_OUTPUT_GATE 1u
#define SPARK_LING_MODEL_MLA_QK_HEAD_DIMENSION \
	(SPARK_LING_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + \
	 SPARK_LING_MODEL_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_LING_MODEL_MLA_QUERY_DIMENSION \
	(SPARK_LING_MODEL_MLA_HEAD_COUNT * SPARK_LING_MODEL_MLA_QK_HEAD_DIMENSION)
#define SPARK_LING_MODEL_MLA_KV_A_DIMENSION \
	(SPARK_LING_MODEL_MLA_LATENT_DIMENSION + \
	 SPARK_LING_MODEL_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_LING_MODEL_MLA_KV_B_DIMENSION \
	(SPARK_LING_MODEL_MLA_HEAD_COUNT * \
	 (SPARK_LING_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + \
	  SPARK_LING_MODEL_MLA_VALUE_HEAD_DIMENSION))
#define SPARK_LING_MODEL_MLA_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_LING_MODEL_MLA_HEAD_COUNT * \
	 SPARK_LING_MODEL_MLA_VALUE_HEAD_DIMENSION)

#define SPARK_LING_MODEL_MOE_EXPERT_COUNT 512u
#define SPARK_LING_MODEL_MOE_TOP_K 8u
#define SPARK_LING_MODEL_MOE_SHARED_EXPERT_COUNT 1u
#define SPARK_LING_MODEL_MOE_INTERMEDIATE_DIMENSION 768u
#define SPARK_LING_MODEL_DENSE_INTERMEDIATE_DIMENSION 6144u
#define SPARK_LING_MODEL_FIRST_DENSE_LAYER_COUNT 2u
#define SPARK_LING_MODEL_FIRST_ROUTED_LAYER 2u
#define SPARK_LING_MODEL_MOE_ROUTED_SCALING_FACTOR 2.5f
#define SPARK_LING_MODEL_MOE_NORM_TOPK_PROB 1u
#define SPARK_LING_MODEL_MOE_W1_COMPONENT_COUNT 2u
#define SPARK_LING_MODEL_MOE_ROUTER_GROUP_COUNT 8u
#define SPARK_LING_MODEL_MOE_ROUTER_TOP_GROUPS 4u
#define SPARK_LING_MODEL_MOE_ROUTER_CORRECTION_BIAS 1u
#define SPARK_LING_MODEL_MOE_ROUTED_GATE_UP_DIMENSION \
	(SPARK_LING_MODEL_MOE_INTERMEDIATE_DIMENSION * \
	 SPARK_LING_MODEL_MOE_W1_COMPONENT_COUNT)

#define SPARK_LING_MODEL_FP8_SCALE_BLOCK 128u

#define SPARK_LING_MODEL_KV_BITS 16u
#define SPARK_LING_MODEL_KV_PAGE_SLOTS 64u
#define SPARK_LING_MODEL_KV_SLOT_BYTES \
	((SPARK_LING_MODEL_MLA_KV_A_DIMENSION * SPARK_LING_MODEL_KV_BITS) / 8u)

#define SPARK_LING_MODEL_HEAD_COUNT \
	SPARK_LING_MODEL_MLA_HEAD_COUNT
#define SPARK_LING_MODEL_LATENT_DIMENSION \
	SPARK_LING_MODEL_MLA_LATENT_DIMENSION
#define SPARK_LING_MODEL_QUERY_DIMENSION \
	SPARK_LING_MODEL_MLA_QUERY_DIMENSION
#define SPARK_LING_MODEL_VALUE_HEAD_DIMENSION \
	SPARK_LING_MODEL_MLA_VALUE_HEAD_DIMENSION
#define SPARK_LING_MODEL_ROPE_DIMENSION \
	SPARK_LING_MODEL_MLA_QK_ROPE_HEAD_DIMENSION
#define SPARK_LING_MODEL_CACHE_TOKEN_ELEMENTS \
	SPARK_LING_MODEL_MLA_KV_A_DIMENSION
#define SPARK_LING_MODEL_BF16_ELEMENT_BYTES 2u
#define SPARK_LING_MODEL_WEIGHT_LAYER_COUNT \
	(SPARK_LING_MODEL_LAYER_COUNT + 1u)

#if SPARK_LING_MODEL_MLA_Q_LORA_RANK != 0u
#error ling applies the query projection directly; a lora rank belongs to another family
#endif
#if SPARK_LING_MODEL_MLA_OUTPUT_GATE != 1u
#error ling gates the attention output head-wise; disable the gate only with a contract change
#endif
#if SPARK_LING_MODEL_MLA_LATENT_DIMENSION != 512u || \
	SPARK_LING_MODEL_MLA_QK_ROPE_HEAD_DIMENSION != 64u
#error ling inherits the k3 latent cache slot layout (512 latent + 64 rope)
#endif
#if (SPARK_LING_MODEL_MLA_HEAD_COUNT % 16u) != 0u || \
	(SPARK_LING_MODEL_KDA_HEAD_COUNT % 16u) != 0u
#error ling assumes TP16: every head count must divide by 16
#endif
#if (SPARK_LING_MODEL_MOE_EXPERT_COUNT % 16u) != 0u
#error ling assumes TP16: the expert count must divide into 16 ranks
#endif
#if SPARK_LING_MODEL_MOE_ROUTER_TOP_GROUPS >= SPARK_LING_MODEL_MOE_ROUTER_GROUP_COUNT
#error ling routes through 4 of 8 score groups; top groups must be a strict subset
#endif
#if (SPARK_LING_MODEL_LAYER_COUNT % SPARK_LING_MODEL_ATTENTION_PERIOD) != 0u
#error ling layer groups must tile the stack exactly
#endif

#endif
