/* Large stage packs exceed 2 GB: 64-bit file offsets are required. */
#define _POSIX_C_SOURCE 200809L
#define _FILE_OFFSET_BITS 64

#include "spark_qwen4_flash_stagepack_format.h"

/*
 * Synthetic qwen4_flash stage pack writer, slice-aware.
 *
 * Emits every tensor one pipeline STAGE will demand, at the geometry the
 * module was compiled for, with reproducible pseudo-random contents: the
 * loader, the shape table, the slice arithmetic and the layer walk run end
 * to end against it. This file is the family configuration — stage-pack
 * types, the HC+MoE and indexer-augmented kind inventory, the FP8 scale
 * layout, and the quantization policy; the machinery is the shared
 * generator core.
 *
 * Family facts (recorded, not re-derived): --bf16 substitutes BF16 only
 * where the quantized codecs would sit (natural F32B128 experts): f32/
 * bf16-natural kinds (A_log, dt_bias, norms...) keep their natural format
 * — the loader accepts BF16 over an F32B128 natural shape ONLY, and a
 * blanket conversion produces pack_entry_invalid on the first f32-natural
 * kind. MXFP4 scales group at 32; the FP8_E4M3 codec scales at 128
 * blocks; everything else is unscaled. The geometry resolver takes the
 * stage index (pinned 0u here, as pasted).
 */

#define SPARK_SYNTH_QWEN_TEMPLATE 1
#define SPARK_SYNTH_TOOL_NAME "qwen4_flash_pack_synthesize"
#define SPARK_SYNTH_MAX_TENSORS 2048u
#define SPARK_SYNTH_CHUNK_BYTES (8u * 1024u * 1024u)
#define SPARK_SYNTH_ALIGN_UNIT SPARK_QWEN4_FLASH_STAGEPACK_PAYLOAD_ALIGNMENT
#define SPARK_SYNTH_ENTRY_T SparkQwen4FlashStagePackEntry
#define SPARK_SYNTH_HEADER_T SparkQwen4FlashStagePackHeader
#define SPARK_SYNTH_SHAPE_T SparkQwen4FlashStagePackTensorShape
#define SPARK_SYNTH_HEADER_BYTES SPARK_QWEN4_FLASH_STAGEPACK_HEADER_BYTES
#define SPARK_SYNTH_ENTRY_BYTES SPARK_QWEN4_FLASH_STAGEPACK_ENTRY_BYTES
#define SPARK_SYNTH_RESOLVE_SHAPE(kind, layer, is_global, shape) \
	(SparkQwen4FlashStagePackResolvedShape((kind),(layer),(is_global),(shape)) < 0)
#define SPARK_SYNTH_SELECT_FORMAT(quantize, shape) \
	((quantize) != 0u ? (shape).natural_format : \
		((shape).natural_format == SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_F32B128 ? \
		 SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_BF16 : (shape).natural_format))
#define SPARK_SYNTH_SCALE_GROUP_SIZE(format) \
	((format) == SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_MXFP4_E2M1 ? 32u : \
		((format) == SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_F32B128 ? 128u : 0u))
#define SPARK_SYNTH_PAYLOAD_KIND(entry) ((entry)->weight_format)
#define SPARK_SYNTH_PACKED_FORMAT SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_MXFP4_E2M1
#define SPARK_SYNTH_PACKED_NAN_MASK 0u
#define SPARK_SYNTH_F32_FORMAT SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_F32
#define SPARK_SYNTH_PAYLOAD_BYTES(format, rows, columns) \
	SparkQwen4FlashStagePackPayloadBytes((format),(rows),(columns))
#define SPARK_SYNTH_SCALE_BYTES(format, rows, columns) \
	SparkQwen4FlashStagePackScaleBytes((format),(rows),(columns))
#define SPARK_SYNTH_FILL_SCALE(entry, buffer, bytes, state) \
	((entry)->weight_format == SPARK_QWEN4_FLASH_RESIDENT_DECODE_STAGE_WEIGHT_FORMAT_FP8_E4M3_F32B128 ? \
		SparkSynthFillScaleF32Blocks((buffer),(bytes),(state)) : \
		SparkSynthFillScaleBytes((buffer),(bytes),(state)))
#define SPARK_SYNTH_MTP_LAYER SPARK_QWEN4_FLASH_STAGEPACK_MTP_LAYER
#define SPARK_SYNTH_GLOBAL_LAYER SPARK_QWEN4_FLASH_STAGEPACK_GLOBAL_LAYER
#define SPARK_SYNTH_TENSOR_EMBEDDING SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_EMBEDDING
#define SPARK_SYNTH_TENSOR_FINAL_NORM SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_FINAL_NORM
#define SPARK_SYNTH_TENSOR_LM_HEAD SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_LM_HEAD
#define SPARK_SYNTH_MODEL_LAYER_COUNT SPARK_QWEN4_FLASH_MODEL_LAYER_COUNT
#define SPARK_SYNTH_MODEL_IS_GDN(layer) (SPARK_QWEN4_FLASH_MODEL_LAYER_IS_GDN(layer) != 0u)
#define SPARK_SYNTH_EXPECTED_TENSOR_COUNT(first, count) \
	SparkQwen4FlashStagePackExpectedTensorCount((first),(count))
#define SPARK_SYNTH_EXPECTED_GEOMETRY(header, first, count) \
	SparkQwen4FlashStagePackExpectedGeometry((header),(first),(count),0u)
#define SPARK_SYNTH_EVERY_LAYER_KINDS \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTENTION_NORM,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MLP_NORM, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_HC_DOWN,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_HC_UP, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_HC_INJECT,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MLP_HC_DOWN, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MLP_HC_UP,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MLP_HC_INJECT, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_GATE,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_W1, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_W3,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_DOWN, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_SHARED_GATE,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_SHARED_UP, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_SHARED_DOWN,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MOE_SHARED_GATE_WEIGHT
#define SPARK_SYNTH_GDN_LAYER_KINDS \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_QKV,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_GATE, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_BETA,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_DECAY, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_OUTPUT,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_CONV_WEIGHT, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_A_LOG,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_DT_BIAS, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_GDN_NORM
#define SPARK_SYNTH_ATTN_LAYER_KINDS \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_QUERY,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_KEY, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_VALUE,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_OUTPUT, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_QUERY_NORM,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_ATTN_KEY_NORM, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_INDEXER_QK,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_INDEXER_Q_NORM, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_INDEXER_K_NORM
#define SPARK_SYNTH_MTP_GLOBAL_KINDS \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MTP_FC,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MTP_EMBED_NORM, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MTP_HIDDEN_NORM,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MTP_FINAL_NORM, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MIXER_DOWN,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MIXER_UP, \
	SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MTP_MIXER_DOWN,SPARK_QWEN4_FLASH_STAGEPACK_TENSOR_MTP_MIXER_UP

#include "sparkpipe/spark_pack_synthesize_common.h"
