#pragma once

#include <stdint.h>

#include "sparkpipe/spark_minimax_h3_model.h"

#define SPARK_MINIMAX_H3_KV_BLOCK_TOKENS 256u
#define SPARK_MINIMAX_H3_KV_TOKEN_LAYER_BYTES \
	(2u * SPARK_MINIMAX_H3_ENCODER_KV_DIMENSION * \
	 SPARK_MINIMAX_H3_BF16_ELEMENT_BYTES)
#define SPARK_MINIMAX_H3_KV_TOKEN_BYTES \
	(SPARK_MINIMAX_H3_KV_TOKEN_LAYER_BYTES * \
	 SPARK_MINIMAX_H3_ENCODER_LAYER_COUNT)
#define SPARK_MINIMAX_H3_KV_MAX_PROMPT_BLOCK_COUNT \
	((SPARK_MINIMAX_H3_ENCODER_MAX_PROMPT_TOKENS + \
	  SPARK_MINIMAX_H3_KV_BLOCK_TOKENS - 1u) / \
	 SPARK_MINIMAX_H3_KV_BLOCK_TOKENS)

SPARK_MINIMAX_H3_STATIC_ASSERT(SPARK_MINIMAX_H3_KV_TOKEN_LAYER_BYTES == 4096u,
	"h3 encoder kv per token per layer must be k+v bf16 at 1024 columns");
SPARK_MINIMAX_H3_STATIC_ASSERT(SPARK_MINIMAX_H3_KV_MAX_PROMPT_BLOCK_COUNT == 2u,
	"h3 encoder prompt must admit within two kv pages at the block size");
