#pragma once

#include <stdint.h>

#define SPARK_MINIMAX_H3_MODEL_ID "MiniMaxAI/MiniMax-H3"
#define SPARK_MINIMAX_H3_MODEL_ARCHITECTURE "MiniMaxH3ModularPipeline"
#define SPARK_MINIMAX_H3_DIT_ARCHITECTURE "MiniMaxH3Transformer3DModel"
#define SPARK_MINIMAX_H3_VAE_ARCHITECTURE "AutoencoderKLMiniMaxH3"
#define SPARK_MINIMAX_H3_AUDIO_VAE_ARCHITECTURE "AutoencoderKLMiniMaxH3Audio"

#define SPARK_MINIMAX_H3_ENCODER_HIDDEN_DIMENSION 5120u
#define SPARK_MINIMAX_H3_ENCODER_LAYER_COUNT 64u
#define SPARK_MINIMAX_H3_ENCODER_ATTENTION_HEAD_COUNT 64u
#define SPARK_MINIMAX_H3_ENCODER_KV_HEAD_COUNT 8u
#define SPARK_MINIMAX_H3_ENCODER_HEAD_DIMENSION 128u
#define SPARK_MINIMAX_H3_ENCODER_INTERMEDIATE_DIMENSION 25600u
#define SPARK_MINIMAX_H3_ENCODER_VOCAB_COUNT 151936u
#define SPARK_MINIMAX_H3_ENCODER_MROPE_SECTION_TEMPORAL 24u
#define SPARK_MINIMAX_H3_ENCODER_MROPE_SECTION_HEIGHT 20u
#define SPARK_MINIMAX_H3_ENCODER_MROPE_SECTION_WIDTH 20u
#define SPARK_MINIMAX_H3_ENCODER_ROPE_THETA 5000000.0f
#define SPARK_MINIMAX_H3_ENCODER_ROPE_DIMENSION 64u
#define SPARK_MINIMAX_H3_ENCODER_QUERY_DIMENSION \
	(SPARK_MINIMAX_H3_ENCODER_ATTENTION_HEAD_COUNT * \
	 SPARK_MINIMAX_H3_ENCODER_HEAD_DIMENSION)
#define SPARK_MINIMAX_H3_ENCODER_KV_DIMENSION \
	(SPARK_MINIMAX_H3_ENCODER_KV_HEAD_COUNT * \
	 SPARK_MINIMAX_H3_ENCODER_HEAD_DIMENSION)
#define SPARK_MINIMAX_H3_ENCODER_MAX_PROMPT_TOKENS 512u
#define SPARK_MINIMAX_H3_ENCODER_RMS_NORM_EPSILON 1e-06f
#define SPARK_MINIMAX_H3_ENCODER_HARVEST_LAYER 50u
#define SPARK_MINIMAX_H3_ENCODER_MAX_POSITION_TOKENS 262144u

#define SPARK_MINIMAX_H3_DIT_HIDDEN_DIMENSION 5376u
#define SPARK_MINIMAX_H3_DIT_BLOCK_COUNT 50u
#define SPARK_MINIMAX_H3_DIT_REFINER_BLOCK_COUNT 2u
#define SPARK_MINIMAX_H3_DIT_ATTENTION_HEAD_COUNT 56u
#define SPARK_MINIMAX_H3_DIT_HEAD_DIMENSION 128u
#define SPARK_MINIMAX_H3_DIT_QKV_DIMENSION \
	(SPARK_MINIMAX_H3_DIT_ATTENTION_HEAD_COUNT * \
	 SPARK_MINIMAX_H3_DIT_HEAD_DIMENSION)
#define SPARK_MINIMAX_H3_DIT_FFN_DIMENSION 14336u
#define SPARK_MINIMAX_H3_DIT_FFN_FUSED_DIMENSION \
	(2u * SPARK_MINIMAX_H3_DIT_FFN_DIMENSION)
#define SPARK_MINIMAX_H3_DIT_TIME_FREQ_DIMENSION 256u
#define SPARK_MINIMAX_H3_DIT_TIME_EMBED_DIMENSION 2688u
#define SPARK_MINIMAX_H3_DIT_ADALN_ROWS \
	(18u * SPARK_MINIMAX_H3_DIT_HIDDEN_DIMENSION)
#define SPARK_MINIMAX_H3_DIT_NORM_OUT_ROWS \
	(2u * SPARK_MINIMAX_H3_DIT_HIDDEN_DIMENSION)
#define SPARK_MINIMAX_H3_DIT_LATENT_CHANNELS 24u
#define SPARK_MINIMAX_H3_DIT_PATCH_TEMPORAL 1u
#define SPARK_MINIMAX_H3_DIT_PATCH_HEIGHT 2u
#define SPARK_MINIMAX_H3_DIT_PATCH_WIDTH 2u
#define SPARK_MINIMAX_H3_DIT_PATCH_ELEMENTS \
	(SPARK_MINIMAX_H3_DIT_LATENT_CHANNELS * \
	 SPARK_MINIMAX_H3_DIT_PATCH_HEIGHT * SPARK_MINIMAX_H3_DIT_PATCH_WIDTH)
#define SPARK_MINIMAX_H3_DIT_AUDIO_LATENT_CHANNELS 32u
#define SPARK_MINIMAX_H3_DIT_AUDIO_PATCH_ELEMENTS \
	SPARK_MINIMAX_H3_DIT_AUDIO_LATENT_CHANNELS
#define SPARK_MINIMAX_H3_DIT_CONTEXT_DIMENSION 5120u
#define SPARK_MINIMAX_H3_DIT_ROPE_FREQ_DIMENSION 16u
#define SPARK_MINIMAX_H3_DIT_ROPE_THETA 10000.0f
#define SPARK_MINIMAX_H3_DIT_NORM_EPSILON 1e-05f
#define SPARK_MINIMAX_H3_DIT_QK_NORM_EPSILON 1e-05f
#define SPARK_MINIMAX_H3_DIT_FINAL_NORM_EPSILON 1e-05f

#define SPARK_MINIMAX_H3_VIDEO_VAE_LATENT_CHANNELS 24u
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_LAYER_COUNT 36u
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HEAD_COUNT 32u
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HEAD_DIMENSION 64u
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HIDDEN_DIMENSION \
	(SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HEAD_COUNT * \
	 SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HEAD_DIMENSION)
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_FFN_MULTIPLIER 4u
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_FFN_DIMENSION \
	(SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HIDDEN_DIMENSION * \
	 SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_FFN_MULTIPLIER)
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_REGISTER_TOKEN_COUNT 4u
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_ROPE_THETA 100.0f
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_ROPE_DIMENSION \
	(SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HEAD_DIMENSION * 3u / 4u)
#define SPARK_MINIMAX_H3_VIDEO_VAE_CLIP_LENGTH 17u
#define SPARK_MINIMAX_H3_VIDEO_VAE_TOKEN_DROP 3u
#define SPARK_MINIMAX_H3_VIDEO_VAE_CONV_LEVEL_COUNT 6u
#define SPARK_MINIMAX_H3_VIDEO_VAE_CONV_BLOCK_OUT_CHANNELS \
	128u,256u,256u,512u,512u,1024u
#define SPARK_MINIMAX_H3_VIDEO_VAE_CONV_TOP_CHANNELS 1024u
#define SPARK_MINIMAX_H3_VIDEO_VAE_LAYERS_PER_BLOCK 2u
#define SPARK_MINIMAX_H3_VIDEO_VAE_NORM_GROUP_COUNT 32u
#define SPARK_MINIMAX_H3_VIDEO_VAE_NORM_EPSILON 1e-06f
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_NORM_EPSILON 1e-05f
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_FFN_FUSED_DIMENSION \
	(2u * SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_FFN_DIMENSION)
#define SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_PROJ_OUT_ELEMENTS 3072u
#define SPARK_MINIMAX_H3_VIDEO_VAE_SPATIAL_DOWNSAMPLE 16u
#define SPARK_MINIMAX_H3_VIDEO_VAE_TEMPORAL_DOWNSAMPLE 4u

#define SPARK_MINIMAX_H3_AUDIO_VAE_LATENT_CHANNELS 32u
#define SPARK_MINIMAX_H3_AUDIO_VAE_SAMPLE_RATE_HZ 32000u
#define SPARK_MINIMAX_H3_AUDIO_VAE_LATENT_RATE_HZ 40u
#define SPARK_MINIMAX_H3_AUDIO_VAE_DECODER_RATE_COUNT 7u
#define SPARK_MINIMAX_H3_AUDIO_VAE_UPSAMPLE_FACTOR 800u
#define SPARK_MINIMAX_H3_AUDIO_VAE_DECODER_DIMENSION 1024u
#define SPARK_MINIMAX_H3_AUDIO_VAE_LATENT_DIM 2048u
#define SPARK_MINIMAX_H3_AUDIO_VAE_PRE_BLOCK_CHANNELS 32u
#define SPARK_MINIMAX_H3_AUDIO_VAE_PRE_BLOCK_HIDDEN 2048u
#define SPARK_MINIMAX_H3_AUDIO_VAE_RESBLOCK_STAGE_COUNT 7u
#define SPARK_MINIMAX_H3_AUDIO_VAE_RESBLOCKS_PER_STAGE 9u
#define SPARK_MINIMAX_H3_AUDIO_SCHEDULER_SHIFT 3.0f

#define SPARK_MINIMAX_H3_SCHEDULER_SHIFT 12.0f

#define SPARK_MINIMAX_H3_SLICE_DURATION_SECONDS 4u
#define SPARK_MINIMAX_H3_SLICE_FPS 24u
#define SPARK_MINIMAX_H3_SLICE_SHORT_EDGE 480u
#define SPARK_MINIMAX_H3_SLICE_WIDTH 832u
#define SPARK_MINIMAX_H3_SLICE_HEIGHT 480u
#define SPARK_MINIMAX_H3_SLICE_FRAME_COUNT 96u
#define SPARK_MINIMAX_H3_SLICE_LATENT_TEMPORAL 25u
#define SPARK_MINIMAX_H3_SLICE_LATENT_HEIGHT 15u
#define SPARK_MINIMAX_H3_SLICE_LATENT_WIDTH 26u
#define SPARK_MINIMAX_H3_SLICE_VIDEO_TOKEN_COUNT \
	(SPARK_MINIMAX_H3_SLICE_LATENT_TEMPORAL * \
	 SPARK_MINIMAX_H3_SLICE_LATENT_HEIGHT * \
	 SPARK_MINIMAX_H3_SLICE_LATENT_WIDTH)
#define SPARK_MINIMAX_H3_SLICE_AUDIO_TOKEN_COUNT 160u

#define SPARK_MINIMAX_H3_TP_DEGREE 4u
#define SPARK_MINIMAX_H3_BF16_ELEMENT_BYTES 2u

_Static_assert(SPARK_MINIMAX_H3_DIT_QKV_DIMENSION == 7168u,
	"h3 dit fused qkv width per landed config");
_Static_assert(SPARK_MINIMAX_H3_DIT_ADALN_ROWS == 96768u,
	"h3 dit per-block modulation width per landed safetensors header");
_Static_assert(SPARK_MINIMAX_H3_DIT_PATCH_ELEMENTS == 96u,
	"h3 dit video proj_in width per landed safetensors header");
_Static_assert(SPARK_MINIMAX_H3_DIT_AUDIO_PATCH_ELEMENTS == 32u,
	"h3 dit audio proj_in width per landed safetensors header");
_Static_assert(SPARK_MINIMAX_H3_DIT_TIME_EMBED_DIMENSION == 2688u,
	"h3 dit time embedding output width per landed safetensors header");
_Static_assert(SPARK_MINIMAX_H3_DIT_NORM_OUT_ROWS == 10752u,
	"h3 dit final modulation width per landed safetensors header");
_Static_assert(SPARK_MINIMAX_H3_ENCODER_QUERY_DIMENSION == 8192u &&
	SPARK_MINIMAX_H3_ENCODER_KV_DIMENSION == 1024u,
	"h3 encoder attention projection widths per landed config");
_Static_assert(SPARK_MINIMAX_H3_ENCODER_MROPE_SECTION_TEMPORAL +
	SPARK_MINIMAX_H3_ENCODER_MROPE_SECTION_HEIGHT +
	SPARK_MINIMAX_H3_ENCODER_MROPE_SECTION_WIDTH ==
	SPARK_MINIMAX_H3_ENCODER_ROPE_DIMENSION,
	"h3 encoder mrope sections must cover the rope dimension");
_Static_assert(SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_HIDDEN_DIMENSION == 2048u,
	"h3 video vae transformer head hidden per landed config");
_Static_assert(SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_ROPE_DIMENSION == 48u,
	"h3 video vae rope dim ratio 0.75 of head dim per landed config");
_Static_assert(SPARK_MINIMAX_H3_AUDIO_VAE_UPSAMPLE_FACTOR == 800u,
	"h3 audio vae decoder rates must multiply to the 800x stride");
_Static_assert(SPARK_MINIMAX_H3_AUDIO_VAE_LATENT_RATE_HZ *
	SPARK_MINIMAX_H3_AUDIO_VAE_UPSAMPLE_FACTOR ==
	SPARK_MINIMAX_H3_AUDIO_VAE_SAMPLE_RATE_HZ,
	"h3 audio vae latent rate times stride must equal the sample rate");
_Static_assert(SPARK_MINIMAX_H3_SLICE_VIDEO_TOKEN_COUNT == 9750u,
	"h3 slice latent grid per design section 6");
_Static_assert(SPARK_MINIMAX_H3_SLICE_FRAME_COUNT ==
	SPARK_MINIMAX_H3_SLICE_DURATION_SECONDS * SPARK_MINIMAX_H3_SLICE_FPS,
	"h3 slice frame count must match duration times fps");
_Static_assert(SPARK_MINIMAX_H3_AUDIO_VAE_RESBLOCK_STAGE_COUNT *
	SPARK_MINIMAX_H3_AUDIO_VAE_RESBLOCKS_PER_STAGE == 63u,
	"h3 audio vae decoder carries 63 resblocks per landed checkpoint");
_Static_assert(SPARK_MINIMAX_H3_VIDEO_VAE_DECODER_PROJ_OUT_ELEMENTS == 3072u,
	"h3 video vae decoder proj_out width per landed safetensors header");
