#pragma once

#define SPARK_LLM_HIDDEN_DIMENSION 3072u
#define SPARK_LLM_LAYER_COUNT 48u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT 100352u
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_LLM_RMS_NORM_EPSILON 1e-06f
#define SPARK_LLM_FP8_SCALE_BLOCK 128u
#define SPARK_LLM_KV_BITS 16u
#define SPARK_LLM_BF16_ELEMENT_BYTES 2u
#define SPARK_LLM_KV_PAGE_SLOTS 64u

#define SPARK_LLM_ATTENTION_KIND SPARK_LLM_ATTENTION_KIND_GQA
#define SPARK_LLM_ATTENTION_PERIOD 4u
#define SPARK_LLM_GLOBAL_ATTENTION_PHASE 0u

#define SPARK_LLM_FULL_QUERY_HEAD_COUNT 48u
#define SPARK_LLM_FULL_KV_HEAD_COUNT 8u
#define SPARK_LLM_HEAD_DIMENSION 128u
#define SPARK_LLM_ATTENTION_SCALE 0.08838834764831845f
#define SPARK_LLM_SLIDING_WINDOW_TOKENS 512u

#define SPARK_LLM_ROPE_MODE SPARK_LLM_ROPE_MODE_YARN
#define SPARK_LLM_ROPE_FULL_THETA 5e5f
#define SPARK_LLM_ROPE_YARN_FACTOR 128.0f

#define SPARK_LLM_ROPE_FULL_ORIGINAL_POSITIONS 8192.0f
#define SPARK_LLM_ROPE_FULL_BETA_FAST 32.0f
#define SPARK_LLM_ROPE_FULL_BETA_SLOW 1.0f
#define SPARK_LLM_ROPE_FULL_ATTENTION_FACTOR 1.4852030263919618f
#define SPARK_LLM_ROPE_FULL_PARTIAL_ROTARY_FACTOR 0.5f
#define SPARK_LLM_ROPE_SLIDING_THETA 1e4f
#define SPARK_LLM_ROPE_SLIDING_PARTIAL_ROTARY_FACTOR 1.0f
#define SPARK_LLM_SLIDING_QUERY_HEAD_COUNT 72u
#define SPARK_LLM_ATTENTION_GATE_HEAD_PER_LAYER 1u

#define SPARK_LLM_FIRST_ROUTED_LAYER 1u
#define SPARK_LLM_MOE_EXPERT_COUNT 256u
#define SPARK_LLM_MOE_TOP_K 10u
#define SPARK_LLM_MOE_SHARED_EXPERT_COUNT 1u
#define SPARK_LLM_MOE_INTERMEDIATE_DIMENSION 1024u
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION 12288u
#define SPARK_LLM_MOE_ROUTED_SCALING_FACTOR 2.5f
#define SPARK_LLM_MOE_W1_COMPONENT_COUNT 2u
#define SPARK_LLM_MOE_ROUTER_GROUP_COUNT 256u
#define SPARK_LLM_MOE_ROUTER_TOP_GROUPS 10u
#define SPARK_LLM_MOE_ROUTER_CORRECTION_BIAS 1u
#define SPARK_LLM_MOE_NORM_TOPK_PROB 1u

#define SPARK_LLM_TENSOR_PARALLEL_DEGREE 8u
#define SPARK_LLM_PIPELINE_STAGE_COUNT 2u

#define SPARK_LLM_KV_POOL_TOKENS 4194304u
#define SPARK_LLM_RESTRICTED_VOCAB_COUNT 256u
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH 256u

#define SPARK_LLM_END_OF_TEXT_TOKEN_ID 2u
#define SPARK_LLM_END_OF_TURN_TOKEN_ID 24u
#define SPARK_LLM_BEGINNING_OF_TEXT_TOKEN_ID 2u
#define SPARK_LLM_PAD_TOKEN_ID 9u
#define SPARK_LLM_END_OF_TEXT_TOKEN_COUNT 2u

#define SPARK_LLM_LAYER_THREADS 256u
#define SPARK_LLM_ATTN_THREADS 256u

#include "sparkpipe/spark_driver_defines.h"

#if (SPARK_LLM_LAYER_COUNT % SPARK_LLM_PIPELINE_STAGE_COUNT) != 0u
#error laguna stages must split the layer count evenly
#endif
#if (SPARK_LLM_FULL_QUERY_HEAD_COUNT % SPARK_LLM_TENSOR_PARALLEL_DEGREE) != 0u || \
	(SPARK_LLM_SLIDING_QUERY_HEAD_COUNT % SPARK_LLM_TENSOR_PARALLEL_DEGREE) != 0u || \
	(SPARK_LLM_FULL_KV_HEAD_COUNT % SPARK_LLM_TENSOR_PARALLEL_DEGREE) != 0u
#error laguna is TP8: every attention head count must divide by 8
#endif
#if (SPARK_LLM_MOE_EXPERT_COUNT % SPARK_LLM_TENSOR_PARALLEL_DEGREE) != 0u
#error laguna is TP8: the expert count must divide into 8 ranks
#endif
#if SPARK_LLM_HEAD_DIMENSION != 128u
#error laguna head_dim is stated 128
#endif
#if SPARK_LLM_OUTPUT_VOCAB_COUNT != 100352u
#error laguna vocab is stated 100352
#endif
#if SPARK_LLM_SLIDING_QUERY_HEAD_COUNT <= SPARK_LLM_FULL_QUERY_HEAD_COUNT
#error laguna sliding layers carry the wider query head slice
#endif
#if SPARK_LLM_MOE_ROUTER_GROUP_COUNT != SPARK_LLM_MOE_EXPERT_COUNT || \
	SPARK_LLM_MOE_ROUTER_TOP_GROUPS != SPARK_LLM_MOE_TOP_K
#error laguna routes per expert: each expert is its own router group
#endif

#define SPARK_LLM_TP_RANK_KV_HEAD_COUNT \
	(SPARK_LLM_FULL_KV_HEAD_COUNT / SPARK_LLM_TENSOR_PARALLEL_DEGREE)
#define SPARK_LLM_TP_RANK_QUERY_HEAD_COUNT_FULL \
	(SPARK_LLM_FULL_QUERY_HEAD_COUNT / SPARK_LLM_TENSOR_PARALLEL_DEGREE)
#define SPARK_LLM_TP_RANK_QUERY_HEAD_COUNT_SLIDING \
	(SPARK_LLM_SLIDING_QUERY_HEAD_COUNT / SPARK_LLM_TENSOR_PARALLEL_DEGREE)
#define SPARK_LLM_TP_RANK_EXPERT_COUNT \
	(SPARK_LLM_MOE_EXPERT_COUNT / SPARK_LLM_TENSOR_PARALLEL_DEGREE)
#define SPARK_LLM_KV_SLOT_BYTES \
	(SPARK_LLM_TP_RANK_KV_HEAD_COUNT * \
	 (SPARK_LLM_HEAD_DIMENSION + SPARK_LLM_HEAD_DIMENSION) * \
	 (SPARK_LLM_KV_BITS / 8u))
#define SPARK_LLM_FULL_ROTARY_DIMENSION \
	((uint32_t)(SPARK_LLM_HEAD_DIMENSION * \
	 SPARK_LLM_ROPE_FULL_PARTIAL_ROTARY_FACTOR))
#define SPARK_LLM_SLIDING_ROTARY_DIMENSION \
	((uint32_t)(SPARK_LLM_HEAD_DIMENSION * \
	 SPARK_LLM_ROPE_SLIDING_PARTIAL_ROTARY_FACTOR))
#define SPARK_LLM_ROUTED_SCALE SPARK_LLM_MOE_ROUTED_SCALING_FACTOR

SPARK_LLM_STATIC_ASSERT(SPARK_LLM_TP_RANK_QUERY_HEAD_COUNT_SLIDING *
		SPARK_LLM_HEAD_DIMENSION ==
	9u * 128u,
	"the sliding rank slice is 9 whole heads at TP8");
SPARK_LLM_STATIC_ASSERT(SPARK_LLM_TP_RANK_QUERY_HEAD_COUNT_FULL *
		SPARK_LLM_HEAD_DIMENSION ==
	6u * 128u,
	"the full-attention rank slice is 6 whole heads at TP8");
SPARK_LLM_STATIC_ASSERT(SPARK_LLM_TP_RANK_KV_HEAD_COUNT == 1u,
	"one kv head per rank at TP8");
SPARK_LLM_STATIC_ASSERT(SPARK_LLM_TP_RANK_QUERY_HEAD_COUNT_SLIDING %
		SPARK_LLM_TP_RANK_KV_HEAD_COUNT ==
	0u,
	"the GQA decode groups query heads onto kv heads");
SPARK_LLM_STATIC_ASSERT(SPARK_LLM_KV_SLOT_BYTES ==
	SPARK_LLM_TP_RANK_KV_HEAD_COUNT * 2u * SPARK_LLM_HEAD_DIMENSION *
		SPARK_LLM_KV_BITS / 8u,
	"the laguna kv slot carries the key-plus-value row in the stated kv format");
