#pragma once

#define SPARK_LLM_FAMILY_TAG                    laguna
#define SPARK_LLM_HIDDEN_DIMENSION              3072u
#define SPARK_LLM_LAYER_COUNT                   48u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT            100352u
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS        1048576u
#define SPARK_LLM_RMS_NORM_EPSILON              1e-06f
#define SPARK_LLM_END_OF_TEXT_TOKEN_ID          2u
#define SPARK_LLM_END_OF_TURN_TOKEN_ID          24u
#define SPARK_LLM_PAD_TOKEN_ID                  9u
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH 256u

#define SPARK_LLM_ATTENTION_HEAD_DIMENSION      128u
#define SPARK_LLM_ATTENTION_KV_HEAD_COUNT       8u
#define SPARK_LLM_Q_HEAD_COUNT_FULL             48u
#define SPARK_LLM_Q_HEAD_COUNT_SLIDING          72u
#define SPARK_LLM_SLIDING_WINDOW                512u
#define SPARK_LLM_ATTENTION_SCALE               0.08838834764831845f

#define SPARK_LLM_ROPE_FULL_THETA               5e5f
#define SPARK_LLM_ROPE_FULL_FACTOR              128.0f
#define SPARK_LLM_ROPE_FULL_ORIGINAL_POSITIONS  8192.0f
#define SPARK_LLM_ROPE_FULL_BETA_FAST           32.0f
#define SPARK_LLM_ROPE_FULL_BETA_SLOW           1.0f
#define SPARK_LLM_ROPE_FULL_ATTENTION_FACTOR    1.4852030263919618f
#define SPARK_LLM_ROPE_FULL_ROTARY_DIMENSION    64u
#define SPARK_LLM_ROPE_SLIDING_THETA            1e4f
#define SPARK_LLM_ROPE_SLIDING_ROTARY_DIMENSION 128u

#define SPARK_LLM_ATTENTION_GATE_HEAD_PER_LAYER 1u

#define SPARK_LLM_MOE_EXPERT_COUNT              256u
#define SPARK_LLM_MOE_TOP_K                     10u
#define SPARK_LLM_MOE_SHARED_EXPERT_COUNT       1u
#define SPARK_LLM_MOE_INTERMEDIATE_DIMENSION    1024u
#define SPARK_LLM_MOE_ROUTED_SCALING_FACTOR     2.5f
#define SPARK_LLM_MOE_NORM_TOPK_PROB            1u
#define SPARK_LLM_FIRST_ROUTED_LAYER            1u
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION  12288u

#define SPARK_LLM_MTP_ENABLED                   0u
#define SPARK_LLM_MTP_DRAFT_DEPTH               1u
