#ifndef SPARKPIPE_SPARK_LAGUNA_MODEL_H
#define SPARKPIPE_SPARK_LAGUNA_MODEL_H

#include <stdint.h>

#define SPARK_LAGUNA_MODEL_HIDDEN_DIMENSION 3072u
#define SPARK_LAGUNA_MODEL_LAYER_COUNT 48u
#define SPARK_LAGUNA_MODEL_OUTPUT_VOCAB_COUNT 100352u
#define SPARK_LAGUNA_MODEL_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_LAGUNA_MODEL_RMS_NORM_EPSILON 1e-06f
#define SPARK_LAGUNA_MODEL_END_OF_TEXT_TOKEN_ID 2u
#define SPARK_LAGUNA_MODEL_END_OF_TURN_TOKEN_ID 24u
#define SPARK_LAGUNA_MODEL_BEGINNING_OF_TEXT_TOKEN_ID 2u
#define SPARK_LAGUNA_MODEL_PAD_TOKEN_ID 9u
#define SPARK_LAGUNA_MODEL_END_OF_TEXT_TOKEN_COUNT 2u

#define SPARK_LAGUNA_MODEL_KV_POOL_TOKENS 4194304u
#define SPARK_LAGUNA_MODEL_RESTRICTED_VOCAB_COUNT 256u
#define SPARK_LAGUNA_MODEL_MAX_PREFILL_TOKENS_PER_DISPATCH 256u

#define SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION 128u
#define SPARK_LAGUNA_MODEL_ATTENTION_KV_HEAD_COUNT 8u
#define SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_FULL 48u
#define SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_SLIDING 72u
#define SPARK_LAGUNA_MODEL_SLIDING_WINDOW 512u
#define SPARK_LAGUNA_MODEL_ATTENTION_SCALE 0.08838834764831845f
#define SPARK_LAGUNA_MODEL_FULL_LAYER_COUNT 12u
#define SPARK_LAGUNA_MODEL_SLIDING_LAYER_COUNT 36u

static const uint32_t SPARK_LAGUNA_MODEL_LAYER_HEAD_COUNT_TABLE[SPARK_LAGUNA_MODEL_LAYER_COUNT] =
{
	48u, 72u, 72u, 72u, 48u, 72u, 72u, 72u,
	48u, 72u, 72u, 72u, 48u, 72u, 72u, 72u,
	48u, 72u, 72u, 72u, 48u, 72u, 72u, 72u,
	48u, 72u, 72u, 72u, 48u, 72u, 72u, 72u,
	48u, 72u, 72u, 72u, 48u, 72u, 72u, 72u,
	48u, 72u, 72u, 72u, 48u, 72u, 72u, 72u
};

static const uint32_t SPARK_LAGUNA_MODEL_LAYER_IS_SLIDING_TABLE[SPARK_LAGUNA_MODEL_LAYER_COUNT] =
{
	0u, 1u, 1u, 1u, 0u, 1u, 1u, 1u,
	0u, 1u, 1u, 1u, 0u, 1u, 1u, 1u,
	0u, 1u, 1u, 1u, 0u, 1u, 1u, 1u,
	0u, 1u, 1u, 1u, 0u, 1u, 1u, 1u,
	0u, 1u, 1u, 1u, 0u, 1u, 1u, 1u,
	0u, 1u, 1u, 1u, 0u, 1u, 1u, 1u
};

#define SPARK_LAGUNA_MODEL_LAYER_HEAD_COUNT(layer_index) \
	(SPARK_LAGUNA_MODEL_LAYER_HEAD_COUNT_TABLE[(layer_index)])
#define SPARK_LAGUNA_MODEL_LAYER_IS_SLIDING(layer_index) \
	(SPARK_LAGUNA_MODEL_LAYER_IS_SLIDING_TABLE[(layer_index)] != 0u)

#define SPARK_LAGUNA_MODEL_ROPE_FULL_THETA 5e5f
#define SPARK_LAGUNA_MODEL_ROPE_FULL_FACTOR 128.0f
#define SPARK_LAGUNA_MODEL_ROPE_FULL_ORIGINAL_POSITIONS 8192.0f
#define SPARK_LAGUNA_MODEL_ROPE_FULL_BETA_FAST 32.0f
#define SPARK_LAGUNA_MODEL_ROPE_FULL_BETA_SLOW 1.0f
#define SPARK_LAGUNA_MODEL_ROPE_FULL_ATTENTION_FACTOR 1.4852030263919618f
#define SPARK_LAGUNA_MODEL_ROPE_FULL_PARTIAL_ROTARY_FACTOR 0.5f
#define SPARK_LAGUNA_MODEL_ROPE_FULL_ROTARY_DIMENSION \
	((uint32_t)(SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION * \
	 SPARK_LAGUNA_MODEL_ROPE_FULL_PARTIAL_ROTARY_FACTOR))
#define SPARK_LAGUNA_MODEL_ROPE_SLIDING_THETA 1e4f
#define SPARK_LAGUNA_MODEL_ROPE_SLIDING_PARTIAL_ROTARY_FACTOR 1.0f
#define SPARK_LAGUNA_MODEL_ROPE_SLIDING_ROTARY_DIMENSION \
	((uint32_t)(SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION * \
	 SPARK_LAGUNA_MODEL_ROPE_SLIDING_PARTIAL_ROTARY_FACTOR))

#define SPARK_LAGUNA_MODEL_ATTENTION_GATE_HEAD_PER_LAYER 1u

#define SPARK_LAGUNA_MODEL_MOE_EXPERT_COUNT 256u
#define SPARK_LAGUNA_MODEL_MOE_TOP_K 10u
#define SPARK_LAGUNA_MODEL_MOE_SHARED_EXPERT_COUNT 1u
#define SPARK_LAGUNA_MODEL_MOE_INTERMEDIATE_DIMENSION 1024u
#define SPARK_LAGUNA_MODEL_DENSE_INTERMEDIATE_DIMENSION 12288u
#define SPARK_LAGUNA_MODEL_FIRST_DENSE_LAYER_COUNT 1u
#define SPARK_LAGUNA_MODEL_FIRST_ROUTED_LAYER 1u
#define SPARK_LAGUNA_MODEL_MOE_ROUTED_SCALING_FACTOR 2.5f
#define SPARK_LAGUNA_MODEL_MOE_NORM_TOPK_PROB 1u
#define SPARK_LAGUNA_MODEL_MOE_W1_COMPONENT_COUNT 2u

#define SPARK_LAGUNA_MODEL_TENSOR_PARALLEL_DEGREE 4u
#define SPARK_LAGUNA_MODEL_PIPELINE_STAGE_COUNT 4u
#define SPARK_LAGUNA_MODEL_TP4_Q_HEAD_COUNT_FULL \
	(SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_FULL / 4u)
#define SPARK_LAGUNA_MODEL_TP4_Q_HEAD_COUNT_SLIDING \
	(SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_SLIDING / 4u)
#define SPARK_LAGUNA_MODEL_TP4_KV_HEAD_COUNT \
	(SPARK_LAGUNA_MODEL_ATTENTION_KV_HEAD_COUNT / 4u)
#define SPARK_LAGUNA_MODEL_TP4_EXPERT_COUNT \
	(SPARK_LAGUNA_MODEL_MOE_EXPERT_COUNT / 4u)
#define SPARK_LAGUNA_MODEL_TP8_Q_HEAD_COUNT_FULL \
	(SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_FULL / 8u)
#define SPARK_LAGUNA_MODEL_TP8_Q_HEAD_COUNT_SLIDING \
	(SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_SLIDING / 8u)
#define SPARK_LAGUNA_MODEL_TP8_KV_HEAD_COUNT \
	(SPARK_LAGUNA_MODEL_ATTENTION_KV_HEAD_COUNT / 8u)
#define SPARK_LAGUNA_MODEL_TP8_EXPERT_COUNT \
	(SPARK_LAGUNA_MODEL_MOE_EXPERT_COUNT / 8u)

#define SPARK_LAGUNA_MODEL_STAGE_LAYER_COUNT(stage_count,stage_index) \
	(SPARK_LAGUNA_MODEL_LAYER_COUNT / (stage_count))

#define SPARK_LAGUNA_MODEL_FP8_SCALE_BLOCK 128u

#define SPARK_LAGUNA_MODEL_KV_BITS 16u
#define SPARK_LAGUNA_MODEL_KV_PAGE_SLOTS 64u
#define SPARK_LAGUNA_MODEL_KV_SLOT_BYTES_TP4 \
	(SPARK_LAGUNA_MODEL_TP4_KV_HEAD_COUNT * \
	 (SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION + \
	  SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION) * \
	 (SPARK_LAGUNA_MODEL_KV_BITS / 8u))
#define SPARK_LAGUNA_MODEL_KV_SLOT_BYTES_TP8 \
	(SPARK_LAGUNA_MODEL_TP8_KV_HEAD_COUNT * \
	 (SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION + \
	  SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION) * \
	 (SPARK_LAGUNA_MODEL_KV_BITS / 8u))

#define SPARK_LAGUNA_MODEL_BF16_ELEMENT_BYTES 2u
#define SPARK_LAGUNA_MODEL_MOE_ROUTED_GATE_UP_DIMENSION \
	(SPARK_LAGUNA_MODEL_MOE_INTERMEDIATE_DIMENSION * \
	 SPARK_LAGUNA_MODEL_MOE_W1_COMPONENT_COUNT)
#define SPARK_LAGUNA_MODEL_ROUTED_LAYERS \
	(SPARK_LAGUNA_MODEL_LAYER_COUNT - SPARK_LAGUNA_MODEL_FIRST_ROUTED_LAYER)
#define SPARK_LAGUNA_MODEL_GATE_UP_DIMENSION \
	(SPARK_LAGUNA_MODEL_MOE_INTERMEDIATE_DIMENSION * \
	 SPARK_LAGUNA_MODEL_MOE_W1_COMPONENT_COUNT)
#define SPARK_LAGUNA_MODEL_WEIGHT_LAYER_COUNT SPARK_LAGUNA_MODEL_LAYER_COUNT

#if (SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_FULL % \
	 SPARK_LAGUNA_MODEL_TENSOR_PARALLEL_DEGREE) != 0u || \
	(SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_SLIDING % \
	 SPARK_LAGUNA_MODEL_TENSOR_PARALLEL_DEGREE) != 0u || \
	(SPARK_LAGUNA_MODEL_ATTENTION_KV_HEAD_COUNT % \
	 SPARK_LAGUNA_MODEL_TENSOR_PARALLEL_DEGREE) != 0u
#error laguna is TP8: every attention head count must divide by 8
#endif
#if (SPARK_LAGUNA_MODEL_MOE_EXPERT_COUNT % SPARK_LAGUNA_MODEL_TENSOR_PARALLEL_DEGREE) != 0u
#error laguna is TP8: the expert count must divide into 8 ranks
#endif
#if SPARK_LAGUNA_MODEL_ATTENTION_HEAD_DIMENSION != 128u
#error laguna head_dim is stated 128
#endif
#if SPARK_LAGUNA_MODEL_OUTPUT_VOCAB_COUNT != 100352u
#error laguna vocab is stated 100352
#endif
#if (SPARK_LAGUNA_MODEL_LAYER_COUNT % SPARK_LAGUNA_MODEL_PIPELINE_STAGE_COUNT) != 0u
#error laguna stages must split the layer count evenly
#endif
#if (SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_FULL % 4u) != 0u || \
	(SPARK_LAGUNA_MODEL_ATTENTION_Q_HEAD_COUNT_SLIDING % 4u) != 0u || \
	(SPARK_LAGUNA_MODEL_ATTENTION_KV_HEAD_COUNT % 4u) != 0u
#error laguna TP4 head slices must be whole heads
#endif

#endif
