#ifndef SPARKPIPE_SPARK_MINIMAX_MODEL_H
#define SPARKPIPE_SPARK_MINIMAX_MODEL_H

#include <stdint.h>

#define SPARK_MINIMAX_TEXT_HIDDEN_DIMENSION 5120u
#define SPARK_MINIMAX_TEXT_LAYER_COUNT 64u
#define SPARK_MINIMAX_TEXT_VOCAB_COUNT 151936u
#define SPARK_MINIMAX_TEXT_OUTPUT_VOCAB_COUNT SPARK_MINIMAX_TEXT_VOCAB_COUNT
#define SPARK_MINIMAX_TEXT_MAXIMUM_CONTEXT_TOKENS 262144u
#define SPARK_MINIMAX_TEXT_RMS_NORM_EPSILON 1e-06f
#define SPARK_MINIMAX_TEXT_END_OF_TEXT_TOKEN_ID 151645u
#define SPARK_MINIMAX_TEXT_BOS_TOKEN_ID 151643u

#define SPARK_MINIMAX_TEXT_ATTENTION_HEAD_COUNT 64u
#define SPARK_MINIMAX_TEXT_KV_HEAD_COUNT 8u
#define SPARK_MINIMAX_TEXT_HEAD_DIMENSION 128u
#define SPARK_MINIMAX_TEXT_QUERY_DIMENSION \
	(SPARK_MINIMAX_TEXT_ATTENTION_HEAD_COUNT * \
	 SPARK_MINIMAX_TEXT_HEAD_DIMENSION)
#define SPARK_MINIMAX_TEXT_KV_DIMENSION \
	(SPARK_MINIMAX_TEXT_KV_HEAD_COUNT * SPARK_MINIMAX_TEXT_HEAD_DIMENSION)
#define SPARK_MINIMAX_TEXT_ROPE_THETA 5000000.0f
#define SPARK_MINIMAX_TEXT_ROPE_SCALING_MROPE_SECTIONS 24u,20u,20u
#define SPARK_MINIMAX_TEXT_ATTENTION_BIAS 0u

#define SPARK_MINIMAX_TEXT_DENSE_INTERMEDIATE_DIMENSION 25600u
#define SPARK_MINIMAX_TEXT_HIDDEN_ACT SILU

#define SPARK_MINIMAX_TEXT_SLIDING_WINDOW_PATTERN 3u
#define SPARK_MINIMAX_TEXT_NOPE_FULL_LAYER_PHASE 3u
#define SPARK_MINIMAX_TEXT_LAYER_IS_NOPE_FULL(layer_index) \
	(((layer_index) % 4u) == SPARK_MINIMAX_TEXT_NOPE_FULL_LAYER_PHASE)

#define SPARK_MINIMAX_TEXT_BF16_ELEMENT_BYTES 2u
#define SPARK_MINIMAX_TEXT_HIDDEN_BF16_BYTES \
	(SPARK_MINIMAX_TEXT_HIDDEN_DIMENSION * \
	 SPARK_MINIMAX_TEXT_BF16_ELEMENT_BYTES)
#define SPARK_MINIMAX_TEXT_LM_HEAD_BYTES \
	((uint64_t)SPARK_MINIMAX_TEXT_VOCAB_COUNT * \
	 SPARK_MINIMAX_TEXT_HIDDEN_BF16_BYTES)

#endif
