#pragma once

#include <stdint.h>

#include "inference/llms/kimi_k3/config.h"


#define SPARK_K3_DSPARK_MAGIC 0x5344334Bu
#define SPARK_K3_DSPARK_FORMAT_VERSION 3u
#define SPARK_K3_DSPARK_CORE_HEADER_BYTES 120u
#define SPARK_K3_DSPARK_EXT_HEADER_BYTES 64u
#define SPARK_K3_DSPARK_HEADER_BYTES \
	(SPARK_K3_DSPARK_CORE_HEADER_BYTES + SPARK_K3_DSPARK_EXT_HEADER_BYTES)
#define SPARK_K3_DSPARK_ENTRY_BYTES 56u
#define SPARK_K3_DSPARK_PAYLOAD_ALIGNMENT 256u
#define SPARK_K3_DSPARK_WEIGHT_BF16 0u

#define SPARK_K3_DSPARK_LAYER_COUNT 5u
#define SPARK_K3_DSPARK_ATTN_QUERY_HEADS 96u
#define SPARK_K3_DSPARK_ATTN_KV_HEADS 16u
#define SPARK_K3_DSPARK_ATTN_HEAD_DIMENSION 64u
#define SPARK_K3_DSPARK_ATTN_ROPE_DIMENSION 64u
#define SPARK_K3_DSPARK_FFN_INTERMEDIATE 14336u
#define SPARK_K3_DSPARK_VOCAB 163840u
#define SPARK_K3_DSPARK_BLOCK_SIZE 8u
#define SPARK_K3_DSPARK_TARGET_TAP_COUNT 5u
#define SPARK_K3_DSPARK_TARGET_TAP_LAYER_0 24u
#define SPARK_K3_DSPARK_TARGET_TAP_LAYER_1 48u
#define SPARK_K3_DSPARK_TARGET_TAP_LAYER_2 72u
#define SPARK_K3_DSPARK_TARGET_TAP_LAYER_3 88u
#define SPARK_K3_DSPARK_TARGET_TAP_LAYER_4 92u
#define SPARK_K3_DSPARK_MARKOV_RANK 256u
#define SPARK_K3_DSPARK_MASK_TOKEN_ID 163837u
#define SPARK_K3_DSPARK_SLIDING_WINDOW 2048u
#define SPARK_K3_DSPARK_ROPE_THETA 10000.0f
#define SPARK_K3_DSPARK_CONFIDENCE_INPUT_DIMENSION \
	(K3_HIDDEN + SPARK_K3_DSPARK_MARKOV_RANK)
#define SPARK_K3_DSPARK_MAX_DRAFT_TOKEN_COUNT (SPARK_K3_DSPARK_BLOCK_SIZE - 1u)

#define SPARK_K3_DSPARK_EXT_TAP_LAYER_0 0u
#define SPARK_K3_DSPARK_EXT_MARKOV_RANK 5u
#define SPARK_K3_DSPARK_EXT_MASK_TOKEN_ID 6u
#define SPARK_K3_DSPARK_EXT_SLIDING_WINDOW 7u
#define SPARK_K3_DSPARK_EXT_FLAGS 8u
#define SPARK_K3_DSPARK_EXT_ROPE_THETA_MILLI 9u
#define SPARK_K3_DSPARK_EXT_CONFIDENCE_INPUT_DIM 10u

#define SPARK_K3_DSPARK_FLAG_EMBED UINT32_C(0x1)
#define SPARK_K3_DSPARK_FLAG_LM_HEAD UINT32_C(0x2)
#define SPARK_K3_DSPARK_FLAG_CONFIDENCE UINT32_C(0x4)
#define SPARK_K3_DSPARK_FLAG_CONFIDENCE_WITH_MARKOV UINT32_C(0x8)
#define SPARK_K3_DSPARK_FLAG_SLIDING_ATTENTION UINT32_C(0x10)
#define SPARK_K3_DSPARK_FLAGS_REQUIRED \
	(SPARK_K3_DSPARK_FLAG_EMBED | SPARK_K3_DSPARK_FLAG_LM_HEAD | \
	 SPARK_K3_DSPARK_FLAG_CONFIDENCE | \
	 SPARK_K3_DSPARK_FLAG_CONFIDENCE_WITH_MARKOV)

typedef enum SparkK3DsparkTensorKind
{
	SPARK_K3_DSPARK_TENSOR_ATTN_QUERY = 0,
	SPARK_K3_DSPARK_TENSOR_ATTN_KEY = 1,
	SPARK_K3_DSPARK_TENSOR_ATTN_VALUE = 2,
	SPARK_K3_DSPARK_TENSOR_ATTN_OUTPUT = 3,
	SPARK_K3_DSPARK_TENSOR_ATTN_QUERY_NORM = 4,
	SPARK_K3_DSPARK_TENSOR_ATTN_KEY_NORM = 5,
	SPARK_K3_DSPARK_TENSOR_ATTENTION_NORM = 6,
	SPARK_K3_DSPARK_TENSOR_MLP_NORM = 7,
	SPARK_K3_DSPARK_TENSOR_FFN_GATE = 8,
	SPARK_K3_DSPARK_TENSOR_FFN_UP = 9,
	SPARK_K3_DSPARK_TENSOR_FFN_DOWN = 10,
	SPARK_K3_DSPARK_TENSOR_PROJECTOR = 11,
	SPARK_K3_DSPARK_TENSOR_MARKOV_W1 = 12,
	SPARK_K3_DSPARK_TENSOR_MARKOV_W2 = 13,
	SPARK_K3_DSPARK_TENSOR_RESERVED_14 = 14,
	SPARK_K3_DSPARK_TENSOR_FINAL_NORM = 15,
	SPARK_K3_DSPARK_TENSOR_HIDDEN_NORM = 16,
	SPARK_K3_DSPARK_TENSOR_EMBED = 17,
	SPARK_K3_DSPARK_TENSOR_LM_HEAD = 18,
	SPARK_K3_DSPARK_TENSOR_CONFIDENCE_PROJ_WEIGHT = 19,
	SPARK_K3_DSPARK_TENSOR_CONFIDENCE_PROJ_BIAS = 20,
	SPARK_K3_DSPARK_TENSOR_KIND_COUNT = 21
} SparkK3DsparkTensorKind;

#define SPARK_K3_DSPARK_PER_LAYER_KIND_COUNT 11u
#define SPARK_K3_DSPARK_GLOBAL_KIND_COUNT 9u
#define SPARK_K3_DSPARK_REDHATAI_TENSOR_COUNT \
	(SPARK_K3_DSPARK_LAYER_COUNT * SPARK_K3_DSPARK_PER_LAYER_KIND_COUNT + \
	 SPARK_K3_DSPARK_GLOBAL_KIND_COUNT)

static inline void SparkK3DsparkKindShape(
	uint32_t kind,
	uint32_t *rows,
	uint32_t *columns)
{
	switch (kind)
	{
	case SPARK_K3_DSPARK_TENSOR_ATTN_QUERY:
		*rows = SPARK_K3_DSPARK_ATTN_QUERY_HEADS * SPARK_K3_DSPARK_ATTN_HEAD_DIMENSION;
		*columns = K3_HIDDEN;
		return;
	case SPARK_K3_DSPARK_TENSOR_ATTN_KEY:
	case SPARK_K3_DSPARK_TENSOR_ATTN_VALUE:
		*rows = SPARK_K3_DSPARK_ATTN_KV_HEADS * SPARK_K3_DSPARK_ATTN_HEAD_DIMENSION;
		*columns = K3_HIDDEN;
		return;
	case SPARK_K3_DSPARK_TENSOR_ATTN_OUTPUT:
		*rows = K3_HIDDEN;
		*columns = SPARK_K3_DSPARK_ATTN_QUERY_HEADS * SPARK_K3_DSPARK_ATTN_HEAD_DIMENSION;
		return;
	case SPARK_K3_DSPARK_TENSOR_ATTN_QUERY_NORM:
	case SPARK_K3_DSPARK_TENSOR_ATTN_KEY_NORM:
		*rows = 1u;
		*columns = SPARK_K3_DSPARK_ATTN_HEAD_DIMENSION;
		return;
	case SPARK_K3_DSPARK_TENSOR_ATTENTION_NORM:
	case SPARK_K3_DSPARK_TENSOR_MLP_NORM:
		*rows = 1u;
		*columns = K3_HIDDEN;
		return;
	case SPARK_K3_DSPARK_TENSOR_FFN_GATE:
	case SPARK_K3_DSPARK_TENSOR_FFN_UP:
		*rows = SPARK_K3_DSPARK_FFN_INTERMEDIATE;
		*columns = K3_HIDDEN;
		return;
	case SPARK_K3_DSPARK_TENSOR_FFN_DOWN:
		*rows = K3_HIDDEN;
		*columns = SPARK_K3_DSPARK_FFN_INTERMEDIATE;
		return;
	case SPARK_K3_DSPARK_TENSOR_PROJECTOR:
		*rows = K3_HIDDEN;
		*columns = SPARK_K3_DSPARK_TARGET_TAP_COUNT * K3_HIDDEN;
		return;
	case SPARK_K3_DSPARK_TENSOR_MARKOV_W1:
	case SPARK_K3_DSPARK_TENSOR_MARKOV_W2:
		*rows = SPARK_K3_DSPARK_VOCAB;
		*columns = SPARK_K3_DSPARK_MARKOV_RANK;
		return;
	case SPARK_K3_DSPARK_TENSOR_FINAL_NORM:
	case SPARK_K3_DSPARK_TENSOR_HIDDEN_NORM:
		*rows = 1u;
		*columns = K3_HIDDEN;
		return;
	case SPARK_K3_DSPARK_TENSOR_EMBED:
	case SPARK_K3_DSPARK_TENSOR_LM_HEAD:
		*rows = SPARK_K3_DSPARK_VOCAB;
		*columns = K3_HIDDEN;
		return;
	case SPARK_K3_DSPARK_TENSOR_CONFIDENCE_PROJ_WEIGHT:
		*rows = 1u;
		*columns = SPARK_K3_DSPARK_CONFIDENCE_INPUT_DIMENSION;
		return;
	case SPARK_K3_DSPARK_TENSOR_CONFIDENCE_PROJ_BIAS:
		*rows = 1u;
		*columns = 1u;
		return;
	default:
		*rows = 0u;
		*columns = 0u;
		return;
	}
}
