#pragma once

#include <stdint.h>

#define SPARK_DSV41_FLASH_MODEL_HIDDEN_DIMENSION 5120u
#define SPARK_DSV41_FLASH_MODEL_LAYER_COUNT 40u
#define SPARK_DSV41_FLASH_MODEL_OUTPUT_VOCAB_COUNT 129280u
#define SPARK_DSV41_FLASH_MODEL_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_DSV41_FLASH_MODEL_RMS_NORM_EPSILON 1e-20f
#define SPARK_DSV41_FLASH_MODEL_SWIGLU_LIMIT 10.0f
#define SPARK_DSV41_FLASH_MODEL_BOS_TOKEN_ID 0u
#define SPARK_DSV41_FLASH_MODEL_EOS_TOKEN_ID 1u
#define SPARK_DSV41_FLASH_MODEL_PAD_TOKEN_ID 2u
#define SPARK_DSV41_FLASH_MODEL_IMAGE_TOKEN_ID 129264u
#define SPARK_DSV41_FLASH_MODEL_DSPARK_NOISE_TOKEN_ID 128799u

#define SPARK_DSV41_FLASH_MODEL_ENCODER_LAYER_COUNT 20u
#define SPARK_DSV41_FLASH_MODEL_DECODER_LAYER_COUNT 20u

#define SPARK_DSV41_FLASH_MODEL_ATTENTION_HEAD_COUNT 64u
#define SPARK_DSV41_FLASH_MODEL_HEAD_DIMENSION 512u
#define SPARK_DSV41_FLASH_MODEL_QK_ROPE_HEAD_DIMENSION 64u
#define SPARK_DSV41_FLASH_MODEL_QK_NOPE_HEAD_DIMENSION \
	(SPARK_DSV41_FLASH_MODEL_HEAD_DIMENSION - \
	 SPARK_DSV41_FLASH_MODEL_QK_ROPE_HEAD_DIMENSION)
#define SPARK_DSV41_FLASH_MODEL_QUERY_B_DIMENSION \
	(SPARK_DSV41_FLASH_MODEL_ATTENTION_HEAD_COUNT * \
	 SPARK_DSV41_FLASH_MODEL_HEAD_DIMENSION)
#define SPARK_DSV41_FLASH_MODEL_QUERY_LORA_RANK 1280u
#define SPARK_DSV41_FLASH_MODEL_KV_LATENT_DIMENSION 512u
#define SPARK_DSV41_FLASH_MODEL_VALUE_HEAD_DIMENSION 64u
#define SPARK_DSV41_FLASH_MODEL_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_DSV41_FLASH_MODEL_ATTENTION_HEAD_COUNT * \
	 SPARK_DSV41_FLASH_MODEL_VALUE_HEAD_DIMENSION)
#define SPARK_DSV41_FLASH_MODEL_OUTPUT_LORA_RANK 1024u
#define SPARK_DSV41_FLASH_MODEL_OUTPUT_GROUP_COUNT 8u
#define SPARK_DSV41_FLASH_MODEL_OUTPUT_A_DIMENSION \
	(SPARK_DSV41_FLASH_MODEL_OUTPUT_GROUP_COUNT * \
	 SPARK_DSV41_FLASH_MODEL_OUTPUT_LORA_RANK)
#define SPARK_DSV41_FLASH_MODEL_ATTENTION_SINK_COUNT \
	SPARK_DSV41_FLASH_MODEL_ATTENTION_HEAD_COUNT

#define SPARK_DSV41_FLASH_MODEL_SLIDING_WINDOW 128u
#define SPARK_DSV41_FLASH_MODEL_SWA_LAYERS 4u

#define SPARK_DSV41_FLASH_MODEL_CSA2_FULL_LAYER_COUNT 4u
#define SPARK_DSV41_FLASH_MODEL_CSA2_REINDEX_LAYER_COUNT 4u
#define SPARK_DSV41_FLASH_MODEL_CSA2_REUSE_LAYER_COUNT 10u
#define SPARK_DSV41_FLASH_MODEL_KV_SOURCE_COUNT 4u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_COUNT 8u
#define SPARK_DSV41_FLASH_MODEL_KV_SOURCE_LAYER_0 2u
#define SPARK_DSV41_FLASH_MODEL_KV_SOURCE_LAYER_1 8u
#define SPARK_DSV41_FLASH_MODEL_KV_SOURCE_LAYER_2 14u
#define SPARK_DSV41_FLASH_MODEL_KV_SOURCE_LAYER_3 20u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_0 2u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_1 8u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_2 14u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_3 20u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_4 24u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_5 28u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_6 32u
#define SPARK_DSV41_FLASH_MODEL_INDEX_SOURCE_LAYER_7 36u
#define SPARK_DSV41_FLASH_MODEL_CANDIDATE_SOURCE_LAYER 20u

#define SPARK_DSV41_FLASH_MODEL_LAYER_IS_SWA_ONLY(layer_index) \
	(((layer_index) < 2u) || ((layer_index) >= 38u && \
	 (layer_index) < SPARK_DSV41_FLASH_MODEL_LAYER_COUNT))

#define SPARK_DSV41_FLASH_MODEL_LAYER_IS_CSA2(layer_index) \
	(((layer_index) >= 2u) && ((layer_index) < 38u))

#define SPARK_DSV41_FLASH_MODEL_LAYER_COMPRESSION_RATIO(layer_index) \
	((uint32_t[]){0u, 0u, 2u, 2u, 2u, 2u, 2u, 2u, 2u, 2u, \
		2u, 2u, 2u, 2u, 2u, 2u, 2u, 2u, 2u, 2u, \
		1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, \
		1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 0u, 0u}[(layer_index)])

#define SPARK_DSV41_FLASH_MODEL_INDEX_HEAD_COUNT 32u
#define SPARK_DSV41_FLASH_MODEL_INDEX_HEAD_DIMENSION 128u
#define SPARK_DSV41_FLASH_MODEL_INDEX_QUERY_DIMENSION \
	(SPARK_DSV41_FLASH_MODEL_INDEX_HEAD_COUNT * \
	 SPARK_DSV41_FLASH_MODEL_INDEX_HEAD_DIMENSION)
#define SPARK_DSV41_FLASH_MODEL_INDEX_TOP_K 512u
#define SPARK_DSV41_FLASH_MODEL_CANDIDATE_BLOCK_COUNT 2048u
#define SPARK_DSV41_FLASH_MODEL_CANDIDATE_BLOCK_SIZE 8u
#define SPARK_DSV41_FLASH_MODEL_CANDIDATE_POOL_POSITIONS \
	(SPARK_DSV41_FLASH_MODEL_CANDIDATE_BLOCK_COUNT * \
	 SPARK_DSV41_FLASH_MODEL_CANDIDATE_BLOCK_SIZE)

#define SPARK_DSV41_FLASH_MODEL_ROUTED_EXPERT_COUNT 384u
#define SPARK_DSV41_FLASH_MODEL_SHARED_EXPERT_COUNT 1u
#define SPARK_DSV41_FLASH_MODEL_EXPERTS_PER_TOKEN 6u
#define SPARK_DSV41_FLASH_MODEL_MOE_INTERMEDIATE_DIMENSION 2304u
#define SPARK_DSV41_FLASH_MODEL_ROUTED_SCALING_FACTOR 1.5f

#define SPARK_DSV41_FLASH_MODEL_HC_MULT 4u
#define SPARK_DSV41_FLASH_MODEL_HC_COEFFICIENT_COUNT 24u
#define SPARK_DSV41_FLASH_MODEL_HC_STREAM_HIDDEN_DIMENSION \
	(SPARK_DSV41_FLASH_MODEL_HC_MULT * \
	 SPARK_DSV41_FLASH_MODEL_HIDDEN_DIMENSION)
#define SPARK_DSV41_FLASH_MODEL_HC_SINKHORN_ITERATIONS 20u

#define SPARK_DSV41_FLASH_MODEL_ENGRAM_MODULE_COUNT 2u
#define SPARK_DSV41_FLASH_MODEL_ENGRAM_LAYER_0 1u
#define SPARK_DSV41_FLASH_MODEL_ENGRAM_LAYER_1 14u
#define SPARK_DSV41_FLASH_MODEL_ENGRAM_HEAD_COUNT 8u
#define SPARK_DSV41_FLASH_MODEL_ENGRAM_HEAD_DIMENSION 256u

#define SPARK_DSV41_FLASH_MODEL_DSPARK_BLOCK_COUNT 3u
#define SPARK_DSV41_FLASH_MODEL_DSPARK_BLOCK_SIZE 5u
#define SPARK_DSV41_FLASH_MODEL_DSPARK_ROUTED_EXPERT_COUNT 128u
#define SPARK_DSV41_FLASH_MODEL_DSPARK_EXPERTS_PER_TOKEN 3u
#define SPARK_DSV41_FLASH_MODEL_DSPARK_MARKOV_RANK 256u

#define SPARK_DSV41_FLASH_MODEL_KV_GLOBAL_SCALE_CHANNELS 16u

#define SPARK_DSV41_FLASH_MODEL_EXPERT_BYTES_PER_EXPERT \
	(2ull * SPARK_DSV41_FLASH_MODEL_MOE_INTERMEDIATE_DIMENSION * \
	 SPARK_DSV41_FLASH_MODEL_HIDDEN_DIMENSION / 2u + \
	 (uint64_t)SPARK_DSV41_FLASH_MODEL_HIDDEN_DIMENSION * \
	 SPARK_DSV41_FLASH_MODEL_MOE_INTERMEDIATE_DIMENSION / 2u)
