#pragma once

#define SPARK_LLM_FAMILY_TAG                    minimax
#define SPARK_LLM_HIDDEN_DIMENSION              5120u
#define SPARK_LLM_LAYER_COUNT                   64u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT            151936u
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS        262144u
#define SPARK_LLM_RMS_NORM_EPSILON              1e-06f
#define SPARK_LLM_END_OF_TEXT_TOKEN_ID          151645u
#define SPARK_LLM_BEGIN_OF_TEXT_TOKEN_ID        151643u

#define SPARK_LLM_ATTENTION_HEAD_COUNT          64u
#define SPARK_LLM_KV_HEAD_COUNT                 8u
#define SPARK_LLM_HEAD_DIMENSION                128u
#define SPARK_LLM_INTERMEDIATE_DIMENSION        25600u
#define SPARK_LLM_ROPE_THETA                    5000000.0f
#define SPARK_LLM_MROPE_SECTION_TEMPORAL        24u
#define SPARK_LLM_MROPE_SECTION_HEIGHT          20u
#define SPARK_LLM_MROPE_SECTION_WIDTH           20u
#define SPARK_LLM_MROPE_INTERLEAVED             1u
#define SPARK_LLM_TIED_WORD_EMBEDDINGS          0u

#define SPARK_LLM_MODEL_SOURCE_URI              "MiniMaxAI/MiniMax-H3"

#define SPARK_LLM_MAX_STAGE_COUNT 1u
#define SPARK_LLM_MAX_PIPELINE_SLOT_COUNT 4u
#define SPARK_LLM_MAX_ACTIVE_SEQUENCE_COUNT 512u
#ifndef SPARK_LLM_KV_BLOCK_TOKENS
#define SPARK_LLM_KV_BLOCK_TOKENS 64u
#endif
#define SPARK_LLM_PREFILL_FRAME_VIEW_ABI_VERSION 1u
#define SPARK_LLM_KV_BLOCK_TABLE_ABI_VERSION 1u
#define SPARK_LLM_LINEAR_VIEW_ABI_VERSION 1u
#define SPARK_LLM_DECODE_BATCH_VIEW_ABI_VERSION 1u
#define SPARK_LLM_INVALID_TOKEN_ID UINT32_MAX
#define SPARK_LLM_NO_BLOCK 0xffffffffu

#define SPARK_LLM_QUERY_DIMENSION \
	(SPARK_LLM_ATTENTION_HEAD_COUNT * SPARK_LLM_HEAD_DIMENSION)
#define SPARK_LLM_KV_DIMENSION \
	(SPARK_LLM_KV_HEAD_COUNT * SPARK_LLM_HEAD_DIMENSION)
#define SPARK_LLM_TP_SHARD_COUNT(tp_degree) \
	(((uint32_t)(tp_degree)))
#define SPARK_LLM_LOCAL_QUERY_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_ATTENTION_HEAD_COUNT / SPARK_LLM_TP_SHARD_COUNT(tp_degree))
#define SPARK_LLM_LOCAL_KV_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_KV_HEAD_COUNT / SPARK_LLM_TP_SHARD_COUNT(tp_degree))
#define SPARK_LLM_LOCAL_KV_DIMENSION(tp_degree) \
	(SPARK_LLM_LOCAL_KV_HEAD_COUNT(tp_degree) * SPARK_LLM_HEAD_DIMENSION)
#define SPARK_LLM_LOCAL_FFN_DIMENSION(tp_degree) \
	(SPARK_LLM_INTERMEDIATE_DIMENSION / SPARK_LLM_TP_SHARD_COUNT(tp_degree))
#define SPARK_LLM_LOCAL_VOCAB_ROWS(tp_degree) \
	(SPARK_LLM_OUTPUT_VOCAB_COUNT / SPARK_LLM_TP_SHARD_COUNT(tp_degree))
