#ifndef SPARKPIPE_SPARK_MIMO26_MODEL_H
#define SPARKPIPE_SPARK_MIMO26_MODEL_H

#include <stdint.h>
#include "llm_defines.h"

#define SPARK_MIMO26_MODEL_HIDDEN_DIMENSION SPARK_LLM_HIDDEN_DIMENSION
#define SPARK_MIMO26_MODEL_LAYER_COUNT SPARK_LLM_LAYER_COUNT
#define SPARK_MIMO26_MODEL_VOCAB_COUNT 152576u
#define SPARK_MIMO26_MODEL_MAX_POSITIONS 1048576u
#define SPARK_MIMO26_MODEL_RMS_NORM_EPSILON SPARK_LLM_RMS_NORM_EPSILON
#define SPARK_MIMO26_MODEL_BF16_ELEMENT_BYTES 2u

#define SPARK_MIMO26_MODEL_ATTN_HEAD_COUNT 64u
#define SPARK_MIMO26_MODEL_ATTN_HEAD_DIMENSION 192u
#define SPARK_MIMO26_MODEL_ATTN_VALUE_DIMENSION 128u
#define SPARK_MIMO26_MODEL_ATTN_ROPE_DIMENSION 64u
#define SPARK_MIMO26_MODEL_FULL_KV_HEAD_COUNT SPARK_LLM_FULL_KV_HEAD_COUNT
#define SPARK_MIMO26_MODEL_SWA_KV_HEAD_COUNT SPARK_LLM_SWA_KV_HEAD_COUNT
#define SPARK_MIMO26_MODEL_FULL_QKV_DIMENSION 13568u
#define SPARK_MIMO26_MODEL_SWA_QKV_DIMENSION 14848u
#define SPARK_MIMO26_MODEL_Q_DIMENSION 12288u
#define SPARK_MIMO26_MODEL_O_INPUT_DIMENSION 8192u
#define SPARK_MIMO26_MODEL_SLIDING_WINDOW_TOKENS SPARK_LLM_SLIDING_WINDOW_TOKENS
#define SPARK_MIMO26_MODEL_ATTN_VALUE_SCALE 0.707f
#define SPARK_MIMO26_MODEL_FULL_ROPE_THETA SPARK_LLM_FULL_ROPE_THETA
#define SPARK_MIMO26_MODEL_SWA_ROPE_THETA SPARK_LLM_SWA_ROPE_THETA
#define SPARK_MIMO26_MODEL_FULL_SINK_BIAS SPARK_LLM_FULL_SINK_BIAS
#define SPARK_MIMO26_MODEL_SWA_SINK_BIAS SPARK_LLM_SWA_SINK_BIAS

#define SPARK_MIMO26_MODEL_DENSE_INTERMEDIATE_DIMENSION SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION
#define SPARK_MIMO26_MODEL_EXPERT_INTERMEDIATE_DIMENSION SPARK_LLM_EXPERT_INTERMEDIATE_DIMENSION
#define SPARK_MIMO26_MODEL_ROUTED_EXPERT_COUNT SPARK_LLM_ROUTED_EXPERT_COUNT
#define SPARK_MIMO26_MODEL_EXPERTS_PER_TOKEN SPARK_LLM_EXPERTS_PER_TOKEN
#define SPARK_MIMO26_MODEL_ROUTED_SCALING_FACTOR SPARK_LLM_ROUTED_SCALING_FACTOR
#define SPARK_MIMO26_MODEL_ROUTER_NORM_EPSILON SPARK_LLM_ROUTER_NORM_EPSILON
#define SPARK_MIMO26_MODEL_ROUTER_GROUP_COUNT SPARK_LLM_ROUTER_GROUP_COUNT
#define SPARK_MIMO26_MODEL_ROUTER_TOP_GROUP_COUNT SPARK_LLM_ROUTER_TOP_GROUP_COUNT

#define SPARK_MIMO26_MODEL_FP8_SCALE_BLOCK 128u
#define SPARK_MIMO26_MODEL_EXPERT_MXFP4_SCALE_BLOCK 32u
#define SPARK_MIMO26_MODEL_FULL_QKV_SCALE_ROWS 108u
#define SPARK_MIMO26_MODEL_SWA_QKV_SCALE_ROWS 116u
#define SPARK_MIMO26_MODEL_MTP_LAYER_COUNT 3u

#define SPARK_MIMO26_MODEL_LAYER_KIND_FULL 0u
#define SPARK_MIMO26_MODEL_LAYER_KIND_SWA 1u
#define SPARK_MIMO26_MODEL_LAYER_INVALID UINT32_MAX

static const uint8_t SPARK_MIMO26_MODEL_LAYER_KIND[SPARK_MIMO26_MODEL_LAYER_COUNT] =
{
	0,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,
	1,0,1,1,1,1,1,0,1,1,1,1,1,0,1,1,
	1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,0
};

static const uint8_t SPARK_MIMO26_MODEL_LAYER_IS_MOE[SPARK_MIMO26_MODEL_LAYER_COUNT] =
{
	0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
};

static inline uint32_t SparkMimo26ModelLayerKind(uint32_t layer_index)
{
	return(layer_index < SPARK_MIMO26_MODEL_LAYER_COUNT ? (uint32_t)SPARK_MIMO26_MODEL_LAYER_KIND[layer_index] : SPARK_MIMO26_MODEL_LAYER_INVALID);
}

static inline uint32_t SparkMimo26ModelLayerIsMoe(uint32_t layer_index)
{
	return(layer_index < SPARK_MIMO26_MODEL_LAYER_COUNT ? (uint32_t)SPARK_MIMO26_MODEL_LAYER_IS_MOE[layer_index] : SPARK_MIMO26_MODEL_LAYER_INVALID);
}

#endif
