#ifndef SPARKPIPE_SPARK_GLM5_NEXT_MODEL_H
#define SPARKPIPE_SPARK_GLM5_NEXT_MODEL_H

#include <stdint.h>

#define SPARK_GLM5_NEXT_MODEL_HIDDEN_DIMENSION 4096u
#define SPARK_GLM5_NEXT_MODEL_LAYER_COUNT 45u
#define SPARK_GLM5_NEXT_MODEL_MTP_LAYER_INDEX 45u
#define SPARK_GLM5_NEXT_MODEL_OUTPUT_VOCAB_COUNT 154880u
#define SPARK_GLM5_NEXT_MODEL_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_GLM5_NEXT_MODEL_RMS_NORM_EPSILON 1e-05f
#define SPARK_GLM5_NEXT_MODEL_SWIGLU_LIMIT 10.0f
#define SPARK_GLM5_NEXT_MODEL_END_OF_TEXT_TOKEN_ID 154820u
#define SPARK_GLM5_NEXT_MODEL_USER_TOKEN_ID 154827u
#define SPARK_GLM5_NEXT_MODEL_OBSERVATION_TOKEN_ID 154829u
#define SPARK_GLM5_NEXT_MODEL_PAD_TOKEN_ID 154820u

#define SPARK_GLM5_NEXT_MODEL_KV_POOL_TOKENS 4194304u
#define SPARK_GLM5_NEXT_MODEL_RESTRICTED_VOCAB_COUNT 256u
#define SPARK_GLM5_NEXT_MODEL_MAX_PREFILL_TOKENS_PER_DISPATCH 256u

#define SPARK_GLM5_NEXT_MODEL_ATTENTION_PERIOD 4u
#define SPARK_GLM5_NEXT_MODEL_GLOBAL_ATTENTION_PHASE 3u
#define SPARK_GLM5_NEXT_MODEL_KDA_LAYER_COUNT 34u
#define SPARK_GLM5_NEXT_MODEL_DSA_LAYER_COUNT 11u
#define SPARK_GLM5_NEXT_MODEL_LAYER_IS_KDA(layer_index) \
	(((layer_index) % SPARK_GLM5_NEXT_MODEL_ATTENTION_PERIOD) != \
	 SPARK_GLM5_NEXT_MODEL_GLOBAL_ATTENTION_PHASE)

#define SPARK_GLM5_NEXT_MODEL_KDA_HEAD_COUNT 64u
#define SPARK_GLM5_NEXT_MODEL_KDA_HEAD_KEY_DIMENSION 128u
#define SPARK_GLM5_NEXT_MODEL_KDA_HEAD_VALUE_DIMENSION 128u
#define SPARK_GLM5_NEXT_MODEL_KDA_QKV_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_KDA_HEAD_COUNT * SPARK_GLM5_NEXT_MODEL_KDA_HEAD_KEY_DIMENSION)
#define SPARK_GLM5_NEXT_MODEL_KDA_CONV_KERNEL 4u
#define SPARK_GLM5_NEXT_MODEL_KDA_CHUNK_TOKENS 64u
#define SPARK_GLM5_NEXT_MODEL_KDA_QK_L2NORM 1u
#define SPARK_GLM5_NEXT_MODEL_KDA_FULL_RANK_GATE 1u
#define SPARK_GLM5_NEXT_MODEL_KDA_GATE_LOWER_BOUND -5.0f
#define SPARK_GLM5_NEXT_MODEL_KDA_LOW_RANK_GATE_BOTTLENECK 128u
#define SPARK_GLM5_NEXT_MODEL_KDA_SHORT_CONV_KERNEL 4u
#define SPARK_GLM5_NEXT_MODEL_KDA_STATE_ELEMENT_BYTES 4u
#define SPARK_GLM5_NEXT_MODEL_KDA_STATE_ELEMENTS_PER_HEAD \
	(SPARK_GLM5_NEXT_MODEL_KDA_HEAD_KEY_DIMENSION * SPARK_GLM5_NEXT_MODEL_KDA_HEAD_VALUE_DIMENSION)
#define SPARK_GLM5_NEXT_MODEL_KDA_STATE_BYTES_PER_LAYER \
	(SPARK_GLM5_NEXT_MODEL_KDA_HEAD_COUNT * \
	 SPARK_GLM5_NEXT_MODEL_KDA_STATE_ELEMENTS_PER_HEAD * \
	 SPARK_GLM5_NEXT_MODEL_KDA_STATE_ELEMENT_BYTES)
#define SPARK_GLM5_NEXT_MODEL_KDA_CONV_WINDOW_BYTES_PER_LAYER \
	(3u * SPARK_GLM5_NEXT_MODEL_KDA_QKV_DIMENSION * \
	 SPARK_GLM5_NEXT_MODEL_KDA_SHORT_CONV_KERNEL * 2u)
#define SPARK_GLM5_NEXT_MODEL_KDA_A_LOG_HEAD_COUNT SPARK_GLM5_NEXT_MODEL_KDA_HEAD_COUNT

#define SPARK_GLM5_NEXT_MODEL_MLA_HEAD_COUNT 64u
#define SPARK_GLM5_NEXT_MODEL_MLA_QUERY_A_DIMENSION 1536u
#define SPARK_GLM5_NEXT_MODEL_MLA_LATENT_DIMENSION 512u
#define SPARK_GLM5_NEXT_MODEL_MLA_QK_NOPE_HEAD_DIMENSION 256u
#define SPARK_GLM5_NEXT_MODEL_MLA_QK_ROPE_HEAD_DIMENSION 0u
#define SPARK_GLM5_NEXT_MODEL_MLA_VALUE_HEAD_DIMENSION 256u
#define SPARK_GLM5_NEXT_MODEL_MLA_USE_NOPE 1u
#define SPARK_GLM5_NEXT_MODEL_MLA_QK_SCALE 0.0625f
#define SPARK_GLM5_NEXT_MODEL_MLA_QK_HEAD_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + \
	 SPARK_GLM5_NEXT_MODEL_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_GLM5_NEXT_MODEL_MLA_QUERY_B_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_MLA_HEAD_COUNT * SPARK_GLM5_NEXT_MODEL_MLA_QK_HEAD_DIMENSION)
#define SPARK_GLM5_NEXT_MODEL_MLA_KV_A_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_MLA_LATENT_DIMENSION + \
	 SPARK_GLM5_NEXT_MODEL_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_GLM5_NEXT_MODEL_MLA_KV_B_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_MLA_HEAD_COUNT * \
	 (SPARK_GLM5_NEXT_MODEL_MLA_QK_NOPE_HEAD_DIMENSION + \
	  SPARK_GLM5_NEXT_MODEL_MLA_VALUE_HEAD_DIMENSION))
#define SPARK_GLM5_NEXT_MODEL_MLA_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_MLA_HEAD_COUNT * \
	 SPARK_GLM5_NEXT_MODEL_MLA_VALUE_HEAD_DIMENSION)

#define SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_COUNT 32u
#define SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_DIMENSION 128u
#define SPARK_GLM5_NEXT_MODEL_INDEX_QUERY_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_COUNT * SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_DIMENSION)
#define SPARK_GLM5_NEXT_MODEL_INDEX_TOP_K 2048u
#define SPARK_GLM5_NEXT_MODEL_INDEX_KPOOL 4u
#define SPARK_GLM5_NEXT_MODEL_INDEX_POOL_SELECT_COUNT \
	(SPARK_GLM5_NEXT_MODEL_INDEX_TOP_K / SPARK_GLM5_NEXT_MODEL_INDEX_KPOOL)
#define SPARK_GLM5_NEXT_MODEL_INDEX_TAIL_MAX (SPARK_GLM5_NEXT_MODEL_INDEX_KPOOL - 1u)
#define SPARK_GLM5_NEXT_MODEL_INDEX_OUTPUT_WIDTH \
	(SPARK_GLM5_NEXT_MODEL_INDEX_TOP_K + SPARK_GLM5_NEXT_MODEL_INDEX_TAIL_MAX)
#define SPARK_GLM5_NEXT_MODEL_INDEX_SOFTMAX_SCALE 0.08838834764831845f
#define SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_WEIGHT_SCALE 0.1767766952966369f
#define SPARK_GLM5_NEXT_MODEL_INDEX_NORM_EPSILON 1e-06f
#define SPARK_GLM5_NEXT_MODEL_INDEX_PACKED_TOKEN_DIMENSION \
	(2u * SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_DIMENSION + 1u)

#define SPARK_GLM5_NEXT_MODEL_HC_MULT 4u
#define SPARK_GLM5_NEXT_MODEL_HC_SINKHORN_ITERATIONS 20u
#define SPARK_GLM5_NEXT_MODEL_HC_EPSILON 1e-06f
#define SPARK_GLM5_NEXT_MODEL_HC_MIX_DIMENSION \
	((2u + SPARK_GLM5_NEXT_MODEL_HC_MULT) * SPARK_GLM5_NEXT_MODEL_HC_MULT)
#define SPARK_GLM5_NEXT_MODEL_HC_FN_COLUMNS \
	(SPARK_GLM5_NEXT_MODEL_HC_MULT * SPARK_GLM5_NEXT_MODEL_HIDDEN_DIMENSION)
#define SPARK_GLM5_NEXT_MODEL_HC_SCALE_COUNT 3u

#define SPARK_GLM5_NEXT_MODEL_MOE_EXPERT_COUNT 288u
#define SPARK_GLM5_NEXT_MODEL_MOE_TOP_K 8u
#define SPARK_GLM5_NEXT_MODEL_MOE_SHARED_EXPERT_COUNT 1u
#define SPARK_GLM5_NEXT_MODEL_MOE_INTERMEDIATE_DIMENSION 2048u
#define SPARK_GLM5_NEXT_MODEL_DENSE_INTERMEDIATE_DIMENSION 12288u
#define SPARK_GLM5_NEXT_MODEL_FIRST_DENSE_LAYER_COUNT 3u
#define SPARK_GLM5_NEXT_MODEL_FIRST_ROUTED_LAYER 3u
#define SPARK_GLM5_NEXT_MODEL_MOE_ROUTED_SCALING_FACTOR 2.5f
#define SPARK_GLM5_NEXT_MODEL_MOE_NORM_TOPK_PROB 1u
#define SPARK_GLM5_NEXT_MODEL_MOE_W1_COMPONENT_COUNT 2u

#define SPARK_GLM5_NEXT_MODEL_FP8_SCALE_BLOCK 128u

#define SPARK_GLM5_NEXT_MODEL_KV_BITS 16u
#define SPARK_GLM5_NEXT_MODEL_KV_PAGE_SLOTS 64u
#define SPARK_GLM5_NEXT_MODEL_KV_SLOT_BYTES \
	((SPARK_GLM5_NEXT_MODEL_MLA_KV_A_DIMENSION * SPARK_GLM5_NEXT_MODEL_KV_BITS) / 8u)

#define SPARK_GLM5_NEXT_MODEL_HEAD_COUNT \
	SPARK_GLM5_NEXT_MODEL_MLA_HEAD_COUNT
#define SPARK_GLM5_NEXT_MODEL_LATENT_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_MLA_LATENT_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_QUERY_A_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_MLA_QUERY_A_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_QUERY_B_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_MLA_QUERY_B_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_VALUE_HEAD_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_MLA_VALUE_HEAD_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_ROPE_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_MLA_QK_ROPE_HEAD_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_CACHE_TOKEN_ELEMENTS \
	SPARK_GLM5_NEXT_MODEL_MLA_KV_A_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_BF16_ELEMENT_BYTES 2u
#define SPARK_GLM5_NEXT_MODEL_DSA_INDEX_HEAD_COUNT \
	SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_COUNT
#define SPARK_GLM5_NEXT_MODEL_DSA_INDEX_HEAD_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_DSA_INDEX_QUERY_DIMENSION \
	SPARK_GLM5_NEXT_MODEL_INDEX_QUERY_DIMENSION
#define SPARK_GLM5_NEXT_MODEL_DSA_SELECTED_TOKEN_COUNT \
	SPARK_GLM5_NEXT_MODEL_INDEX_TOP_K
#define SPARK_GLM5_NEXT_MODEL_MOE_ROUTED_GATE_UP_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_MOE_INTERMEDIATE_DIMENSION * \
	 SPARK_GLM5_NEXT_MODEL_MOE_W1_COMPONENT_COUNT)
#define SPARK_GLM5_NEXT_MODEL_ROUTED_LAYERS \
	(SPARK_GLM5_NEXT_MODEL_LAYER_COUNT - SPARK_GLM5_NEXT_MODEL_FIRST_ROUTED_LAYER)
#define SPARK_GLM5_NEXT_MODEL_GATE_UP_DIMENSION \
	(SPARK_GLM5_NEXT_MODEL_MOE_INTERMEDIATE_DIMENSION * \
	 SPARK_GLM5_NEXT_MODEL_MOE_W1_COMPONENT_COUNT)
#define SPARK_GLM5_NEXT_MODEL_WEIGHT_LAYER_COUNT \
	(SPARK_GLM5_NEXT_MODEL_LAYER_COUNT + 1u)

#if SPARK_GLM5_NEXT_MODEL_MLA_QK_ROPE_HEAD_DIMENSION != 0u
#error glm5_next is the rope-0 MLA instantiation; a nonzero rope dim belongs to another family
#endif
#if SPARK_GLM5_NEXT_MODEL_KDA_QKV_DIMENSION % 128u != 0u
#error kda qkv rows must stay whole-head at the TP16 slice
#endif
#if (SPARK_GLM5_NEXT_MODEL_KDA_HEAD_COUNT % 16u) != 0u || \
	(SPARK_GLM5_NEXT_MODEL_MLA_HEAD_COUNT % 16u) != 0u || \
	(SPARK_GLM5_NEXT_MODEL_INDEX_HEAD_COUNT % 16u) != 0u
#error glm5_next assumes TP16: every head count must divide by 16
#endif
#if (SPARK_GLM5_NEXT_MODEL_MOE_EXPERT_COUNT % 16u) != 0u
#error glm5_next assumes TP16: the expert count must divide into 16 ranks
#endif
#if SPARK_GLM5_NEXT_MODEL_INDEX_OUTPUT_WIDTH != 2051u
#error pool expansion width changed; update the indexer consumers
#endif

#endif
