#pragma once

#include "spark_glm5_next_model.h"

#define SPARK_LLM_FAMILY_TAG                    glm5_next
#define SPARK_LLM_HIDDEN_DIMENSION              SPARK_GLM5_NEXT_MODEL_HIDDEN_DIMENSION
#define SPARK_LLM_LAYER_COUNT                   SPARK_GLM5_NEXT_MODEL_LAYER_COUNT
#define SPARK_LLM_OUTPUT_VOCAB_COUNT            SPARK_GLM5_NEXT_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS        SPARK_GLM5_NEXT_MODEL_MAXIMUM_CONTEXT_TOKENS
#define SPARK_LLM_RMS_NORM_EPSILON              SPARK_GLM5_NEXT_MODEL_RMS_NORM_EPSILON
#define SPARK_LLM_SWIGLU_LIMIT                  SPARK_GLM5_NEXT_MODEL_SWIGLU_LIMIT
#define SPARK_LLM_END_OF_TEXT_TOKEN_ID          SPARK_GLM5_NEXT_MODEL_END_OF_TEXT_TOKEN_ID
#define SPARK_LLM_KV_POOL_TOKENS                SPARK_GLM5_NEXT_MODEL_KV_POOL_TOKENS
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH SPARK_GLM5_NEXT_MODEL_MAX_PREFILL_TOKENS_PER_DISPATCH

#define SPARK_LLM_MLA_HEAD_COUNT                SPARK_GLM5_NEXT_MODEL_MLA_HEAD_COUNT
#define SPARK_LLM_MLA_QUERY_A_DIMENSION         SPARK_GLM5_NEXT_MODEL_MLA_QUERY_A_DIMENSION
#define SPARK_LLM_MLA_LATENT_DIMENSION          SPARK_GLM5_NEXT_MODEL_MLA_LATENT_DIMENSION
#define SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION    SPARK_GLM5_NEXT_MODEL_MLA_QK_NOPE_HEAD_DIMENSION
#define SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION    SPARK_GLM5_NEXT_MODEL_MLA_QK_ROPE_HEAD_DIMENSION
#define SPARK_LLM_MLA_V_HEAD_DIMENSION          512u

#define SPARK_LLM_ATTENTION_PERIOD              SPARK_GLM5_NEXT_MODEL_ATTENTION_PERIOD
#define SPARK_LLM_GLOBAL_ATTENTION_PHASE        SPARK_GLM5_NEXT_MODEL_GLOBAL_ATTENTION_PHASE
#define SPARK_LLM_ROPE_THETA                    10000.0f
#define SPARK_LLM_ROPE_YARN_FACTOR              1.0f

#define SPARK_LLM_MOE_EXPERT_COUNT              SPARK_GLM5_NEXT_MODEL_MOE_EXPERT_COUNT
#define SPARK_LLM_MOE_TOP_K                     SPARK_GLM5_NEXT_MODEL_MOE_TOP_K
#define SPARK_LLM_MOE_SHARED_EXPERT_COUNT       SPARK_GLM5_NEXT_MODEL_MOE_SHARED_EXPERT_COUNT
#define SPARK_LLM_MOE_INTERMEDIATE_DIMENSION    SPARK_GLM5_NEXT_MODEL_MOE_INTERMEDIATE_DIMENSION
#define SPARK_LLM_MOE_ROUTED_SCALING_FACTOR     SPARK_GLM5_NEXT_MODEL_MOE_ROUTED_SCALING_FACTOR
#define SPARK_LLM_MOE_NORM_TOPK_PROB            SPARK_GLM5_NEXT_MODEL_MOE_NORM_TOPK_PROB
#define SPARK_LLM_FIRST_ROUTED_LAYER            SPARK_GLM5_NEXT_MODEL_FIRST_ROUTED_LAYER
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION  SPARK_GLM5_NEXT_MODEL_DENSE_INTERMEDIATE_DIMENSION

#define SPARK_LLM_KDA_LAYER_COUNT               SPARK_GLM5_NEXT_MODEL_KDA_LAYER_COUNT
#define SPARK_LLM_KDA_HEAD_COUNT                SPARK_GLM5_NEXT_MODEL_KDA_HEAD_COUNT
#define SPARK_LLM_KDA_HEAD_KEY_DIMENSION        SPARK_GLM5_NEXT_MODEL_KDA_HEAD_KEY_DIMENSION
#define SPARK_LLM_KDA_HEAD_VALUE_DIMENSION      SPARK_GLM5_NEXT_MODEL_KDA_HEAD_VALUE_DIMENSION
#define SPARK_LLM_KDA_CONV_KERNEL               SPARK_GLM5_NEXT_MODEL_KDA_CONV_KERNEL
#define SPARK_LLM_KDA_CHUNK_TOKENS              SPARK_GLM5_NEXT_MODEL_KDA_CHUNK_TOKENS
#define SPARK_LLM_KDA_STATE_ELEMENT_BYTES       SPARK_GLM5_NEXT_MODEL_KDA_STATE_ELEMENT_BYTES
#define SPARK_LLM_KDA_GATE_LOWER_BOUND          SPARK_GLM5_NEXT_MODEL_KDA_GATE_LOWER_BOUND
#define SPARK_LLM_KDA_LOW_RANK_GATE_BOTTLENECK  SPARK_GLM5_NEXT_MODEL_KDA_LOW_RANK_GATE_BOTTLENECK

#define SPARK_LLM_TILE_N                        128u
#define SPARK_LLM_TILE_STAGES                   2u
#define SPARK_LLM_LAYER_THREADS                 256u

#define SPARK_LLM_MTP_ENABLED                   0u
#define SPARK_LLM_MTP_DRAFT_DEPTH               1u

#define SPARK_LLM_TP_COLLECTIVE_BACKEND         0u
#define SPARK_LLM_TP_DEGREE                     16u
#define SPARK_LLM_STAGE_INDEX                   0u

#define SPARK_LLM_MISS_PACK_STRIDE              SPARK_GLM5_NEXT_MODEL_MISS_PACK_STRIDE
#define SPARK_LLM_MISS_RING_CAPACITY            SPARK_GLM5_NEXT_MODEL_MISS_RING_CAPACITY
#define SPARK_LLM_ROUTE_UNION_MAX               2400u
#define SPARK_LLM_ROUTE_UNION_TRIM              1888u

#define SPARK_LLM_ADAPTER_DESCRIPTOR            "spark.glm5_next.serving-adapter.tp8.expert_fp8.v1"
#define SPARK_LLM_MODEL_SOURCE_URI              "zai-org/GLM-5.3-Flash"
#define SPARK_LLM_MODEL_REVISION                "84c6a6aa9497188e15a635ba793b0f95a79b1033"
