#!/usr/bin/env python3
"""Install transparent Spark SSH route selection into the operator account."""

from __future__ import annotations

import argparse
import datetime as dt
import os
from pathlib import Path
import shlex
import shutil
import stat
import subprocess
import sys

from spark_ssh_proxy import RouteFailure, RouteProfile, load_profile


BEGIN = "# BEGIN DS4 SPARKNETWORK"
END = "# END DS4 SPARKNETWORK"


def _proxy_command(helper: Path, profile: Path, node: str, route: str) -> str:
    argv = [
        str(helper),
        "--profile", str(profile),
        "--node", node,
        "--port", "%p",
        "--route", route,
    ]
    return(" ".join(shlex.quote(item) for item in argv))


def _common_lines(
    user: str,
    host_key_alias: str,
    known_hosts: Path,
    connect_timeout: int,
) -> list[str]:
    return([
        f"    User {user}",
        f"    HostKeyAlias {host_key_alias}",
        "    BatchMode yes",
        f"    ConnectTimeout {connect_timeout}",
        "    ConnectionAttempts 1",
        "    CanonicalizeHostname no",
        "    CheckHostIP no",
        "    StrictHostKeyChecking accept-new",
        f"    UserKnownHostsFile {known_hosts}",
    ])


def generate_config(profile: RouteProfile, helper: Path, installed_profile: Path) -> str:
    lines = [
        BEGIN,
        "# Generated by tools/install_spark_ssh_failover.py.",
        "# Each sparkN follows its profile route policy without caller changes.",
    ]
    for node in profile.nodes.values():
        ten_g_lines = [
            f"Host {node.node_id}",
            f"    HostName {node.management_ip}",
            *_common_lines(node.user,node.node_id,profile.spark_known_hosts,30),
            f"    ProxyCommand {_proxy_command(helper,installed_profile,'%n','auto')}",
            "",
            f"Host {node.node_id}-10g",
            f"    HostName {node.management_ip}",
            *_common_lines(node.user,node.node_id,profile.spark_known_hosts,5),
        ]
        if not node.direct_enabled:
            ten_g_lines.append(
                f"    ProxyCommand {_proxy_command(helper,installed_profile,node.node_id,'auto')}"
            )
        lines.extend([
            *ten_g_lines,
            "",
            f"Host {node.node_id}-200g",
            f"    HostName {node.fabric_ip}",
            *_common_lines(node.user,node.node_id,profile.spark_known_hosts,20),
            f"    ProxyCommand {_proxy_command(helper,installed_profile,node.node_id,'200g')}",
            "",
            f"Host {node.node_id}-wifi",
            f"    HostName {node.management_ip}",
            *_common_lines(node.user,node.node_id,profile.spark_known_hosts,30),
            f"    ProxyCommand {_proxy_command(helper,installed_profile,node.node_id,'wifi')}",
            "",
        ])
        if node.wifi_hosts:
            lines.extend([
                f"Host {node.node_id}-emergency",
                f"    HostName {node.wifi_hosts[0]}",
                f"    User {profile.emergency.user}",
                f"    Port {profile.emergency.port}",
                f"    HostKeyAlias {node.node_id}-emergency",
                "    BatchMode yes",
                "    ConnectTimeout 8",
                "    ConnectionAttempts 1",
                "    StrictHostKeyChecking accept-new",
                f"    UserKnownHostsFile {profile.emergency.known_hosts}",
                "",
            ])
    lines.extend([END,""])
    return("\n".join(lines))


def replace_managed_block(original: str, block: str) -> str:
    begin_count = original.count(BEGIN)
    end_count = original.count(END)
    if begin_count != end_count or begin_count > 1:
        raise RouteFailure("SSH config has malformed DS4 Spark markers")
    if begin_count == 0:
        separator = "" if original == "" or original.startswith("\n") else "\n"
        return(block + separator + original)
    begin = original.index(BEGIN)
    end = original.index(END,begin) + len(END)
    while end < len(original) and original[end] in "\r\n":
        end += 1
    return(original[:begin] + block + original[end:])


def _copy_file(source: Path, destination: Path, mode: int) -> None:
    destination.parent.mkdir(parents=True,exist_ok=True)
    shutil.copy2(source,destination)
    destination.chmod(mode)


def _validate_ssh_config(ssh_binary: str, path: Path, profile: RouteProfile) -> None:
    for node in profile.nodes.values():
        for host in (
            node.node_id,
            f"{node.node_id}-10g",
            f"{node.node_id}-200g",
            f"{node.node_id}-wifi",
        ):
            result = subprocess.run(
                [ssh_binary,"-G","-F",str(path),host],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                text=True,
            )
            if result.returncode != 0:
                detail = result.stderr.strip()
                raise RouteFailure(f"generated SSH config rejected for {host}: {detail}")


def install(arguments: argparse.Namespace) -> None:
    source_profile = arguments.profile.resolve()
    source_helper = Path(__file__).with_name("spark_ssh_proxy.py").resolve()
    profile = load_profile(source_profile)
    install_root = arguments.install_root.expanduser().resolve()
    installed_helper = install_root / "spark_ssh_proxy.py"
    installed_profile = install_root / "spark_ssh_failover.json"
    ssh_config = arguments.ssh_config.expanduser()
    original = ssh_config.read_text(encoding="utf-8") if ssh_config.exists() else ""
    block = generate_config(profile,installed_helper,installed_profile)
    updated = replace_managed_block(original,block)
    if arguments.dry_run:
        print(updated,end="")
        return
    _copy_file(source_helper,installed_helper,0o755)
    _copy_file(source_profile,installed_profile,0o644)
    ssh_config.parent.mkdir(parents=True,exist_ok=True)
    ssh_config.parent.chmod(0o700)
    if ssh_config.exists():
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        backup = ssh_config.with_name(f"{ssh_config.name}.ds4-backup-{stamp}")
        shutil.copy2(ssh_config,backup)
        backup.chmod(stat.S_IRUSR | stat.S_IWUSR)
    temporary = ssh_config.with_name(f".{ssh_config.name}.ds4.tmp")
    temporary.write_text(updated,encoding="utf-8")
    temporary.chmod(stat.S_IRUSR | stat.S_IWUSR)
    _validate_ssh_config(profile.ssh_binary,temporary,profile)
    os.replace(temporary,ssh_config)
    for path in (profile.spark_known_hosts,profile.emergency.known_hosts):
        path.parent.mkdir(parents=True,exist_ok=True)
        path.touch(exist_ok=True)
        path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    print(f"installed helper={installed_helper}")
    print(f"installed profile={installed_profile}")
    print(f"updated ssh_config={ssh_config}")


def parse_arguments(argv: list[str] | None = None) -> argparse.Namespace:
    repo = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--profile",
        type=Path,
        default=repo / "deployment" / "rtx5090_speculation" / "spark_ssh_failover.local.json",
    )
    parser.add_argument(
        "--install-root",
        type=Path,
        default=Path("~/.local/libexec/ds4-spark-management"),
    )
    parser.add_argument("--ssh-config",type=Path,default=Path("~/.ssh/config"))
    parser.add_argument("--dry-run",action="store_true")
    return(parser.parse_args(argv))


def main(argv: list[str] | None = None) -> int:
    try:
        install(parse_arguments(argv))
        return(0)
    except (OSError,RouteFailure) as error:
        print(f"install_spark_ssh_failover: {error}",file=sys.stderr)
        return(1)


if __name__ == "__main__":
    raise SystemExit(main())
