#pragma once

#include "sparkpipe/spark_dsv4_model.h"

#define SPARK_DSV4_SPARSE_ATTN_HEADS_PER_CTA 4u
#define SPARK_DSV4_SPARSE_ATTN_MAX_SPLITS 32u
#define SPARK_DSV4_SPARSE_ATTN_MIN_SLOTS_PER_SPLIT 16u
#define SPARK_DSV4_SPARSE_ATTN_PARTIAL_SCALARS \
	(2u * SPARK_DSV4_SPARSE_ATTN_HEADS_PER_CTA + \
	 SPARK_DSV4_SPARSE_ATTN_HEADS_PER_CTA * SPARK_DSV4_MODEL_ATTN_HEAD_DIMENSION)
