typedef struct SPARK_ABI_TYPE(PipelineSlot)
{
	void *cuda_stream;
	const uint32_t *input_token_ids;
	uint32_t *output_token_ids;
	const uint32_t *row_lane_indices;
	const uint32_t *slot_mapping;
	const uint32_t *context_lengths;
	void *hidden_input_bf16;
	void *hidden_bf16;
	void *normalized_bf16;
	void *attn_query_bf16;
	void *attn_key_bf16;
	void *attn_value_bf16;
	void *attn_gate_bf16;
	void *attn_head_output_bf16;
	void *attn_output_bf16;
	void *gdn_conv_workspace_bf16;
	void *gdn_query_bf16;
	void *gdn_key_bf16;
	void *gdn_value_bf16;
	void *gdn_gate_bf16;
	void *gdn_ba_bf16;
	void *gdn_log_decay_f32;
	void *gdn_beta_f32;
	void *gdn_core_output_bf16;
	void *moe_slot_up_bf16;
	void *moe_slot_out_bf16;
	void *moe_indices_u32;
	float *moe_weights_f32;
	uint32_t *moe_inverse_u32;
	uint32_t *moe_grouped_rows_u32;
	uint32_t *moe_tile_prefix_w1_u32;
	uint32_t *moe_tile_prefix_w2_u32;
	void *argmax_score_f32;
	void *argmax_token_ids;
	float *chunk_qn_f32;
	float *chunk_kn_f32;
	float *chunk_cum_g_f32;
	float *chunk_decay_f32;
	float *chunk_attn_f32;
	float *chunk_w_f32;
	float *chunk_kg_f32;
	uint32_t *mtp_draft_token_ids;
} SPARK_ABI_TYPE(PipelineSlot);

typedef struct SPARK_ABI_TYPE(ResidentDecodeStageNodeContext)
{
	uint32_t abi_version;
	uint32_t stage_count;
	uint32_t stage_index;
	uint32_t first_layer_index;
	uint32_t layer_count;
	uint32_t owns_embedding;
	uint32_t owns_final_head;
	uint32_t max_active_sequence_count;
	uint32_t max_prefill_tokens;
	uint32_t pipeline_slot_count;
	uint32_t kv_cache_block_count;
	uint32_t enable_cuda_graph_replay;
	float rms_norm_epsilon;
	const void *token_embedding_bf16;
	const void *final_norm_weight_bf16;
	const void *lm_head_weight_bf16;
	const void *attention_norm_weights_by_layer_bf16[SPARK_LLM_LAYER_COUNT];
	const void *mlp_norm_weights_by_layer_bf16[SPARK_LLM_LAYER_COUNT];
	const SPARK_ABI_TYPE(GdnLayerWeights) *gdn_weights_by_layer;
	const SPARK_ABI_TYPE(AttnLayerWeights) *attn_weights_by_layer;
	const SPARK_ABI_TYPE(MoeWeights) *moe_weights_by_layer;
	SPARK_ABI_TYPE(GdnStatePool) gdn_state_pool;
	void *kv_cache_bf16;
	const SPARK_ABI_TYPE(PipelineSlot) *pipeline_slots;
	uint64_t estimated_service_time_ns;
} SPARK_ABI_TYPE(ResidentDecodeStageNodeContext);
