#ifndef SPARKPIPE_SPARK_STATUS_H
#define SPARKPIPE_SPARK_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum SparkStatus
{
    SPARK_STATUS_OK = 0,
    SPARK_STATUS_INVALID_ARGUMENT,
    SPARK_STATUS_CAPACITY_EXCEEDED,
    SPARK_STATUS_NOT_FOUND,
    SPARK_STATUS_IO_ERROR,
    SPARK_STATUS_PARSE_ERROR,
    SPARK_STATUS_SCHEMA_ERROR,
    SPARK_STATUS_HASH_MISMATCH,
    SPARK_STATUS_MODULE_NOT_VALIDATED,
    SPARK_STATUS_VALIDATION_FAILED,
    SPARK_STATUS_ABI_MISMATCH,
    SPARK_STATUS_TARGET_MISMATCH,
    SPARK_STATUS_COMPILER_ERROR,
    SPARK_STATUS_DRIVER_LOAD_ERROR,
    SPARK_STATUS_ROUTE_NOT_FOUND,
    SPARK_STATUS_BUSY,
    SPARK_STATUS_DUPLICATE,
    SPARK_STATUS_INTERNAL_ERROR
} SparkStatus;

const char *SparkStatusToString(SparkStatus status);

#ifdef __cplusplus
}
#endif

#endif
