#!/usr/bin/env python3
"""Generate the dsv4_pro TP4xPP4 shared-lane family deployment (lane 5).

Emits deployment/dsv4_pro_tp4pp4/model_resident.json (schema 2, one nodes[]
entry per rank, rank_index 0..15 = logical rank = index in --nodes, order
identical to the mesh map) and the lane-5 stage config
deployment/dsv4_pro_tp4pp4/config/dsv4_pro_tp4_pp4_stage.json derived from
examples/deployments/dsv4_pro_tp4_pp4_stage.json with the collective block
moved into this lane's reserved range.

Port blocks (tools/devcycle/lane_assignments.json as amended by PR #1094 -
the table's original collective base 67000+16L exceeded the 16-bit port
limit and the queue rejects it):
  lane 5 control    23080..23095
  lane 5 collective 53080..53095
  lane 5 transport  64080..64095

The stage config's stage_pack_path is the uniform rank-pack name
packs/dsv4_pro_tp4_pp4_stage.spstage (per-rank CONTENT, uniform NAME): the
deployed roots originally carried per-rank file names, which never matched
the stage config the adapter validates against (solo boots stopped before
module init, so it never fired); the multidev fleet prepare renames the
packs to the uniform name and places the .sha256/.experts sidecars beside
them.

The deployed pre-multidev deployment used runtime limits
(1024 active / 4096 resident / 1M logical / 16K physical pages) with a
4 TiB unbounded KV backing claim; the lane deployment keeps the proven
runtime_limits byte-identical (they passed deployment_validation on all 16
ranks) and bounds kv_backing_maximum_bytes at 16 GiB for shared-lane smoke.
eos_token_ids stays empty exactly as in the deployed config and the
recorded batches (tools/devcycle/batches/*.json carry stop_token_ids: []).

Usage: python3 tools/dsv4_pro_tp4pp4_gen_deployment.py [--output-dir DIR]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_STAGE = ROOT / "examples" / "deployments" / "dsv4_pro_tp4_pp4_stage.json"
DEFAULT_OUTPUT = ROOT / "deployment" / "dsv4_pro_tp4pp4"

LANE = 5
RANKS = 16
# Lane table bases for lane 5 (control 23000+16L, transport 64000+16L;
# collective amended by PR #1094 to 53080+16L - 67000+16L exceeds u16).
CONTROL_BASE = 23080                   # 23080..23095
COLLECTIVE_BASE = 53080                # 53080..53095
TRANSPORT_BASE = 64080                 # 64080..64095

RUNTIME_ROOT = "/home/spark{host:x}/sparkdata/dsv4_pro.tp4pp4"
KV_BACKING = "/home/spark{host:x}/kvcache/dsv4_pro/tp4_pp4.bf16"
KV_BACKING_MAX = 16 * 1024 ** 3
NODE_TARGET = "cuda.sm121.dsv4.pro.resident_decode_stage.linear_fp8.expert_mxfp4.kv_bf16"
ADAPTER = "lib/libdsv4_pro_tp4_pp4_serving_adapter.so"
DRIVER = "lib/model_driver.so"
TRANSPORT = "lib/libhidden_transport_spark_host_rdma_verbs.so"
STAGE_CONFIG_NAME = "config/dsv4_pro_tp4_pp4_stage.json"
WEIGHTD_SOCKET = "/run/sparkpipe-weightd-shared/weightd.sock"

# Runtime limits: byte-identical to the deployed pre-multidev config (they
# passed deployment_validation on all 16 ranks; changing them here would
# open an unvalidated path before the first shared E2E measures real use).
RUNTIME_LIMITS = {
    "max_inflight_submissions": 4,
    "max_active_sequences": 1024,
    "max_input_rows": 1024,
    "resident_sequence_capacity": 4096,
    "kv_logical_page_capacity": 1048576,
    "kv_physical_page_capacity": 16384,
}


def build_deployment() -> dict:
    nodes = []
    for rank in range(RANKS):
        host = f"spark{rank:x}"
        nodes.append({
            "rank_index": rank,
            "stage_index": rank,
            "runtime_root": RUNTIME_ROOT.format(host=rank),
            "node_target": NODE_TARGET,
            "transport_host": f"{host}-fabric",
            "adapter_configuration_path": STAGE_CONFIG_NAME,
            "kv_backing_directory": KV_BACKING.format(host=rank),
            "kv_backing_maximum_bytes": KV_BACKING_MAX,
            "control_endpoint": {
                "kind": "tcp",
                "host": host,
                "port": CONTROL_BASE + rank,
            },
        })
    return {
        "schema_version": 2,
        "@comment": "dsv4_pro TP4xPP4 shared-lane deployment (lane 5). Generated by "
                    "tools/dsv4_pro_tp4pp4_gen_deployment.py - regenerate, never hand-edit. "
                    "stage_index is the per-rank failure-domain id residentd validates as "
                    "unique (NOT the PP stage; the serving adapter derives TP4xPP4 stage "
                    "layers from the rank via TpDeriveLayerSlice 16/15/15/15).",
        "eos_token_ids": [],
        "coordinator_rank_index": 0,
        "adapter": {"shared_object_path": ADAPTER},
        "driver": {"shared_object_path": DRIVER, "program_name": "resident_decode"},
        "transport": {
            "shared_object_path": TRANSPORT,
            "mode": "host-rdma",
            "control_port_base": TRANSPORT_BASE,
        },
        "weightd": {"socket_path": WEIGHTD_SOCKET},
        "runtime_limits": RUNTIME_LIMITS,
        "nodes": nodes,
    }


def build_stage_config() -> dict:
    config = json.loads(EXAMPLES_STAGE.read_text())
    collective = config["tp_collective"]
    collective["listen_port"] = COLLECTIVE_BASE
    collective["peer_ports"] = [COLLECTIVE_BASE + r for r in range(RANKS)]
    return config


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output = args.output_dir
    (output / "config").mkdir(parents=True, exist_ok=True)
    deployment = build_deployment()
    stage = build_stage_config()
    (output / "model_resident.json").write_text(
        json.dumps(deployment, indent=1) + "\n")
    (output / "config" / "dsv4_pro_tp4_pp4_stage.json").write_text(
        json.dumps(stage, indent=1) + "\n")

    for node in deployment["nodes"]:
        assert node["rank_index"] == node["stage_index"]
        assert 0 < node["control_endpoint"]["port"] < 65536
    peers = stage["tp_collective"]["peer_ports"]
    assert peers == [COLLECTIVE_BASE + r for r in range(RANKS)]
    assert all(0 < p < 65536 for p in peers + [stage["tp_collective"]["listen_port"]])
    print(f"wrote {output}/model_resident.json ({RANKS} ranks, "
          f"control {CONTROL_BASE}..{CONTROL_BASE + 15}, "
          f"collective {COLLECTIVE_BASE}..{COLLECTIVE_BASE + 15}, "
          f"transport {TRANSPORT_BASE}..{TRANSPORT_BASE + 15})")
    print(f"wrote {output}/config/dsv4_pro_tp4_pp4_stage.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
