#!/usr/bin/env bash
set -euo pipefail

PREFIX="${SPARKPIPE_B12X_ENV_PREFIX:-$HOME/.cache/sparkpipe/glm52-b12x}"
CONFIG_DIR="${SPARKPIPE_CONFIG_DIR:-$HOME/.config/sparkpipe}"
SYSROOT="$PREFIX/python3.12-dev-sysroot"
DOWNLOAD_DIR="$PREFIX/download"
ENV_FILE="$CONFIG_DIR/glm52_b12x_aot_env.sh"
PYTHON_BIN="${SPARKPIPE_B12X_AOT_PYTHON:-$HOME/ds4-vllm-local/bin/python}"
NVCC_BIN="${SPARKPIPE_B12X_AOT_NVCC:-/usr/local/cuda/bin/nvcc}"

mkdir -p "$DOWNLOAD_DIR" "$SYSROOT" "$CONFIG_DIR"

if [ ! -x "$PYTHON_BIN" ]; then
    echo "missing B12x AOT Python: $PYTHON_BIN" >&2
    exit 2
fi
if [ ! -x "$NVCC_BIN" ]; then
    echo "missing B12x AOT nvcc: $NVCC_BIN" >&2
    exit 3
fi

"$PYTHON_BIN" - <<'PY'
import importlib.util
import torch

missing = []
for name in ("flashinfer", "tvm_ffi", "triton", "cupy"):
    if importlib.util.find_spec(name) is None:
        missing.append(name)
if missing:
    raise SystemExit("missing Python modules: " + ",".join(missing))
if not torch.cuda.is_available():
    raise SystemExit("CUDA is unavailable to torch")
if torch.cuda.get_device_capability(0) not in ((12, 0), (12, 1)):
    raise SystemExit(f"expected SM120/SM121, got {torch.cuda.get_device_capability(0)}")
print(f"torch={torch.__version__} capability={torch.cuda.get_device_capability(0)}")
PY

if [ ! -f "$SYSROOT/usr/include/python3.12/Python.h" ] ||
   [ ! -f "$SYSROOT/usr/include/aarch64-linux-gnu/python3.12/pyconfig.h" ]; then
    rm -rf "$DOWNLOAD_DIR" "$SYSROOT"
    mkdir -p "$DOWNLOAD_DIR" "$SYSROOT"
    (
        cd "$DOWNLOAD_DIR"
        apt-get download python3.12-dev libpython3.12-dev
        for package in ./*.deb; do
            dpkg-deb -x "$package" "$SYSROOT"
        done
    )
fi

if [ ! -f "$SYSROOT/usr/include/python3.12/Python.h" ]; then
    echo "Python.h was not installed into $SYSROOT" >&2
    exit 4
fi
if [ ! -f "$SYSROOT/usr/include/aarch64-linux-gnu/python3.12/pyconfig.h" ]; then
    echo "multiarch pyconfig.h was not installed into $SYSROOT" >&2
    exit 5
fi

cat > "$ENV_FILE" <<EOF
# Generated by tools/glm52_b12x_prepare_spark_env.sh
export SPARKPIPE_B12X_AOT_PYTHON="$PYTHON_BIN"
export SPARKPIPE_B12X_AOT_NVCC="$NVCC_BIN"
export SPARKPIPE_PY312_DEV_SYSROOT="$SYSROOT"
export CPATH="$SYSROOT/usr/include/python3.12:$SYSROOT/usr/include\${CPATH:+:\$CPATH}"
export LIBRARY_PATH="$SYSROOT/usr/lib/aarch64-linux-gnu\${LIBRARY_PATH:+:\$LIBRARY_PATH}"
export FLASHINFER_B12X_STATIC_COMPACT_CUTOVER_PAIRS="\${FLASHINFER_B12X_STATIC_COMPACT_CUTOVER_PAIRS:-1024}"
EOF

echo "wrote $ENV_FILE"
echo "source $ENV_FILE before running tools/glm52_b12x_aot_compile.py"
