#!/usr/bin/env python3
"""DFlash2 selector parity case: numpy oracle in, expected outputs out.

Generates one deterministic case for the two DFlash2 selector kernels (W4, the
top-16 over the vocabulary, and W3, the K x K edge lattice plus the greedy
walk) and dumps the EXPECTED outputs computed by the landed numpy oracles in
tools/qwen36_dspark_reference.py (_score_edges and _greedy_walk are exact ports
of vLLM PR #52816 and are the contract).

Inputs are NOT dumped. Every input tensor is generated by a counter-based
splitmix64 that the CUDA validator mirrors element for element, so the two
sides agree on multi-gigabyte tensors without moving them through a file.

EXACT ARITHMETIC BY CONSTRUCTION - this is what makes bit-for-bit parity a
meaningful claim rather than a tolerance. Every generated value is a small
integer (hidden in [-4,4], every weight in [-1,0,1]), so:

  * each dot product is a sum of integers bounded by 4*5120 = 20480 (head,
    context gate) or 256*20480 = 5242880 (edge lattice), both far inside
    fp32's exact-integer range (2^24), hence INDEPENDENT of summation order:
    numpy's BLAS order and the kernel's warp-tree/ascending orders give the
    IDENTICAL fp32 value, so a mismatch can only be a real bug, never fp32
    associativity;
  * the BF16 truncation points still round for real (integers above 256 are
    not BF16-representable) and hit exact ties-to-even, so the contract's
    truncation points are genuinely exercised.

TIE RULE. The unary logits are BF16-truncated BEFORE the top-K, so exact ties
across the vocabulary are the common case and the top-K is only well defined
once the tie rule is pinned. The kernels pin first-max (lowest id wins), the
same rule _greedy_walk uses for its argmax and SparkLmArgmaxReduce uses for
the landed head. numpy's default np.argsort(-x) is quicksort, i.e. UNSTABLE,
so this script computes the expectation with kind="stable" (the stable-sort
spelling of first-max) and reports whether the default sort would have
disagreed, which is the diagnostic for the oracle's own ambiguity.
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import qwen36_dspark_reference as reference  # noqa: E402  (the contract oracles)

MAGIC = b"Q6DF2CS1"
MASK64 = (1 << 64) - 1
GOLDEN = 0x9E3779B97F4A7C15

STREAM_HIDDEN = 0x0000000011111111
STREAM_HEAD = 0x0000000022222222
STREAM_PROJECTION = 0x0000000033333333
STREAM_PREDECESSOR = 0x0000000044444444
STREAM_SUCCESSOR = 0x0000000055555555
STREAM_ANCHOR = 0x0000000066666666

SCALES = {
    # name: (vocab_count, hidden_dimension)
    "smoke": (4096, 512),
    "mid": (32768, 1024),
    "full": (reference.VOCAB, reference.HIDDEN),
}


def splitmix64(index: np.ndarray, stream_seed: int, seed: int) -> np.ndarray:
    """Counter-based splitmix64: value(index) with no sequential state.

    Mirrored bit for bit by SparkQwen36Dflash2CaseValue in the CUDA validator.
    """
    state = np.uint64((stream_seed + seed) & MASK64)
    z = (index.astype(np.uint64) + np.uint64(1)) * np.uint64(GOLDEN) + state
    z = (z ^ (z >> np.uint64(30))) * np.uint64(0xBF58476D1CE4E5B9)
    z = (z ^ (z >> np.uint64(27))) * np.uint64(0x94D049BB133111EB)
    return z ^ (z >> np.uint64(31))


def small_integers(count: int, stream_seed: int, seed: int, span: int, first_index: int = 0) -> np.ndarray:
    """count integer-valued fp32 samples in [-span, span], addressable by index."""
    index = np.arange(first_index, first_index + count, dtype=np.uint64)
    raw = splitmix64(index, stream_seed, seed) >> np.uint64(11)
    return (raw % np.uint64(2 * span + 1)).astype(np.int64).astype(np.float32) - np.float32(span)


def bf16_round(values: np.ndarray) -> np.ndarray:
    """The reference's own BF16 truncation (RNE, ties to even)."""
    return reference.bf16_to_f32(reference.f32_to_bf16(np.ascontiguousarray(values, dtype=np.float32)))


def head_logits(hidden: np.ndarray, vocab_count: int, hidden_dimension: int, seed: int, chunk_rows: int = 4096) -> np.ndarray:
    """hidden @ lm_head.T with the head materialised one row chunk at a time."""
    logits = np.empty((hidden.shape[0], vocab_count), dtype=np.float32)
    for first in range(0, vocab_count, chunk_rows):
        rows = min(chunk_rows, vocab_count - first)
        chunk = small_integers(rows * hidden_dimension, STREAM_HEAD, seed, 1,
                               first_index=first * hidden_dimension).reshape(rows, hidden_dimension)
        logits[:, first:first + rows] = hidden @ chunk.T
    return logits


def greedy_walk_with_slots(scores: np.ndarray, candidate_ids: np.ndarray) -> tuple[list[int], list[int]]:
    """_greedy_walk, additionally reporting WHICH lattice column was taken."""
    previous = 0
    drafts: list[int] = []
    slots: list[int] = []
    for step in range(scores.shape[0]):
        row = scores[step, previous]
        nxt = int(np.min(np.where(row == row.max())[0]))
        drafts.append(int(candidate_ids[step, nxt]))
        slots.append(nxt)
        previous = nxt
    return drafts, slots


def build(scale: str, batch_count: int, slot_count: int, seed: int, output: Path) -> int:
    vocab_count, hidden_dimension = SCALES[scale]
    rank = reference.SELECTOR_RANK
    top_k = reference.SELECTOR_TOP_K
    rows = batch_count * slot_count
    if vocab_count < top_k or hidden_dimension % 2 != 0:
        raise SystemExit("case geometry is invalid")

    hidden = small_integers(rows * hidden_dimension, STREAM_HIDDEN, seed, 4).reshape(rows, hidden_dimension)
    anchor_token_ids = (splitmix64(np.arange(batch_count, dtype=np.uint64), STREAM_ANCHOR, seed)
                        % np.uint64(vocab_count)).astype(np.uint32)

    # W4: BF16-truncate the whole logit row, THEN take the top-k (oracle order).
    logits = bf16_round(head_logits(hidden, vocab_count, hidden_dimension, seed))
    stable_order = np.argsort(-logits, axis=-1, kind="stable")
    top_ids = stable_order[:, :top_k].astype(np.uint32)
    unary = np.take_along_axis(logits, top_ids.astype(np.int64), axis=-1).astype(np.float32)
    default_order = np.argsort(-logits, axis=-1)[:, :top_k]
    tie_disagreements = int(np.count_nonzero(default_order.astype(np.uint32) != top_ids))
    boundary_ties = int(np.count_nonzero(logits == unary[:, top_k - 1:top_k]) - rows)

    # W3 step 1: the context gate H = bf16(hidden_projection @ h_t).
    projection = small_integers(rank * hidden_dimension, STREAM_PROJECTION, seed, 1).reshape(rank, hidden_dimension)
    context_gate = bf16_round(hidden @ projection.T)

    # W3 steps 2 and 3: the lattice and the walk, straight from the oracles.
    predecessor = small_integers(vocab_count * rank, STREAM_PREDECESSOR, seed, 1).reshape(vocab_count, rank)
    successor = small_integers(vocab_count * rank, STREAM_SUCCESSOR, seed, 1).reshape(vocab_count, rank)
    edges = reference._score_edges(
        predecessor,
        successor,
        top_ids.reshape(batch_count, slot_count, top_k).astype(np.int64),
        unary.reshape(batch_count, slot_count, top_k),
        context_gate.reshape(batch_count, slot_count, rank),
        anchor_token_ids.astype(np.int64),
        top_k,
    ).astype(np.float32)
    draft_ids = np.empty((batch_count, slot_count), dtype=np.uint32)
    draft_slots = np.empty((batch_count, slot_count), dtype=np.uint32)
    for batch in range(batch_count):
        lane_ids = top_ids.reshape(batch_count, slot_count, top_k)[batch]
        walked, slots = greedy_walk_with_slots(edges[batch], lane_ids)
        oracle = reference._greedy_walk(edges[batch], lane_ids)
        if walked != oracle:
            raise SystemExit("internal: slot-reporting walk disagrees with _greedy_walk")
        draft_ids[batch] = np.asarray(walked, dtype=np.uint32)
        draft_slots[batch] = np.asarray(slots, dtype=np.uint32)

    exact_integers = bool(np.all(edges == np.rint(edges)) and np.all(unary == np.rint(unary)))
    payload = bytearray()
    payload += MAGIC
    payload += struct.pack("<8I", batch_count, slot_count, vocab_count, hidden_dimension, rank, top_k, 4, 1)
    payload += struct.pack("<Q", seed)
    payload += anchor_token_ids.astype("<u4").tobytes()
    payload += top_ids.astype("<u4").tobytes()
    payload += unary.astype("<f4").tobytes()
    payload += reference.f32_to_bf16(context_gate).astype("<u2").tobytes()
    payload += edges.astype("<f4").tobytes()
    payload += draft_ids.astype("<u4").tobytes()
    payload += draft_slots.astype("<u4").tobytes()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(bytes(payload))

    print(f"case            = {output}")
    print(f"scale           = {scale} batch={batch_count} slots={slot_count} vocab={vocab_count} "
          f"hidden={hidden_dimension} rank={rank} top_k={top_k} seed={seed}")
    print(f"bytes           = {len(payload)}")
    print(f"exact_integers  = {exact_integers} (fp32 accumulation order cannot change any expected value)")
    print(f"unary[0][:4]    = {unary[0][:4].tolist()}")
    print(f"top_ids[0][:4]  = {top_ids[0][:4].tolist()}")
    print(f"edges[0,0,0,:4] = {edges[0, 0, 0, :4].tolist()}")
    print(f"draft_ids[0]    = {draft_ids[0].tolist()}")
    print(f"draft_slots[0]  = {draft_slots[0].tolist()}")
    print(f"tie_boundary    = {boundary_ties} extra candidates tied with the 16th score "
          f"(BF16 logits over {vocab_count} ids)")
    print(f"argsort_default_vs_stable_id_diffs = {tie_disagreements} "
          f"(non-zero means the oracle's unstable np.argsort picks different ids among ties)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scale", choices=sorted(SCALES), default="smoke")
    parser.add_argument("--batch", type=int, default=2)
    parser.add_argument("--slots", type=int, default=reference.BLOCK - 1)
    parser.add_argument("--seed", type=lambda text: int(text, 0), default=0x51A4C0DE)
    parser.add_argument("--output", type=Path, default=Path("build/dflash2/dflash2_selector_case.bin"))
    arguments = parser.parse_args()
    return build(arguments.scale, arguments.batch, arguments.slots, arguments.seed, arguments.output)


if __name__ == "__main__":
    raise SystemExit(main())
