#!/usr/bin/env python3
"""DFlash2 selector parity case: numpy oracle in, expected outputs out.

Generates one deterministic case for the two DFlash2 selector kernels (W4, the
top-16 over the vocabulary, and W3, the K x K edge lattice plus the greedy
walk) and dumps the EXPECTED outputs computed by the landed numpy oracles in
tools/qwen36_dspark_reference.py (_score_edges and _greedy_walk are exact ports
of vLLM PR #52816 and are the contract; the top-K expectation uses the same
stable / id-ascending tie rule the reference now pins).

Inputs are NOT dumped. Every input tensor is generated by a counter-based
splitmix64 that the CUDA validator mirrors element for element, so the two
sides agree on multi-gigabyte tensors without moving them through a file.

EXACT ARITHMETIC BY CONSTRUCTION - this is what makes bit-for-bit parity a
meaningful claim rather than a tolerance. Every generated value is a small
integer (hidden in [-4,4], weights in [-1,0,1]), so:

  * each dot product is a sum of integers well inside fp32's exact-integer
    range (2^24), hence INDEPENDENT of summation order: numpy's BLAS order and
    the kernel's warp-tree / ascending orders give the IDENTICAL fp32 value, so
    a mismatch can only be a real bug, never fp32 associativity;
  * the BF16 truncation points still round for real (integers above 256 are not
    BF16-representable) and hit exact ties-to-even, so the contract's
    truncation points are genuinely exercised.

TWO DISCRIMINATORS, so the harness PROVES the two rules instead of trusting a
comment. Both are dumped alongside the expectations and both are asserted by
the validator, which also fails if a case stopped discriminating:

  1. TRUNCATION BEFORE SELECTION - the reference truncates the whole logit row
     to BF16 (line 348) and only then takes the top-K (line 349). The case also
     dumps the top-K that selecting on the UNTRUNCATED fp32 logits would give;
     where the two disagree, a kernel that truncated AFTER selecting is caught.
  2. STRICT-GREATER FIRST-MAX in the walk - _greedy_walk takes
     min(where(row == row.max())). The case dumps the walk a NON-strict (>=,
     last-max) implementation would produce plus how many walked lattice rows
     have a tied maximum; where those disagree, a >= walk is caught. The "tie"
     scale forces this by construction: its codebook span is zero, so every
     lattice row collapses onto the BF16-truncated unary logits, whose ties are
     dense.
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import qwen36_dspark_reference as reference  # noqa: E402  (the contract oracles)

MAGIC = b"Q6DF2CS2"
MASK64 = (1 << 64) - 1
GOLDEN = 0x9E3779B97F4A7C15

STREAM_HIDDEN = 0x0000000011111111
STREAM_HEAD = 0x0000000022222222
STREAM_PROJECTION = 0x0000000033333333
STREAM_PREDECESSOR = 0x0000000044444444
STREAM_SUCCESSOR = 0x0000000055555555
STREAM_ANCHOR = 0x0000000066666666

# name: (vocab, hidden, rank, hidden_span, weight_span, codebook_span, head_row_pairing)
SCALES = {
    "smoke": (4096, 512, reference.SELECTOR_RANK, 4, 1, 1, 0),
    "mid": (32768, 1024, reference.SELECTOR_RANK, 4, 1, 1, 0),
    "full": (reference.VOCAB, reference.HIDDEN, reference.SELECTOR_RANK, 4, 1, 1, 0),
    # The discriminator scale. hidden_span 64 pushes the logits past 256 so the
    # BF16 truncation actually collapses distinct values (that is what makes
    # truncate-then-select observable), and codebook_span 0 collapses every
    # lattice row onto those truncated unary logits, so the walked rows carry
    # dense tied maxima and a >= walk necessarily diverges.
    # ... and head_row_pairing makes every EVEN vocabulary row identical to the
    # odd row above it, so each logit value occurs exactly twice: the maximum of
    # every walked row is then a guaranteed exact tie between two adjacent
    # candidate columns, which is what a >= walk gets wrong.
    "tie": (4096, 512, reference.SELECTOR_RANK, 64, 1, 0, 1),
}


def splitmix64(index: np.ndarray, stream_seed: int, seed: int) -> np.ndarray:
    """Counter-based splitmix64: value(index) with no sequential state.

    Mirrored bit for bit by SparkDflash2CaseValue in the CUDA validator.
    """
    state = np.uint64((stream_seed + seed) & MASK64)
    z = (index.astype(np.uint64) + np.uint64(1)) * np.uint64(GOLDEN) + state
    z = (z ^ (z >> np.uint64(30))) * np.uint64(0xBF58476D1CE4E5B9)
    z = (z ^ (z >> np.uint64(27))) * np.uint64(0x94D049BB133111EB)
    return z ^ (z >> np.uint64(31))


def small_integers(count: int, stream_seed: int, seed: int, span: int, first_index: int = 0) -> np.ndarray:
    """count integer-valued fp32 samples in [-span, span], addressable by index."""
    index = np.arange(first_index, first_index + count, dtype=np.uint64)
    raw = splitmix64(index, stream_seed, seed) >> np.uint64(11)
    if span == 0:
        return np.zeros(count, dtype=np.float32)
    return (raw % np.uint64(2 * span + 1)).astype(np.int64).astype(np.float32) - np.float32(span)


def bf16_round(values: np.ndarray) -> np.ndarray:
    """The reference's own BF16 truncation (RNE, ties to even)."""
    return reference.bf16_to_f32(reference.f32_to_bf16(np.ascontiguousarray(values, dtype=np.float32)))


def head_row_index(first_row: int, row_count: int, hidden_dimension: int, pairing: int) -> np.ndarray:
    """Flat PRNG indices for head rows [first_row, first_row+row_count).

    pairing folds every odd row onto the even row below it (row & ~1), so the
    two rows are bit-identical and their logits tie exactly. The CUDA
    validator's filler applies the same fold.
    """
    rows = np.arange(first_row, first_row + row_count, dtype=np.uint64)
    if pairing != 0:
        rows = rows & ~np.uint64(1)
    return ((rows[:, None] * np.uint64(hidden_dimension)) +
            np.arange(hidden_dimension, dtype=np.uint64)[None, :]).ravel()


def head_logits(hidden: np.ndarray, vocab_count: int, hidden_dimension: int, seed: int, weight_span: int,
                pairing: int, chunk_rows: int = 4096) -> np.ndarray:
    """hidden @ lm_head.T with the head materialised one row chunk at a time."""
    logits = np.empty((hidden.shape[0], vocab_count), dtype=np.float32)
    for first in range(0, vocab_count, chunk_rows):
        rows = min(chunk_rows, vocab_count - first)
        index = head_row_index(first, rows, hidden_dimension, pairing)
        raw = splitmix64(index, STREAM_HEAD, seed) >> np.uint64(11)
        chunk = ((raw % np.uint64(2 * weight_span + 1)).astype(np.int64).astype(np.float32) -
                 np.float32(weight_span)).reshape(rows, hidden_dimension)
        logits[:, first:first + rows] = hidden @ chunk.T
    return logits


def walk_with_slots(scores: np.ndarray, candidate_ids: np.ndarray, strict: bool) -> tuple[list[int], list[int], int]:
    """_greedy_walk, reporting the taken column and the tied-maximum row count.

    strict=True is the oracle's first-max; strict=False is the last-max a
    non-strict (>=) implementation would take, kept only as the discriminator.
    """
    previous = 0
    drafts: list[int] = []
    slots: list[int] = []
    tied_rows = 0
    for step in range(scores.shape[0]):
        row = scores[step, previous]
        maximum = row.max()
        if int(np.count_nonzero(row == maximum)) > 1:
            tied_rows += 1
        chosen = int(np.min(np.where(row == maximum)[0])) if strict else int(np.max(np.where(row == maximum)[0]))
        drafts.append(int(candidate_ids[step, chosen]))
        slots.append(chosen)
        previous = chosen
    return drafts, slots, tied_rows


def build(scale: str, batch_count: int, slot_count: int, seed: int, output: Path) -> int:
    vocab_count, hidden_dimension, rank, hidden_span, weight_span, codebook_span, head_row_pairing = SCALES[scale]
    top_k = reference.SELECTOR_TOP_K
    rows = batch_count * slot_count
    if vocab_count < top_k or hidden_dimension % 2 != 0:
        raise SystemExit("case geometry is invalid")

    hidden = small_integers(rows * hidden_dimension, STREAM_HIDDEN, seed, hidden_span).reshape(rows, hidden_dimension)
    anchor_token_ids = (splitmix64(np.arange(batch_count, dtype=np.uint64), STREAM_ANCHOR, seed)
                        % np.uint64(vocab_count)).astype(np.uint32)

    # W4: the oracle truncates the whole logit row to BF16 and only THEN takes
    # the top-k, stable / id-ascending.
    raw_logits = head_logits(hidden, vocab_count, hidden_dimension, seed, weight_span, head_row_pairing)
    logits = bf16_round(raw_logits)
    top_ids = np.argsort(-logits, axis=-1, kind="stable")[:, :top_k].astype(np.uint32)
    unary = np.take_along_axis(logits, top_ids.astype(np.int64), axis=-1).astype(np.float32)
    untruncated_top_ids = np.argsort(-raw_logits, axis=-1, kind="stable")[:, :top_k].astype(np.uint32)
    truncation_discriminator = int(np.count_nonzero(untruncated_top_ids != top_ids))
    boundary_ties = int(np.count_nonzero(logits == unary[:, top_k - 1:top_k]) - rows)

    # W3 step 1: the context gate H = bf16(hidden_projection @ h_t).
    projection = small_integers(rank * hidden_dimension, STREAM_PROJECTION, seed, weight_span).reshape(rank, hidden_dimension)
    context_gate = bf16_round(hidden @ projection.T)

    # W3 steps 2 and 3: the lattice and the walk, straight from the oracles.
    predecessor = small_integers(vocab_count * rank, STREAM_PREDECESSOR, seed, codebook_span).reshape(vocab_count, rank)
    successor = small_integers(vocab_count * rank, STREAM_SUCCESSOR, seed, codebook_span).reshape(vocab_count, rank)
    edges = reference._score_edges(
        predecessor,
        successor,
        top_ids.reshape(batch_count, slot_count, top_k).astype(np.int64),
        unary.reshape(batch_count, slot_count, top_k),
        context_gate.reshape(batch_count, slot_count, rank),
        anchor_token_ids.astype(np.int64),
        top_k,
    ).astype(np.float32)
    draft_ids = np.empty((batch_count, slot_count), dtype=np.uint32)
    draft_slots = np.empty((batch_count, slot_count), dtype=np.uint32)
    lastmax_ids = np.empty((batch_count, slot_count), dtype=np.uint32)
    lastmax_slots = np.empty((batch_count, slot_count), dtype=np.uint32)
    walk_tie_rows = 0
    for batch in range(batch_count):
        lane_ids = top_ids.reshape(batch_count, slot_count, top_k)[batch]
        walked, slots, tied_rows = walk_with_slots(edges[batch], lane_ids, True)
        if walked != reference._greedy_walk(edges[batch], lane_ids):
            raise SystemExit("internal: slot-reporting walk disagrees with _greedy_walk")
        loose, loose_slots, _ = walk_with_slots(edges[batch], lane_ids, False)
        draft_ids[batch] = np.asarray(walked, dtype=np.uint32)
        draft_slots[batch] = np.asarray(slots, dtype=np.uint32)
        lastmax_ids[batch] = np.asarray(loose, dtype=np.uint32)
        lastmax_slots[batch] = np.asarray(loose_slots, dtype=np.uint32)
        walk_tie_rows += tied_rows
    walk_lastmax_diffs = int(np.count_nonzero(lastmax_slots != draft_slots))

    exact_integers = bool(np.all(edges == np.rint(edges)) and np.all(unary == np.rint(unary)))
    payload = bytearray()
    payload += MAGIC
    payload += struct.pack("<13I", batch_count, slot_count, vocab_count, hidden_dimension, rank, top_k,
                           hidden_span, weight_span, codebook_span, head_row_pairing,
                           truncation_discriminator, walk_tie_rows, walk_lastmax_diffs)
    payload += struct.pack("<Q", seed)
    payload += anchor_token_ids.astype("<u4").tobytes()
    payload += top_ids.astype("<u4").tobytes()
    payload += untruncated_top_ids.astype("<u4").tobytes()
    payload += unary.astype("<f4").tobytes()
    payload += reference.f32_to_bf16(context_gate).astype("<u2").tobytes()
    payload += edges.astype("<f4").tobytes()
    payload += draft_ids.astype("<u4").tobytes()
    payload += draft_slots.astype("<u4").tobytes()
    payload += lastmax_ids.astype("<u4").tobytes()
    payload += lastmax_slots.astype("<u4").tobytes()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(bytes(payload))

    print(f"case            = {output}")
    print(f"scale           = {scale} batch={batch_count} slots={slot_count} vocab={vocab_count} "
          f"hidden={hidden_dimension} rank={rank} top_k={top_k} seed={seed}")
    print(f"spans           = hidden={hidden_span} weight={weight_span} codebook={codebook_span} "
          f"head_row_pairing={head_row_pairing}")
    print(f"exact_integers  = {exact_integers} (fp32 accumulation order cannot change any expected value)")
    print(f"unary[0][:4]    = {unary[0][:4].tolist()}")
    print(f"top_ids[0][:4]  = {top_ids[0][:4].tolist()}")
    print(f"edges[0,0,0,:4] = {edges[0, 0, 0, :4].tolist()}")
    print(f"draft_ids[0]    = {draft_ids[0].tolist()}")
    print(f"draft_slots[0]  = {draft_slots[0].tolist()}")
    print(f"tie_boundary    = {boundary_ties} extra candidates tied with the 16th score "
          f"(BF16 logits over {vocab_count} ids)")
    print(f"discriminator_truncation_before_selection = {truncation_discriminator} of {rows * top_k} ids differ "
          f"if the top-K is taken on UNtruncated logits")
    print(f"discriminator_walk_strict_first_max       = {walk_lastmax_diffs} of {rows} columns differ under a "
          f">= walk; {walk_tie_rows} walked rows have a tied maximum")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scale", choices=sorted(SCALES), default="smoke")
    parser.add_argument("--batch", type=int, default=2)
    parser.add_argument("--slots", type=int, default=reference.BLOCK - 1)
    parser.add_argument("--seed", type=lambda text: int(text, 0), default=0x51A4C0DE)
    parser.add_argument("--output", type=Path, default=Path("build/dflash2/dflash2_selector_case.bin"))
    arguments = parser.parse_args()
    return build(arguments.scale, arguments.batch, arguments.slots, arguments.seed, arguments.output)


if __name__ == "__main__":
    raise SystemExit(main())
