#!/usr/bin/env python3
"""Generate model-families/qwen38_27b/smoke_experts.json from a rank pack.

The 27B is DENSE: the routed-expert set a prompt set touches is every
layer's FFN (no routing selectivity), so the deduplicated smoke working set
is one (layer, expert 0) group per pack layer - 64 pairs for the TP4 rank
packs, well inside the small-prompt-set convention's 500-pair cap. The
bytes are what they are: the full nvfp4a16 FFN tier plus the bf16 spine the
loader computes as the complement.

Values are FULL-MODEL (per-rank bytes x tp_degree from the pack header);
tools/devcycle/lane_budget_calc.py shards them back per node. The manifest
is machine-generated by this tool from pack bytes - never hand-edited.

Usage:
  python3 tools/qwen38_27b_smoke_experts.py --pack tp4-rank00.q38sp \
      [--allow-prefix] [--prompt-set qwen38-27b-lane-smoke-v1] \
      [--kv-floor-tokens 512] [--kv-sequences 16] [--workspace-mib 1024] \
      [--output model-families/qwen38_27b/smoke_experts.json]

--allow-prefix accepts a header+directory prefix of the pack (the generator
reads no payload bytes); the header's file_bytes is authoritative.
"""
from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

HEADER_BYTES = 120
ENTRY_BYTES = 56
MAGIC = 0x50533651
FORMAT_VERSION = 3
GLOBAL_LAYER = 0xFFFFFFFF
MTP_LAYER = 0xFFFFFFFE
KIND_FFN_GATE, KIND_FFN_UP, KIND_FFN_DOWN = 5, 6, 7
WEIGHT_BF16, WEIGHT_NVFP4_PACKED = 0, 8
FFN_KINDS = (KIND_FFN_GATE, KIND_FFN_UP, KIND_FFN_DOWN)

# Family geometry (model-families/qwen38_27b/.../spark_qwen38_27b_model.h):
# 64 layers = 48 GDN + 16 full-attention (period 4, phase 3); TP4 shards the
# 4 attention KV heads one-per-rank and the GDN heads 4/12 per rank.
LAYER_COUNT = 64
ATTENTION_PERIOD = 4
FULL_ATTENTION_KV_HEADS = 4
FULL_ATTENTION_HEAD_DIM = 256
GDN_LAYERS = LAYER_COUNT - LAYER_COUNT // ATTENTION_PERIOD
GDN_KEY_HEADS, GDN_VALUE_HEADS = 16, 48
GDN_HEAD_DIM = 128
BF16_BYTES = 2


class GeneratorError(Exception):
    pass


def parse_pack(path: Path, allow_prefix: bool) -> dict:
    needed_probe = HEADER_BYTES
    with path.open("rb") as stream:
        header = stream.read(HEADER_BYTES)
        if len(header) != HEADER_BYTES:
            raise GeneratorError("pack is smaller than the wire header")
        (magic, version, header_bytes, entry_bytes, tensor_count,
         _hidden, layer_count, first_layer, _total_layers) = struct.unpack_from("<9I", header, 0)
        tp_degree, tp_rank = struct.unpack_from("<2I", header, 96)
        directory_offset, file_bytes = struct.unpack_from("<2Q", header, 104)
        if magic != MAGIC or version != FORMAT_VERSION:
            raise GeneratorError(f"not a qwen38_27b stagepack v3: magic={magic:#x} version={version}")
        if header_bytes != HEADER_BYTES or entry_bytes != ENTRY_BYTES:
            raise GeneratorError("stagepack wire sizes drifted from the module format")
        if tp_degree < 1 or tp_rank >= tp_degree:
            raise GeneratorError(f"invalid tp degree/rank {tp_degree}/{tp_rank}")
        directory_bytes = tensor_count * ENTRY_BYTES
        if directory_offset < HEADER_BYTES:
            raise GeneratorError("directory overlaps the header")
        stream.seek(directory_offset)
        directory = stream.read(directory_bytes)
        if len(directory) != directory_bytes:
            raise GeneratorError("truncated pack directory")
        size = path.stat().st_size
        if size != file_bytes and not allow_prefix:
            raise GeneratorError(
                f"pack size {size} differs from header file_bytes {file_bytes} "
                "(use --allow-prefix only for a header+directory prefix)")
        if file_bytes < directory_offset + directory_bytes:
            raise GeneratorError("directory escapes the pack")
    entries = []
    for index in range(tensor_count):
        base = index * ENTRY_BYTES
        kind, layer, weight_format = struct.unpack_from("<3I", directory, base)
        payload_bytes = struct.unpack_from("<Q", directory, base + 32)[0]
        scale_bytes = struct.unpack_from("<Q", directory, base + 48)[0]
        entries.append((kind, layer, weight_format, payload_bytes, scale_bytes))
    return {
        "tensor_count": tensor_count,
        "layer_count": layer_count,
        "first_layer": first_layer,
        "tp_degree": tp_degree,
        "tp_rank": tp_rank,
        "file_bytes": file_bytes,
        "entries": entries,
    }


def codec_name(weight_format: int) -> str:
    if weight_format == WEIGHT_NVFP4_PACKED:
        return "nvfp4a16"
    if weight_format == WEIGHT_BF16:
        return "bf16"
    raise GeneratorError(f"unsupported FFN weight format code {weight_format}")


def ffn_tiers(pack: dict) -> tuple[list[dict], int, str]:
    per_layer: dict[int, dict[int, int]] = {}
    formats: set[int] = set()
    for kind, layer, weight_format, payload_bytes, scale_bytes in pack["entries"]:
        if kind not in FFN_KINDS or layer in (GLOBAL_LAYER, MTP_LAYER):
            continue
        if layer >= LAYER_COUNT:
            raise GeneratorError(f"FFN layer {layer} outside the 64-layer stack")
        per_layer.setdefault(layer, {})[kind] = payload_bytes + scale_bytes
        formats.add(weight_format)
    if len(per_layer) != pack["layer_count"]:
        raise GeneratorError(
            f"FFN covers {len(per_layer)} layers, pack declares {pack['layer_count']}")
    if len(formats) != 1:
        raise GeneratorError(f"mixed FFN weight formats in one pack: {sorted(formats)}")
    codec = codec_name(formats.pop())
    experts = []
    for layer in sorted(per_layer):
        tensors = per_layer[layer]
        if sorted(tensors) != list(FFN_KINDS):
            raise GeneratorError(f"layer {layer} FFN is incomplete: {sorted(tensors)}")
        experts.append({
            "layer": layer,
            "expert": 0,
            "codec": codec,
            "bytes": sum(tensors.values()) * pack["tp_degree"],
        })
    return experts, sum(expert["bytes"] for expert in experts), codec


def kv_floor_bytes(tp_degree: int, tokens: int, sequences: int) -> int:
    """Per-rank paged-KV floor for the smoke context, from geometry:
    full-attention pages (K+V, one KV head per rank at TP4) plus the GDN
    recurrent state (key 4x128 + value 12x128 bf16 per layer per rank)."""
    if FULL_ATTENTION_KV_HEADS % tp_degree:
        raise GeneratorError("attention KV heads do not shard onto the TP degree")
    kv_heads = FULL_ATTENTION_KV_HEADS // tp_degree
    if GDN_KEY_HEADS % tp_degree or GDN_VALUE_HEADS % tp_degree:
        raise GeneratorError("GDN heads do not shard onto the TP degree")
    gdn_key = (GDN_KEY_HEADS // tp_degree) * GDN_HEAD_DIM * BF16_BYTES
    gdn_value = (GDN_VALUE_HEADS // tp_degree) * GDN_HEAD_DIM * BF16_BYTES
    attention = (LAYER_COUNT // ATTENTION_PERIOD) * tokens * kv_heads * \
        FULL_ATTENTION_HEAD_DIM * 2 * BF16_BYTES
    recurrent = GDN_LAYERS * sequences * (gdn_key + gdn_value)
    return attention + recurrent


def build_manifest(pack: dict, prompt_set: str, kv_tokens: int,
                   kv_sequences: int, workspace_mib: int) -> dict:
    experts, expert_bytes, codec = ffn_tiers(pack)
    spine_bytes = (pack["file_bytes"] - expert_bytes // pack["tp_degree"]) * pack["tp_degree"]
    return {
        "schema_version": 1,
        "family": "qwen38_27b",
        "prompt_set": prompt_set,
        "topology": f"TP{pack['tp_degree']}",
        "nodes": pack["tp_degree"],
        "expert_shard": "tp",
        "spine_bytes": spine_bytes,
        "kv_floor_bytes": kv_floor_bytes(pack["tp_degree"], kv_tokens, kv_sequences),
        "workspace_bytes": workspace_mib * 1024 * 1024,
        "experts": experts,
        "provenance": {
            "generator": "tools/qwen38_27b_smoke_experts.py",
            "dense_family_note": (
                "dense SwiGLU FFN: the touched set is every layer; "
                "no prompt-dependence to trim"),
            "ffn_codec": codec,
            "expert_bytes_full_model": expert_bytes,
            "expert_bytes_per_rank": expert_bytes // pack["tp_degree"],
            "spine_bytes_per_rank": pack["file_bytes"] - expert_bytes // pack["tp_degree"],
            "kv_floor": {
                "tokens": kv_tokens,
                "sequences": kv_sequences,
                "formula": "16 attn layers x tokens x (kv_heads/tp) x 256 x 2(K+V) x 2B + 48 GDN layers x sequences x ((16/4)x128 + (48/4)x128) x 2B",
            },
            "workspace_note": "1 GiB conservative estimate; replaced by the measured resident allocation at the M4 smoke",
            "mtp_ffn_note": "the MTP layer's FFN stays in the spine (non-speculative lane)",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--pack", type=Path, required=True)
    parser.add_argument("--allow-prefix", action="store_true")
    parser.add_argument("--prompt-set", default="qwen38-27b-lane-smoke-v1")
    parser.add_argument("--kv-floor-tokens", type=int, default=512)
    parser.add_argument("--kv-sequences", type=int, default=16)
    parser.add_argument("--workspace-mib", type=int, default=1024)
    parser.add_argument("--output", type=Path,
                        default=Path("model-families/qwen38_27b/smoke_experts.json"))
    args = parser.parse_args()
    try:
        pack = parse_pack(args.pack, args.allow_prefix)
        manifest = build_manifest(pack, args.prompt_set, args.kv_floor_tokens,
                                  args.kv_sequences, args.workspace_mib)
    except (GeneratorError, OSError, struct.error) as error:
        print(f"qwen38_27b_smoke_experts: FAIL: {error}", file=sys.stderr)
        return 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(manifest, indent=1) + "\n")
    print(f"{args.output}: {len(manifest['experts'])} layers, codec "
          f"{manifest['provenance']['ffn_codec']}, experts/full-model "
          f"{manifest['provenance']['expert_bytes_full_model']} B, spine/full-model "
          f"{manifest['spine_bytes']} B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
