#!/usr/bin/env python3
"""Hardware topology: validate the JSON, emit the C tables and the runtime
projections.

schema/hardware_topology.schema.json is the contract; examples/topologies/*.json
are the facts. From them this tool derives everything else, so no fact lives
in two places:

  deployment/include/sparkpipe/spark_hardware_topology.h
  deployment/src/spark_hardware_topology_tables.c
      the compile-time tables a deployment loads to learn its nodes, fabrics
      and ranks
  examples/runtime_configs/{ring_debug_single_rail,single_switch_100g,
  dual_switch_dual_rail_future}.json
      the phase-6 runtime configs, now projections of the topology files.
      They predate this tool; they are regenerated byte-identically and any
      hand edit is lost on the next run, so edit the topology file instead.

The schema is checked by a small local walker rather than the jsonschema
package: the gates run on hosts with no third-party Python packages (the same
reason the test suite carries no numpy), and the walker only needs the six
constructs this schema uses. Semantic rules the schema cannot express -
rank contiguity, per-mode port counts, reference existence - are checked in
validate_topology below.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schema" / "hardware_topology.schema.json"
TOPOLOGIES_DIR = ROOT / "examples" / "topologies"
GENERATED_HEADER = ROOT / "deployment" / "include" / "sparkpipe" / "spark_hardware_topology.h"
GENERATED_TABLES = ROOT / "deployment" / "src" / "spark_hardware_topology_tables.c"

GENERATED_NOTICE = (
    "Generated by tools/generate_topology.py from the schema in\n"
    "schema/hardware_topology.schema.json and the topology files under\n"
    "examples/topologies. Do not edit: edit the topology JSON and rerun the\n"
    "generator."
)

# The runtime (ring/transport/fabric_topology.c) knows the three modes by
# these names and validates these exact rail/switch counts; the projection
# must agree with it or the emitted runtime config fails closed at load.
PROJECTION_BY_MODE = {
    "ring": {"mode": "ring_debug_single_rail", "rail_count": 1, "switch_count": 0},
    "single_switch": {"mode": "single_switch_single_rail", "rail_count": 1, "switch_count": 1},
    "dual_switch": {"mode": "dual_switch_dual_rail_future", "rail_count": 2, "switch_count": 2},
}

# Ports a node must cable per mode: a ring runs on one or two direct links
# (two in every deployment here; one is tolerated for a degraded bring-up),
# a single switch takes exactly one port, the dual-switch production end
# state takes both ports, one per switch.
PORT_COUNT_BY_MODE = {"ring": (1, 2), "single_switch": (1, 1), "dual_switch": (2, 2)}

# Topology names become C symbols, so they must be C identifiers.
NAME_PATTERN = re.compile(r"[a-z][a-z0-9_]*$")


class TopologyError(ValueError):
    pass


# --------------------------------------------------------------------------
# schema walker: just the constructs hardware_topology.schema.json uses


def check_schema(value: Any, schema: dict[str, Any], path: str) -> None:
    if "const" in schema and value != schema["const"]:
        raise TopologyError(f"{path}: expected const {schema['const']!r}, got {value!r}")
    if "enum" in schema and value not in schema["enum"]:
        raise TopologyError(f"{path}: {value!r} not in {schema['enum']!r}")
    kind = schema.get("type")
    if kind == "object":
        if not isinstance(value, dict):
            raise TopologyError(f"{path}: expected object")
        for key in schema.get("required", []):
            if key not in value:
                raise TopologyError(f"{path}: missing required key {key!r}")
        properties = schema.get("properties", {})
        if schema.get("additionalProperties") is False:
            extra = set(value) - set(properties)
            if extra:
                raise TopologyError(f"{path}: unexpected keys {sorted(extra)!r}")
        for key, subschema in properties.items():
            if key in value:
                check_schema(value[key], subschema, f"{path}.{key}")
    elif kind == "array":
        if not isinstance(value, list):
            raise TopologyError(f"{path}: expected array")
        if "minItems" in schema and len(value) < schema["minItems"]:
            raise TopologyError(f"{path}: fewer than {schema['minItems']} items")
        if "maxItems" in schema and len(value) > schema["maxItems"]:
            raise TopologyError(f"{path}: more than {schema['maxItems']} items")
        for index, item in enumerate(value):
            check_schema(item, schema["items"], f"{path}[{index}]")
    elif kind == "string":
        if not isinstance(value, str):
            raise TopologyError(f"{path}: expected string")
        if "minLength" in schema and len(value) < schema["minLength"]:
            raise TopologyError(f"{path}: string shorter than {schema['minLength']}")
    elif kind == "integer":
        if not isinstance(value, int) or isinstance(value, bool):
            raise TopologyError(f"{path}: expected integer")
        if "minimum" in schema and value < schema["minimum"]:
            raise TopologyError(f"{path}: {value} below minimum {schema['minimum']}")
        if "maximum" in schema and value > schema["maximum"]:
            raise TopologyError(f"{path}: {value} above maximum {schema['maximum']}")
    elif kind == "boolean":
        if not isinstance(value, bool):
            raise TopologyError(f"{path}: expected boolean")


# --------------------------------------------------------------------------
# semantic validation: what the schema cannot say


def validate_topology(document: dict[str, Any], schema: dict[str, Any], source: str) -> dict[str, Any]:
    check_schema(document, schema, source)
    topology = document["topology"]
    mode = topology["mode"]
    node_types = document["node_types"]
    fabrics = document["fabrics"]
    nodes = document["compute_nodes"]

    if not NAME_PATTERN.match(topology["name"]):
        raise TopologyError(f"{source}: topology name {topology['name']!r} is not a C identifier")

    def duplicates(names: list[str], what: str) -> None:
        seen: set[str] = set()
        for name in names:
            if name in seen:
                raise TopologyError(f"{source}: duplicate {what} {name!r}")
            seen.add(name)

    type_by_name = {entry["name"]: entry for entry in node_types}
    fabric_by_name = {entry["name"]: entry for entry in fabrics}
    duplicates(list(type_by_name), "node type")
    duplicates(list(fabric_by_name), "fabric")
    duplicates([node["name"] for node in nodes], "compute node")

    # Ranks are the ring order and the PP stage order; a gap or a duplicate
    # makes the pipeline skip a stage or run one twice.
    ranks = sorted(node["rank"] for node in nodes)
    if ranks != list(range(len(nodes))):
        raise TopologyError(f"{source}: ranks must be contiguous 0..{len(nodes) - 1}, got {ranks}")

    # Every referenced node type and fabric must exist, and every fabric
    # endpoint must carry a valid, globally unique address: a reused address
    # on two endpoints is a cabling mistake the runtime cannot diagnose.
    used_fabrics: set[str] = set()
    addresses: set[str] = set()
    minimum_ports, maximum_ports = PORT_COUNT_BY_MODE[mode]
    port_counts: set[int] = set()
    for node in nodes:
        where = f"{source}: node {node['name']!r}"
        node_type = type_by_name.get(node["node_type"])
        if node_type is None:
            raise TopologyError(f"{where} references unknown node type {node['node_type']!r}")
        ports = node["ports"]
        port_counts.add(len(ports))
        if not minimum_ports <= len(ports) <= maximum_ports:
            raise TopologyError(
                f"{where} has {len(ports)} ports; mode {mode!r} requires "
                f"{minimum_ports}" + (f"..{maximum_ports}" if maximum_ports != minimum_ports else ""))
        if len(ports) > node_type["network_port_count"]:
            raise TopologyError(
                f"{where} cables {len(ports)} ports but node type "
                f"{node['node_type']!r} has {node_type['network_port_count']}")
        for port in ports:
            fabric = fabric_by_name.get(port["fabric"])
            if fabric is None:
                raise TopologyError(f"{where} references unknown fabric {port['fabric']!r}")
            used_fabrics.add(port["fabric"])
            try:
                address = ipaddress.IPv4Address(port["ipv4"])
            except ipaddress.AddressValueError:
                raise TopologyError(f"{where} has invalid ipv4 {port['ipv4']!r}") from None
            if str(address) in addresses:
                raise TopologyError(f"{where} reuses ipv4 {port['ipv4']!r}")
            addresses.add(str(address))

    if len(port_counts) != 1:
        raise TopologyError(f"{source}: port counts differ across nodes: {sorted(port_counts)}")

    for name in fabric_by_name:
        if name not in used_fabrics:
            raise TopologyError(f"{source}: fabric {name!r} has no endpoints")

    # Fabric kinds must match what the mode means: a ring is direct links, a
    # switched mode is switch ports. The dual-switch end state additionally
    # requires each node's two ports to land on two DIFFERENT switches - both
    # ports on one switch is a single point of failure wearing a dual-rail
    # name.
    kinds = {fabric_by_name[name]["kind"] for name in used_fabrics}
    if mode == "ring":
        if kinds != {"direct"}:
            raise TopologyError(f"{source}: ring mode requires direct fabrics, got {sorted(kinds)}")
    else:
        if kinds != {"switch"}:
            raise TopologyError(f"{source}: mode {mode!r} requires switch fabrics, got {sorted(kinds)}")
        expected_fabrics = 1 if mode == "single_switch" else 2
        if len(used_fabrics) != expected_fabrics:
            raise TopologyError(
                f"{source}: mode {mode!r} uses exactly {expected_fabrics} "
                f"fabric(s), got {sorted(used_fabrics)}")
        if mode == "dual_switch":
            for node in nodes:
                node_fabrics = {port["fabric"] for port in node["ports"]}
                if node_fabrics != used_fabrics:
                    raise TopologyError(
                        f"{source}: node {node['name']!r} must reach both "
                        f"fabrics {sorted(used_fabrics)}, has {sorted(node_fabrics)}")

    # The runtime projection is one flat link speed and MTU, so a topology
    # whose fabrics disagree cannot be projected; refuse it rather than pick.
    speeds = {fabric_by_name[name]["speed_gbps"] for name in used_fabrics}
    mtus = {fabric_by_name[name]["mtu_bytes"] for name in used_fabrics}
    if len(speeds) != 1 or len(mtus) != 1:
        raise TopologyError(f"{source}: used fabrics disagree on speed/mtu; no flat projection exists")

    # The projection spec must agree with the mode, or the generator would be
    # emitting a runtime config the topology contradicts.
    projection = topology["runtime_projection"]
    expected = PROJECTION_BY_MODE[mode]
    if projection["mode"] != expected["mode"]:
        raise TopologyError(
            f"{source}: topology mode {mode!r} projects to {expected['mode']!r}, "
            f"not {projection['mode']!r}")
    link_speed_key = projection.get("link_speed_key", "link_speed_gbps")
    if mode == "dual_switch" and link_speed_key != "link_speed_gbps_per_rail":
        raise TopologyError(f"{source}: dual_switch projection must use link_speed_gbps_per_rail")

    return document


# --------------------------------------------------------------------------
# runtime projection (examples/runtime_configs/*.json, byte-stable)


def render_projection(document: dict[str, Any]) -> tuple[Path, str]:
    topology = document["topology"]
    projection = topology["runtime_projection"]
    mode = topology["mode"]
    fabric_by_name = {entry["name"]: entry for entry in document["fabrics"]}
    used = {port["fabric"] for node in document["compute_nodes"] for port in node["ports"]}
    speed = {fabric_by_name[name]["speed_gbps"] for name in used}.pop()
    mtu = {fabric_by_name[name]["mtu_bytes"] for name in used}.pop()
    expected = PROJECTION_BY_MODE[mode]

    rendered: dict[str, Any] = {
        "schema_version": 1,
        "mode": projection["mode"],
        "rail_count": expected["rail_count"],
        "switch_count": expected["switch_count"],
        "active_ports_per_node": len(document["compute_nodes"][0]["ports"]),
        projection.get("link_speed_key", "link_speed_gbps"): speed,
    }
    if projection.get("include_mtu", True):
        rendered["mtu_bytes"] = mtu
    rendered.update(projection.get("extra", {}))
    rendered["description"] = projection["description"]
    return ROOT / projection["path"], json.dumps(rendered, indent=2) + "\n"


# --------------------------------------------------------------------------
# C tables (deployment/): compile-time facts for the node daemons


def c_block_comment(text: str) -> str:
    lines = text.splitlines()
    return "/* " + lines[0] + "\n" + "\n".join(f" * {line}" for line in lines[1:]) + " */"


def c_symbol(name: str) -> str:
    return f"spark_hardware_topology_{name}"


def render_header(documents: list[dict[str, Any]]) -> str:
    lines = [
        "#ifndef SPARKPIPE_SPARK_HARDWARE_TOPOLOGY_H",
        "#define SPARKPIPE_SPARK_HARDWARE_TOPOLOGY_H",
        "",
        c_block_comment(GENERATED_NOTICE),
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "#define SPARK_HARDWARE_TOPOLOGY_ABI_VERSION 1u",
        "",
        "/* Mirrors the fabric flags in spark_fabric_topology.h so a consumer can",
        "   fill a SparkFabricTopologyConfiguration without re-deriving them. */",
        "#define SPARK_HARDWARE_TOPOLOGY_FLAG_DEBUG_ONLY 0x00000001u",
        "#define SPARK_HARDWARE_TOPOLOGY_FLAG_FUTURE_ONLY 0x00000004u",
        "",
        "typedef enum SparkHardwareTopologyMode",
        "{",
        "\tSPARK_HARDWARE_TOPOLOGY_MODE_INVALID = 0,",
        "\tSPARK_HARDWARE_TOPOLOGY_MODE_RING = 1,",
        "\tSPARK_HARDWARE_TOPOLOGY_MODE_SINGLE_SWITCH = 2,",
        "\tSPARK_HARDWARE_TOPOLOGY_MODE_DUAL_SWITCH = 3",
        "} SparkHardwareTopologyMode;",
        "",
        "typedef enum SparkHardwareFabricKind",
        "{",
        "\tSPARK_HARDWARE_FABRIC_KIND_INVALID = 0,",
        "\tSPARK_HARDWARE_FABRIC_KIND_DIRECT = 1,",
        "\tSPARK_HARDWARE_FABRIC_KIND_SWITCH = 2",
        "} SparkHardwareFabricKind;",
        "",
        "typedef struct SparkHardwareNodeType",
        "{",
        "\tconst char *name;",
        "\tuint32_t memory_bandwidth_gb_s;",
        "\tuint32_t bf16_tflops;",
        "\tuint32_t fp8_tflops;",
        "\tuint32_t fp4_tflops;",
        "\tuint64_t unified_memory_bytes;",
        "\tuint32_t nvme_read_gb_s;",
        "\tuint32_t network_port_count;",
        "} SparkHardwareNodeType;",
        "",
        "typedef struct SparkHardwareFabric",
        "{",
        "\tconst char *name;",
        "\tSparkHardwareFabricKind kind;",
        "\tuint32_t speed_gbps;",
        "\tuint32_t latency_ns;",
        "\tuint32_t mtu_bytes;",
        "} SparkHardwareFabric;",
        "",
        "typedef struct SparkHardwareNodePort",
        "{",
        "\tuint32_t fabric_index;",
        "\tconst char *ipv4;",
        "} SparkHardwareNodePort;",
        "",
        "typedef struct SparkHardwareComputeNode",
        "{",
        "\tconst char *name;",
        "\tuint32_t node_type_index;",
        "\tuint32_t rank;",
        "\tconst char *nvme_device;",
        "\tconst SparkHardwareNodePort *ports;",
        "\tuint32_t port_count;",
        "} SparkHardwareComputeNode;",
        "",
        "/* The flat view ring/transport/fabric_topology.c validates against.",
        "   mtu_bytes is 0 when the runtime config does not pin an MTU. */",
        "typedef struct SparkHardwareTopologyProjection",
        "{",
        "\tuint32_t rail_count;",
        "\tuint32_t switch_count;",
        "\tuint32_t active_port_count;",
        "\tuint32_t link_speed_gbps;",
        "\tuint32_t mtu_bytes;",
        "\tuint32_t flags;",
        "} SparkHardwareTopologyProjection;",
        "",
        "typedef struct SparkHardwareTopology",
        "{",
        "\tconst char *name;",
        "\tSparkHardwareTopologyMode mode;",
        "\tconst SparkHardwareNodeType *node_types;",
        "\tuint32_t node_type_count;",
        "\tconst SparkHardwareFabric *fabrics;",
        "\tuint32_t fabric_count;",
        "\tconst SparkHardwareComputeNode *compute_nodes;",
        "\tuint32_t compute_node_count;",
        "\tSparkHardwareTopologyProjection projection;",
        "} SparkHardwareTopology;",
        "",
        f"#define SPARK_HARDWARE_TOPOLOGY_REGISTRY_COUNT {len(documents)}u",
        "",
    ]
    for document in documents:
        lines.append(
            f"extern const SparkHardwareTopology {c_symbol(document['topology']['name'])};")
    lines += [
        "",
        "extern const SparkHardwareTopology *const "
        "spark_hardware_topology_registry[SPARK_HARDWARE_TOPOLOGY_REGISTRY_COUNT];",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def render_tables(documents: list[dict[str, Any]]) -> str:
    lines = [
        c_block_comment(GENERATED_NOTICE),
        "",
        '#include "sparkpipe/spark_hardware_topology.h"',
        "",
    ]
    mode_enumerator = {
        "ring": "SPARK_HARDWARE_TOPOLOGY_MODE_RING",
        "single_switch": "SPARK_HARDWARE_TOPOLOGY_MODE_SINGLE_SWITCH",
        "dual_switch": "SPARK_HARDWARE_TOPOLOGY_MODE_DUAL_SWITCH",
    }
    kind_enumerator = {
        "direct": "SPARK_HARDWARE_FABRIC_KIND_DIRECT",
        "switch": "SPARK_HARDWARE_FABRIC_KIND_SWITCH",
    }
    for document in documents:
        topology = document["topology"]
        name = topology["name"]
        mode = topology["mode"]
        projection = topology["runtime_projection"]
        symbol = c_symbol(name)
        node_types = document["node_types"]
        fabrics = document["fabrics"]
        nodes = document["compute_nodes"]
        fabric_index = {entry["name"]: index for index, entry in enumerate(fabrics)}
        type_index = {entry["name"]: index for index, entry in enumerate(node_types)}

        lines.append(f"static const SparkHardwareNodeType {symbol}_node_types[] = {{")
        for entry in node_types:
            lines.append(
                f'\t{{ "{entry["name"]}", {entry["memory_bandwidth_gb_s"]}u, '
                f'{entry["bf16_tflops"]}u, {entry["fp8_tflops"]}u, {entry["fp4_tflops"]}u, '
                f'{entry["unified_memory_bytes"]}ull, {entry["nvme_read_gb_s"]}u, '
                f'{entry["network_port_count"]}u }},')
        lines.append("};")
        lines.append("")

        lines.append(f"static const SparkHardwareFabric {symbol}_fabrics[] = {{")
        for entry in fabrics:
            lines.append(
                f'\t{{ "{entry["name"]}", {kind_enumerator[entry["kind"]]}, '
                f'{entry["speed_gbps"]}u, {entry["latency_ns"]}u, {entry["mtu_bytes"]}u }},')
        lines.append("};")
        lines.append("")

        for node in nodes:
            node_symbol = f"{symbol}_node_{node['rank']}_ports"
            lines.append(f"static const SparkHardwareNodePort {node_symbol}[] = {{")
            for port in node["ports"]:
                lines.append(f'\t{{ {fabric_index[port["fabric"]]}u, "{port["ipv4"]}" }},')
            lines.append("};")
        lines.append("")

        lines.append(f"static const SparkHardwareComputeNode {symbol}_compute_nodes[] = {{")
        for node in nodes:
            lines.append(
                f'\t{{ "{node["name"]}", {type_index[node["node_type"]]}u, {node["rank"]}u, '
                f'"{node["nvme_device"]}", {symbol}_node_{node["rank"]}_ports, '
                f'{len(node["ports"])}u }},')
        lines.append("};")
        lines.append("")

        expected = PROJECTION_BY_MODE[mode]
        extra = projection.get("extra", {})
        flags = []
        if extra.get("debug_only", False):
            flags.append("SPARK_HARDWARE_TOPOLOGY_FLAG_DEBUG_ONLY")
        if extra.get("enabled", True) is False:
            flags.append("SPARK_HARDWARE_TOPOLOGY_FLAG_FUTURE_ONLY")
        flags_value = " | ".join(flags) if flags else "0u"
        speed = {entry["speed_gbps"] for entry in fabrics}.pop()
        mtu = {entry["mtu_bytes"] for entry in fabrics}.pop() if projection.get("include_mtu", True) else 0
        lines.append(f"const SparkHardwareTopology {symbol} = {{")
        lines.append(f'\t"{name}",')
        lines.append(f"\t{mode_enumerator[mode]},")
        lines.append(f"\t{symbol}_node_types, {len(node_types)}u,")
        lines.append(f"\t{symbol}_fabrics, {len(fabrics)}u,")
        lines.append(f"\t{symbol}_compute_nodes, {len(nodes)}u,")
        lines.append(
            f'\t{{ {expected["rail_count"]}u, {expected["switch_count"]}u, '
            f'{len(nodes[0]["ports"])}u, {speed}u, {mtu}u, {flags_value} }}')
        lines.append("};")
        lines.append("")

    lines.append("const SparkHardwareTopology *const "
                 "spark_hardware_topology_registry[SPARK_HARDWARE_TOPOLOGY_REGISTRY_COUNT] = {")
    for document in documents:
        lines.append(f"\t&{c_symbol(document['topology']['name'])},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# driver


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def load_validated_topologies(paths: list[Path]) -> list[dict[str, Any]]:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    documents = []
    for path in paths:
        document = json.loads(path.read_text(encoding="utf-8"))
        validate_topology(document, schema, str(path.relative_to(ROOT)))
        documents.append(document)
    names = [document["topology"]["name"] for document in documents]
    if len(set(names)) != len(names):
        raise TopologyError(f"topology names must be unique across files: {sorted(names)}")
    return documents


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if any generated file is stale instead of writing it")
    parser.add_argument("--topology", type=Path, action="append",
                        help="one topology file; defaults to every file in examples/topologies/")
    args = parser.parse_args()

    paths = args.topology or sorted(TOPOLOGIES_DIR.glob("*.json"))
    try:
        documents = load_validated_topologies(paths)
    except TopologyError as error:
        print(f"FAIL {error}")
        return 1

    outputs = {
        GENERATED_HEADER: render_header(documents),
        GENERATED_TABLES: render_tables(documents),
    }
    for document in documents:
        path, content = render_projection(document)
        outputs[path] = content

    stale = [str(path.relative_to(ROOT))
             for path, content in outputs.items()
             if not write_or_check(path, content, args.check)]
    if stale:
        print("stale generated hardware topology files:")
        for path in stale:
            print(path)
        return 1
    action = "fresh" if args.check else "written"
    print(f"hardware topology: {len(documents)} topologies, "
          f"{len(outputs)} generated files {action}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
