#pragma once

#include <stdint.h>

#include "common/common_stagepack_format_ext.h"

#define SPARK_LLM_HIDDEN_DIMENSION 2560u
#define SPARK_LLM_LAYER_COUNT 48u
#define SPARK_LLM_VOCAB_COUNT 248320u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT SPARK_LLM_VOCAB_COUNT
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS 262144u
#define SPARK_LLM_RMS_NORM_EPSILON 1e-06f
#ifndef SPARK_LLM_MTP_LAYER_COUNT
#define SPARK_LLM_MTP_LAYER_COUNT 1u
#endif

#define SPARK_LLM_ATTN_HEAD_COUNT 24u
#define SPARK_LLM_KV_HEAD_COUNT 2u
#define SPARK_LLM_HEAD_DIMENSION 256u
#define SPARK_LLM_ATTN_QUERY_HEAD_COUNT SPARK_LLM_ATTN_HEAD_COUNT
#define SPARK_LLM_ATTN_KV_HEAD_COUNT SPARK_LLM_KV_HEAD_COUNT
#define SPARK_LLM_ATTN_HEAD_DIMENSION SPARK_LLM_HEAD_DIMENSION
#define SPARK_LLM_ROPE_DIMENSION 64u
#define SPARK_LLM_ROPE_THETA 10000000.0f
#define SPARK_LLM_ATTN_QUERY_DIMENSION \
	(SPARK_LLM_ATTN_QUERY_HEAD_COUNT * SPARK_LLM_ATTN_HEAD_DIMENSION)
#define SPARK_LLM_ATTN_KV_DIMENSION \
	(SPARK_LLM_ATTN_KV_HEAD_COUNT * SPARK_LLM_ATTN_HEAD_DIMENSION)
#define SPARK_LLM_ATTN_CACHE_TOKEN_ELEMENTS \
	(2u * SPARK_LLM_ATTN_KV_DIMENSION)
#define SPARK_LLM_ATTN_KV_SHARD_COUNT(tp_degree) \
	(((tp_degree) < SPARK_LLM_ATTN_KV_HEAD_COUNT) \
		? (uint32_t)(tp_degree) \
		: SPARK_LLM_ATTN_KV_HEAD_COUNT)
#define SPARK_LLM_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_ATTN_KV_HEAD_COUNT \
		/ SPARK_LLM_ATTN_KV_SHARD_COUNT(tp_degree))
#define SPARK_LLM_ATTN_RANK_KV_HEAD_BASE(tp_degree, tp_rank) \
	((((uint32_t)(tp_rank)) * SPARK_LLM_ATTN_KV_HEAD_COUNT) \
		/ (uint32_t)(tp_degree))
#define SPARK_LLM_ATTN_LOCAL_KV_DIMENSION(tp_degree) \
	(SPARK_LLM_ATTN_LOCAL_KV_HEAD_COUNT(tp_degree) \
		* SPARK_LLM_ATTN_HEAD_DIMENSION)
#define SPARK_LLM_ATTN_HEADS_PER_CTA 2u

#define SPARK_LLM_ATTN_PERIOD 4u
#define SPARK_LLM_FULL_ATTENTION_PHASE 3u
#define SPARK_LLM_LAYER_IS_GDN(layer_index) \
	(((layer_index) % SPARK_LLM_ATTN_PERIOD) != SPARK_LLM_FULL_ATTENTION_PHASE)
#define SPARK_LLM_GDN_LAYER_COUNT 36u
#define SPARK_LLM_FULL_ATTENTION_LAYER_COUNT 12u

#define SPARK_LLM_GDN_KEY_HEAD_COUNT 16u
#define SPARK_LLM_GDN_VALUE_HEAD_COUNT 48u
#define SPARK_LLM_GDN_HEAD_KEY_DIMENSION 128u
#define SPARK_LLM_GDN_HEAD_VALUE_DIMENSION 128u
#define SPARK_LLM_GDN_VALUE_HEADS_PER_KEY_HEAD \
	(SPARK_LLM_GDN_VALUE_HEAD_COUNT / SPARK_LLM_GDN_KEY_HEAD_COUNT)
#define SPARK_LLM_GDN_LOCAL_KEY_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_GDN_KEY_HEAD_COUNT / (tp_degree))
#define SPARK_LLM_GDN_LOCAL_VALUE_HEAD_COUNT(tp_degree) \
	(SPARK_LLM_GDN_VALUE_HEAD_COUNT / (tp_degree))
#define SPARK_LLM_GDN_LOCAL_QK_DIMENSION(tp_degree) \
	(SPARK_LLM_GDN_LOCAL_KEY_HEAD_COUNT(tp_degree) \
		* SPARK_LLM_GDN_HEAD_KEY_DIMENSION)
#define SPARK_LLM_GDN_LOCAL_VALUE_DIMENSION(tp_degree) \
	(SPARK_LLM_GDN_LOCAL_VALUE_HEAD_COUNT(tp_degree) \
		* SPARK_LLM_GDN_HEAD_VALUE_DIMENSION)
#define SPARK_LLM_GDN_LOCAL_CONV_CHANNELS(tp_degree) \
	((2u * SPARK_LLM_GDN_LOCAL_QK_DIMENSION(tp_degree)) \
		+ SPARK_LLM_GDN_LOCAL_VALUE_DIMENSION(tp_degree))
#define SPARK_LLM_GDN_CONV_KERNEL 4u
#define SPARK_LLM_GDN_QK_DIMENSION \
	(SPARK_LLM_GDN_KEY_HEAD_COUNT * SPARK_LLM_GDN_HEAD_KEY_DIMENSION)
#define SPARK_LLM_GDN_VALUE_DIMENSION \
	(SPARK_LLM_GDN_VALUE_HEAD_COUNT * SPARK_LLM_GDN_HEAD_VALUE_DIMENSION)
#define SPARK_LLM_GDN_CONV_CHANNELS \
	((2u * SPARK_LLM_GDN_QK_DIMENSION) + SPARK_LLM_GDN_VALUE_DIMENSION)
#define SPARK_LLM_GDN_CONV_TAIL_COLUMNS (SPARK_LLM_GDN_CONV_KERNEL - 1u)
#define SPARK_LLM_GDN_CHUNK_TOKENS 64u

#define SPARK_LLM_ROUTED_EXPERT_COUNT 512u
#define SPARK_LLM_EXPERTS_PER_TOKEN 10u
#define SPARK_LLM_SHARED_EXPERT_COUNT 1u
#define SPARK_LLM_EXPERT_INTERMEDIATE_DIMENSION 640u
#define SPARK_LLM_SHARED_EXPERT_INTERMEDIATE_DIMENSION 640u
#define SPARK_LLM_MXFP4_GROUP_SIZE 32u
#define SPARK_LLM_FP8_BLOCK 128u
#define SPARK_LLM_SWIGLU_LIMIT 10.0f
#define SPARK_LLM_ROUTER_SORT_CAPACITY 512u

#define SPARK_LLM_HC_STREAM_COUNT 4u
#define SPARK_LLM_HC_LOWRANK_DIMENSION 320u
#define SPARK_LLM_HC_STREAM_WIDTH \
	(SPARK_LLM_HC_STREAM_COUNT * SPARK_LLM_HIDDEN_DIMENSION)

#define SPARK_LLM_INDEXER_HEAD_COUNT 4u
#define SPARK_LLM_INDEXER_KV_HEAD_COUNT 1u
#define SPARK_LLM_INDEXER_HEAD_DIMENSION 128u
#define SPARK_LLM_INDEXER_BUDGET 2048u
#define SPARK_LLM_INDEXER_COMPRESS_RATIO 4u

#define SPARK_LLM_PLE_LAYER_INDEX 1u
#define SPARK_LLM_PLE_NGRAM_SIZE 3u
#define SPARK_LLM_PLE_HEADS_PER_NGRAM 8u
#define SPARK_LLM_PLE_NGRAM_HEAD_COUNT \
	(SPARK_LLM_PLE_HEADS_PER_NGRAM * \
	 (SPARK_LLM_PLE_NGRAM_SIZE - 1u))
#define SPARK_LLM_PLE_NGRAM_HEAD_DIMENSION \
	(SPARK_LLM_PLE_EMBED_DIMENSION / \
	 SPARK_LLM_PLE_NGRAM_HEAD_COUNT)
#define SPARK_LLM_PLE_CONTEXT_LENGTH \
	(SPARK_LLM_PLE_NGRAM_SIZE - 1u)
#define SPARK_LLM_PLE_SHARD_COUNT 128u
#define SPARK_LLM_PLE_EMBED_DIMENSION SPARK_LLM_HIDDEN_DIMENSION
#define SPARK_LLM_PLE_CONV_KERNEL 4u
#define SPARK_LLM_PLE_CONV_DILATION SPARK_LLM_PLE_NGRAM_SIZE
#define SPARK_LLM_PLE_CONV_TAIL_COLUMNS \
	((SPARK_LLM_PLE_CONV_KERNEL - 1u) * \
	 SPARK_LLM_PLE_CONV_DILATION)
#define SPARK_LLM_PLE_NGRAM_ROW_COUNT 320001536u
#define SPARK_LLM_EOS_TOKEN_ID 248044u

#define SPARK_LLM_BF16_ELEMENT_BYTES 2u
#define SPARK_LLM_HIDDEN_BF16_BYTES \
	(SPARK_LLM_HIDDEN_DIMENSION * SPARK_LLM_BF16_ELEMENT_BYTES)

#define SPARK_LLM_NODE_CONTEXT_ABI_VERSION 1u
#define SPARK_LLM_FRAME_CONTEXT_ABI_VERSION 3u
#define SPARK_LLM_PREFILL_FRAME_VIEW_ABI_VERSION 1u
#define SPARK_LLM_MTP_DRAFT_VIEW_ABI_VERSION 1u
#define SPARK_LLM_GDN_SNAPSHOT_VIEW_ABI_VERSION 1u
#define SPARK_LLM_MAX_MTP_DRAFT_TOKENS 8u
#define SPARK_LLM_MAX_GDN_SNAPSHOT_SLOTS 8u
#define SPARK_LLM_GDN_STATE_POOL_ABI_VERSION 1u
#define SPARK_LLM_KV_BLOCK_TABLE_ABI_VERSION 1u
#define SPARK_LLM_LINEAR_VIEW_ABI_VERSION 1u
#define SPARK_LLM_DECODE_BATCH_VIEW_ABI_VERSION 1u
#define SPARK_LLM_MAX_STAGE_COUNT 32u
#define SPARK_LLM_HEAD_SCREEN_CAP 4096u
#define SPARK_LLM_MAX_PIPELINE_SLOT_COUNT 4u
#define SPARK_LLM_MAX_ACTIVE_SEQUENCE_COUNT 512u
#ifndef SPARK_LLM_KV_BLOCK_TOKENS
#define SPARK_LLM_KV_BLOCK_TOKENS 64u
#endif
#define SPARK_LLM_KV_STAGING_RECORDS 16u
#define SPARK_LLM_KV_POLL_BOUND 10000u
#define SPARK_LLM_KV_MAX_BLOCKS_PER_LANE 4096u
#define SPARK_LLM_KV_RESTORE_PRIORITY_IMMEDIATE 0u
#define SPARK_LLM_KV_RESTORE_PRIORITY_SPECULATIVE 1u
#define SPARK_LLM_KV_BATCH_IDLE 0u
#define SPARK_LLM_KV_BATCH_SUBMITTED 1u
#define SPARK_LLM_KV_BATCH_READY 2u
#define SPARK_LLM_INVALID_TOKEN_ID UINT32_MAX
#define SPARK_LLM_NO_BLOCK 0xffffffffu

#define SPARK_LLM_FRAME_CONTEXT_FLAG_KV_BLOCK_TABLE 0x00000001u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_DECODE_BATCH_VIEW 0x00000002u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_HIDDEN_INPUT_TRANSPORT 0x00000004u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_HIDDEN_OUTPUT_TRANSPORT 0x00000008u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_PREFILL_FRAME_VIEW 0x00000010u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_MTP_DRAFT_AFTER 0x00000020u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_SPECULATIVE_VERIFY 0x00000040u
#define SPARK_LLM_FRAME_CONTEXT_FLAG_GDN_RESTORE_FIRST 0x00000080u

#define SPARK_LLM_STAGEPACK_MAGIC 0x50533451u
#define SPARK_LLM_STAGEPACK_FORMAT_VERSION 2u
#define SPARK_LLM_STAGEPACK_GLOBAL_LAYER SPARK_STAGEPACK_LAYER_GLOBAL
#define SPARK_LLM_STAGEPACK_MTP_LAYER SPARK_STAGEPACK_LAYER_MTP
#define SPARK_LLM_RESIDENT_DECODE_STAGE_LAYER_COUNT SPARK_LLM_LAYER_COUNT
#define SPARK_LLM_RESIDENT_DECODE_STAGE_LINEAR_VIEW_ABI_VERSION SPARK_LLM_LINEAR_VIEW_ABI_VERSION
#define SPARK_LLM_STAGEPACK_TENSOR_EMBEDDING 0u
#define SPARK_LLM_STAGEPACK_TENSOR_FINAL_NORM 1u
#define SPARK_LLM_STAGEPACK_TENSOR_LM_HEAD 2u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_QUERY 22u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_KEY 23u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_VALUE 24u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_OUTPUT 25u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_QUERY_NORM 26u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_KEY_NORM 27u
#define SPARK_LLM_STAGEPACK_TENSOR_MTP_FC 28u
#define SPARK_LLM_STAGEPACK_TENSOR_MTP_EMBED_NORM 29u
#define SPARK_LLM_STAGEPACK_TENSOR_MTP_HIDDEN_NORM 30u
#define SPARK_LLM_STAGEPACK_TENSOR_MTP_FINAL_NORM 31u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_HC_DOWN 32u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_HC_UP 33u
#define SPARK_LLM_STAGEPACK_TENSOR_ATTN_HC_INJECT 34u
#define SPARK_LLM_STAGEPACK_TENSOR_MLP_HC_DOWN 35u
#define SPARK_LLM_STAGEPACK_TENSOR_MLP_HC_UP 36u
#define SPARK_LLM_STAGEPACK_TENSOR_MLP_HC_INJECT 37u
#define SPARK_LLM_STAGEPACK_TENSOR_INDEXER_QK 38u
#define SPARK_LLM_STAGEPACK_TENSOR_INDEXER_Q_NORM 39u
#define SPARK_LLM_STAGEPACK_TENSOR_INDEXER_K_NORM 40u
#define SPARK_LLM_STAGEPACK_TENSOR_MIXER_DOWN 41u
#define SPARK_LLM_STAGEPACK_TENSOR_MIXER_UP 42u
#define SPARK_LLM_STAGEPACK_TENSOR_MTP_MIXER_DOWN 43u
#define SPARK_LLM_STAGEPACK_TENSOR_MTP_MIXER_UP 44u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_KEY 45u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_VALUE 46u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_NORM_KEY 47u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_NORM_QUERY 48u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_NORM_CONV 49u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_CONV 50u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_MULTIPLIERS 51u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_HEAD_VOCABS 52u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_HEAD_OFFSETS 53u
#define SPARK_LLM_STAGEPACK_TENSOR_PLE_NGRAM 54u

_Static_assert(SPARK_LLM_GDN_LAYER_COUNT + SPARK_LLM_FULL_ATTENTION_LAYER_COUNT == SPARK_LLM_LAYER_COUNT,"layer split must cover the stack");
_Static_assert((SPARK_LLM_LAYER_COUNT % SPARK_LLM_ATTN_PERIOD) == 0u,"layer count must be whole periods");
_Static_assert(SPARK_LLM_GDN_LAYER_COUNT == (SPARK_LLM_LAYER_COUNT / SPARK_LLM_ATTN_PERIOD) * (SPARK_LLM_ATTN_PERIOD - 1u),"gdn count must match the 3:1 period");
_Static_assert((SPARK_LLM_GDN_VALUE_HEAD_COUNT % SPARK_LLM_GDN_KEY_HEAD_COUNT) == 0u,"value heads must group evenly onto key heads");
_Static_assert(SPARK_LLM_GDN_VALUE_HEADS_PER_KEY_HEAD == 3u,"grouped-value ratio is three per config (48 value heads over 16 key heads)");
_Static_assert((SPARK_LLM_ATTN_QUERY_HEAD_COUNT % SPARK_LLM_ATTN_KV_HEAD_COUNT) == 0u,"query heads must group evenly onto kv heads");
_Static_assert(SPARK_LLM_ROPE_DIMENSION == SPARK_LLM_ATTN_HEAD_DIMENSION / 4u,"rope covers a quarter of the head");
_Static_assert((SPARK_LLM_ROPE_DIMENSION % 2u) == 0u,"rope dimension must pair");
_Static_assert(SPARK_LLM_GDN_CONV_CHANNELS == 10240u,"conv width is q+k+v concatenated");
_Static_assert(SPARK_LLM_GDN_QK_DIMENSION == 2048u && SPARK_LLM_GDN_VALUE_DIMENSION == 6144u,"gdn projection widths per config");
_Static_assert(SPARK_LLM_ATTN_QUERY_DIMENSION == 6144u && SPARK_LLM_ATTN_KV_DIMENSION == 512u,"attention projection widths per config");
_Static_assert(SPARK_LLM_MXFP4_GROUP_SIZE == 32u,"mxfp4 group size must be 32");
_Static_assert((SPARK_LLM_EXPERT_INTERMEDIATE_DIMENSION % SPARK_LLM_MXFP4_GROUP_SIZE) == 0u,"expert intermediate must tile for mxfp4 groups");
_Static_assert((SPARK_LLM_HIDDEN_DIMENSION % SPARK_LLM_MXFP4_GROUP_SIZE) == 0u,"hidden must tile for mxfp4 groups");
_Static_assert(SPARK_LLM_ROUTED_EXPERT_COUNT <= SPARK_LLM_ROUTER_SORT_CAPACITY,"expert count exceeds router sort capacity");

static const SparkStagePackFamilySpec SparkLlmStagePackFamilySpec =
{
	.magic = SPARK_LLM_STAGEPACK_MAGIC,
	.format_version = SPARK_LLM_STAGEPACK_FORMAT_VERSION,
	.hidden_dimension = SPARK_LLM_HIDDEN_DIMENSION,
	.output_vocab_count = SPARK_LLM_OUTPUT_VOCAB_COUNT,
	.layer_count = SPARK_LLM_LAYER_COUNT,
	.attention_period = SPARK_LLM_ATTN_PERIOD,
	.full_attention_phase = SPARK_LLM_FULL_ATTENTION_PHASE,
	.gdn_key_head_count = SPARK_LLM_GDN_KEY_HEAD_COUNT,
	.gdn_value_head_count = SPARK_LLM_GDN_VALUE_HEAD_COUNT,
	.gdn_head_key_dimension = SPARK_LLM_GDN_HEAD_KEY_DIMENSION,
	.gdn_head_value_dimension = SPARK_LLM_GDN_HEAD_VALUE_DIMENSION,
	.gdn_conv_kernel = SPARK_LLM_GDN_CONV_KERNEL,
	.attn_query_head_count = SPARK_LLM_ATTN_QUERY_HEAD_COUNT,
	.attn_kv_head_count = SPARK_LLM_ATTN_KV_HEAD_COUNT,
	.attn_head_dimension = SPARK_LLM_ATTN_HEAD_DIMENSION,
	.attn_rope_dimension = SPARK_LLM_ROPE_DIMENSION,
	.routed_expert_count = SPARK_LLM_ROUTED_EXPERT_COUNT,
	.experts_per_token = SPARK_LLM_EXPERTS_PER_TOKEN,
	.expert_intermediate_dimension = SPARK_LLM_EXPERT_INTERMEDIATE_DIMENSION,
	.mxfp4_group_size = SPARK_LLM_MXFP4_GROUP_SIZE,
	.fp8_block = SPARK_LLM_FP8_BLOCK,
	.bf16_element_bytes = SPARK_LLM_BF16_ELEMENT_BYTES,
	.mtp_layer_count = SPARK_LLM_MTP_LAYER_COUNT,
	.hc_stream_count = SPARK_LLM_HC_STREAM_COUNT,
	.hc_lowrank_dimension = SPARK_LLM_HC_LOWRANK_DIMENSION,
	.indexer_head_count = SPARK_LLM_INDEXER_HEAD_COUNT,
	.indexer_kv_head_count = SPARK_LLM_INDEXER_KV_HEAD_COUNT,
	.indexer_head_dimension = SPARK_LLM_INDEXER_HEAD_DIMENSION,
	.ple_layer_index = SPARK_LLM_PLE_LAYER_INDEX,
	.ple_layer_class = 4u,
	.ple_ngram_size = SPARK_LLM_PLE_NGRAM_SIZE,
	.ple_heads_per_ngram = SPARK_LLM_PLE_HEADS_PER_NGRAM,
	.ple_embed_dimension = SPARK_LLM_PLE_EMBED_DIMENSION,
	.ple_conv_kernel = SPARK_LLM_PLE_CONV_KERNEL,
	.ple_ngram_row_count = SPARK_LLM_PLE_NGRAM_ROW_COUNT,
	.layer_tensor_count = 16u,
	.gdn_layer_tensor_count = 9u,
	.attn_layer_tensor_count = 9u,
	.tail_tensor_count_no_mtp = 4u,
	.tail_tensor_count_mtp = 35u,
	.first_stage_tensor_count = 1u,
	.last_stage_tensor_count = 1u
};

static const SparkStagePackKindRow SparkLlmStagePackKindRows[] =
{
	{SPARK_LLM_STAGEPACK_TENSOR_EMBEDDING,SPARK_STAGEPACK_ROLE_EMBEDDING},
	{SPARK_LLM_STAGEPACK_TENSOR_FINAL_NORM,SPARK_STAGEPACK_ROLE_FINAL_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_LM_HEAD,SPARK_STAGEPACK_ROLE_LM_HEAD},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_QUERY,SPARK_STAGEPACK_ROLE_ATTN_QUERY},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_KEY,SPARK_STAGEPACK_ROLE_ATTN_KEY},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_VALUE,SPARK_STAGEPACK_ROLE_ATTN_VALUE},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_OUTPUT,SPARK_STAGEPACK_ROLE_ATTN_OUTPUT},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_QUERY_NORM,SPARK_STAGEPACK_ROLE_ATTN_QUERY_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_KEY_NORM,SPARK_STAGEPACK_ROLE_ATTN_KEY_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_MTP_FC,SPARK_STAGEPACK_ROLE_MTP_FC},
	{SPARK_LLM_STAGEPACK_TENSOR_MTP_EMBED_NORM,SPARK_STAGEPACK_ROLE_MTP_EMBED_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_MTP_HIDDEN_NORM,SPARK_STAGEPACK_ROLE_MTP_HIDDEN_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_MTP_FINAL_NORM,SPARK_STAGEPACK_ROLE_MTP_FINAL_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_HC_DOWN,SPARK_STAGEPACK_ROLE_HC_DOWN},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_HC_UP,SPARK_STAGEPACK_ROLE_HC_UP},
	{SPARK_LLM_STAGEPACK_TENSOR_ATTN_HC_INJECT,SPARK_STAGEPACK_ROLE_HC_INJECT},
	{SPARK_LLM_STAGEPACK_TENSOR_MLP_HC_DOWN,SPARK_STAGEPACK_ROLE_HC_DOWN},
	{SPARK_LLM_STAGEPACK_TENSOR_MLP_HC_UP,SPARK_STAGEPACK_ROLE_HC_UP},
	{SPARK_LLM_STAGEPACK_TENSOR_MLP_HC_INJECT,SPARK_STAGEPACK_ROLE_HC_INJECT},
	{SPARK_LLM_STAGEPACK_TENSOR_INDEXER_QK,SPARK_STAGEPACK_ROLE_INDEXER_QK},
	{SPARK_LLM_STAGEPACK_TENSOR_INDEXER_Q_NORM,SPARK_STAGEPACK_ROLE_INDEXER_Q_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_INDEXER_K_NORM,SPARK_STAGEPACK_ROLE_INDEXER_K_NORM},
	{SPARK_LLM_STAGEPACK_TENSOR_MIXER_DOWN,SPARK_STAGEPACK_ROLE_MIXER_DOWN},
	{SPARK_LLM_STAGEPACK_TENSOR_MIXER_UP,SPARK_STAGEPACK_ROLE_MIXER_UP},
	{SPARK_LLM_STAGEPACK_TENSOR_MTP_MIXER_DOWN,SPARK_STAGEPACK_ROLE_MIXER_DOWN},
	{SPARK_LLM_STAGEPACK_TENSOR_MTP_MIXER_UP,SPARK_STAGEPACK_ROLE_MIXER_UP},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_KEY,SPARK_STAGEPACK_ROLE_PLE_KEY},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_VALUE,SPARK_STAGEPACK_ROLE_PLE_VALUE},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_NORM_KEY,SPARK_STAGEPACK_ROLE_PLE_NORM_KEY},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_NORM_QUERY,SPARK_STAGEPACK_ROLE_PLE_NORM_QUERY},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_NORM_CONV,SPARK_STAGEPACK_ROLE_PLE_NORM_CONV},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_CONV,SPARK_STAGEPACK_ROLE_PLE_CONV},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_MULTIPLIERS,SPARK_STAGEPACK_ROLE_PLE_MULTIPLIERS},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_HEAD_VOCABS,SPARK_STAGEPACK_ROLE_PLE_HEAD_VOCABS},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_HEAD_OFFSETS,SPARK_STAGEPACK_ROLE_PLE_HEAD_OFFSETS},
	{SPARK_LLM_STAGEPACK_TENSOR_PLE_NGRAM,SPARK_STAGEPACK_ROLE_PLE_NGRAM}
};

static const SparkStagePackKindTable SparkLlmStagePackKindTable =
{
	.rows = SparkLlmStagePackKindRows,
	.row_count = sizeof(SparkLlmStagePackKindRows) / sizeof(SparkLlmStagePackKindRows[0])
};
