#pragma once

#include <stdint.h>

#define SPARK_LLM_FAMILY_TAG "qwen4_flash"
#define SPARK_LLM_HIDDEN_DIMENSION 2560u
#define SPARK_LLM_LAYER_COUNT 48u
#define SPARK_LLM_VOCAB_COUNT 248320u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT SPARK_LLM_VOCAB_COUNT
#define SPARK_LLM_RMS_NORM_EPSILON 1e-06f

#define SPARK_LLM_ATTN_HEAD_COUNT 24u
#define SPARK_LLM_KV_HEAD_COUNT 2u
#define SPARK_LLM_HEAD_DIMENSION 256u
#define SPARK_LLM_ROPE_DIMENSION 64u
#define SPARK_LLM_ROPE_THETA 10000000.0f
#define SPARK_LLM_ATTN_PERIOD 4u
#define SPARK_LLM_FULL_ATTENTION_PHASE 3u

#define SPARK_LLM_GDN_KEY_HEAD_COUNT 16u
#define SPARK_LLM_GDN_VALUE_HEAD_COUNT 48u
#define SPARK_LLM_GDN_HEAD_KEY_DIMENSION 128u
#define SPARK_LLM_GDN_HEAD_VALUE_DIMENSION 128u
#define SPARK_LLM_GDN_CONV_KERNEL 4u

#define SPARK_LLM_ROUTED_EXPERT_COUNT 512u
#define SPARK_LLM_EXPERTS_PER_TOKEN 10u
#define SPARK_LLM_EXPERT_INTERMEDIATE_DIMENSION 640u
#define SPARK_LLM_SWIGLU_LIMIT 10.0f

#define SPARK_LLM_HC_STREAM_COUNT 4u
#define SPARK_LLM_HC_LOWRANK_DIMENSION 320u

#define SPARK_LLM_PLE_LAYER_INDEX 1u
#define SPARK_LLM_EOS_TOKEN_ID 248044u
