#!/usr/bin/env python3
"""Lane memory budget calculator.

Reads a family smoke-expert manifest and prints the per-node lane budget
(total MiB and device MiB) for the lane's topology, checked against the
verified 8-lane fleet envelope from PR #1082.

Manifest convention (one per family, PR'd, machine-generated by the
family's expert-manifest tooling - never hand-edited):

  model-families/<family>/smoke_experts.json
  {
    "schema_version": 1,
    "family": "glm53flash",
    "prompt_set": "smoke-standard-v1",        # the recorded prompt set id
    "topology": "TP16",
    "nodes": 16,
    "expert_shard": "tp",                     # tp = sharded across nodes, replicated = every node
    "spine_bytes": ...,                       # full-resolution spine (quality law), full model
    "kv_floor_bytes": ...,                    # KV for the smoke context floor
    "workspace_bytes": ...,                   # activations/graph workspace
    "experts": [ {"layer": L, "expert": E, "codec": "fp8_e4m3", "bytes": B}, ... ]
  }

The experts list is the deduplicated set of routed experts the recorded
smoke prompt set actually touches - that is the batch-preload working set
for the < 5 s cold-launch goal.
"""

import argparse
import json
import math
import sys

MIB = 1024 * 1024
FLEET_LANE_ENVELOPE_MIB = 78336   # verified 8-lane total reservation per Spark (PR #1082)
FLEET_HEADROOM_MIB = 8192         # queue headroom per Spark, operator-level
DEFAULT_TOTAL_MIB = 9792          # envelope / 8
DEFAULT_DEVICE_MIB = 6400         # measured 8xGLM: 48346 MiB device / 8 + margin
MARGIN = 1.08                     # CUDA context, allocator slop, manifest drift


def fail(msg):
    print(f"lane_budget_calc: FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", help="path to smoke_experts.json")
    ap.add_argument("--lane-total-mib", type=int, default=DEFAULT_TOTAL_MIB,
                    help="lane's allocated total budget (default %(default)s)")
    args = ap.parse_args()

    try:
        m = json.load(open(args.manifest))
    except (OSError, ValueError) as e:
        fail(f"cannot read manifest: {e}")

    for key in ("family", "nodes", "expert_shard", "spine_bytes", "kv_floor_bytes",
                "workspace_bytes", "experts"):
        if key not in m:
            fail(f"missing field {key!r}")

    nodes = m["nodes"]
    if nodes < 1 or nodes > 16:
        fail(f"nodes {nodes} outside 1..16")

    experts = m["experts"]
    seen = set()
    expert_bytes = 0
    for e in experts:
        k = (e["layer"], e["expert"])
        if k in seen:
            fail(f"duplicate expert entry {k} - the manifest must be deduplicated")
        seen.add(k)
        if e["bytes"] <= 0:
            fail(f"expert {k} has bytes={e['bytes']}")
        expert_bytes += e["bytes"]

    if m["expert_shard"] == "tp":
        per_node_experts = math.ceil(expert_bytes / nodes)
    elif m["expert_shard"] == "replicated":
        per_node_experts = expert_bytes
    else:
        fail(f"expert_shard {m['expert_shard']!r} is not tp or replicated")

    spine = m["spine_bytes"]
    if m["expert_shard"] == "tp":
        spine = math.ceil(spine / nodes)

    per_node_raw = spine + per_node_experts + m["kv_floor_bytes"] + m["workspace_bytes"]
    per_node = math.ceil(per_node_raw * MARGIN / MIB)

    device_mib = per_node
    total_mib = math.ceil(per_node * 1.5)  # host-side cgroup gets the difference (queue contract)
    total_mib = max(total_mib, device_mib + 1024)

    fleet_sum = device_mib * 8
    verdict = "OK"
    if fleet_sum > FLEET_LANE_ENVELOPE_MIB:
        verdict = (f"EXCEEDS ENVELOPE: 8 lanes x {device_mib} MiB device = {fleet_sum} MiB "
                   f"> {FLEET_LANE_ENVELOPE_MIB} MiB - shrink the smoke working set or get "
                   f"manager approval to rebalance lanes")
    if total_mib > args.lane_total_mib:
        verdict += (f" | OVER LANE ALLOCATION {args.lane_total_mib} MiB - manager approval required")

    print(f"family            : {m['family']}")
    print(f"topology          : {m.get('topology','?')} on {nodes} nodes (expert_shard={m['expert_shard']})")
    print(f"smoke experts     : {len(experts)} experts, {expert_bytes/MIB:.1f} MiB full model")
    print(f"per-node experts  : {per_node_experts/MIB:.1f} MiB")
    print(f"per-node spine    : {spine/MIB:.1f} MiB (full-resolution, quality law)")
    print(f"per-node raw      : {per_node_raw/MIB:.1f} MiB -> x{MARGIN} margin")
    print(f"DEVICE_MIB        : {device_mib}")
    print(f"TOTAL_MIB         : {total_mib}")
    print(f"fleet check       : {verdict}")


if __name__ == "__main__":
    main()
