#!/bin/bash
# dsv4_pro TP4xPP4 shared-socket family wrapper (multidev lane 5).
#
# Ported from tools/devcycle/templates/run-family-job.sh.template (PR #1084,
# the extracted VALIDATED GLM5.3-flash wrapper pattern). The only block
# edited beyond FAMILY PARAMETERS is marked DSV4 ADAPTATIONS: preserving the
# -fabric transport_host aliases (the 100G GID discovery fix from the
# single-spark receipts, round 8), providing the runtime lib/ artifacts
# (adapter/driver/transport resolve against runtime_root), and the amended
# collective block (PR #1094: the table's 67000+16L base exceeded the 16-bit
# port limit; lane 5 collective is 53080..53095).
#
# Provenance: the behavioral contract is pinned by the template and
# docs/MULTIDEV_QUICKSTART.md + docs/PARALLEL_DRIVER_DEBUG.md. The family
# deployment is generated by tools/dsv4_pro_tp4pp4_gen_deployment.py.
# The smoke working set lives in model-families/dsv4/smoke_experts.json
# (PR #1092); the weightd_warm identity for this family is NOT yet
# expressible (tools/weightd_warm.c hardcodes the GLM identity) - the
# preload hook stays empty until that lands (milestone 3).
#
# Laws inherited from the template (each paid for with an incident):
#   - Fail closed: missing/malformed pack identity, unknown listener key,
#     unreserved port, or a missing shared socket is a hard error.
#   - The wrapper never starts daemons in shared-socket mode.
#   - No nested SSH GPU launches; every child stays in this queue cgroup.
#   - Logical rank = index in --nodes = rank_index in the deployment =
#     mesh rank (identity TP4xPP4 map, order identical to the mesh map).
#
# QUEUE INVOCATION (measured, not assumed): submit with
#   --cmd 'bash tools/devcycle/run-dsv4-pro-family-job.sh'
# NOT --cmd-file: the dispatcher routes command text through systemd-run,
# which pre-expands every $VAR/${VAR} pattern before bash executes (probe
# receipt dsv4pro-dollar-probe, 2026-09-22: [/home/${X}] -> [/home/]).
# A bare repo-resident invocation keeps this script's variables inside
# real bash.

set -euo pipefail

# ----------------------------- FAMILY PARAMETERS -----------------------------

FAMILY="dsv4_pro"
LANE=5
TOPOLOGY="TP4xPP4"
HOSTS=(spark0 spark1 spark2 spark3 spark4 spark5 spark6 spark7 \
       spark8 spark9 sparka sparkb sparkc sparkd sparke sparkf)
MESH_RANKS="0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
EXEC_PREFIX="${FAMILY_EXEC_PREFIX:-build}"
DEPLOYMENT_SOURCE="${FAMILY_DEPLOYMENT_SOURCE:-}"

# Lane port math (lane_assignments.json as amended by PR #1094: the
# collective base moved from 67000+16L to 53000+16L - 67000+16L is above
# the 16-bit port limit and the queue rejects the reservation).
CONTROL_BASE=$((23000 + 16 * LANE))       # 23080..23095
COLLECTIVE_BASE=$((53000 + 16 * LANE))    # 53080..53095
TRANSPORT_BASE=$((64000 + 16 * LANE))     # 64080..64095
SESSION_BASE=$((23168 + 64 * LANE))       # 23488..23551 (reserve when used)

DEVICE_MIB=6400   # lane device budget (resident side; daemon budgets are the operator's)

WEIGHTD_MODE="${FAMILY_WEIGHTD_MODE:-shared-socket}"
SHARED_SOCKET="${FAMILY_WEIGHTD_SOCKET:-}"

# Family model environment: the pinned shared-lane CUDA trio. dsv4_pro has
# no whole-chain graph flags (the TP4xPP4 adapter captures its graph islands
# unconditionally); never invent new ones.
FAMILY_ENV=(
  "CUDA_MODULE_LOADING=LAZY"
  "CUDA_MODULE_DATA_LOADING=LAZY"
  "CUDA_DEVICE_MAX_CONNECTIONS=32"
)

# Milestone 3 hook: warm the smoke expert set through the same shared
# socket before the resident attaches. Empty FAMILY_WORKING_SET skips the
# warm; the default (applied below, where the repo root is known) is the
# committed manifest's .wset companion. weightd_warm derives the exact
# module attach identity via --family dsv4_pro --world-rank.
WORKING_SET="${FAMILY_WORKING_SET:-default}"

# ------------------------------ QUEUE CONTRACT -------------------------------

ATTEMPT="${SPARK_QUEUE_ATTEMPT:?run through the authoritative spark queue}"
case "$ATTEMPT" in
  *[!0-9a-f]*|""|?????????????????????????????????*) echo "bad attempt id" >&2; exit 2 ;;
esac
[ "${#ATTEMPT}" -eq 32 ] || { echo "bad attempt id length" >&2; exit 2; }

ROOT="${SPARK_QUEUE_RUNTIME_ROOT:?missing queue runtime root}"
[ "$ROOT" = "/tmp/sparkqueue-$ATTEMPT" ] || { echo "unexpected job namespace: $ROOT" >&2; exit 2; }

RANK="${SPARK_QUEUE_RANK:?}"; SIZE="${SPARK_QUEUE_SIZE:?}"
[ "$SIZE" -eq "${#HOSTS[@]}" ] || { echo "queue size ${SIZE} != deployment hosts ${#HOSTS[@]}" >&2; exit 2; }
[ "$RANK" -ge 0 ] && [ "$RANK" -lt "$SIZE" ] || { echo "rank out of range" >&2; exit 2; }
# TP4xPP4 rank hygiene: logical rank R must run on HOSTS[R].
# (FAMILY_SKIP_HOST_CHECK=1 exists only for the offline contract test;
# the queue always runs with the check enforced.)
if [ "${FAMILY_SKIP_HOST_CHECK:-0}" != "1" ]; then
  ACTUAL_HOST="$(hostname)"
  [ "$ACTUAL_HOST" = "${HOSTS[$RANK]}" ] || {
    echo "rank/host mismatch: rank $RANK belongs on ${HOSTS[$RANK]}, this is $ACTUAL_HOST" >&2; exit 2; }
fi

reserved_ok() {
  local port="$1" entry first last
  [ -n "${SPARK_QUEUE_PORTS:-}" ] || { echo "queue reserved no ports" >&2; exit 2; }
  for entry in ${SPARK_QUEUE_PORTS//,/ }; do
    first="${entry%%:*}"; last="${entry##*:}"
    if [ "$port" -ge "$first" ] && [ "$port" -le "$last" ]; then return 0; fi
  done
  echo "listener port $port is not inside a queue-reserved range" >&2; return 1
}

for r in $(seq 0 $((SIZE - 1))); do
  reserved_ok $((CONTROL_BASE + r)) || exit 2
  reserved_ok $((COLLECTIVE_BASE + r)) || exit 2
  reserved_ok $((TRANSPORT_BASE + r)) || exit 2
done

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
[ -n "$DEPLOYMENT_SOURCE" ] || DEPLOYMENT_SOURCE="$REPO/deployment/dsv4_pro_tp4pp4/model_resident.json"
[ -f "$DEPLOYMENT_SOURCE" ] || { echo "missing family deployment: $DEPLOYMENT_SOURCE" >&2; exit 2; }

# --------------------------- PRIVATE RUNTIME PREP ----------------------------

python3 - "$ROOT" "$RANK" "$SIZE" "$CONTROL_BASE" "$COLLECTIVE_BASE" \
         "$TRANSPORT_BASE" "$SESSION_BASE" "$ATTEMPT" "$LANE" \
         "$DEPLOYMENT_SOURCE" <<'PYEOF'
import json, sys
from pathlib import Path

root, rank, size = Path(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])
control_base, collective_base, transport_base, session_base = (int(a) for a in sys.argv[4:8])
attempt, lane, deployment_source = sys.argv[8], int(sys.argv[9]), sys.argv[10]

def fail(msg):
    raise SystemExit("dsv4_pro wrapper prepare: FAIL: " + msg)

if not 1 <= size <= 16:
    fail(f"topology size {size} outside 1..16")
host_names = [f"spark{index:x}" for index in range(size)]

def load(path):
    try:
        return json.loads(Path(path).read_text())
    except (OSError, ValueError) as error:
        fail(f"cannot read {path}: {error}")

deployment = load(deployment_source)
if len(deployment["nodes"]) != size:
    fail("deployment node count differs from queue topology")
value = json.loads(json.dumps(deployment))
value["transport"]["control_port_base"] = transport_base
for r, node in enumerate(value["nodes"]):
    if node["rank_index"] != r:
        fail("deployment ranks must be ordered")
    node["runtime_root"] = str(root / "runtime")
    # DSV4 ADAPTATION: keep the committed transport_host (sparkN-fabric,
    # the 100G GID discovery alias); only the control endpoint moves to
    # the plain mgmt host inside the lane block.
    expected = f"spark{r:x}-fabric"
    if node["transport_host"] != expected:
        fail(f"rank {r} transport_host {node['transport_host']!r} != {expected!r}")
    node["control_endpoint"] = {"kind": "tcp", "host": host_names[r], "port": control_base + r}
    if node.get("kv_backing_directory") is not None:
        if not node.get("kv_backing_maximum_bytes", 0) > 0:
            fail("unbounded kv backing store")
        node["kv_backing_directory"] = str(root / "kv")

config_name = value["nodes"][rank]["adapter_configuration_path"]
source_root = Path(deployment["nodes"][rank]["runtime_root"])
config = load(source_root / config_name)

PORT_NAMES = {"listen_port", "peer_ports", "session_ports", "session_ports_hc", "draft_bridge_port"}

def remap(item):
    if isinstance(item, list):
        return [remap(entry) for entry in item]
    if not isinstance(item, int):
        fail("non-integer listener value")
    return 0 if item == 0 else session_base + (item % 4096)

def rewrite(node):
    result = {}
    for key, item in node.items():
        if key.endswith("_port") or key.endswith("_ports") or key.startswith("session_ports"):
            if key not in PORT_NAMES:
                fail(f"unhandled listener configuration: {key}")
            result[key] = remap(item)
        elif isinstance(item, dict):
            result[key] = rewrite(item)
        else:
            result[key] = item
    return result

config = rewrite(config)
if "tp_collective" in config:
    tp = config["tp_collective"]
    tp["collective_identifier"] = int(attempt[:15], 16) + 1 + lane
    tp["listen_port"] = collective_base + rank
    tp["peer_ports"] = [collective_base + peer for peer in range(size)]

runtime = root / "runtime"
runtime.mkdir(parents=True, exist_ok=True)
pack_path = config["stage_pack_path"]
if Path(pack_path).is_absolute() or ".." in Path(pack_path).parts:
    fail("pack escapes runtime root")
source_pack = source_root / pack_path
if not source_pack.is_file():
    fail(f"stage pack missing: {source_pack} (uniform per-rank pack name; "
         "the multidev fleet prepare renames rank packs to it)")
pack_dir = runtime / "packs"
pack_dir.mkdir()
pack_dir.joinpath(source_pack.name).symlink_to(source_pack.resolve())
for suffix in (".sha256", ".experts"):
    sidecar = Path(str(source_pack) + suffix)
    if not sidecar.is_file():
        fail(f"missing pack sidecar {suffix} - generate the family expert manifest first")
    pack_dir.joinpath(sidecar.name).write_bytes(sidecar.read_bytes())
digests = sorted(pack_dir.glob("*.sha256"))
if len(digests) != 1:
    fail(f"packs/ must contain exactly one *.sha256 digest, found {len(digests)}")

# DSV4 ADAPTATION: adapter/driver/transport resolve against runtime_root;
# provide the verified coherent set from the source runtime root (the same
# artifacts the fleet build staged; replacing one .so alone is not a
# coherent release).
lib_dir = runtime / "lib"
lib_dir.mkdir()
deployment_json = load(deployment_source)
for relative in (deployment_json["adapter"]["shared_object_path"],
                 deployment_json["driver"]["shared_object_path"],
                 deployment_json["transport"]["shared_object_path"]):
    source_lib = source_root / relative
    if not source_lib.is_file():
        fail(f"runtime artifact missing: {source_lib}")
    target = lib_dir / Path(relative).name
    target.symlink_to(source_lib.resolve())

(runtime / config_name).parent.mkdir(parents=True, exist_ok=True)
(runtime / config_name).write_text(json.dumps(config) + "\n")
(root / "kv").mkdir(exist_ok=True)
(root / "deployment.json").write_text(json.dumps(value) + "\n")
print("dsv4_pro wrapper prepare: rank", rank, "pack", source_pack.name,
      "digest", digests[0].name, "collective_id", config.get("tp_collective", {}).get("collective_identifier"))
PYEOF

# ------------------------------ WEIGHTD MODE ---------------------------------

if [ "$WEIGHTD_MODE" = "shared-socket" ]; then
  [ -n "$SHARED_SOCKET" ] || { echo "shared-socket mode requires FAMILY_WEIGHTD_SOCKET" >&2; exit 2; }
  [ -S "$SHARED_SOCKET" ] || { echo "shared weightd socket is not present: $SHARED_SOCKET (operator-level; do not start daemons by hand)" >&2; exit 2; }
  WEIGHTD_SOCKET="$SHARED_SOCKET"
elif [ "$WEIGHTD_MODE" = "private" ]; then
  [ "$SIZE" -eq 1 ] || { echo "private-daemon mode is single-node; use tools/inference_smoke.py for the qualified multi-node smoke" >&2; exit 2; }
  WEIGHTD_SOCKET="$ROOT/weightd.sock"
  "$EXEC_PREFIX/sparkpipe_weightd" --socket "$WEIGHTD_SOCKET" \
    --device-bytes-max $((DEVICE_MIB * 1024 * 1024)) \
    >"$ROOT/weightd.log" 2>&1 &
  WEIGHTD_PID=$!
  for _ in $(seq 1 300); do
    grep -q "spark_weightd ready " "$ROOT/weightd.log" 2>/dev/null && break
    kill -0 "$WEIGHTD_PID" 2>/dev/null || { echo "private weightd exited early" >&2; exit 2; }
    sleep 0.1
  done
  grep -q "spark_weightd ready " "$ROOT/weightd.log" || { echo "private weightd not ready in 30s" >&2; exit 2; }
else
  echo "unknown WEIGHTD_MODE: $WEIGHTD_MODE" >&2; exit 2
fi

# Optional cold-launch preload (milestone 3): warm the smoke expert set
# through the same socket before the resident attaches, with the exact
# module attach identity (--family dsv4_pro --world-rank).
if [ "$WORKING_SET" = "default" ]; then
  WORKING_SET="$REPO/model-families/dsv4/smoke-standard-v1.wset"
fi
if [ -n "$WORKING_SET" ] && [ "$WORKING_SET" != "default" ]; then
  CONFIG_REL="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["nodes"][int(sys.argv[2])]["adapter_configuration_path"])' "$ROOT/deployment.json" "$RANK")"
  PACK_REL="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["stage_pack_path"])' "$ROOT/runtime/$CONFIG_REL")"
  REVISION="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("model_revision","0"))' "$ROOT/runtime/$CONFIG_REL")"
  PACK="$ROOT/runtime/$PACK_REL"
  SHA="$(cut -d' ' -f1 "$PACK.sha256")"
  # Pool bound with 2 MiB chunk-granularity headroom (see
  # tools/devcycle/dsv4pro_smoke_warm.sh): ~18 MiB chunked per expert.
  export SPARK_WEIGHTD_EXPERT_POOL_BYTES=4294967296
  "$EXEC_PREFIX/weightd_warm" "$WEIGHTD_SOCKET" "$PACK" "$SHA" "$REVISION" "$SIZE" \
    --family dsv4_pro --world-rank "$RANK" \
    --wset "$WORKING_SET" 300 >"$ROOT/warm.log" 2>&1
  grep -q "WSET-WARM keys=" "$ROOT/warm.log" || { echo "working set warm failed" >&2; exit 2; }
fi

# ----------------------------- RESIDENT LAUNCH -------------------------------

export SPARK_WEIGHTD_ATTACH=1
export SPARK_WEIGHTD_SOCKET="$WEIGHTD_SOCKET"
export SPARK_WEIGHTD_LANE="$LANE"
export SPARK_TP_MESH_RANKS="$MESH_RANKS"
for entry in "${FAMILY_ENV[@]}"; do
  [ -n "$entry" ] || continue
  case "$entry" in *=*) export "$entry" ;; *) echo "bad FAMILY_ENV entry: $entry" >&2; exit 2 ;; esac
done

if [ "$WEIGHTD_MODE" = "private" ]; then
  trap 'kill -TERM "$WEIGHTD_PID" 2>/dev/null || true' EXIT
fi

exec "$EXEC_PREFIX/sparkpipe_model_residentd" \
  --deployment "$ROOT/deployment.json" \
  --rank-index "$RANK"
