#pragma once

#include <stdint.h>

/* Generated from the exact source revision by
 * tools/generate_hy4_contracts.py. Execution codec binds land with
 * the module milestone; this header freezes geometry and identity
 * only. The source of truth is the AngelSlim UD-IQ1_M GGUF (operator
 * ruling 2026-09-01); the FP8 safetensors are reference-only. */
#define SPARK_HY4_MODEL_ID "AngelSlim/Hy4-preview-GGUF"
#define SPARK_HY4_MODEL_SOURCE_REVISION "779242edccdedc2109a0b36b164263a88f015bfa"
#define SPARK_HY4_MODEL_SOURCE_SHA256 "12d325844103bac75bd286d14e0e45f87e35e8e60401877282a30b6f26ba6ac6"
#define SPARK_HY4_MODEL_TP_RANKS 16u

#define SPARK_HY4_MODEL_HIDDEN_DIMENSION 6144u
#define SPARK_HY4_MODEL_LAYER_COUNT 78u
#define SPARK_HY4_MODEL_MTP_LAYER_COUNT 0u
#define SPARK_HY4_MODEL_VOCAB_COUNT 120832u
#define SPARK_HY4_MODEL_VOCAB_PER_RANK 7552u
#define SPARK_HY4_MODEL_MAX_POSITIONS 1048576u
#define SPARK_HY4_MODEL_ATTN_QUERY_HEAD_COUNT 64u
#define SPARK_HY4_MODEL_ATTN_QUERY_HEADS_PER_RANK 4u
#define SPARK_HY4_MODEL_ATTN_KV_HEAD_COUNT 8u
#define SPARK_HY4_MODEL_QK_HEAD_DIMENSION 256u
#define SPARK_HY4_MODEL_QK_NOPE_HEAD_DIMENSION 192u
#define SPARK_HY4_MODEL_QK_ROPE_HEAD_DIMENSION 64u
#define SPARK_HY4_MODEL_V_HEAD_DIMENSION 256u
#define SPARK_HY4_MODEL_KV_LORA_RANK 512u
#define SPARK_HY4_MODEL_QUERY_LORA_RANK 2048u
#define SPARK_HY4_MODEL_LEARNABLE_SINK 1u
#define SPARK_HY4_MODEL_INDEX_HEAD_COUNT 32u
#define SPARK_HY4_MODEL_INDEX_HEADS_PER_RANK 2u
#define SPARK_HY4_MODEL_INDEX_HEAD_DIMENSION 128u
#define SPARK_HY4_MODEL_INDEX_TOP_K 2048u
#define SPARK_HY4_MODEL_INDEXER_FULL_PERIOD 4u
#define SPARK_HY4_MODEL_ROUTED_EXPERT_COUNT 256u
#define SPARK_HY4_MODEL_EXPERTS_PER_RANK 16u
#define SPARK_HY4_MODEL_SHARED_EXPERT_COUNT 1u
#define SPARK_HY4_MODEL_EXPERTS_PER_TOKEN 8u
#define SPARK_HY4_MODEL_EXPERT_INTERMEDIATE_DIMENSION 2048u
#define SPARK_HY4_MODEL_DENSE_FFN_INTERMEDIATE_DIMENSION 18432u
#define SPARK_HY4_MODEL_HC_STREAM_COUNT 4u
#define SPARK_HY4_MODEL_ROPE_THETA 10000000.0f
#define SPARK_HY4_MODEL_RMS_NORM_EPSILON 1e-05f
#define SPARK_HY4_MODEL_HC_MAGNITUDE 2.0f
#define SPARK_HY4_MODEL_HC_EPSILON 1e-06f
#define SPARK_HY4_MODEL_ROUTED_SCALING_FACTOR 2.827f
#define SPARK_HY4_MODEL_SWIGLU_LIMIT 10.0f
#define SPARK_HY4_MODEL_ATTN_QUERY_DIMENSION (SPARK_HY4_MODEL_ATTN_QUERY_HEAD_COUNT * SPARK_HY4_MODEL_QK_HEAD_DIMENSION)
#define SPARK_HY4_MODEL_INDEX_DIMENSION (SPARK_HY4_MODEL_INDEX_HEAD_COUNT * SPARK_HY4_MODEL_INDEX_HEAD_DIMENSION)
#define SPARK_HY4_MODEL_IS_INDEXER_FULL_LAYER(layer) (((layer) % SPARK_HY4_MODEL_INDEXER_FULL_PERIOD) == 0u)
/* Layer 0 and 1 are indexer-full in addition to the period pattern (the checkpoint's is_full sequence is 1,1,0,0,0,1,...). */
#define SPARK_HY4_MODEL_IS_INDEXER_ACTIVE_LAYER(layer) \
	(((layer) < 2u) || SPARK_HY4_MODEL_IS_INDEXER_FULL_LAYER(layer))
#define SPARK_HY4_MODEL_ATTN_KV_HEADS_PER_RANK \
	(SPARK_HY4_MODEL_ATTN_KV_HEAD_COUNT / SPARK_HY4_MODEL_TP_RANKS)
#define SPARK_HY4_MODEL_EXPERT_GROUPS_PER_LAYER \
	(SPARK_HY4_MODEL_ROUTED_EXPERT_COUNT / SPARK_HY4_MODEL_EXPERTS_PER_RANK)
/* hc_attn_fn/hc_ffn_fn mix the flattened stream vector down to 2*HC outputs (per-stream gate+scale pairs); hc_*_base has 2*HC biases and hc_*_scale has 2 scalars. */
#define SPARK_HY4_MODEL_HC_FN_OUTPUT_ROWS (2u * SPARK_HY4_MODEL_HC_STREAM_COUNT)
#define SPARK_HY4_MODEL_HC_FLAT_WIDTH (SPARK_HY4_MODEL_HC_STREAM_COUNT * SPARK_HY4_MODEL_HIDDEN_DIMENSION)
/* FP8 execution arm: F8_E4M3 payloads with U8 E8M0 group-32 scales. */
#define SPARK_HY4_MODEL_EXPERT_SCALE_GROUP_SIZE 32u
#define SPARK_HY4_MODEL_ROUTE_GROUP_MAX \
	(SPARK_HY4_MODEL_EXPERTS_PER_TOKEN * SPARK_HY4_MODEL_HC_STREAM_COUNT)
