#pragma once

#include <stdint.h>

#define SPARK_GLM_MODEL_HEAD_COUNT SPARK_LLM_MLA_HEAD_COUNT
#define SPARK_GLM_MODEL_QK_NOPE_HEAD_DIMENSION SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION
#define SPARK_GLM_MODEL_ROPE_DIMENSION SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION
#define SPARK_GLM_MODEL_VALUE_HEAD_DIMENSION SPARK_LLM_MLA_V_HEAD_DIMENSION
#define SPARK_GLM_MODEL_QK_SCALE SPARK_LLM_QK_SCALE
#define SPARK_GLM_MODEL_OUTPUT_VOCAB_COUNT SPARK_LLM_OUTPUT_VOCAB_COUNT
#define SPARK_GLM_MODEL_DENSE_INTERMEDIATE_DIMENSION SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION
#define SPARK_GLM_MODEL_MOE_INTERMEDIATE_DIMENSION SPARK_LLM_MOE_INTERMEDIATE_DIMENSION
#define SPARK_LLM_FAMILY_TAG glm52
#define SPARK_LLM_FAMILY_NAME "glm52"

#define SPARK_LLM_HIDDEN_DIMENSION 6144u
#define SPARK_LLM_LAYER_COUNT 78u
#define SPARK_LLM_OUTPUT_VOCAB_COUNT 154880u
#define SPARK_LLM_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_LLM_KV_POOL_TOKENS 4194304u
#define SPARK_LLM_RMS_NORM_EPSILON 1e-05f
#define SPARK_LLM_END_OF_TEXT_TOKEN_ID 154820u
#define SPARK_LLM_MAX_PREFILL_TOKENS_PER_DISPATCH 256u
#define SPARK_LLM_FIRST_ROUTED_LAYER 3u
#define SPARK_LLM_RESTRICTED_VOCAB_COUNT 256u
#define SPARK_LLM_USER_TOKEN_ID 154827u
#define SPARK_LLM_OBSERVATION_TOKEN_ID 154829u
#define SPARK_LLM_EOS_TOKEN_IDS_INITIALIZER \
	{ \
		SPARK_LLM_END_OF_TEXT_TOKEN_ID, \
		SPARK_LLM_USER_TOKEN_ID, \
		SPARK_LLM_OBSERVATION_TOKEN_ID \
	}

#define SPARK_LLM_MLA_HEAD_COUNT 64u
#define SPARK_LLM_MLA_QUERY_A_DIMENSION 2048u
#define SPARK_LLM_MLA_LATENT_DIMENSION 512u
#define SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION 192u
#define SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION 64u
#define SPARK_LLM_MLA_V_HEAD_DIMENSION 256u

#define SPARK_LLM_ROPE_THETA 8000000.0f
#define SPARK_LLM_ROPE_INTERLEAVE 1u
#define SPARK_LLM_QK_SCALE 0.0625f

#define SPARK_LLM_DSA_SELECTED_TOKEN_COUNT 2048u
#define SPARK_LLM_DSA_INDEX_HEAD_COUNT 32u
#define SPARK_LLM_DSA_INDEX_HEAD_DIMENSION 128u
#define SPARK_LLM_DSA_INDEX_SHARE_GROUP_LAYER_COUNT 4u
#define SPARK_LLM_DSA_INDEX_FULL_FIRST_LAYER 3u
#define SPARK_LLM_DSA_INDEX_FULL_GROUP_LAYER 6u
#define SPARK_LLM_DSA_INDEX_SKIP_TOPK_OFFSET 3u
#define SPARK_LLM_DSA_INDEX_NORM_EPSILON 1e-06f
#define SPARK_LLM_DSA_INDEX_SOFTMAX_SCALE 0.0883883476f
#define SPARK_LLM_DSA_ROPE_INTERLEAVE 1u

#define SPARK_LLM_MOE_EXPERT_COUNT 256u
#define SPARK_LLM_MOE_TOP_K 8u
#define SPARK_LLM_MOE_INTERMEDIATE_DIMENSION 2048u
#define SPARK_LLM_MOE_W1_COMPONENT_COUNT 2u
#define SPARK_LLM_MOE_ROUTED_SCALING_FACTOR 2.5f
#define SPARK_LLM_DENSE_INTERMEDIATE_DIMENSION 12288u

#define SPARK_LLM_FP8_SCALE_BLOCK 128u
#define SPARK_LLM_MXFP4_GROUP_SIZE 32u
#define SPARK_LLM_NVFP4_GROUP_SIZE 16u

#define SPARK_LLM_MTP_DRAFT_TOKEN_COUNT 6u
#define SPARK_LLM_MTP_TARGET_HIDDEN_POSITION_DELTA 1u
#define SPARK_LLM_MTP_EXECUTION_POSITION_OFFSET 0u
#define SPARK_LLM_MTP_LAYER_INDEX SPARK_LLM_LAYER_COUNT
#define SPARK_LLM_WEIGHT_LAYER_COUNT (SPARK_LLM_MTP_LAYER_INDEX + 1u)

#define SPARK_LLM_DSPARK_AUX_LAYER_COUNT 5u
#define SPARK_LLM_DSPARK_AUX_LAYER_IDS_INITIALIZER { 8u, 23u, 39u, 55u, 70u }
#define SPARK_LLM_DSPARK_AUX_CAPTURE_LAYER_OFFSET 1u
#define SPARK_LLM_DSPARK_DRAFT_LAYER_COUNT 5u
#define SPARK_LLM_DSPARK_BLOCK_SIZE 8u
#define SPARK_LLM_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT 7u
#define SPARK_LLM_DSPARK_DRAFT_INTERMEDIATE_DIMENSION 12288u
#define SPARK_LLM_DSPARK_DRAFT_ATTENTION_HEAD_COUNT 64u
#define SPARK_LLM_DSPARK_DRAFT_KV_HEAD_COUNT 64u
#define SPARK_LLM_DSPARK_DRAFT_HEAD_DIMENSION 64u
#define SPARK_LLM_DSPARK_MARKOV_RANK 256u
#define SPARK_LLM_DSPARK_MASK_TOKEN_ID 154856u
#define SPARK_LLM_DSPARK_MAX_ANCHORS 1024u
#define SPARK_LLM_DSPARK_PP_STAGE_COUNT 13u
#define SPARK_LLM_DSPARK_PP_STAGE_LAYER_COUNT 6u
#define SPARK_LLM_MAX_SPECULATIVE_ROWS_PER_LANE \
	(SPARK_LLM_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT + 1u)
#define SPARK_LLM_DSPARK_AUX_CAPTURE_LAYER_INDEX(aux_layer_id) \
	((aux_layer_id) - SPARK_LLM_DSPARK_AUX_CAPTURE_LAYER_OFFSET)

#define SPARK_LLM_BF16_ELEMENT_BYTES ((uint32_t)sizeof(uint16_t))
#define SPARK_LLM_HIDDEN_BF16_BYTES \
	(SPARK_LLM_HIDDEN_DIMENSION * SPARK_LLM_BF16_ELEMENT_BYTES)
#define SPARK_LLM_DSA_SELECTED_INDEX_BYTES \
	(SPARK_LLM_DSA_SELECTED_TOKEN_COUNT * ((uint32_t)sizeof(uint32_t)))
#define SPARK_LLM_DSA_INDEX_QUERY_DIMENSION \
	(SPARK_LLM_DSA_INDEX_HEAD_COUNT * SPARK_LLM_DSA_INDEX_HEAD_DIMENSION)
#define SPARK_LLM_QK_HEAD_DIMENSION \
	(SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION + \
	 SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_LLM_QUERY_B_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * SPARK_LLM_QK_HEAD_DIMENSION)
#define SPARK_LLM_KV_A_DIMENSION \
	(SPARK_LLM_MLA_LATENT_DIMENSION + SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_LLM_KV_B_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * \
	 (SPARK_LLM_MLA_QK_NOPE_HEAD_DIMENSION + \
	  SPARK_LLM_MLA_V_HEAD_DIMENSION))
#define SPARK_LLM_CACHE_TOKEN_ELEMENTS SPARK_LLM_KV_A_DIMENSION
#define SPARK_LLM_QUERY_LATENT_PROJECTION_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * SPARK_LLM_MLA_LATENT_DIMENSION)
#define SPARK_LLM_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * SPARK_LLM_MLA_V_HEAD_DIMENSION)
#define SPARK_LLM_QUERY_ROPE_PROJECTION_DIMENSION \
	(SPARK_LLM_MLA_HEAD_COUNT * SPARK_LLM_MLA_QK_ROPE_HEAD_DIMENSION)
#define SPARK_LLM_MOE_ROUTED_GATE_UP_DIMENSION \
	(SPARK_LLM_MOE_TOP_K * SPARK_LLM_MOE_W1_COMPONENT_COUNT * \
	 SPARK_LLM_MOE_INTERMEDIATE_DIMENSION)
#define SPARK_LLM_FP8_SCALE_EXTENT(dimension) \
	(((dimension) + SPARK_LLM_FP8_SCALE_BLOCK - 1u) / \
	 SPARK_LLM_FP8_SCALE_BLOCK)
#define SPARK_LLM_FP8_SCALE_COUNT(rows, columns) \
	(SPARK_LLM_FP8_SCALE_EXTENT(rows) * SPARK_LLM_FP8_SCALE_EXTENT(columns))
#define SPARK_LLM_MAX_FP8_LINEAR_SCALE_COUNT \
	SPARK_LLM_FP8_SCALE_COUNT( \
		SPARK_LLM_HIDDEN_DIMENSION, \
		SPARK_LLM_ATTENTION_PROJECTION_DIMENSION)

#define SPARK_LLM_KV_BITS 16u
#define SPARK_LLM_KV_PAGE_SLOTS 64u
#define SPARK_LLM_KV_SLOT_BYTES ((SPARK_LLM_KV_A_DIMENSION * SPARK_LLM_KV_BITS) / 8u)
#define SPARK_LLM_KV_BLOCK_TOKEN_COUNT 64u
#define SPARK_LLM_KV_BYTES_PER_SCALAR 2u
#define SPARK_LLM_KV_ARENA_KV_HEAD_COUNT 1u
#define SPARK_LLM_KV_INDEX_KEY_LAYER_COUNT 0u
#define SPARK_LLM_KV_INDEX_KEY_DIMENSION 0u
#define SPARK_LLM_KV_INDEX_KEY_BYTES_PER_SCALAR 0u

#define SPARK_LLM_TILE_N 128u
#define SPARK_LLM_TILE_K 64u
#define SPARK_LLM_TILE_STAGES 2u
#define SPARK_LLM_TILE_WARPS 8u
#define SPARK_LLM_HEAD_TILE 1024u
#define SPARK_LLM_LAYER_THREADS 256u
#define SPARK_LLM_ATTN_THREADS 256u

#define SPARK_LLM_STAGE_NODE_CONTEXT_ABI_VERSION 5u
#define SPARK_LLM_STAGE_FRAME_CONTEXT_ABI_VERSION 1u
#define SPARK_LLM_STAGE_BATCH_VIEW_ABI_VERSION 1u
#define SPARK_LLM_STAGE_COUNT 1u
#define SPARK_LLM_STAGE_LAYERS_PER_STAGE SPARK_LLM_LAYER_COUNT
#define SPARK_LLM_STAGE_MAX_INPUT_ROW_COUNT 65536u
#define SPARK_LLM_STAGE_MAX_PIPELINE_SLOT_COUNT 4u
#define SPARK_LLM_STAGE_BOUNDARY_ELEMENT_BYTES 2u
#define SPARK_LLM_STAGE_DSA_SIDEBAND_KIND 1u
#define SPARK_LLM_STAGE_ATTN_SPLIT_PARTITIONS 16u

#define SPARK_LLM_BATCH_MODULE_ID_SHAPE ".h6144.l78.e256.k8"
#define SPARK_LLM_BATCH_MODULE_ID_SUFFIX "v2"

#define SPARK_LLM_MLA_QK_SCALE                  0.0625f
#define SPARK_LLM_MOE_SHARED_EXPERT_COUNT       1u
#define SPARK_LLM_MOE_NORM_TOPK_PROB            1u
#define SPARK_LLM_TP_DEGREE                     16u
#define SPARK_LLM_STAGE_INDEX                   0u
#define SPARK_LLM_ADAPTER_DESCRIPTOR            "spark.glm52.serving-adapter.tp16.expert_fp8.v1"
#define SPARK_LLM_MODEL_SOURCE_URI              "zai-org/GLM-5.3"
#define SPARK_LLM_MODEL_REVISION                "935644c05e76fc198714f4cca449fd8b970ff6d7"
