#pragma once

#include <stdint.h>

#define SPARK_GLM52_MODEL_HIDDEN_DIMENSION 6144u
#define SPARK_GLM52_MODEL_LAYER_COUNT 78u
#define SPARK_GLM52_MODEL_MAXIMUM_CONTEXT_TOKENS 1048576u
#define SPARK_GLM52_MODEL_KV_POOL_TOKENS 4194304u
#define SPARK_GLM52_MODEL_FIRST_ROUTED_LAYER 3u
#define SPARK_GLM52_MODEL_HEAD_COUNT 64u
#define SPARK_GLM52_MODEL_LATENT_DIMENSION 512u
#define SPARK_GLM52_MODEL_ROPE_DIMENSION 64u
#define SPARK_GLM52_MODEL_QUERY_A_DIMENSION 2048u
#define SPARK_GLM52_MODEL_QK_NOPE_HEAD_DIMENSION 192u
#define SPARK_GLM52_MODEL_VALUE_HEAD_DIMENSION 256u
#define SPARK_GLM52_MODEL_MOE_EXPERT_COUNT 256u
#define SPARK_GLM52_MODEL_MOE_TOP_K 8u
#define SPARK_GLM52_MODEL_MOE_INTERMEDIATE_DIMENSION 2048u
#define SPARK_GLM52_MODEL_MOE_W1_COMPONENT_COUNT 2u
#define SPARK_GLM52_MODEL_DENSE_INTERMEDIATE_DIMENSION 12288u
#define SPARK_GLM52_MODEL_FP8_SCALE_BLOCK 128u
#define SPARK_GLM52_MODEL_DSA_SELECTED_TOKEN_COUNT 2048u
#define SPARK_GLM52_MODEL_DSA_INDEX_HEAD_COUNT 32u
#define SPARK_GLM52_MODEL_DSA_INDEX_HEAD_DIMENSION 128u
#define SPARK_GLM52_MODEL_DSA_INDEX_SHARE_GROUP_LAYER_COUNT 4u
#define SPARK_GLM52_MODEL_DSA_INDEX_SKIP_TOPK_OFFSET 3u
#define SPARK_GLM52_MODEL_OUTPUT_VOCAB_COUNT 154880u
#define SPARK_GLM52_MODEL_RESTRICTED_VOCAB_COUNT 256u
#define SPARK_GLM52_MODEL_MAX_PREFILL_TOKENS_PER_DISPATCH 256u
#define SPARK_GLM52_MODEL_MTP_DRAFT_TOKEN_COUNT 6u
#define SPARK_GLM52_MODEL_MTP_TARGET_HIDDEN_POSITION_DELTA 1u
#define SPARK_GLM52_MODEL_MXFP4_GROUP_SIZE 32u
#define SPARK_GLM52_MODEL_NVFP4_GROUP_SIZE 16u
#define SPARK_GLM52_MODEL_MTP_EXECUTION_POSITION_OFFSET 0u
#define SPARK_GLM52_MODEL_END_OF_TEXT_TOKEN_ID 154820u
#define SPARK_GLM52_MODEL_USER_TOKEN_ID 154827u
#define SPARK_GLM52_MODEL_OBSERVATION_TOKEN_ID 154829u
#define SPARK_GLM52_MODEL_EOS_TOKEN_IDS_INITIALIZER \
	{ \
		SPARK_GLM52_MODEL_END_OF_TEXT_TOKEN_ID, \
		SPARK_GLM52_MODEL_USER_TOKEN_ID, \
		SPARK_GLM52_MODEL_OBSERVATION_TOKEN_ID \
	}
#define SPARK_GLM52_MODEL_MTP_LAYER_INDEX SPARK_GLM52_MODEL_LAYER_COUNT
#define SPARK_GLM52_MODEL_WEIGHT_LAYER_COUNT \
	(SPARK_GLM52_MODEL_MTP_LAYER_INDEX + 1u)
#define SPARK_GLM52_MODEL_RMS_NORM_EPSILON 1e-05f
#define SPARK_GLM52_MODEL_DSA_INDEX_NORM_EPSILON 1e-06f
#define SPARK_GLM52_MODEL_MOE_ROUTED_SCALING_FACTOR 2.5f
#define SPARK_GLM52_MODEL_ROPE_THETA 8000000.0f
#define SPARK_GLM52_MODEL_QK_SCALE 0.0625f
#define SPARK_GLM52_MODEL_DSA_INDEX_SOFTMAX_SCALE 0.0883883476f
#define SPARK_GLM52_MODEL_DSA_ROPE_INTERLEAVE 1u
#define SPARK_GLM52_MODEL_ROPE_INTERLEAVE 1u
#define SPARK_GLM52_MODEL_DSPARK_AUX_LAYER_COUNT 5u
#define SPARK_GLM52_MODEL_DSPARK_AUX_LAYER_IDS_INITIALIZER { 8u, 23u, 39u, 55u, 70u }
#define SPARK_GLM52_MODEL_DSPARK_AUX_CAPTURE_LAYER_OFFSET 1u
#define SPARK_GLM52_MODEL_DSPARK_DRAFT_LAYER_COUNT 5u
#define SPARK_GLM52_MODEL_DSPARK_BLOCK_SIZE 8u
#define SPARK_GLM52_MODEL_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT 7u
#define SPARK_GLM52_MODEL_DSPARK_DRAFT_INTERMEDIATE_DIMENSION 12288u
#define SPARK_GLM52_MODEL_DSPARK_DRAFT_ATTENTION_HEAD_COUNT 64u
#define SPARK_GLM52_MODEL_DSPARK_DRAFT_KV_HEAD_COUNT 64u
#define SPARK_GLM52_MODEL_DSPARK_DRAFT_HEAD_DIMENSION 64u
#define SPARK_GLM52_MODEL_DSPARK_MARKOV_RANK 256u
#define SPARK_GLM52_MODEL_DSPARK_MASK_TOKEN_ID 154856u
#define SPARK_GLM52_MODEL_DSPARK_MAX_ANCHORS 1024u
#define SPARK_GLM52_MODEL_MAX_SPECULATIVE_ROWS_PER_LANE \
	(SPARK_GLM52_MODEL_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT + 1u)
#define SPARK_GLM52_MODEL_DSPARK_AUX_CAPTURE_LAYER_INDEX(aux_layer_id) \
	((aux_layer_id) - SPARK_GLM52_MODEL_DSPARK_AUX_CAPTURE_LAYER_OFFSET)
#define SPARK_GLM52_MODEL_BF16_ELEMENT_BYTES ((uint32_t)sizeof(uint16_t))
#define SPARK_GLM52_MODEL_HIDDEN_BF16_BYTES \
	(SPARK_GLM52_MODEL_HIDDEN_DIMENSION * SPARK_GLM52_MODEL_BF16_ELEMENT_BYTES)
#define SPARK_GLM52_MODEL_DSA_SELECTED_INDEX_BYTES \
	(SPARK_GLM52_MODEL_DSA_SELECTED_TOKEN_COUNT * ((uint32_t)sizeof(uint32_t)))
#define SPARK_GLM52_MODEL_DSA_INDEX_QUERY_DIMENSION \
	(SPARK_GLM52_MODEL_DSA_INDEX_HEAD_COUNT * \
	 SPARK_GLM52_MODEL_DSA_INDEX_HEAD_DIMENSION)

#define SPARK_GLM52_MODEL_QK_HEAD_DIMENSION \
	(SPARK_GLM52_MODEL_QK_NOPE_HEAD_DIMENSION + \
	 SPARK_GLM52_MODEL_ROPE_DIMENSION)
#define SPARK_GLM52_MODEL_QUERY_B_DIMENSION \
	(SPARK_GLM52_MODEL_HEAD_COUNT * SPARK_GLM52_MODEL_QK_HEAD_DIMENSION)
#define SPARK_GLM52_MODEL_KV_A_DIMENSION \
	(SPARK_GLM52_MODEL_LATENT_DIMENSION + SPARK_GLM52_MODEL_ROPE_DIMENSION)
#define SPARK_GLM52_MODEL_KV_B_DIMENSION \
	(SPARK_GLM52_MODEL_HEAD_COUNT * \
	 (SPARK_GLM52_MODEL_QK_NOPE_HEAD_DIMENSION + \
	  SPARK_GLM52_MODEL_VALUE_HEAD_DIMENSION))
#define SPARK_GLM52_MODEL_CACHE_TOKEN_ELEMENTS SPARK_GLM52_MODEL_KV_A_DIMENSION
#define SPARK_GLM52_MODEL_QUERY_LATENT_PROJECTION_DIMENSION \
	(SPARK_GLM52_MODEL_HEAD_COUNT * SPARK_GLM52_MODEL_LATENT_DIMENSION)
#define SPARK_GLM52_MODEL_ATTENTION_PROJECTION_DIMENSION \
	(SPARK_GLM52_MODEL_HEAD_COUNT * SPARK_GLM52_MODEL_VALUE_HEAD_DIMENSION)
#define SPARK_GLM52_MODEL_QUERY_ROPE_PROJECTION_DIMENSION \
	(SPARK_GLM52_MODEL_HEAD_COUNT * SPARK_GLM52_MODEL_ROPE_DIMENSION)
#define SPARK_GLM52_MODEL_FP8_SCALE_EXTENT(dimension) \
	(((dimension) + SPARK_GLM52_MODEL_FP8_SCALE_BLOCK - 1u) / \
	 SPARK_GLM52_MODEL_FP8_SCALE_BLOCK)
#define SPARK_GLM52_MODEL_FP8_SCALE_COUNT(rows, columns) \
	(SPARK_GLM52_MODEL_FP8_SCALE_EXTENT(rows) * \
	 SPARK_GLM52_MODEL_FP8_SCALE_EXTENT(columns))
#define SPARK_GLM52_MODEL_MAX_FP8_LINEAR_SCALE_COUNT \
	SPARK_GLM52_MODEL_FP8_SCALE_COUNT( \
		SPARK_GLM52_MODEL_HIDDEN_DIMENSION, \
		SPARK_GLM52_MODEL_ATTENTION_PROJECTION_DIMENSION)
