#pragma once

#include <stdint.h>

#include "sparkpipe/spark_minimax_h3_model.h"
#include "sparkpipe/spark_stagepack_format.h"

#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_WEIGHT_FORMAT_BF16 \
	SPARK_STAGEPACK_FORMAT_WEIGHT_BF16
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_WEIGHT_FORMAT_F32 \
	SPARK_STAGEPACK_FORMAT_WEIGHT_F32
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_WEIGHT_FORMAT_I64 \
	SPARK_STAGEPACK_FORMAT_WEIGHT_I64

#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_TP_DEGREE \
	SPARK_MINIMAX_H3_TP_DEGREE
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_PP_STAGE_COUNT 4u
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_RANK_COUNT \
	(SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_TP_DEGREE * \
	 SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_PP_STAGE_COUNT)
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_DIT_BLOCKS_PER_STAGE 13u
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_DIT_TAIL_BLOCKS \
	(SPARK_MINIMAX_H3_DIT_BLOCK_COUNT - \
	 SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_DIT_BLOCKS_PER_STAGE * 3u)

#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_MAX_ACTIVE_JOBS 4u
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_MAX_PROMPT_TOKENS \
	SPARK_MINIMAX_H3_ENCODER_MAX_PROMPT_TOKENS
#define SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_MAX_STEPS 200u

SPARK_MINIMAX_H3_STATIC_ASSERT(SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_RANK_COUNT == 16u,
	"h3 media stage fills the sixteen-spark cell");
SPARK_MINIMAX_H3_STATIC_ASSERT(SPARK_MINIMAX_H3_DIT_BLOCK_COUNT ==
	SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_DIT_BLOCKS_PER_STAGE * 3u +
	SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_DIT_TAIL_BLOCKS,
	"h3 dit block split must cover the main stack across four stages");
SPARK_MINIMAX_H3_STATIC_ASSERT(SPARK_MINIMAX_H3_RESIDENT_MEDIA_STAGE_DIT_TAIL_BLOCKS == 11u,
	"h3 exit stage carries the eleven remaining main blocks");
